-- ============================================================
-- AptiPath360 V3 Post-12 ENGINEERING Stream Questions
-- 18 questions: Engineering Aptitude (10) + Technical Problem Solving (8)
-- ============================================================

USE robodynamics_db;
START TRANSACTION;

-- ---- ENGINEERING APTITUDE (10 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_ENG_EA_01', 29, 'ENGINEERING_APTITUDE',
   'MCQ',
   'What is the output of this pseudocode?\nx = 1\nfor i = 1 to 4:\n    x = x * 2 + 1\nprint(x)',
   CAST('[{"code":"A","label":"15"},{"code":"B","label":"31"},{"code":"C","label":"16"},{"code":"D","label":"9"}]' AS JSON),
   'B',
   4,
   'POST_12', 'APPLY', 'MEDIUM',
   0,
   'CORRECT=TECH+ENGINEERING+DATA_SCIENCE',
   'BOOST_TECH',
   'Trace: x=1 → 1*2+1=3 → 3*2+1=7 → 7*2+1=15 → 15*2+1=31. Code tracing is a fundamental programming skill. The pattern x=2^n - 1 (Mersenne numbers) appears in binary systems and computer science.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_EA_02', 30, 'ENGINEERING_APTITUDE',
   'MCQ',
   'A sorted array of 1024 elements is searched using binary search. What is the MAXIMUM number of comparisons needed to find any element?',
   CAST('[{"code":"A","label":"10"},{"code":"B","label":"11"},{"code":"C","label":"512"},{"code":"D","label":"1024"}]' AS JSON),
   'B',
   4,
   'POST_12', 'APPLY', 'MEDIUM',
   0,
   'CORRECT=TECH+DATA_SCIENCE+ENGINEERING',
   'BOOST_TECH',
   'Binary search halves the search space each step. log2(1024) = 10, but we need one extra comparison for the final element check, so maximum is 11 (or ceil(log2(n)) + 1). This O(log n) efficiency makes binary search fundamental in computer science.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_EA_03', 31, 'ENGINEERING_APTITUDE',
   'MCQ',
   'In a relational database, which operation combines rows from two tables based on a matching column?',
   CAST('[{"code":"A","label":"UNION"},{"code":"B","label":"JOIN"},{"code":"C","label":"GROUP BY"},{"code":"D","label":"INDEX"}]' AS JSON),
   'B',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=TECH+DATA_SCIENCE',
   'BOOST_TECH',
   'JOIN combines rows from two tables based on a related column (foreign key). UNION stacks results vertically. GROUP BY aggregates rows. INDEX speeds up queries but does not combine tables. SQL JOINs are among the most used operations in backend development and data engineering.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_EA_04', 32, 'ENGINEERING_APTITUDE',
   'MCQ',
   'A web application loads slowly. The server response time is 50ms but the page takes 4 seconds to render. The bottleneck is MOST likely:',
   CAST('[{"code":"A","label":"The database is too slow"},{"code":"B","label":"The server CPU is overloaded"},{"code":"C","label":"Large unoptimized frontend assets (images, JS bundles)"},{"code":"D","label":"The internet is down"}]' AS JSON),
   'C',
   4,
   'POST_12', 'ANALYZE', 'MEDIUM',
   0,
   'CORRECT=TECH+ENGINEERING+WEB_DEV',
   'BOOST_TECH+ENGINEERING',
   'Server response is fast (50ms), so backend/database are fine. The 4-second render time points to frontend issues — large images, unminified JavaScript, render-blocking CSS. This is a classic frontend performance diagnosis. Understanding the full stack (server vs client) is key for web engineers.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_EA_05', 33, 'ENGINEERING_APTITUDE',
   'MCQ',
   'Which data structure is BEST for implementing an "Undo" feature in a text editor?',
   CAST('[{"code":"A","label":"Queue"},{"code":"B","label":"Stack"},{"code":"C","label":"Array"},{"code":"D","label":"Hash Map"}]' AS JSON),
   'B',
   3,
   'POST_12', 'APPLY', 'EASY',
   0,
   'CORRECT=TECH+ENGINEERING',
   'BOOST_TECH',
   'Stack follows LIFO (Last In, First Out) — the most recent action is undone first, which is exactly how Undo works. Queue is FIFO (wrong order). Array works but does not enforce LIFO naturally. Hash Map has no ordering. Choosing the right data structure is a core engineering skill.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_EA_06', 34, 'ENGINEERING_APTITUDE',
   'MCQ',
   'A steel beam supports a load. If the cross-sectional area is doubled while keeping the same material and load, the stress in the beam will:',
   CAST('[{"code":"A","label":"Double"},{"code":"B","label":"Remain the same"},{"code":"C","label":"Become half"},{"code":"D","label":"Become four times"}]' AS JSON),
   'C',
   4,
   'POST_12', 'APPLY', 'MEDIUM',
   0,
   'CORRECT=ENGINEERING+MECHANICAL+CIVIL',
   'BOOST_ENGINEERING',
   'Stress = Force / Area. If area doubles with same force, stress = F/(2A) = half the original. This fundamental relationship governs structural design in civil, mechanical, and aerospace engineering.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_EA_07', 35, 'ENGINEERING_APTITUDE',
   'MCQ',
   'In a simple electrical circuit, three resistors of 6 ohms each are connected in parallel. The equivalent resistance is:',
   CAST('[{"code":"A","label":"18 ohms"},{"code":"B","label":"6 ohms"},{"code":"C","label":"2 ohms"},{"code":"D","label":"3 ohms"}]' AS JSON),
   'C',
   3,
   'POST_12', 'APPLY', 'EASY',
   0,
   'CORRECT=ENGINEERING+ELECTRICAL+TECH',
   'BOOST_ENGINEERING',
   'For parallel resistors: 1/R_eq = 1/6 + 1/6 + 1/6 = 3/6 = 1/2, so R_eq = 2 ohms. Parallel resistance is always less than the smallest individual resistor. This is fundamental in electrical and electronics engineering.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_EA_08', 36, 'ENGINEERING_APTITUDE',
   'MCQ',
   'A 3D printer builds objects layer by layer. If a cube of side 10cm is printed at 0.2mm layer height, how many layers are needed?',
   CAST('[{"code":"A","label":"50"},{"code":"B","label":"500"},{"code":"C","label":"100"},{"code":"D","label":"5000"}]' AS JSON),
   'B',
   3,
   'POST_12', 'APPLY', 'EASY',
   0,
   'CORRECT=ENGINEERING+MANUFACTURING+TECH',
   'BOOST_ENGINEERING',
   '10cm = 100mm. Number of layers = 100mm / 0.2mm = 500 layers. Understanding manufacturing parameters like layer height, resolution, and build time is essential in mechanical engineering and product design.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_EA_09', 37, 'ENGINEERING_APTITUDE',
   'MCQ',
   'Which protocol is primarily used for sending emails between mail servers on the internet?',
   CAST('[{"code":"A","label":"HTTP"},{"code":"B","label":"FTP"},{"code":"C","label":"SMTP"},{"code":"D","label":"SSH"}]' AS JSON),
   'C',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=TECH+NETWORKING',
   'BOOST_TECH',
   'SMTP (Simple Mail Transfer Protocol) handles email transmission between servers. HTTP is for web pages. FTP is for file transfer. SSH is for secure remote access. Understanding network protocols is fundamental for any software or network engineer.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_EA_10', 38, 'ENGINEERING_APTITUDE',
   'MCQ',
   'An engineer needs to store sensor data from 10,000 IoT devices, each sending 1 reading per second. Which storage approach is MOST appropriate?',
   CAST('[{"code":"A","label":"A single Excel spreadsheet"},{"code":"B","label":"A time-series database like InfluxDB or TimescaleDB"},{"code":"C","label":"A Word document with a table"},{"code":"D","label":"Email each reading to a shared inbox"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   0,
   'CORRECT=TECH+DATA_SCIENCE+ENGINEERING+IOT',
   'BOOST_TECH+ENGINEERING',
   '10,000 devices × 1/sec = 10,000 writes/sec = 864 million rows/day. Time-series databases are optimized for high-volume, time-stamped data with efficient compression and queries. Excel has a 1M row limit. This is a real-world IoT architecture decision.',
   90,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- ---- TECHNICAL PROBLEM SOLVING (8 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_ENG_TPS_01', 39, 'TECHNICAL_PROBLEM_SOLVING',
   'SITUATIONAL',
   'Your team''s code is in production and a critical bug is reported at 11 PM on Friday. Your first action should be:',
   CAST('[{"code":"A","label":"Fix the bug immediately and push to production without testing"},{"code":"B","label":"Assess the impact: how many users affected and is there a workaround?"},{"code":"C","label":"Ignore it until Monday — it is the weekend"},{"code":"D","label":"Revert the entire last release to be safe"}]' AS JSON),
   'B',
   5,
   'POST_12', 'EVALUATE', 'HARD',
   1,
   'A=IMPULSIVE;B=METHODICAL_ENGINEER;C=NEGLIGENT;D=OVERCAUTIOUS',
   'BOOST_TECH+ENGINEERING',
   'Impact assessment first: Is it affecting 10 users or 10,000? Is there a workaround? This determines urgency. Untested fixes can create worse bugs. Ignoring critical bugs is unprofessional. Reverting everything may break other features. Triage before action is the engineering discipline.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_TPS_02', 40, 'TECHNICAL_PROBLEM_SOLVING',
   'MCQ',
   'A mobile app crashes when users upload photos larger than 5MB. The BEST fix is:',
   CAST('[{"code":"A","label":"Tell users to only upload small photos in the FAQ"},{"code":"B","label":"Compress and resize images on the client side before uploading"},{"code":"C","label":"Increase server memory to handle larger files"},{"code":"D","label":"Remove the photo upload feature entirely"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   0,
   'CORRECT=TECH+ENGINEERING+MOBILE_DEV',
   'BOOST_TECH',
   'Client-side compression reduces upload size, saves bandwidth, and prevents the crash — addressing root cause. Relying on users to resize is poor UX. Increasing server memory treats the symptom, not the cause. Removing the feature is surrender. Always fix at the appropriate layer.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_TPS_03', 41, 'TECHNICAL_PROBLEM_SOLVING',
   'SITUATIONAL',
   'You are building a college event registration system. Expected users: 2,000 students over 3 days. Which technology stack is the MOST practical choice?',
   CAST('[{"code":"A","label":"Microservices with Kubernetes, Redis cache, and PostgreSQL cluster"},{"code":"B","label":"A simple web app with a single database (e.g., Django/Flask + SQLite or MySQL)"},{"code":"C","label":"A Google Form linked to a spreadsheet"},{"code":"D","label":"A custom blockchain-based registration system"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   1,
   'A=OVER_ENGINEER;B=PRAGMATIC_ENGINEER;C=MINIMAL;D=HYPE_DRIVEN',
   'BOOST_TECH+ENGINEERING',
   '2,000 users over 3 days is modest traffic. A simple web app with a database handles this easily and is quick to build. Microservices/Kubernetes is massive overengineering. Google Form works but lacks customization. Blockchain adds zero value here. Right-sizing architecture is a key engineering skill.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_TPS_04', 42, 'TECHNICAL_PROBLEM_SOLVING',
   'MCQ',
   'Your team uses Git for version control. Two developers edited the same file. The BEST way to combine their changes is:',
   CAST('[{"code":"A","label":"Delete one person''s changes and keep the other"},{"code":"B","label":"Create separate branches, then merge and resolve conflicts"},{"code":"C","label":"Copy-paste both versions into a new file manually"},{"code":"D","label":"Stop using version control to avoid conflicts"}]' AS JSON),
   'B',
   3,
   'POST_12', 'APPLY', 'EASY',
   0,
   'CORRECT=TECH+ENGINEERING',
   'BOOST_TECH',
   'Git branching and merging is the standard workflow for collaborative development. Merge conflicts are normal and are resolved by reviewing both changes. Deleting work wastes effort. Manual copy-paste is error-prone. Avoiding version control is regressive.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_TPS_05', 43, 'TECHNICAL_PROBLEM_SOLVING',
   'MCQ',
   'A user reports that a website form submits successfully but data does not appear in the database. Which is the MOST likely cause?',
   CAST('[{"code":"A","label":"The user''s internet is too slow"},{"code":"B","label":"The form data is being sent to the wrong API endpoint or the server is not committing the transaction"},{"code":"C","label":"The browser is blocking the data"},{"code":"D","label":"The database is full and cannot accept new records"}]' AS JSON),
   'B',
   4,
   'POST_12', 'ANALYZE', 'MEDIUM',
   0,
   'CORRECT=TECH+ENGINEERING+DEBUGGING',
   'BOOST_TECH',
   'A successful form submission with missing database data indicates the server received the request but did not persist it. Common causes: wrong endpoint, missing database commit, validation failure handled silently. Slow internet would cause timeout, not silent failure. Full databases throw explicit errors.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_TPS_06', 44, 'TECHNICAL_PROBLEM_SOLVING',
   'SITUATIONAL',
   'You discover a security vulnerability in your college project that could expose student email addresses. The project demo is tomorrow. You would:',
   CAST('[{"code":"A","label":"Ignore it — it is just a college project, not a real product"},{"code":"B","label":"Fix the vulnerability tonight even if it means less sleep, then demo"},{"code":"C","label":"Demo without mentioning it and fix after the deadline"},{"code":"D","label":"Cancel the demo and inform the professor about the security issue"}]' AS JSON),
   'B',
   5,
   'POST_12', 'EVALUATE', 'HARD',
   1,
   'A=NEGLIGENT;B=SECURITY_CONSCIOUS;C=DECEPTIVE;D=OVERCAUTIOUS',
   'BOOST_TECH+ETHICS',
   'Security vulnerabilities with real student data must be fixed regardless of project vs production status. Fixing it before demo shows professional security mindset. Ignoring or hiding vulnerabilities is unethical especially with PII. Canceling the demo entirely may be excessive if the fix is feasible.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_TPS_07', 45, 'TECHNICAL_PROBLEM_SOLVING',
   'MCQ',
   'A bridge designer must choose between steel and concrete for a pedestrian bridge in a coastal area with high humidity. The KEY factor favoring one material over the other is:',
   CAST('[{"code":"A","label":"Steel is always cheaper than concrete"},{"code":"B","label":"Concrete resists corrosion better than steel in humid salty environments"},{"code":"C","label":"Steel bridges always look better"},{"code":"D","label":"Concrete is lighter than steel"}]' AS JSON),
   'B',
   4,
   'POST_12', 'ANALYZE', 'MEDIUM',
   0,
   'CORRECT=ENGINEERING+CIVIL+MATERIALS',
   'BOOST_ENGINEERING',
   'In coastal high-humidity environments, salt spray accelerates steel corrosion. Concrete (with proper cover) resists this better, though reinforcement still needs protection. Material selection based on environmental factors is a core civil/structural engineering decision.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_ENG_TPS_08', 46, 'TECHNICAL_PROBLEM_SOLVING',
   'MCQ',
   'An autonomous drone needs to navigate from point A to point B while avoiding obstacles detected by sensors. Which algorithmic approach is MOST suitable?',
   CAST('[{"code":"A","label":"Linear regression"},{"code":"B","label":"Path-finding algorithm like A* with real-time sensor input"},{"code":"C","label":"Bubble sort"},{"code":"D","label":"Binary search on the map coordinates"}]' AS JSON),
   'B',
   4,
   'POST_12', 'APPLY', 'MEDIUM',
   0,
   'CORRECT=AI_TECH+ENGINEERING+ROBOTICS',
   'BOOST_TECH+ENGINEERING',
   'A* (A-star) is the standard path-finding algorithm that considers both distance traveled and estimated remaining distance. Combined with real-time sensor data for dynamic obstacle avoidance, it powers autonomous navigation in drones, robots, and self-driving vehicles. Sorting and searching algorithms solve different problem classes.',
   90,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- Engineering stream complete: 18 questions (seq 29-46)

COMMIT;
