-- ============================================================
-- AptiPath360 V3 Post-12 MEDICAL Stream Questions
-- 18 questions: Biomedical Foundation (10) + Clinical Reasoning (8)
-- For: MBBS, BDS, Pharmacy, Nursing, Allied Health
-- ============================================================

USE robodynamics_db;
START TRANSACTION;

-- ---- BIOMEDICAL FOUNDATION (10 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_MED_BMF_01', 47, 'BIOMEDICAL_FOUNDATION',
   'MCQ',
   'Which organ is responsible for filtering blood, removing waste products, and maintaining fluid balance in the body?',
   CAST('[{"code":"A","label":"Liver"},{"code":"B","label":"Kidney"},{"code":"C","label":"Spleen"},{"code":"D","label":"Pancreas"}]' AS JSON),
   'B',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=HEALTH+BIOLOGY+MEDICAL',
   'BOOST_HEALTH',
   'Kidneys filter approximately 180 liters of blood daily, removing waste as urine and maintaining electrolyte balance. The liver detoxifies and produces bile. The spleen filters old blood cells. The pancreas produces insulin and digestive enzymes.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_BMF_02', 48, 'BIOMEDICAL_FOUNDATION',
   'MCQ',
   'Antibiotics are effective against:',
   CAST('[{"code":"A","label":"Viral infections like the common cold and flu"},{"code":"B","label":"Bacterial infections like strep throat and urinary tract infections"},{"code":"C","label":"All types of infections including viral, bacterial, and fungal"},{"code":"D","label":"Only infections that cause fever"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=HEALTH+MEDICAL+PHARMACOLOGY',
   'BOOST_HEALTH',
   'Antibiotics target bacteria, not viruses. Antibiotic resistance is a major global health crisis partly caused by misuse (taking antibiotics for viral infections). Understanding this distinction is crucial for any healthcare professional.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_BMF_03', 49, 'BIOMEDICAL_FOUNDATION',
   'MCQ',
   'A patient with Type 1 diabetes has a deficiency of which hormone?',
   CAST('[{"code":"A","label":"Thyroxine"},{"code":"B","label":"Insulin"},{"code":"C","label":"Adrenaline"},{"code":"D","label":"Cortisol"}]' AS JSON),
   'B',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=HEALTH+MEDICAL+ENDOCRINOLOGY',
   'BOOST_HEALTH',
   'Type 1 diabetes is an autoimmune condition where the pancreas produces little or no insulin. Insulin regulates blood glucose. Type 2 diabetes involves insulin resistance. Understanding endocrine disorders is fundamental in medicine.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_BMF_04', 50, 'BIOMEDICAL_FOUNDATION',
   'MCQ',
   'DNA replication occurs during which phase of the cell cycle?',
   CAST('[{"code":"A","label":"G1 phase"},{"code":"B","label":"S phase (Synthesis)"},{"code":"C","label":"G2 phase"},{"code":"D","label":"M phase (Mitosis)"}]' AS JSON),
   'B',
   3,
   'POST_12', 'REMEMBER', 'MEDIUM',
   0,
   'CORRECT=BIOLOGY+RESEARCH+BIOTECH',
   'BOOST_RESEARCH',
   'The S (Synthesis) phase is when DNA replicates so each daughter cell gets a complete copy. G1 is growth before synthesis. G2 is preparation for division. M phase is actual mitosis (cell division). Understanding the cell cycle is essential for genetics, oncology, and biotechnology.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_BMF_05', 51, 'BIOMEDICAL_FOUNDATION',
   'MCQ',
   'A vaccine works by:',
   CAST('[{"code":"A","label":"Killing all bacteria in the body"},{"code":"B","label":"Training the immune system to recognize and fight a specific pathogen"},{"code":"C","label":"Providing permanent immunity to all diseases"},{"code":"D","label":"Replacing white blood cells with stronger ones"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=HEALTH+MEDICAL+IMMUNOLOGY',
   'BOOST_HEALTH',
   'Vaccines introduce a weakened, killed, or fragment of a pathogen to stimulate immune memory (B-cells and T-cells) without causing disease. When the real pathogen is encountered, the immune system responds rapidly. Understanding immunology is critical for public health and biomedical careers.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_BMF_06', 52, 'BIOMEDICAL_FOUNDATION',
   'MCQ',
   'The human heart has four chambers. Which chamber pumps oxygenated blood to the entire body?',
   CAST('[{"code":"A","label":"Right atrium"},{"code":"B","label":"Right ventricle"},{"code":"C","label":"Left atrium"},{"code":"D","label":"Left ventricle"}]' AS JSON),
   'D',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=HEALTH+MEDICAL+ANATOMY',
   'BOOST_HEALTH',
   'The left ventricle has the thickest wall because it pumps oxygenated blood through the aorta to the entire body (systemic circulation). Right ventricle pumps to lungs only. Understanding cardiac anatomy is foundational for all medical professionals.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_BMF_07', 53, 'BIOMEDICAL_FOUNDATION',
   'MCQ',
   'CRISPR-Cas9 is a revolutionary tool used in:',
   CAST('[{"code":"A","label":"Medical imaging like MRI and CT scans"},{"code":"B","label":"Gene editing — precisely modifying DNA sequences"},{"code":"C","label":"Manufacturing pharmaceutical tablets"},{"code":"D","label":"Sterilizing surgical equipment"}]' AS JSON),
   'B',
   4,
   'POST_12', 'UNDERSTAND', 'MEDIUM',
   0,
   'CORRECT=BIOTECH+RESEARCH+GENETICS',
   'BOOST_RESEARCH+HEALTH',
   'CRISPR-Cas9 allows precise cutting and editing of DNA sequences. It has transformative potential in treating genetic diseases, cancer therapy, agriculture, and research. Understanding emerging biotech tools is vital for future healthcare and research professionals.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_BMF_08', 54, 'BIOMEDICAL_FOUNDATION',
   'MCQ',
   'Hemoglobin, the molecule that carries oxygen in blood, contains which metal ion at its core?',
   CAST('[{"code":"A","label":"Calcium"},{"code":"B","label":"Iron"},{"code":"C","label":"Zinc"},{"code":"D","label":"Copper"}]' AS JSON),
   'B',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=HEALTH+MEDICAL+BIOCHEMISTRY',
   'BOOST_HEALTH',
   'Each hemoglobin molecule contains four iron (Fe2+) ions in its heme groups, which reversibly bind oxygen. Iron deficiency leads to anemia (reduced oxygen-carrying capacity). This is why iron-rich diet is crucial. Biochemistry of blood is fundamental in clinical medicine.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_BMF_09', 55, 'BIOMEDICAL_FOUNDATION',
   'MCQ',
   'Which of the following is a communicable disease?',
   CAST('[{"code":"A","label":"Diabetes"},{"code":"B","label":"Tuberculosis"},{"code":"C","label":"Hypertension"},{"code":"D","label":"Arthritis"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=HEALTH+MEDICAL+PUBLIC_HEALTH',
   'BOOST_HEALTH',
   'Tuberculosis (TB) is caused by Mycobacterium tuberculosis and spreads through airborne droplets. Diabetes, hypertension, and arthritis are non-communicable diseases (NCDs). India has the highest TB burden globally — understanding communicable vs NCD is essential for public health.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_BMF_10', 56, 'BIOMEDICAL_FOUNDATION',
   'MCQ',
   'A patient''s blood report shows WBC count of 15,000/mcL (normal: 4,000-11,000). This elevated count MOST likely indicates:',
   CAST('[{"code":"A","label":"Dehydration"},{"code":"B","label":"An active infection or inflammatory response"},{"code":"C","label":"Iron deficiency"},{"code":"D","label":"High cholesterol"}]' AS JSON),
   'B',
   4,
   'POST_12', 'ANALYZE', 'MEDIUM',
   0,
   'CORRECT=HEALTH+MEDICAL+PATHOLOGY',
   'BOOST_HEALTH',
   'Elevated WBC (leukocytosis) typically indicates the immune system is fighting an infection or there is inflammation. The body produces more white blood cells to combat pathogens. Interpreting blood reports is a core clinical skill for all medical professionals.',
   75,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- ---- CLINICAL REASONING (8 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_MED_CLR_01', 57, 'CLINICAL_REASONING',
   'SITUATIONAL',
   'A patient in the emergency department has severe chest pain. As a medical intern, your FIRST priority should be:',
   CAST('[{"code":"A","label":"Order a full body CT scan immediately"},{"code":"B","label":"Stabilize the patient: check vitals, administer oxygen, call senior doctor"},{"code":"C","label":"Ask the patient detailed questions about their medical history"},{"code":"D","label":"Give pain medication first to make the patient comfortable"}]' AS JSON),
   'B',
   5,
   'POST_12', 'EVALUATE', 'HARD',
   1,
   'A=OVER_INVESTIGATOR;B=CLINICAL_PRIORITY;C=HISTORY_FIRST;D=SYMPTOM_MANAGER',
   'BOOST_HEALTH',
   'ABC (Airway, Breathing, Circulation) comes first in emergency medicine. Stabilize vitals and call for senior help. Chest pain could be cardiac emergency — delay can be fatal. Detailed history comes after stabilization. Pain medication without diagnosis can mask critical symptoms.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_CLR_02', 58, 'CLINICAL_REASONING',
   'SITUATIONAL',
   'A patient refuses a blood transfusion due to religious beliefs, but the transfusion could be life-saving. As a doctor, you should:',
   CAST('[{"code":"A","label":"Proceed with the transfusion anyway — saving life is more important"},{"code":"B","label":"Respect the patient''s autonomy, document their decision, and explore alternative treatments"},{"code":"C","label":"Convince the family to override the patient''s decision"},{"code":"D","label":"Discharge the patient since they refuse treatment"}]' AS JSON),
   'B',
   5,
   'POST_12', 'EVALUATE', 'HARD',
   1,
   'A=PATERNALISTIC;B=ETHICAL_PRACTITIONER;C=FAMILY_OVERRIDE;D=ABANDONMENT',
   'BOOST_HEALTH+ETHICS',
   'Patient autonomy is a fundamental principle of medical ethics. A competent adult patient has the right to refuse treatment. The doctor must document the refusal, explain risks clearly, and seek alternative treatments. Forcing treatment violates informed consent. Discharging a sick patient is abandonment.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_CLR_03', 59, 'CLINICAL_REASONING',
   'MCQ',
   'A rural health center receives a patient with suspected dengue. Which diagnostic test should be ordered FIRST?',
   CAST('[{"code":"A","label":"MRI brain scan"},{"code":"B","label":"NS1 antigen test and complete blood count (CBC)"},{"code":"C","label":"ECG (electrocardiogram)"},{"code":"D","label":"Liver biopsy"}]' AS JSON),
   'B',
   4,
   'POST_12', 'APPLY', 'MEDIUM',
   0,
   'CORRECT=HEALTH+MEDICAL+DIAGNOSTICS',
   'BOOST_HEALTH',
   'NS1 antigen test detects dengue virus in the first 5 days of fever. CBC checks platelet count (which drops in dengue). These are affordable, available in rural settings, and directly relevant. MRI and biopsy are expensive, invasive, and unnecessary. ECG is for cardiac issues. Appropriate investigation ordering is a key clinical skill.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_CLR_04', 60, 'CLINICAL_REASONING',
   'SITUATIONAL',
   'During your rural posting, a mother brings her 2-year-old child with diarrhea and dehydration. You have limited medical supplies. Your MOST important intervention is:',
   CAST('[{"code":"A","label":"Prescribe broad-spectrum antibiotics immediately"},{"code":"B","label":"Start oral rehydration solution (ORS) and monitor fluid intake"},{"code":"C","label":"Refer to district hospital 50 km away immediately"},{"code":"D","label":"Give anti-diarrheal medication to stop symptoms"}]' AS JSON),
   'B',
   5,
   'POST_12', 'APPLY', 'MEDIUM',
   1,
   'A=OVER_MEDICATE;B=EVIDENCE_BASED;C=REFERRAL_ONLY;D=SYMPTOM_SUPPRESS',
   'BOOST_HEALTH',
   'ORS is the WHO-recommended first-line treatment for dehydration from diarrhea and has saved millions of lives globally. Most childhood diarrhea is viral (antibiotics ineffective). Anti-diarrheals are contraindicated in children. Immediate referral delays critical rehydration. ORS is the single most important intervention in this scenario.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_CLR_05', 61, 'CLINICAL_REASONING',
   'MCQ',
   'A clinical trial is described as "double-blind." This means:',
   CAST('[{"code":"A","label":"The study involves two groups of patients"},{"code":"B","label":"Neither the patients nor the researchers know who receives the treatment vs placebo"},{"code":"C","label":"The trial is conducted in two different hospitals"},{"code":"D","label":"Two different drugs are being compared"}]' AS JSON),
   'B',
   4,
   'POST_12', 'UNDERSTAND', 'MEDIUM',
   0,
   'CORRECT=RESEARCH+HEALTH+SCIENCE',
   'BOOST_RESEARCH',
   'Double-blinding eliminates observer bias (researcher) and placebo effect (patient). Neither party knows the allocation until the study is unblinded. This is the gold standard for clinical research. Understanding research methodology is essential for evidence-based medicine.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_CLR_06', 62, 'CLINICAL_REASONING',
   'SITUATIONAL',
   'You are a pharmacist. A customer asks for an antibiotic without a prescription, saying their doctor prescribed it last time for similar symptoms. You should:',
   CAST('[{"code":"A","label":"Sell it since the customer seems to know what they need"},{"code":"B","label":"Politely decline, explain antibiotic resistance risks, and recommend they see a doctor"},{"code":"C","label":"Sell a lower dose to be safe"},{"code":"D","label":"Suggest an alternative over-the-counter medicine instead"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   1,
   'A=COMMERCIAL;B=ETHICAL_PHARMACIST;C=COMPROMISE;D=ALTERNATIVE_PUSH',
   'BOOST_HEALTH+ETHICS',
   'Selling prescription drugs without prescription is illegal and dangerous. Self-medication with antibiotics contributes to antimicrobial resistance — a global health crisis. The pharmacist must prioritize patient safety and public health over sales.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_CLR_07', 63, 'CLINICAL_REASONING',
   'MCQ',
   'In India, the National Health Mission focuses primarily on:',
   CAST('[{"code":"A","label":"Building more super-specialty hospitals in metro cities"},{"code":"B","label":"Strengthening primary healthcare, maternal and child health, and disease prevention in rural areas"},{"code":"C","label":"Training only specialist doctors"},{"code":"D","label":"Importing advanced medical equipment from abroad"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=HEALTH+PUBLIC_HEALTH+GOVERNANCE',
   'BOOST_HEALTH+SOCIAL',
   'The National Health Mission (NHM) focuses on strengthening primary and secondary healthcare infrastructure, especially in rural and underserved areas. It covers maternal/child health (RMNCH+A), communicable diseases, and health systems strengthening. Understanding health policy is crucial for public health careers.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_MED_CLR_08', 64, 'CLINICAL_REASONING',
   'SITUATIONAL',
   'A patient shows you information from a health website claiming that a particular herbal supplement cures cancer. As a healthcare professional, your response should be:',
   CAST('[{"code":"A","label":"Agree with the patient to maintain rapport"},{"code":"B","label":"Acknowledge their concern, explain the difference between evidence-based and unverified claims, and guide them to reliable sources"},{"code":"C","label":"Mock the patient for believing internet health claims"},{"code":"D","label":"Tell them to stop all current medication and try the supplement"}]' AS JSON),
   'B',
   5,
   'POST_12', 'EVALUATE', 'MEDIUM',
   1,
   'A=AGREEABLE;B=EVIDENCE_BASED_COMMUNICATOR;C=DISMISSIVE;D=DANGEROUS',
   'BOOST_HEALTH+ETHICS',
   'Empathetic but evidence-based communication is the gold standard. Acknowledge the patient''s autonomy while educating them about scientific evidence vs anecdotal claims. Mocking destroys trust. Agreeing with misinformation or recommending unproven treatments can cause direct harm.',
   90,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- Medical stream complete: 18 questions (seq 47-64)

COMMIT;
