-- ============================================================
-- AptiPath360 V3 Post-12 (College) Question Bank Migration
-- Generated: 2026-03-10
-- Streams: ENGINEERING, MEDICAL, COMMERCE, PURE_SCIENCE, HUMANITIES
-- Common Core: 28 questions (all streams share)
-- Per Stream: ~18 questions each
-- Total: ~118 questions
-- ============================================================

USE robodynamics_db;
START TRANSACTION;

-- ============================================================
-- PHASE 1: COMMON CORE QUESTIONS (28 questions)
-- Shared across ALL post-12 streams
-- ============================================================

-- ---- CORE APTITUDE (6 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_CA_01', 1, 'CORE_APTITUDE',
   'MCQ',
   'A company''s revenue grew from Rs. 12 crore to Rs. 18 crore in 3 years. If the growth rate was uniform, what was the approximate annual compound growth rate?',
   CAST('[{"code":"A","label":"12.5%"},{"code":"B","label":"14.5%"},{"code":"C","label":"16.7%"},{"code":"D","label":"50%"}]' AS JSON),
   'B',
   4,
   'POST_12', 'ANALYZE', 'MEDIUM',
   0,
   'CORRECT=ANALYTICAL+FINANCE+DATA_SCIENCE',
   'BOOST_ANALYTICAL',
   'CAGR = (18/12)^(1/3) - 1 = (1.5)^0.333 - 1 ≈ 0.1447 ≈ 14.5%. Compound growth differs from simple growth (which would give 16.7%). Understanding CAGR is essential in finance, business analytics, and data science.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_CA_02', 2, 'CORE_APTITUDE',
   'MCQ',
   'In a survey of 500 college students, 280 use Instagram, 310 use YouTube, and 160 use both. How many students use neither platform?',
   CAST('[{"code":"A","label":"70"},{"code":"B","label":"110"},{"code":"C","label":"130"},{"code":"D","label":"160"}]' AS JSON),
   'A',
   3,
   'POST_12', 'APPLY', 'MEDIUM',
   0,
   'CORRECT=ANALYTICAL+DATA_SCIENCE',
   'BOOST_ANALYTICAL',
   'Using inclusion-exclusion: Users of at least one = 280 + 310 - 160 = 430. Neither = 500 - 430 = 70. Set theory and Venn diagrams are foundational in data analysis, probability, and database queries.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_CA_03', 3, 'CORE_APTITUDE',
   'MCQ',
   'A train leaves Delhi at 8:00 AM at 60 km/h. Another train leaves the same station at 9:30 AM on a parallel track at 90 km/h in the same direction. At what time will the second train overtake the first?',
   CAST('[{"code":"A","label":"11:30 AM"},{"code":"B","label":"12:00 PM"},{"code":"C","label":"12:30 PM"},{"code":"D","label":"1:00 PM"}]' AS JSON),
   'C',
   3,
   'POST_12', 'APPLY', 'MEDIUM',
   0,
   'CORRECT=ANALYTICAL+ENGINEERING',
   'BOOST_ANALYTICAL',
   'By 9:30 AM, Train 1 has covered 90 km (1.5 hrs × 60). Relative speed = 90-60 = 30 km/h. Time to close 90 km gap = 90/30 = 3 hrs. Second train overtakes at 9:30 + 3:00 = 12:30 PM.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_CA_04', 4, 'CORE_APTITUDE',
   'MCQ',
   'All roses are flowers. Some flowers fade quickly. Which conclusion is DEFINITELY true?',
   CAST('[{"code":"A","label":"All roses fade quickly"},{"code":"B","label":"Some roses fade quickly"},{"code":"C","label":"Some flowers are roses"},{"code":"D","label":"No rose fades quickly"}]' AS JSON),
   'C',
   3,
   'POST_12', 'ANALYZE', 'EASY',
   0,
   'CORRECT=REASONING+LAW+RESEARCH',
   'BOOST_ANALYTICAL',
   'Since all roses are flowers, it is definitely true that some flowers are roses. We cannot conclude anything about roses fading because "some flowers fade" does not specify which ones. Syllogistic reasoning is critical in law, research, and analytical professions.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_CA_05', 5, 'CORE_APTITUDE',
   'MCQ',
   'A data table shows: Q1 sales = 45 units, Q2 = 52, Q3 = 48, Q4 = 55. The marketing budget was: Q1 = 10K, Q2 = 15K, Q3 = 8K, Q4 = 12K. Which quarter had the best sales-per-rupee efficiency?',
   CAST('[{"code":"A","label":"Q1 (4.5 units per 1K)"},{"code":"B","label":"Q2 (3.5 units per 1K)"},{"code":"C","label":"Q3 (6.0 units per 1K)"},{"code":"D","label":"Q4 (4.6 units per 1K)"}]' AS JSON),
   'C',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   0,
   'CORRECT=DATA_SCIENCE+BUSINESS+ANALYTICAL',
   'BOOST_ANALYTICAL',
   'Sales per 1K: Q1=45/10=4.5, Q2=52/15=3.47, Q3=48/8=6.0, Q4=55/12=4.58. Q3 had the best efficiency at 6.0 units per 1K spent. Efficiency metrics help compare performance controlling for input costs — a core skill in business analytics.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_CA_06', 6, 'CORE_APTITUDE',
   'MCQ',
   'If the day after tomorrow is Wednesday, what day was it 3 days before yesterday?',
   CAST('[{"code":"A","label":"Wednesday"},{"code":"B","label":"Thursday"},{"code":"C","label":"Friday"},{"code":"D","label":"Saturday"}]' AS JSON),
   'B',
   3,
   'POST_12', 'APPLY', 'EASY',
   0,
   'CORRECT=REASONING+ANALYTICAL',
   'BOOST_ANALYTICAL',
   'Day after tomorrow is Wednesday → tomorrow is Tuesday → today is Monday → yesterday is Sunday → 3 days before yesterday = Sunday - 3 = Thursday.',
   60,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- ---- APPLIED CHALLENGE (5 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_AC_01', 7, 'APPLIED_CHALLENGE',
   'SITUATIONAL',
   'During a college group project, you discover that a teammate has copied a section from Wikipedia without citation. The submission deadline is tomorrow. You would:',
   CAST('[{"code":"A","label":"Ignore it — everyone does it and the deadline is near"},{"code":"B","label":"Quietly rewrite the section yourself overnight"},{"code":"C","label":"Raise it with the team and collectively rewrite with proper sources"},{"code":"D","label":"Report the teammate to the professor immediately"}]' AS JSON),
   'C',
   5,
   'POST_12', 'EVALUATE', 'MEDIUM',
   1,
   'A=BYSTANDER;B=INDIVIDUAL_FIXER;C=COLLABORATIVE_ETHICS;D=FORMAL_AUTHORITY',
   'BOOST_RESEARCH+ETHICS',
   'Raising the issue with the team and fixing it together shows integrity, leadership, and collaboration. Ignoring plagiarism risks academic penalties for all. Doing it alone avoids team accountability. Immediate reporting without discussion is disproportionate.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_AC_02', 8, 'APPLIED_CHALLENGE',
   'SITUATIONAL',
   'You are interning at a startup. Your manager asks you to present data to investors that you know is selectively chosen to look more favorable. You would:',
   CAST('[{"code":"A","label":"Present it as asked — the manager knows best"},{"code":"B","label":"Add a footnote about limitations and present the full picture"},{"code":"C","label":"Refuse to present and report to HR"},{"code":"D","label":"Present it but privately tell one investor the full truth"}]' AS JSON),
   'B',
   5,
   'POST_12', 'EVALUATE', 'HARD',
   1,
   'A=COMPLIANCE;B=ETHICAL_PROFESSIONAL;C=WHISTLE_BLOWER;D=INCONSISTENT',
   'BOOST_ETHICS+BUSINESS',
   'Adding context about data limitations shows professional integrity while being constructive. Blind compliance enables misrepresentation. Outright refusal may be premature. Selectively telling one investor creates trust issues with your employer.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_AC_03', 9, 'APPLIED_CHALLENGE',
   'SITUATIONAL',
   'Your college fest committee has Rs. 50,000 budget. The event needs: venue setup (Rs. 20K), marketing (Rs. 15K), food (Rs. 25K), and entertainment (Rs. 10K). Total needed is Rs. 70K. How would you handle this?',
   CAST('[{"code":"A","label":"Cut entertainment entirely and reduce food budget to fit Rs. 50K"},{"code":"B","label":"Seek sponsorships for food/entertainment while spending budget on venue and marketing"},{"code":"C","label":"Borrow the extra Rs. 20K from college funds and repay later"},{"code":"D","label":"Reduce all four categories equally by ~28% each"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   1,
   'A=COST_CUTTER;B=RESOURCEFUL_LEADER;C=RISK_TAKER;D=LINEAR_THINKER',
   'BOOST_LEADERSHIP+BUSINESS',
   'Seeking external sponsorships expands the resource pool without compromising experience. Cutting entertainment entirely hurts the event. Borrowing creates financial risk. Equal cuts ignore that some items (venue) have minimum thresholds.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_AC_04', 10, 'APPLIED_CHALLENGE',
   'SITUATIONAL',
   'A classmate who is struggling asks to copy your assignment. You know they are dealing with a family crisis. You would:',
   CAST('[{"code":"A","label":"Let them copy — they are going through a tough time"},{"code":"B","label":"Offer to explain the concepts so they can write their own version"},{"code":"C","label":"Say no firmly — rules are rules regardless of circumstances"},{"code":"D","label":"Help them request an extension from the professor"}]' AS JSON),
   'D',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   1,
   'A=PERMISSIVE;B=MENTORING;C=RIGID;D=SYSTEMS_THINKER',
   'BOOST_SOCIAL+ETHICS',
   'Helping them seek an extension addresses both the immediate need and maintains integrity. Professors often accommodate genuine crises. Copying helps short-term but risks both students. Refusing without alternatives lacks empathy. Option B is good but may not be enough if they are in crisis.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_AC_05', 11, 'APPLIED_CHALLENGE',
   'SITUATIONAL',
   'You notice that the college canteen is generating significant food waste daily. As a student council member, your first step would be:',
   CAST('[{"code":"A","label":"Start a social media campaign to shame the canteen"},{"code":"B","label":"Measure the waste for a week to understand the scale and patterns"},{"code":"C","label":"Immediately switch to a smaller menu to reduce waste"},{"code":"D","label":"Propose donating all leftover food to an NGO"}]' AS JSON),
   'B',
   4,
   'POST_12', 'ANALYZE', 'MEDIUM',
   1,
   'A=REACTIVE;B=DATA_DRIVEN;C=IMPULSIVE;D=CHARITABLE_BUT_REACTIVE',
   'BOOST_RESEARCH+GREEN',
   'Measuring first (data-driven approach) lets you understand root causes before acting. Social media shaming is destructive. Reducing menu without data may cut popular items. Donating is good but does not reduce waste at the source. Measure → Analyze → Act is the professional approach.',
   90,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- ---- VALUES & MOTIVATION (4 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_VM_01', 12, 'VALUES_MOTIVATION',
   'RANK_ORDER',
   'Rank these career factors from 1 (MOST important to you) to 5 (LEAST important):',
   CAST('[{"code":"A","label":"High salary and financial security"},{"code":"B","label":"Making a positive impact on society"},{"code":"C","label":"Work-life balance and personal time"},{"code":"D","label":"Rapid career growth and leadership opportunities"},{"code":"E","label":"Creative freedom and intellectual stimulation"}]' AS JSON),
   'PREFERENCE',
   0,
   'POST_12', NULL, NULL,
   1,
   'A=FINANCE+BUSINESS;B=SOCIAL+HEALTH+EDUCATION;C=BALANCED;D=LEADERSHIP+MANAGEMENT;E=CREATIVE+RESEARCH',
   'CLUSTER_DETECT',
   'Top-ranked factor reveals dominant career motivator. Finance-driven students lean toward corporate/consulting. Impact-driven lean toward healthcare/education/NGO. Growth-driven toward startups/management. Creative-driven toward research/design.',
   120,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_VM_02', 13, 'VALUES_MOTIVATION',
   'LIKERT',
   'I would rather work on a challenging problem alone for hours than brainstorm in a group meeting.',
   CAST('[{"code":"1","label":"Strongly disagree"},{"code":"2","label":"Disagree"},{"code":"3","label":"Neutral"},{"code":"4","label":"Agree"},{"code":"5","label":"Strongly agree"}]' AS JSON),
   'PREFERENCE',
   0,
   'POST_12', NULL, NULL,
   1,
   '4-5=RESEARCH+ENGINEERING+TECH;1-2=MANAGEMENT+SOCIAL+EDUCATION;3=BALANCED',
   'CLUSTER_DETECT',
   'High scores indicate deep-work preference — common in research, engineering, and technical roles. Low scores suggest collaborative preference — common in management, consulting, and teaching. Neither is better; it indicates work style fit.',
   30,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_VM_03', 14, 'VALUES_MOTIVATION',
   'LIKERT',
   'I feel excited about the idea of starting my own business or venture someday.',
   CAST('[{"code":"1","label":"Strongly disagree"},{"code":"2","label":"Disagree"},{"code":"3","label":"Neutral"},{"code":"4","label":"Agree"},{"code":"5","label":"Strongly agree"}]' AS JSON),
   'PREFERENCE',
   0,
   'POST_12', NULL, NULL,
   1,
   '4-5=ENTREPRENEURSHIP+BUSINESS+LEADERSHIP;1-2=STABLE_CAREER+RESEARCH;3=BALANCED',
   'CLUSTER_DETECT',
   'High entrepreneurial drive signals startup aptitude, business leadership, and risk tolerance. Low scores suggest preference for structured careers with stability. Both are valid paths — this helps match career recommendations.',
   30,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_VM_04', 15, 'VALUES_MOTIVATION',
   'LIKERT',
   'I am willing to study for 5+ more years (post-graduation, PhD) if it means becoming an expert in my field.',
   CAST('[{"code":"1","label":"Strongly disagree"},{"code":"2","label":"Disagree"},{"code":"3","label":"Neutral"},{"code":"4","label":"Agree"},{"code":"5","label":"Strongly agree"}]' AS JSON),
   'PREFERENCE',
   0,
   'POST_12', NULL, NULL,
   1,
   '4-5=RESEARCH+SCIENCE+HEALTH+PhD;1-2=INDUSTRY+BUSINESS+STARTUP;3=BALANCED',
   'CLUSTER_DETECT',
   'Willingness for extended study strongly correlates with research, academia, and specialized fields (medicine, law, PhD). Low scores indicate preference for early industry entry — common in tech, business, and entrepreneurship.',
   30,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- ---- LEARNING BEHAVIOR (3 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_LB_01', 16, 'LEARNING_BEHAVIOR',
   'SITUATIONAL',
   'You scored poorly in a mid-semester exam. Your approach to the next exam would be:',
   CAST('[{"code":"A","label":"Study the same way but put in more hours"},{"code":"B","label":"Analyze which topics you got wrong and focus practice on those"},{"code":"C","label":"Get notes from a topper and memorize them"},{"code":"D","label":"Skip the next exam and focus on the final instead"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'EASY',
   1,
   'A=EFFORT_ONLY;B=STRATEGIC_LEARNER;C=DEPENDENT;D=AVOIDANT',
   'BOOST_RESEARCH',
   'Targeted practice based on error analysis is the most effective learning strategy. Just increasing hours without changing approach is inefficient. Copying notes promotes surface learning. Avoidance compounds the problem.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_LB_02', 17, 'LEARNING_BEHAVIOR',
   'LIKERT',
   'When learning something new, I prefer to understand the WHY behind it rather than just memorize the HOW.',
   CAST('[{"code":"1","label":"Strongly disagree"},{"code":"2","label":"Disagree"},{"code":"3","label":"Neutral"},{"code":"4","label":"Agree"},{"code":"5","label":"Strongly agree"}]' AS JSON),
   'PREFERENCE',
   0,
   'POST_12', NULL, NULL,
   1,
   '4-5=RESEARCH+SCIENCE+ENGINEERING;1-2=PROCEDURAL+OPERATIONS;3=BALANCED',
   'BOOST_RESEARCH',
   'Deep understanding (why) indicates research mindset and conceptual learning preference. Procedural focus (how) fits operational and execution-heavy roles. Both are valuable in different career contexts.',
   30,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_LB_03', 18, 'LEARNING_BEHAVIOR',
   'SITUATIONAL',
   'You are given a complex topic to present in class next week. Your preparation approach would be:',
   CAST('[{"code":"A","label":"Read the textbook chapter the night before and wing it"},{"code":"B","label":"Watch YouTube videos about it and make bullet points"},{"code":"C","label":"Read multiple sources, make notes, create slides, and rehearse twice"},{"code":"D","label":"Ask a senior for their old presentation and modify it"}]' AS JSON),
   'C',
   4,
   'POST_12', 'APPLY', 'EASY',
   1,
   'A=PROCRASTINATOR;B=VISUAL_LEARNER;C=THOROUGH_PREPARER;D=SHORTCUT_TAKER',
   'BOOST_LEADERSHIP',
   'Multi-source research with structured preparation and rehearsal produces the best outcomes. Last-minute cramming and reusing others work limit learning. Video-only learning misses depth that reading provides.',
   60,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- ---- AI READINESS (4 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_AIR_01', 19, 'AI_READINESS',
   'MCQ',
   'A college uses an AI tool to predict which students might fail a course. Which is the BIGGEST ethical concern?',
   CAST('[{"code":"A","label":"The AI might be wrong sometimes"},{"code":"B","label":"Students flagged as at-risk might face bias and reduced opportunities"},{"code":"C","label":"It costs the college too much money to run"},{"code":"D","label":"Teachers might feel replaced by AI"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   0,
   'CORRECT=AI_ETHICS+TECH+SOCIAL',
   'BOOST_AI_ETHICS',
   'Algorithmic bias is the primary concern — if the AI is trained on historical data that reflects systemic inequalities, it can perpetuate discrimination. Being wrong sometimes is expected in any prediction. Cost and teacher feelings are secondary to potential harm to students.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_AIR_02', 20, 'AI_READINESS',
   'MCQ',
   'Which of these tasks is MOST suitable for a large language model (like ChatGPT) to help with?',
   CAST('[{"code":"A","label":"Getting the latest cricket score from today"},{"code":"B","label":"Brainstorming ideas for a research proposal on renewable energy"},{"code":"C","label":"Calculating your exact GPA from grade data"},{"code":"D","label":"Predicting tomorrow stock market prices accurately"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=AI_TECH+RESEARCH',
   'BOOST_AI_TECH',
   'LLMs excel at brainstorming, summarization, and creative ideation. They do NOT have access to real-time data (cricket scores), are unreliable for precise calculations (GPA), and cannot predict future events (stock prices). Understanding AI capabilities and limitations is essential digital literacy.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_AIR_03', 21, 'AI_READINESS',
   'MCQ',
   'You use an AI tool to draft your assignment and submit it as your own work without disclosure. This is:',
   CAST('[{"code":"A","label":"Fine — AI is just a tool like a calculator"},{"code":"B","label":"Academic dishonesty if the assignment requires original thought"},{"code":"C","label":"Always acceptable since everyone does it"},{"code":"D","label":"Only wrong if the professor specifically bans AI"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'EASY',
   0,
   'CORRECT=AI_ETHICS+RESEARCH',
   'BOOST_AI_ETHICS',
   'Submitting AI-generated work as your own without disclosure is academic dishonesty when the assignment tests YOUR understanding and original thinking. Using AI for research, brainstorming, or editing WITH disclosure is different from passing off AI output as your own analysis.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_AIR_04', 22, 'AI_READINESS',
   'MCQ',
   'A hospital deploys an AI system that can diagnose skin conditions from photos with 92% accuracy, while the average dermatologist achieves 87%. Should the hospital rely entirely on the AI?',
   CAST('[{"code":"A","label":"Yes — the AI is more accurate, so replace dermatologists"},{"code":"B","label":"No — AI should assist doctors, not replace clinical judgment"},{"code":"C","label":"Yes — but only for common conditions"},{"code":"D","label":"No — AI can never be used in healthcare"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   0,
   'CORRECT=AI_ETHICS+HEALTH+TECH',
   'BOOST_AI_ETHICS+HEALTH',
   'AI-assisted diagnosis (human-in-the-loop) is the gold standard. Higher average accuracy does not mean AI is right in every case — edge cases, rare conditions, and patient context require human expertise. Complete replacement ignores liability, explainability, and patient trust. Blanket rejection of AI in healthcare is also impractical.',
   90,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- ---- CAREER REALITY (3 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_CR_01', 23, 'CAREER_REALITY',
   'MCQ',
   'Which of these is the MOST important factor that companies look for when hiring fresh graduates in India today?',
   CAST('[{"code":"A","label":"College brand name and rank"},{"code":"B","label":"CGPA above 8.0"},{"code":"C","label":"Problem-solving skills demonstrated through projects and internships"},{"code":"D","label":"Number of certifications on resume"}]' AS JSON),
   'C',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=CAREER_AWARENESS+PROFESSIONAL',
   'BOOST_LEADERSHIP',
   'While college brand and CGPA open doors, demonstrated problem-solving through real projects and internship experience is what drives hiring decisions. Certifications without practical skills are seen as superficial. Industry surveys consistently show employers value applied skills over credentials.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_CR_02', 24, 'CAREER_REALITY',
   'MCQ',
   'A B.Tech graduate wants to work in data science. Which path gives the strongest entry point?',
   CAST('[{"code":"A","label":"Apply directly to data scientist roles at top companies"},{"code":"B","label":"Build a portfolio of 3-4 real data projects on GitHub, learn SQL and Python, then apply to analyst roles"},{"code":"C","label":"Get an MBA first and then transition"},{"code":"D","label":"Wait for the perfect job posting that matches every requirement"}]' AS JSON),
   'B',
   3,
   'POST_12', 'APPLY', 'EASY',
   0,
   'CORRECT=DATA_SCIENCE+TECH+CAREER_AWARENESS',
   'BOOST_TECH',
   'Building a project portfolio demonstrates actual capability. Entry through analyst roles is realistic for freshers. Direct data scientist roles usually require experience. MBA is overkill for technical data roles. Waiting for perfect fits causes analysis paralysis.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_CR_03', 25, 'CAREER_REALITY',
   'MCQ',
   'Which of these is a growing career field in India that did NOT widely exist 5 years ago?',
   CAST('[{"code":"A","label":"Chartered Accountant"},{"code":"B","label":"AI Prompt Engineer and LLM Fine-tuning Specialist"},{"code":"C","label":"Civil Engineer"},{"code":"D","label":"Bank Probationary Officer"}]' AS JSON),
   'B',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=AI_TECH+CAREER_AWARENESS',
   'BOOST_AI_TECH',
   'AI Prompt Engineering and LLM fine-tuning are entirely new roles that emerged with the rise of ChatGPT and large language models post-2022. CA, Civil Engineering, and Bank PO have existed for decades. Awareness of emerging careers helps students stay future-ready.',
   60,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- ---- GENERAL AWARENESS (3 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_GA_01', 26, 'GENERAL_AWARENESS',
   'MCQ',
   'India''s National Education Policy (NEP 2020) introduced a major structural change in higher education. What is it?',
   CAST('[{"code":"A","label":"Mandatory coding from Class 1"},{"code":"B","label":"4-year undergraduate degree with multiple exit options"},{"code":"C","label":"Abolishing board exams entirely"},{"code":"D","label":"Making engineering the only professional degree"}]' AS JSON),
   'B',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=EDUCATION+GOVERNANCE+AWARENESS',
   'BOOST_SOCIAL',
   'NEP 2020 introduced the 4-year undergraduate program with exit points at 1 year (certificate), 2 years (diploma), 3 years (degree), and 4 years (honours/research). This is one of the biggest structural reforms in Indian higher education.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_GA_02', 27, 'GENERAL_AWARENESS',
   'MCQ',
   'Which Indian space mission made India the first country to successfully land near the Moon''s south pole?',
   CAST('[{"code":"A","label":"Mangalyaan"},{"code":"B","label":"Chandrayaan-3"},{"code":"C","label":"Gaganyaan"},{"code":"D","label":"Aditya-L1"}]' AS JSON),
   'B',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=SCIENCE+ENGINEERING+AWARENESS',
   'BOOST_STEM',
   'Chandrayaan-3 successfully soft-landed on the lunar south pole on August 23, 2023, making India the 4th country to land on the Moon and the first to land near the south pole. Mangalyaan was Mars mission. Gaganyaan is the crewed mission (upcoming). Aditya-L1 is the solar observatory.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_GA_03', 28, 'GENERAL_AWARENESS',
   'MCQ',
   'India aims to reach net-zero carbon emissions by which target year?',
   CAST('[{"code":"A","label":"2030"},{"code":"B","label":"2047"},{"code":"C","label":"2070"},{"code":"D","label":"2100"}]' AS JSON),
   'C',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=GREEN+SUSTAINABILITY+AWARENESS',
   'BOOST_GREEN',
   'India pledged net-zero emissions by 2070 at COP26 in Glasgow (2021). This is later than many Western nations (2050) but accounts for India''s development stage. Understanding climate commitments is important for careers in sustainability, policy, and green technology.',
   60,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- Common Core complete: 28 questions (seq 1-28)

COMMIT;
