USE robodynamics_db;

START TRANSACTION;

CREATE TABLE IF NOT EXISTS rd_ci_career_roadmap (
  ci_career_roadmap_id BIGINT NOT NULL AUTO_INCREMENT,
  module_code VARCHAR(40) NOT NULL,
  assessment_version VARCHAR(20) NOT NULL,
  career_code VARCHAR(120) NOT NULL,
  plan_tier VARCHAR(20) NOT NULL,
  grade_stage VARCHAR(40) NOT NULL DEFAULT 'ANY',
  section_type VARCHAR(40) NOT NULL,
  item_order INT NOT NULL DEFAULT 1,
  title VARCHAR(255) DEFAULT NULL,
  detail_text TEXT DEFAULT NULL,
  metadata_json TEXT DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ci_career_roadmap_id),
  UNIQUE KEY uk_ci_career_roadmap (
    module_code,
    assessment_version,
    career_code,
    plan_tier,
    grade_stage,
    section_type,
    item_order
  ),
  KEY idx_ci_career_roadmap_lookup (
    module_code,
    assessment_version,
    career_code,
    plan_tier,
    grade_stage,
    status
  )
);

INSERT INTO rd_ci_career_roadmap
  (module_code, assessment_version, career_code, plan_tier, grade_stage, section_type, item_order, title, detail_text, status, created_at, updated_at)
VALUES
  ('APTIPATH','v3','AI_ML_ENGINEER','BASIC','ANY','OVERVIEW',1,'Career Overview',
   'AI Engineers design and build intelligent systems such as chatbots, recommendation engines, and autonomous solutions.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','BASIC','ANY','RELEVANCE',1,'2026-2036 Relevance',
   'AI adoption across India is accelerating through 2036, creating strong demand in software, manufacturing, healthcare, finance, and public systems.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','BASIC','ANY','SALARY',1,'Salary Band',
   'Entry salary is typically INR 12-25 LPA for strong profiles; growth depends on skills, internships, and portfolio quality.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','BASIC','ANY','PHASE',1,'Foundation (Grades 8-10)',
   'Build strong basics in Math, Science, and problem-solving. Start coding with Python/Scratch and logical puzzles.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','BASIC','ANY','PHASE',2,'Preparation (Grades 11-12)',
   'Prefer PCM with Computer Science. Build exam discipline and strengthen calculus, probability, and programming depth.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','BASIC','ANY','PHASE',3,'Higher Education (Post-12)',
   'Target B.Tech CSE/AI/ML, Data Science, or related pathways through suitable entrance routes.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','BASIC','ANY','PHASE',4,'Skill Building and Experience',
   'Build projects in ML, participate in hackathons, and complete practical internships.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','BASIC','ANY','PHASE',5,'Career Launch (2034-2036)',
   'Start in AI engineer / data roles and progressively specialize in NLP, CV, MLOps, or product AI.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','BASIC','ANY','UPGRADE',1,'Upgrade to Pro',
   'For grade-specific steps, exam combinations, college targeting, and personalized 30/60/90-day plan, upgrade to Pro (INR 1299).','ACTIVE',NOW(),NOW()),

  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','OVERVIEW',1,'Personalized Overview',
   'Based on current profile (Grade {GRADE}, {BOARD}), this path aligns with your analytical and tech readiness signals.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','STUDY',1,'Grade 8-9 Focus',
   'Strengthen Algebra, Geometry, Physics basics, and communication. Track weekly concept mastery.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','STUDY',2,'Grade 10 Focus',
   'Build board-year rigor; target high PCM baseline and basic CS proficiency.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','SKILLS',1,'Core Skills',
   'Python basics, logical thinking, spreadsheet data handling, and disciplined revision routine.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','PROJECTS',1,'Project Path',
   'Begin with chatbot, mini data visualizations, and one practical automation project.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','WHERE_TO_STUDY',1,'Where to Study',
   'Shortlist schools with strong CS labs and mentoring support; map future entrance targets early.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','EXAMS',1,'Exam Pathways',
   'Plan A: JEE route. Plan B: BITSAT / VITEEE / SRMJEEE. Plan C: CUET + private university pathways.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','ACTION_90',1,'Days 1-30',
   '30 minutes daily coding + weekly math reinforcement.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','ACTION_90',2,'Days 31-60',
   'Build first guided project and maintain error log.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','ACTION_90',3,'Days 61-90',
   'Complete mentor review and benchmark test.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','MILESTONE',1,'2030 Milestone',
   'Strong entrance readiness and project portfolio baseline.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','MILESTONE',2,'2032 Milestone',
   'Internship / practical exposure to real datasets and product problems.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','MILESTONE',3,'2036 Milestone',
   'Launch into AI/ML engineering role with specialization path.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','DATABASE_SCALE',1,'Exam Database',
   '12+ entrance routes with attempt/eligibility combinations.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','DATABASE_SCALE',2,'College Database',
   '500+ mapped institutes/program pathways for engineering and AI tracks.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','DATABASE_SCALE',3,'Depth',
   'Grade x stream x career roadmap depth is 5x the Basic layer.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','FOUNDATION_8_10','UPGRADE',1,'Pro Personalization',
   'This Pro plan adapts by grade, board, stream, performance, and evolving intent signals.','ACTIVE',NOW(),NOW()),

  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','SENIOR_11_12','OVERVIEW',1,'Personalized Overview',
   'For Grade {GRADE}, this roadmap prioritizes PCM/CS depth, exam strategy, and portfolio proof aligned to AI roles.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','SENIOR_11_12','STUDY',1,'Grade 11-12 Study Plan',
   'Daily PCM + CS structure with topic rotation, test analysis, and revision loops.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','SENIOR_11_12','SKILLS',1,'Technical Skills',
   'Python, DSA, introductory ML, Git, and clean project documentation.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','SENIOR_11_12','PROJECTS',1,'Project Strategy',
   'Model building projects (classification, regression), hackathon participation, and deployment basics.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','SENIOR_11_12','WHERE_TO_STUDY',1,'College Strategy',
   'Tiered college targeting (dream/match/safe) with entrance-wise pathways and contingency routes.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','SENIOR_11_12','EXAMS',1,'Exam Strategy',
   'Primary: JEE Main/Advanced. Secondary: BITSAT, VITEEE, SRMJEEE, MET, state CET, CUET-based pathways.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','SENIOR_11_12','ACTION_90',1,'Days 1-30',
   'Fix schedule, complete weak-topic map, and enforce timed practice blocks.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','SENIOR_11_12','ACTION_90',2,'Days 31-60',
   'Increase mock intensity and complete one deployable AI mini-project.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','SENIOR_11_12','ACTION_90',3,'Days 61-90',
   'Performance review + attempt strategy lock + final college bracket alignment.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','SENIOR_11_12','MILESTONE',1,'2030 Milestone',
   'Graduate with credible AI portfolio and internship track record.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','SENIOR_11_12','MILESTONE',2,'2032 Milestone',
   'Move into core AI/ML role and specialization pathway.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','AI_ML_ENGINEER','PRO','SENIOR_11_12','MILESTONE',3,'2036 Milestone',
   'Advance to product-critical AI ownership and domain specialization.','ACTIVE',NOW(),NOW()),

  ('APTIPATH','v3','DEFAULT','BASIC','ANY','OVERVIEW',1,'Career Overview',
   '{CAREER} is a viable path when aligned with your strengths, subject readiness, and sustained effort.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','DEFAULT','BASIC','ANY','RELEVANCE',1,'2026-2036 Relevance',
   '2026-2036 will reward students who combine subject depth, execution discipline, and practical skills.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','DEFAULT','BASIC','ANY','SALARY',1,'Career Growth',
   'Salary and growth vary by pathway quality, exams, college, projects, and consistency.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','DEFAULT','BASIC','ANY','PHASE',1,'Foundation',
   'Build core academic clarity and consistent learning habits.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','DEFAULT','BASIC','ANY','PHASE',2,'Preparation',
   'Align stream, subjects, and exam path to target career requirements.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','DEFAULT','BASIC','ANY','PHASE',3,'Execution',
   'Build project/internship evidence and benchmark performance regularly.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','DEFAULT','BASIC','ANY','PHASE',4,'Launch',
   'Enter role-ready pathways and continue specialization with mentor support.','ACTIVE',NOW(),NOW()),
  ('APTIPATH','v3','DEFAULT','BASIC','ANY','UPGRADE',1,'Upgrade to Pro',
   'For personalized grade-wise plan, exam permutations, and college intelligence, upgrade to Pro (INR 1299).','ACTIVE',NOW(),NOW());

COMMIT;
