-- ============================================================
-- AptiPath360 V3 Post-12 COMMERCE & MANAGEMENT Stream Questions
-- 20 questions: Financial Literacy (10) + Business Acumen (10)
-- For: B.Com, BBA, CA, CS, CMA, MBA prep
-- ============================================================

USE robodynamics_db;
START TRANSACTION;

-- ---- FINANCIAL LITERACY (10 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_COM_FL_01', 65, 'FINANCIAL_LITERACY',
   'MCQ',
   'A company''s Balance Sheet shows Total Assets = Rs. 50 lakh and Total Liabilities = Rs. 30 lakh. The Owner''s Equity (Net Worth) is:',
   CAST('[{"code":"A","label":"Rs. 80 lakh"},{"code":"B","label":"Rs. 20 lakh"},{"code":"C","label":"Rs. 30 lakh"},{"code":"D","label":"Rs. 50 lakh"}]' AS JSON),
   'B',
   3,
   'POST_12', 'APPLY', 'EASY',
   0,
   'CORRECT=FINANCE+BUSINESS+ACCOUNTING',
   'BOOST_FINANCE',
   'The fundamental accounting equation: Assets = Liabilities + Equity. Therefore Equity = 50 - 30 = Rs. 20 lakh. This equation is the foundation of double-entry bookkeeping and financial reporting.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_FL_02', 66, 'FINANCIAL_LITERACY',
   'MCQ',
   'You invest Rs. 1,00,000 in a fixed deposit at 7% annual compound interest. After 2 years, the maturity amount is approximately:',
   CAST('[{"code":"A","label":"Rs. 1,14,000"},{"code":"B","label":"Rs. 1,14,490"},{"code":"C","label":"Rs. 1,07,000"},{"code":"D","label":"Rs. 1,21,000"}]' AS JSON),
   'B',
   3,
   'POST_12', 'APPLY', 'EASY',
   0,
   'CORRECT=FINANCE+ANALYTICAL',
   'BOOST_FINANCE',
   'Compound interest: A = P(1+r)^n = 1,00,000 × (1.07)^2 = 1,00,000 × 1.1449 = Rs. 1,14,490. Simple interest would give Rs. 1,14,000 (no compounding). Understanding compound interest is essential for personal finance and banking careers.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_FL_03', 67, 'FINANCIAL_LITERACY',
   'MCQ',
   'GST (Goods and Services Tax) in India replaced multiple indirect taxes. Which of these is NOT a component of GST?',
   CAST('[{"code":"A","label":"CGST (Central GST)"},{"code":"B","label":"SGST (State GST)"},{"code":"C","label":"IGST (Integrated GST)"},{"code":"D","label":"DGST (District GST)"}]' AS JSON),
   'D',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=FINANCE+GOVERNANCE+ACCOUNTING',
   'BOOST_FINANCE',
   'GST has three components: CGST (goes to Centre), SGST (goes to State) for intra-state transactions, and IGST for inter-state transactions. There is no DGST. Understanding India''s tax structure is fundamental for commerce, CA, and business professionals.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_FL_04', 68, 'FINANCIAL_LITERACY',
   'MCQ',
   'A company''s Profit & Loss statement shows Revenue = Rs. 10 crore, COGS = Rs. 6 crore, Operating Expenses = Rs. 2 crore. The operating profit margin is:',
   CAST('[{"code":"A","label":"40%"},{"code":"B","label":"20%"},{"code":"C","label":"60%"},{"code":"D","label":"80%"}]' AS JSON),
   'B',
   4,
   'POST_12', 'ANALYZE', 'MEDIUM',
   0,
   'CORRECT=FINANCE+BUSINESS+ANALYTICAL',
   'BOOST_FINANCE',
   'Operating Profit = Revenue - COGS - OpEx = 10 - 6 - 2 = Rs. 2 crore. Operating Margin = 2/10 × 100 = 20%. Gross Margin would be 40% (before OpEx). Distinguishing gross vs operating vs net margins is essential in financial analysis.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_FL_05', 69, 'FINANCIAL_LITERACY',
   'MCQ',
   'Which financial statement shows the inflows and outflows of cash over a period?',
   CAST('[{"code":"A","label":"Balance Sheet"},{"code":"B","label":"Profit & Loss Account"},{"code":"C","label":"Cash Flow Statement"},{"code":"D","label":"Trial Balance"}]' AS JSON),
   'C',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=FINANCE+ACCOUNTING',
   'BOOST_FINANCE',
   'The Cash Flow Statement tracks actual cash movements in three categories: Operating, Investing, and Financing activities. P&L shows revenues/expenses (accrual basis, not cash). Balance Sheet shows position at a point in time. Trial Balance is a working paper, not a formal statement.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_FL_06', 70, 'FINANCIAL_LITERACY',
   'MCQ',
   'An investor buys shares at Rs. 200 and sells at Rs. 250. The brokerage is 1% on both buy and sell. The net profit per share is approximately:',
   CAST('[{"code":"A","label":"Rs. 50"},{"code":"B","label":"Rs. 45.50"},{"code":"C","label":"Rs. 47.50"},{"code":"D","label":"Rs. 48"}]' AS JSON),
   'B',
   4,
   'POST_12', 'APPLY', 'MEDIUM',
   0,
   'CORRECT=FINANCE+INVESTMENT+ANALYTICAL',
   'BOOST_FINANCE',
   'Buy cost = 200 + 1% of 200 = Rs. 202. Sell proceeds = 250 - 1% of 250 = Rs. 247.50. Net profit = 247.50 - 202 = Rs. 45.50. Transaction costs reduce returns — understanding this is vital for investment analysis.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_FL_07', 71, 'FINANCIAL_LITERACY',
   'MCQ',
   'A startup has high revenue growth but negative cash flow. This MOST likely means:',
   CAST('[{"code":"A","label":"The company is failing and should shut down"},{"code":"B","label":"The company is investing heavily in growth and spending more than it earns currently"},{"code":"C","label":"The revenue numbers are fake"},{"code":"D","label":"The company has no customers"}]' AS JSON),
   'B',
   4,
   'POST_12', 'ANALYZE', 'MEDIUM',
   0,
   'CORRECT=BUSINESS+FINANCE+ENTREPRENEURSHIP',
   'BOOST_FINANCE+BUSINESS',
   'Many high-growth startups operate at a cash loss while scaling — investing in hiring, marketing, and infrastructure. Amazon was cash-flow negative for years while growing revenue. Negative cash flow is concerning only if there is no path to profitability. This is a core concept in startup finance.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_FL_08', 72, 'FINANCIAL_LITERACY',
   'MCQ',
   'Depreciation of a fixed asset represents:',
   CAST('[{"code":"A","label":"The actual market value decline of the asset"},{"code":"B","label":"A systematic allocation of the asset''s cost over its useful life"},{"code":"C","label":"The amount of cash spent on repairs"},{"code":"D","label":"The insurance premium paid for the asset"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=ACCOUNTING+FINANCE',
   'BOOST_FINANCE',
   'Depreciation is an accounting concept that allocates cost over useful life (matching principle). It is NOT about market value or cash outflow. Common methods: Straight Line (equal amounts) and Written Down Value (declining balance). This is fundamental in financial accounting and tax computation.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_FL_09', 73, 'FINANCIAL_LITERACY',
   'MCQ',
   'Under Section 80C of the Income Tax Act, an individual can claim deduction up to Rs. 1.5 lakh for investments in:',
   CAST('[{"code":"A","label":"Only fixed deposits in banks"},{"code":"B","label":"PPF, ELSS, life insurance premium, NPS (Tier 1), and tuition fees among others"},{"code":"C","label":"Only stock market investments"},{"code":"D","label":"Gold jewelry purchases"}]' AS JSON),
   'B',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=FINANCE+TAX+ACCOUNTING',
   'BOOST_FINANCE',
   'Section 80C allows deductions for PPF, ELSS mutual funds, life insurance, NPS, 5-year tax-saving FDs, home loan principal, tuition fees, and more. This is the most commonly used tax-saving provision. Tax planning knowledge is essential for CA, CS, and finance professionals.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_FL_10', 74, 'FINANCIAL_LITERACY',
   'MCQ',
   'What is the key difference between a current account and a savings account in a bank?',
   CAST('[{"code":"A","label":"Current accounts earn higher interest than savings accounts"},{"code":"B","label":"Current accounts are for businesses with unlimited transactions; savings accounts earn interest but have transaction limits"},{"code":"C","label":"Savings accounts cannot be opened by individuals"},{"code":"D","label":"There is no difference — they are the same"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=FINANCE+BANKING',
   'BOOST_FINANCE',
   'Current accounts are designed for businesses with frequent transactions (no interest, no withdrawal limit). Savings accounts earn interest (3-7% in India) but have daily transaction limits. Understanding banking products is fundamental for commerce and finance careers.',
   60,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- ---- BUSINESS ACUMEN (10 questions — includes Management/BBA focus) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_COM_BNA_01', 75, 'BUSINESS_ACUMEN',
   'MCQ',
   'A company uses the "4 Ps of Marketing" framework. Which is NOT one of the 4 Ps?',
   CAST('[{"code":"A","label":"Product"},{"code":"B","label":"Price"},{"code":"C","label":"Profit"},{"code":"D","label":"Promotion"}]' AS JSON),
   'C',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=BUSINESS+MARKETING+MANAGEMENT',
   'BOOST_BUSINESS',
   'The 4 Ps are Product, Price, Place, and Promotion — the marketing mix framework by McCarthy. Profit is an outcome, not a marketing strategy element. Modern versions add People, Process, and Physical Evidence (7 Ps for services).',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_BNA_02', 76, 'BUSINESS_ACUMEN',
   'SITUATIONAL',
   'You are launching a food delivery app in a tier-2 Indian city already served by Swiggy and Zomato. Your BEST differentiation strategy would be:',
   CAST('[{"code":"A","label":"Offer the same service but at half the price permanently"},{"code":"B","label":"Focus on local specialty food, home chefs, and regional cuisine that big apps ignore"},{"code":"C","label":"Copy their app design exactly so users feel familiar"},{"code":"D","label":"Spend all budget on celebrity endorsements"}]' AS JSON),
   'B',
   5,
   'POST_12', 'EVALUATE', 'HARD',
   1,
   'A=PRICE_WAR;B=NICHE_STRATEGY;C=COPYCAT;D=MARKETING_HEAVY',
   'BOOST_BUSINESS+ENTREPRENEURSHIP',
   'Competing on price alone against well-funded incumbents is unsustainable. Niche focus (local cuisine, home chefs) creates a unique value proposition that big players overlook. This is classic Blue Ocean strategy — create uncontested market space rather than compete head-on.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_BNA_03', 77, 'BUSINESS_ACUMEN',
   'MCQ',
   'SWOT analysis in strategic management stands for:',
   CAST('[{"code":"A","label":"Sales, Wages, Operations, Technology"},{"code":"B","label":"Strengths, Weaknesses, Opportunities, Threats"},{"code":"C","label":"Strategy, Workflow, Objectives, Tactics"},{"code":"D","label":"Supply, Warehousing, Orders, Transport"}]' AS JSON),
   'B',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=BUSINESS+MANAGEMENT+LEADERSHIP',
   'BOOST_BUSINESS',
   'SWOT is a strategic planning tool: Strengths and Weaknesses are internal factors; Opportunities and Threats are external. Used in business planning, competitive analysis, and personal career planning. Every MBA and management student must master this framework.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_BNA_04', 78, 'BUSINESS_ACUMEN',
   'SITUATIONAL',
   'As a team leader in a college business competition, two team members have a conflict about the project approach. You should:',
   CAST('[{"code":"A","label":"Take sides with the person you agree with"},{"code":"B","label":"Listen to both perspectives, identify the merits of each, and help the team agree on a combined approach"},{"code":"C","label":"Make the decision yourself without discussion"},{"code":"D","label":"Remove the disagreeing member from the team"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   1,
   'A=BIASED;B=INCLUSIVE_LEADER;C=AUTHORITARIAN;D=EXCLUSIONARY',
   'BOOST_LEADERSHIP+MANAGEMENT',
   'Effective leaders facilitate resolution, not impose it. Listening to both sides, finding common ground, and synthesizing the best approach builds team trust and often produces superior outcomes. This is conflict resolution — a core management competency.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_BNA_05', 79, 'BUSINESS_ACUMEN',
   'MCQ',
   'A company sells 10,000 units at Rs. 100 each. Variable cost is Rs. 60 per unit and fixed costs are Rs. 2,50,000. The break-even point in units is:',
   CAST('[{"code":"A","label":"2,500 units"},{"code":"B","label":"4,167 units"},{"code":"C","label":"6,250 units"},{"code":"D","label":"10,000 units"}]' AS JSON),
   'C',
   4,
   'POST_12', 'APPLY', 'MEDIUM',
   0,
   'CORRECT=FINANCE+BUSINESS+ANALYTICAL',
   'BOOST_FINANCE+BUSINESS',
   'Contribution per unit = Selling Price - Variable Cost = 100 - 60 = Rs. 40. Break-even = Fixed Costs / Contribution per unit = 2,50,000 / 40 = 6,250 units. Below this, the company loses money. Break-even analysis is fundamental in business planning and cost accounting.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_BNA_06', 80, 'BUSINESS_ACUMEN',
   'MCQ',
   'Which leadership style involves the leader making decisions after consulting with the team?',
   CAST('[{"code":"A","label":"Autocratic"},{"code":"B","label":"Laissez-faire"},{"code":"C","label":"Democratic / Participative"},{"code":"D","label":"Transactional"}]' AS JSON),
   'C',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=MANAGEMENT+LEADERSHIP',
   'BOOST_LEADERSHIP',
   'Democratic/Participative leadership involves consulting the team before deciding. Autocratic is unilateral decisions. Laissez-faire is hands-off. Transactional is reward/punishment-based. Understanding leadership styles helps in management and organizational behavior.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_BNA_07', 81, 'BUSINESS_ACUMEN',
   'SITUATIONAL',
   'Your startup receives two funding offers: (A) Rs. 50 lakh from an angel investor for 40% equity, (B) Rs. 30 lakh from a bank as a loan at 12% interest. Your startup has steady revenue. Which is generally better?',
   CAST('[{"code":"A","label":"Angel investment — more money is always better"},{"code":"B","label":"Bank loan — you keep 100% ownership and the interest cost is lower than giving away 40% equity"},{"code":"C","label":"Take both to maximize cash"},{"code":"D","label":"Reject both and bootstrap forever"}]' AS JSON),
   'B',
   5,
   'POST_12', 'EVALUATE', 'HARD',
   1,
   'A=DILUTION_BLIND;B=OWNERSHIP_SMART;C=OVER_CAPITALIZE;D=RIGID',
   'BOOST_ENTREPRENEURSHIP+FINANCE',
   'With steady revenue, a loan at 12% is cheaper than giving up 40% equity (which could be worth crores if the startup succeeds). 40% equity for 50 lakh implies a 1.25 crore valuation — very cheap. Debt preserves ownership. This is the equity vs debt tradeoff — fundamental in startup finance.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_BNA_08', 82, 'BUSINESS_ACUMEN',
   'MCQ',
   'In supply chain management, "Just-In-Time" (JIT) inventory means:',
   CAST('[{"code":"A","label":"Keeping maximum stock to never run out"},{"code":"B","label":"Receiving goods only when needed for production, minimizing storage costs"},{"code":"C","label":"Ordering everything at the start of the year"},{"code":"D","label":"Using only local suppliers regardless of cost"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=BUSINESS+MANAGEMENT+OPERATIONS',
   'BOOST_BUSINESS',
   'JIT reduces inventory holding costs by receiving materials only when needed. Pioneered by Toyota, it requires reliable suppliers and precise demand forecasting. Excess inventory ties up capital and storage space. JIT is a core operations management concept.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_BNA_09', 83, 'BUSINESS_ACUMEN',
   'MCQ',
   'A company''s market share drops from 25% to 20% while the total market size grew by 50%. This means the company''s actual sales:',
   CAST('[{"code":"A","label":"Definitely decreased"},{"code":"B","label":"Could have increased — smaller share of a bigger market can still mean more sales"},{"code":"C","label":"Stayed exactly the same"},{"code":"D","label":"Cannot be determined without more data"}]' AS JSON),
   'B',
   4,
   'POST_12', 'ANALYZE', 'MEDIUM',
   0,
   'CORRECT=BUSINESS+ANALYTICAL+DATA_SCIENCE',
   'BOOST_BUSINESS+ANALYTICAL',
   'If original market = 100, company sales = 25. New market = 150, company sales = 150 × 20% = 30. Sales actually GREW from 25 to 30 despite lower share. Market share vs absolute sales is a crucial distinction in business strategy. Growing markets can benefit all players.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_COM_BNA_10', 84, 'BUSINESS_ACUMEN',
   'SITUATIONAL',
   'You are hired as a management trainee. On your first day, you notice an inefficient process that wastes 2 hours daily. You should:',
   CAST('[{"code":"A","label":"Immediately announce to everyone that the process is inefficient"},{"code":"B","label":"Observe for a week to understand why it exists, then propose an improvement to your manager with data"},{"code":"C","label":"Ignore it — you are too junior to suggest changes"},{"code":"D","label":"Quietly change the process yourself without telling anyone"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   1,
   'A=IMPULSIVE;B=THOUGHTFUL_CONTRIBUTOR;C=PASSIVE;D=ROGUE_OPERATOR',
   'BOOST_LEADERSHIP+MANAGEMENT',
   'Observing first shows respect for existing systems (there may be reasons you do not see). Proposing with data is credible. Announcing inefficiency on day one is presumptuous. Ignoring waste is passive. Changing processes without approval can break dependencies.',
   90,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- Commerce & Management stream complete: 20 questions (seq 65-84)

COMMIT;
