-- ============================================================
-- AptiPath360 V3 Post-12 PURE SCIENCE Stream Questions
-- 18 questions: Scientific Method (10) + Research Aptitude (8)
-- For: B.Sc Physics, Chemistry, Biology, Math, Biotech
-- ============================================================

USE robodynamics_db;
START TRANSACTION;

-- ---- SCIENTIFIC METHOD (10 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_SCI_SM_01', 85, 'SCIENTIFIC_METHOD',
   'MCQ',
   'A researcher observes that plants near a factory grow slower. To test whether factory emissions cause this, the BEST experimental design is:',
   CAST('[{"code":"A","label":"Compare growth of plants near the factory vs identical plants far from the factory under similar conditions"},{"code":"B","label":"Just observe the slow-growing plants for longer"},{"code":"C","label":"Ask factory workers if they think emissions affect plants"},{"code":"D","label":"Read about factories on the internet"}]' AS JSON),
   'A',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   0,
   'CORRECT=RESEARCH+SCIENCE+ENVIRONMENTAL',
   'BOOST_RESEARCH',
   'A controlled experiment with a treatment group (near factory) and control group (far away, same conditions) isolates the variable being tested. Observation alone shows correlation, not causation. Surveys and internet searches are not experimental evidence.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_SM_02', 86, 'SCIENTIFIC_METHOD',
   'MCQ',
   'Which of these is a TESTABLE scientific hypothesis?',
   CAST('[{"code":"A","label":"Plants with blue pots grow better because blue is a nicer color"},{"code":"B","label":"Increasing nitrogen concentration in soil from 2% to 5% will increase wheat yield by at least 15% over 90 days"},{"code":"C","label":"The universe is beautiful"},{"code":"D","label":"Good students always score well"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   0,
   'CORRECT=RESEARCH+SCIENCE',
   'BOOST_RESEARCH',
   'A testable hypothesis must be specific, measurable, and falsifiable. Option B specifies the variable (nitrogen), measurement (yield %), condition (90 days), and threshold (15%). The others are subjective opinions or vague statements that cannot be rigorously tested.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_SM_03', 87, 'SCIENTIFIC_METHOD',
   'MCQ',
   'A researcher finds that ice cream sales and drowning incidents both increase in summer. The CORRECT interpretation is:',
   CAST('[{"code":"A","label":"Ice cream causes drowning"},{"code":"B","label":"Drowning causes people to buy ice cream"},{"code":"C","label":"Both are caused by a common factor (hot weather) — correlation does not imply causation"},{"code":"D","label":"The data must be wrong"}]' AS JSON),
   'C',
   4,
   'POST_12', 'ANALYZE', 'EASY',
   0,
   'CORRECT=RESEARCH+DATA_SCIENCE+SCIENCE',
   'BOOST_RESEARCH+ANALYTICAL',
   'This is the classic example of a confounding variable. Hot weather independently increases both ice cream consumption and swimming (leading to more drownings). Assuming causation from correlation is one of the most common errors in reasoning and data analysis.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_SM_04', 88, 'SCIENTIFIC_METHOD',
   'MCQ',
   'In a chemistry experiment, you measure the boiling point of a liquid three times and get: 78.2°C, 78.5°C, 78.3°C. The accepted value is 78.4°C. These measurements show:',
   CAST('[{"code":"A","label":"High accuracy and high precision"},{"code":"B","label":"Low accuracy and low precision"},{"code":"C","label":"High precision but cannot determine accuracy from this alone"},{"code":"D","label":"High precision and reasonably high accuracy"}]' AS JSON),
   'D',
   4,
   'POST_12', 'ANALYZE', 'MEDIUM',
   0,
   'CORRECT=SCIENCE+RESEARCH+ANALYTICAL',
   'BOOST_RESEARCH',
   'Precision = consistency of measurements (range 0.3°C — high precision). Accuracy = closeness to true value (average 78.33 vs accepted 78.4 — reasonably close). Understanding precision vs accuracy is fundamental in experimental science and quality control.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_SM_05', 89, 'SCIENTIFIC_METHOD',
   'MCQ',
   'A pharmaceutical company claims their new drug reduces fever in 95% of patients based on a trial of 12 patients. A scientist should be MOST concerned about:',
   CAST('[{"code":"A","label":"The drug is too effective"},{"code":"B","label":"The sample size is too small to draw reliable conclusions"},{"code":"C","label":"95% is not 100%"},{"code":"D","label":"Pharmaceutical companies always lie"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   0,
   'CORRECT=RESEARCH+HEALTH+SCIENCE+DATA_SCIENCE',
   'BOOST_RESEARCH',
   'A sample of 12 is far too small for reliable conclusions. With n=12, even 1 non-responder changes the rate from 92% to 83%. Large sample sizes reduce sampling error and increase statistical power. Drug trials typically require hundreds to thousands of participants for regulatory approval.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_SM_06', 90, 'SCIENTIFIC_METHOD',
   'MCQ',
   'The pH of a solution is 3. This means the solution is:',
   CAST('[{"code":"A","label":"Strongly basic (alkaline)"},{"code":"B","label":"Neutral"},{"code":"C","label":"Strongly acidic"},{"code":"D","label":"Mildly basic"}]' AS JSON),
   'C',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=SCIENCE+CHEMISTRY',
   'BOOST_STEM',
   'pH scale: 0-6 = acidic (lower = more acidic), 7 = neutral, 8-14 = basic. pH 3 is strongly acidic (like vinegar or citrus juice). Stomach acid is pH 1-2. Understanding pH is essential in chemistry, biology, environmental science, and food science.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_SM_07', 91, 'SCIENTIFIC_METHOD',
   'MCQ',
   'A radioactive element has a half-life of 10 years. If you start with 80 grams, how much remains after 30 years?',
   CAST('[{"code":"A","label":"40 grams"},{"code":"B","label":"20 grams"},{"code":"C","label":"10 grams"},{"code":"D","label":"0 grams"}]' AS JSON),
   'C',
   3,
   'POST_12', 'APPLY', 'MEDIUM',
   0,
   'CORRECT=SCIENCE+PHYSICS+RESEARCH',
   'BOOST_STEM',
   '30 years = 3 half-lives. After 1 half-life: 80/2 = 40g. After 2: 40/2 = 20g. After 3: 20/2 = 10g. Exponential decay is fundamental in nuclear physics, carbon dating, pharmacology (drug half-life), and environmental science.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_SM_08', 92, 'SCIENTIFIC_METHOD',
   'MCQ',
   'Which microscopy technique is used to visualize structures at the atomic level?',
   CAST('[{"code":"A","label":"Optical (light) microscope"},{"code":"B","label":"Scanning Electron Microscope (SEM)"},{"code":"C","label":"Transmission Electron Microscope (TEM)"},{"code":"D","label":"Magnifying glass"}]' AS JSON),
   'C',
   4,
   'POST_12', 'UNDERSTAND', 'MEDIUM',
   0,
   'CORRECT=SCIENCE+RESEARCH+NANOTECHNOLOGY',
   'BOOST_RESEARCH',
   'TEM can achieve atomic resolution (<0.1 nm) by transmitting electrons through thin specimens. SEM provides surface topology at nanometer scale. Optical microscopes are limited to ~200nm (diffraction limit). Understanding instrumentation is key for experimental scientists.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_SM_09', 93, 'SCIENTIFIC_METHOD',
   'MCQ',
   'In ecology, a food chain always begins with:',
   CAST('[{"code":"A","label":"Herbivores (plant eaters)"},{"code":"B","label":"Producers (plants/algae that perform photosynthesis)"},{"code":"C","label":"Carnivores (predators)"},{"code":"D","label":"Decomposers (fungi and bacteria)"}]' AS JSON),
   'B',
   3,
   'POST_12', 'REMEMBER', 'EASY',
   0,
   'CORRECT=SCIENCE+BIOLOGY+ENVIRONMENTAL',
   'BOOST_STEM+GREEN',
   'Producers (autotrophs) form the base of every food chain by converting solar energy to chemical energy via photosynthesis. Energy flows: Producers → Primary Consumers → Secondary Consumers → Tertiary Consumers. Only ~10% of energy transfers between levels (10% rule).',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_SM_10', 94, 'SCIENTIFIC_METHOD',
   'MCQ',
   'Newton''s Third Law states that for every action there is an equal and opposite reaction. Which real-world example BEST illustrates this?',
   CAST('[{"code":"A","label":"A ball rolling downhill due to gravity"},{"code":"B","label":"A rocket propelling forward by expelling gas backward"},{"code":"C","label":"A book sitting still on a table"},{"code":"D","label":"The sun rising in the east"}]' AS JSON),
   'B',
   3,
   'POST_12', 'APPLY', 'EASY',
   0,
   'CORRECT=SCIENCE+PHYSICS+ENGINEERING',
   'BOOST_STEM',
   'Rocket propulsion is the classic Third Law example: the rocket pushes gas backward (action) and the gas pushes the rocket forward (reaction). The book on a table demonstrates equilibrium (First Law). Gravity is a force, not an action-reaction pair in the Third Law sense.',
   60,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- ---- RESEARCH APTITUDE (8 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_SCI_RA_01', 95, 'RESEARCH_APTITUDE',
   'MCQ',
   'When writing a research paper, a "literature review" section serves to:',
   CAST('[{"code":"A","label":"Summarize your own experimental results"},{"code":"B","label":"Survey existing published research to identify gaps your study addresses"},{"code":"C","label":"List all the books in the university library"},{"code":"D","label":"Write your personal opinions about the topic"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=RESEARCH+SCIENCE+ACADEMIA',
   'BOOST_RESEARCH',
   'A literature review synthesizes prior work to show what is already known, identify gaps, and justify your research question. It demonstrates awareness of the field and positions your contribution. This is a mandatory section in any thesis or journal paper.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_RA_02', 96, 'RESEARCH_APTITUDE',
   'MCQ',
   'Which of these is considered a primary source of scientific information?',
   CAST('[{"code":"A","label":"A Wikipedia article about the topic"},{"code":"B","label":"A peer-reviewed journal paper reporting original experimental findings"},{"code":"C","label":"A news article summarizing research"},{"code":"D","label":"A YouTube video explaining the concept"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=RESEARCH+SCIENCE+ACADEMIA',
   'BOOST_RESEARCH',
   'Primary sources report original research (peer-reviewed journals, conference proceedings, patents). Wikipedia, news, and YouTube are secondary/tertiary sources that summarize primary work. Using primary sources is essential for academic rigor and scientific credibility.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_RA_03', 97, 'RESEARCH_APTITUDE',
   'MCQ',
   'A p-value of 0.03 in a statistical test means:',
   CAST('[{"code":"A","label":"There is a 3% chance the results are correct"},{"code":"B","label":"There is a 3% probability of observing these results if the null hypothesis were true"},{"code":"C","label":"97% of the data is accurate"},{"code":"D","label":"The experiment failed 3% of the time"}]' AS JSON),
   'B',
   4,
   'POST_12', 'UNDERSTAND', 'HARD',
   0,
   'CORRECT=RESEARCH+DATA_SCIENCE+SCIENCE',
   'BOOST_RESEARCH+ANALYTICAL',
   'A p-value is the probability of observing results at least as extreme as those found, assuming the null hypothesis is true. p=0.03 < 0.05 threshold, so we typically reject the null hypothesis. It does NOT mean 3% chance of being correct. P-value interpretation is commonly misunderstood even by researchers.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_RA_04', 98, 'RESEARCH_APTITUDE',
   'SITUATIONAL',
   'You are writing your B.Sc thesis and find a published paper that contradicts your results. You should:',
   CAST('[{"code":"A","label":"Ignore the contradicting paper and only cite papers that agree with you"},{"code":"B","label":"Acknowledge the contradiction, discuss possible reasons for the difference, and suggest further research"},{"code":"C","label":"Change your results to match the published paper"},{"code":"D","label":"Conclude that your entire experiment was wrong"}]' AS JSON),
   'B',
   5,
   'POST_12', 'EVALUATE', 'HARD',
   1,
   'A=CHERRY_PICKER;B=HONEST_RESEARCHER;C=DATA_FABRICATOR;D=DEFEATIST',
   'BOOST_RESEARCH+ETHICS',
   'Scientific integrity requires acknowledging contradictions. Differences could be due to methodology, sample size, conditions, or genuinely different findings. Discussing contradictions strengthens your paper. Cherry-picking citations is a form of research bias. Changing your data is fabrication — a serious ethical violation.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_RA_05', 99, 'RESEARCH_APTITUDE',
   'MCQ',
   'A researcher wants to study the effect of a new fertilizer on crop yield. They divide a field into two halves — one with fertilizer and one without. All other conditions are kept the same. The half without fertilizer is called:',
   CAST('[{"code":"A","label":"The experimental group"},{"code":"B","label":"The control group"},{"code":"C","label":"The variable group"},{"code":"D","label":"The observation group"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=RESEARCH+SCIENCE',
   'BOOST_RESEARCH',
   'The control group receives no treatment and serves as a baseline for comparison. The experimental group receives the treatment (fertilizer). Keeping all other conditions the same (controlled variables) ensures any difference in yield is due to the fertilizer, not other factors.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_RA_06', 100, 'RESEARCH_APTITUDE',
   'MCQ',
   'Which type of research error occurs when a study finds a significant effect that does not actually exist?',
   CAST('[{"code":"A","label":"Type I error (false positive)"},{"code":"B","label":"Type II error (false negative)"},{"code":"C","label":"Sampling error"},{"code":"D","label":"Systematic error"}]' AS JSON),
   'A',
   4,
   'POST_12', 'UNDERSTAND', 'MEDIUM',
   0,
   'CORRECT=RESEARCH+DATA_SCIENCE+SCIENCE',
   'BOOST_RESEARCH+ANALYTICAL',
   'Type I error (alpha error) is a false positive — concluding an effect exists when it does not. Type II (beta error) is a false negative — missing a real effect. The significance level (usually 0.05) sets the acceptable Type I error rate. Understanding error types is essential for research design and data analysis.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_RA_07', 101, 'RESEARCH_APTITUDE',
   'LIKERT',
   'I enjoy reading scientific research papers and understanding methodology, even when the topic is outside my main subject.',
   CAST('[{"code":"1","label":"Strongly disagree"},{"code":"2","label":"Disagree"},{"code":"3","label":"Neutral"},{"code":"4","label":"Agree"},{"code":"5","label":"Strongly agree"}]' AS JSON),
   'PREFERENCE',
   0,
   'POST_12', NULL, NULL,
   1,
   '4-5=RESEARCH+PhD+ACADEMIA;1-2=INDUSTRY+APPLIED;3=BALANCED',
   'BOOST_RESEARCH',
   'Intrinsic curiosity about research methodology across disciplines is a strong predictor of research aptitude and academic career fit. Students who enjoy reading papers often thrive in PhD programs and research roles.',
   30,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_SCI_RA_08', 102, 'RESEARCH_APTITUDE',
   'SITUATIONAL',
   'Your lab partner accidentally deletes some experimental data from the shared folder. Some of it was not backed up. The best approach is:',
   CAST('[{"code":"A","label":"Blame your partner and report them to the professor"},{"code":"B","label":"Recreate the lost data from memory — approximate values are fine"},{"code":"C","label":"Document what was lost, repeat the affected experiments, and set up a backup system"},{"code":"D","label":"Submit the thesis with whatever data remains and hope no one notices"}]' AS JSON),
   'C',
   5,
   'POST_12', 'EVALUATE', 'HARD',
   1,
   'A=BLAME_FIXER;B=DATA_FABRICATOR;C=SYSTEMATIC_RESEARCHER;D=NEGLIGENT',
   'BOOST_RESEARCH+ETHICS',
   'Repeating experiments is the only honest approach. Fabricating data from memory is scientific misconduct. Blaming without fixing does not solve the problem. Hiding data gaps is deceptive. Additionally, establishing backups prevents future loss — systematic problem-solving is a hallmark of good researchers.',
   90,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- Pure Science stream complete: 18 questions (seq 85-102)

COMMIT;
