-- ============================================================
-- AptiPath360 V3 Post-12 HUMANITIES Stream Questions
-- 18 questions: Critical Analysis (10) + Communication & Expression (8)
-- For: BA (English, History, Political Science, Sociology, Psychology,
--       Economics, Journalism, Law prep, Liberal Arts)
-- ============================================================

USE robodynamics_db;
START TRANSACTION;

-- ---- CRITICAL ANALYSIS (10 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_HUM_CRA_01', 103, 'CRITICAL_ANALYSIS',
   'MCQ',
   'A newspaper headline reads: "Study shows mobile phones cause brain cancer." The study was funded by a group that campaigns against mobile towers. The BIGGEST concern about this claim is:',
   CAST('[{"code":"A","label":"Newspapers always publish false information"},{"code":"B","label":"The funding source creates a potential conflict of interest that may bias the study design or interpretation"},{"code":"C","label":"Mobile phones are perfectly safe and no study is needed"},{"code":"D","label":"Only government studies can be trusted"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   0,
   'CORRECT=REASONING+MEDIA+LAW+RESEARCH',
   'BOOST_ANALYTICAL+SOCIAL',
   'Funding source bias is a legitimate concern in research credibility assessment. It does not automatically invalidate the study, but it means the methodology and conclusions should be scrutinized more carefully. Media literacy involves evaluating who funds research and what their agenda might be.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CRA_02', 104, 'CRITICAL_ANALYSIS',
   'MCQ',
   'An argument states: "India should ban all private vehicles because pollution is increasing." Which is the STRONGEST counter-argument?',
   CAST('[{"code":"A","label":"People like their cars too much to give them up"},{"code":"B","label":"A complete ban is disproportionate; incentivizing electric vehicles and improving public transport addresses pollution without eliminating personal mobility"},{"code":"C","label":"Pollution is not actually increasing"},{"code":"D","label":"Other countries have not banned vehicles either"}]' AS JSON),
   'B',
   5,
   'POST_12', 'EVALUATE', 'HARD',
   0,
   'CORRECT=REASONING+LAW+GOVERNANCE+ANALYTICAL',
   'BOOST_ANALYTICAL+SOCIAL',
   'The strongest counter-argument addresses the goal (reducing pollution) while showing the proposed solution is disproportionate and alternatives exist. Personal preference (A) is weak. Denying the premise (C) avoids the argument. Appeal to what others do (D) is irrelevant. Proportionality analysis is central to law and policy.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CRA_03', 105, 'CRITICAL_ANALYSIS',
   'MCQ',
   'Which logical fallacy is present in: "My grandfather smoked his whole life and lived to 95. Therefore, smoking is not harmful."?',
   CAST('[{"code":"A","label":"Ad hominem (attacking the person)"},{"code":"B","label":"Anecdotal evidence (using one case to disprove statistical evidence)"},{"code":"C","label":"Straw man (misrepresenting the argument)"},{"code":"D","label":"False dilemma (only two options presented)"}]' AS JSON),
   'B',
   4,
   'POST_12', 'ANALYZE', 'MEDIUM',
   0,
   'CORRECT=REASONING+LAW+RESEARCH',
   'BOOST_ANALYTICAL',
   'Using one personal example to counter overwhelming statistical evidence is the anecdotal evidence fallacy (also called survivorship bias). Medical research shows smoking significantly increases disease risk — one exception does not disprove the pattern. Recognizing fallacies is essential in law, journalism, and critical thinking.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CRA_04', 106, 'CRITICAL_ANALYSIS',
   'MCQ',
   'The Indian Constitution guarantees the Right to Equality (Article 14). Yet affirmative action (reservations) provides preferential treatment to certain groups. The constitutional justification for this apparent contradiction is:',
   CAST('[{"code":"A","label":"The Constitution allows any form of discrimination"},{"code":"B","label":"Substantive equality — treating unequals equally perpetuates inequality, so affirmative action levels the playing field"},{"code":"C","label":"The Right to Equality was a mistake that should be removed"},{"code":"D","label":"Reservations are unconstitutional but nobody challenges them"}]' AS JSON),
   'B',
   5,
   'POST_12', 'EVALUATE', 'HARD',
   0,
   'CORRECT=LAW+GOVERNANCE+SOCIAL+ETHICS',
   'BOOST_SOCIAL+LAW',
   'The Supreme Court has upheld reservations under the principle of substantive equality (Articles 15(4), 16(4)). Formal equality (treating everyone identically) ignores historical disadvantages. Substantive equality recognizes that different starting points require different support to achieve genuine equal opportunity. This is foundational in constitutional law.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CRA_05', 107, 'CRITICAL_ANALYSIS',
   'MCQ',
   'A social media post claiming "ancient India had nuclear weapons" goes viral with 50,000 shares. Which approach should a critical thinker take?',
   CAST('[{"code":"A","label":"Share it because many people believe it"},{"code":"B","label":"Check the original source, look for peer-reviewed evidence, and cross-reference with established historical and archaeological records"},{"code":"C","label":"Reject it because it sounds unusual"},{"code":"D","label":"Believe it because it promotes national pride"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   0,
   'CORRECT=REASONING+MEDIA+RESEARCH',
   'BOOST_ANALYTICAL',
   'Critical thinking requires source verification, not popularity-based acceptance or reflexive rejection. Extraordinary claims require extraordinary evidence. Cross-referencing with archaeological records and peer-reviewed research is the standard approach. Neither viral shares nor emotional appeal substitute for evidence.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CRA_06', 108, 'CRITICAL_ANALYSIS',
   'MCQ',
   'In a democracy, the primary function of the Opposition in Parliament is:',
   CAST('[{"code":"A","label":"To always oppose every government decision"},{"code":"B","label":"To hold the government accountable, scrutinize legislation, and offer alternative policies"},{"code":"C","label":"To help the ruling party pass all bills quickly"},{"code":"D","label":"To prepare for the next election only"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=GOVERNANCE+LAW+SOCIAL',
   'BOOST_SOCIAL',
   'A healthy opposition provides checks and balances by questioning policies, demanding transparency, and proposing alternatives. Blind opposition and rubber-stamping are both dysfunctional extremes. Parliamentary democracy depends on constructive dissent and debate.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CRA_07', 109, 'CRITICAL_ANALYSIS',
   'MCQ',
   'A historian finds two conflicting accounts of the same event — one from a British colonial officer and one from an Indian freedom fighter. The historian should:',
   CAST('[{"code":"A","label":"Accept only the British account since officers kept official records"},{"code":"B","label":"Accept only the Indian account since it represents the colonized perspective"},{"code":"C","label":"Analyze both accounts for bias, corroborate with other sources, and present a nuanced interpretation"},{"code":"D","label":"Discard both since they disagree"}]' AS JSON),
   'C',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   0,
   'CORRECT=RESEARCH+SOCIAL+EDUCATION',
   'BOOST_RESEARCH+SOCIAL',
   'Historical methodology requires analyzing sources for perspective, bias, and context. Neither account is automatically right or wrong — each reflects a viewpoint. Corroboration with additional sources (other accounts, physical evidence, contemporary records) builds a more complete picture. This is the foundation of critical historiography.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CRA_08', 110, 'CRITICAL_ANALYSIS',
   'MCQ',
   'Which of the following BEST describes "confirmation bias"?',
   CAST('[{"code":"A","label":"Seeking out information that supports your existing beliefs while ignoring contradicting evidence"},{"code":"B","label":"Always agreeing with authority figures"},{"code":"C","label":"Being unable to make decisions"},{"code":"D","label":"Trusting only scientific sources"}]' AS JSON),
   'A',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=REASONING+RESEARCH+SOCIAL',
   'BOOST_ANALYTICAL',
   'Confirmation bias is the tendency to search for, interpret, and remember information that confirms existing beliefs. It affects everyone — researchers, journalists, politicians, and ordinary people. Awareness of this bias is the first step to countering it in decision-making and research.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CRA_09', 111, 'CRITICAL_ANALYSIS',
   'SITUATIONAL',
   'During a class discussion about gender equality, a classmate says: "Women should not work because traditionally they stayed at home." Your BEST analytical response is:',
   CAST('[{"code":"A","label":"Agree because tradition should be respected"},{"code":"B","label":"Point out that appeal to tradition is a logical fallacy — past practices do not justify current norms, and women''s labor force participation has economic and social benefits backed by evidence"},{"code":"C","label":"Get angry and refuse to discuss further"},{"code":"D","label":"Change the topic to avoid conflict"}]' AS JSON),
   'B',
   5,
   'POST_12', 'EVALUATE', 'HARD',
   1,
   'A=TRADITIONALIST;B=EVIDENCE_BASED_ANALYST;C=REACTIVE;D=AVOIDANT',
   'BOOST_SOCIAL+ETHICS',
   'The appeal to tradition fallacy assumes past practices are correct simply because they are traditional. Critical analysis requires evaluating claims against evidence, not history alone. Women''s workforce participation correlates with GDP growth, lower poverty, and better child outcomes. Engaging respectfully with evidence is the hallmark of critical thinking.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CRA_10', 112, 'CRITICAL_ANALYSIS',
   'MCQ',
   'The concept of "soft power" in international relations means:',
   CAST('[{"code":"A","label":"A country''s military strength and nuclear capability"},{"code":"B","label":"A country''s ability to influence others through culture, values, policies, and diplomacy rather than force"},{"code":"C","label":"Economic sanctions imposed on other countries"},{"code":"D","label":"Physical infrastructure like roads and bridges"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=GOVERNANCE+SOCIAL+COMMUNICATION',
   'BOOST_SOCIAL',
   'Soft power (coined by Joseph Nye) is influence through attraction rather than coercion. India''s soft power includes yoga, Bollywood, cuisine, democracy, IT talent, and diaspora. Understanding soft vs hard power is essential in political science, diplomacy, and international relations.',
   60,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- ---- COMMUNICATION & EXPRESSION (8 questions) ----

INSERT INTO rd_ci_question_bank
  (module_code, assessment_version, question_code, sequence_no, section_code,
   question_type, question_text, options_json, correct_option, weightage,
   grade_level, bloom_level, difficulty, is_behavioral, career_cluster_map,
   adaptive_trigger, explanation, time_limit_secs,
   status, created_at, updated_at)
VALUES
  ('APTIPATH', 'v3',
   'APPOST12_HUM_CE_01', 113, 'COMMUNICATION_EXPRESSION',
   'MCQ',
   'In professional email communication, which subject line is MOST effective?',
   CAST('[{"code":"A","label":"Hi!!!"},{"code":"B","label":"Request: Extension for Project Submission — Due March 15"},{"code":"C","label":"URGENT PLEASE READ IMMEDIATELY"},{"code":"D","label":"(no subject)"}]' AS JSON),
   'B',
   3,
   'POST_12', 'APPLY', 'EASY',
   0,
   'CORRECT=COMMUNICATION+PROFESSIONAL',
   'BOOST_COMMUNICATION',
   'Effective subject lines are specific, concise, and action-oriented. They tell the recipient what the email is about and what is needed. Vague subjects, excessive urgency, and missing subjects reduce open rates and professionalism.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CE_02', 114, 'COMMUNICATION_EXPRESSION',
   'SITUATIONAL',
   'You are giving a college presentation and notice the audience looking bored halfway through. The BEST response is:',
   CAST('[{"code":"A","label":"Speed up and rush through the remaining slides"},{"code":"B","label":"Pause, ask an engaging question or share a relevant anecdote, and adjust your pace"},{"code":"C","label":"Stop the presentation and apologize"},{"code":"D","label":"Ignore the audience and continue reading from slides"}]' AS JSON),
   'B',
   4,
   'POST_12', 'APPLY', 'MEDIUM',
   1,
   'A=RUSHER;B=ADAPTIVE_COMMUNICATOR;C=DEFEATIST;D=RIGID_PRESENTER',
   'BOOST_COMMUNICATION+LEADERSHIP',
   'Adaptive communication — reading the room and adjusting — is a hallmark of effective presenters. Questions re-engage attention. Anecdotes create connection. Rushing loses the audience further. Reading from slides is the fastest way to bore any audience.',
   75,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CE_03', 115, 'COMMUNICATION_EXPRESSION',
   'MCQ',
   'Which of these sentences demonstrates the ACTIVE voice (preferred in professional and academic writing)?',
   CAST('[{"code":"A","label":"The report was submitted by the team on Friday"},{"code":"B","label":"The team submitted the report on Friday"},{"code":"C","label":"The submission of the report was done on Friday"},{"code":"D","label":"It was on Friday that the report was submitted"}]' AS JSON),
   'B',
   3,
   'POST_12', 'APPLY', 'EASY',
   0,
   'CORRECT=COMMUNICATION+MEDIA+EDUCATION',
   'BOOST_COMMUNICATION',
   'Active voice (Subject + Verb + Object) is direct, concise, and energetic. Passive voice is wordier and can obscure responsibility. Academic and professional writing style guides (APA, business writing) generally prefer active voice. Exception: scientific methods sections sometimes use passive.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CE_04', 116, 'COMMUNICATION_EXPRESSION',
   'SITUATIONAL',
   'You are writing a newspaper article about a local environmental issue. The factory owner and the affected residents give conflicting accounts. As a journalist, you should:',
   CAST('[{"code":"A","label":"Only quote the residents since they are the victims"},{"code":"B","label":"Only quote the factory owner since they have more authority"},{"code":"C","label":"Present both perspectives fairly, provide factual context from official records, and let readers form their own judgment"},{"code":"D","label":"Write the story based on whichever version is more dramatic"}]' AS JSON),
   'C',
   5,
   'POST_12', 'EVALUATE', 'MEDIUM',
   1,
   'A=BIASED;B=AUTHORITY_BIASED;C=BALANCED_JOURNALIST;D=SENSATIONALIST',
   'BOOST_COMMUNICATION+MEDIA+ETHICS',
   'Balanced journalism presents multiple perspectives with factual evidence and lets readers decide. Favoring either side creates biased reporting. Sensationalism prioritizes drama over truth. Journalism ethics (fairness, accuracy, independence) are the bedrock of press freedom and informed democracy.',
   90,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CE_05', 117, 'COMMUNICATION_EXPRESSION',
   'MCQ',
   'In cross-cultural communication, when an Indian business executive meets a Japanese counterpart for the first time, what is the MOST culturally appropriate greeting?',
   CAST('[{"code":"A","label":"A firm handshake and direct eye contact"},{"code":"B","label":"A respectful bow followed by an exchange of business cards with both hands"},{"code":"C","label":"A hug to show warmth and friendliness"},{"code":"D","label":"Just wave casually from a distance"}]' AS JSON),
   'B',
   3,
   'POST_12', 'APPLY', 'MEDIUM',
   0,
   'CORRECT=COMMUNICATION+BUSINESS+SOCIAL',
   'BOOST_COMMUNICATION+BUSINESS',
   'In Japanese business culture, bowing and meishi koukan (business card exchange) are essential etiquette. Cards are presented and received with both hands and examined respectfully. Understanding cultural communication norms is vital for international business, diplomacy, and global careers.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CE_06', 118, 'COMMUNICATION_EXPRESSION',
   'MCQ',
   'An effective essay introduction should:',
   CAST('[{"code":"A","label":"State your conclusion first and skip background"},{"code":"B","label":"Provide context, state the thesis clearly, and outline what the essay will cover"},{"code":"C","label":"Be as long as possible to show knowledge"},{"code":"D","label":"Start with a dictionary definition of every key term"}]' AS JSON),
   'B',
   3,
   'POST_12', 'UNDERSTAND', 'EASY',
   0,
   'CORRECT=COMMUNICATION+EDUCATION+RESEARCH',
   'BOOST_COMMUNICATION',
   'A strong introduction hooks the reader, provides necessary context, states the thesis (main argument), and previews the structure. Dictionary definitions are cliched. Length should serve purpose, not impress. Clear thesis statements are the foundation of academic and professional writing.',
   60,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CE_07', 119, 'COMMUNICATION_EXPRESSION',
   'LIKERT',
   'I enjoy debating ideas with people who hold completely different opinions from mine.',
   CAST('[{"code":"1","label":"Strongly disagree"},{"code":"2","label":"Disagree"},{"code":"3","label":"Neutral"},{"code":"4","label":"Agree"},{"code":"5","label":"Strongly agree"}]' AS JSON),
   'PREFERENCE',
   0,
   'POST_12', NULL, NULL,
   1,
   '4-5=LAW+GOVERNANCE+MEDIA+LEADERSHIP;1-2=TECHNICAL+INDEPENDENT;3=BALANCED',
   'BOOST_COMMUNICATION',
   'Enjoying intellectual debate with opposing viewpoints indicates strong suitability for law, policy, journalism, diplomacy, and leadership roles where persuasion and argumentation are core skills. Lower scores may indicate preference for consensus-based or technical work environments.',
   30,
   'ACTIVE', NOW(), NOW()),

  ('APTIPATH', 'v3',
   'APPOST12_HUM_CE_08', 120, 'COMMUNICATION_EXPRESSION',
   'SITUATIONAL',
   'You are asked to mediate between two student groups who disagree about how to allocate the college festival budget. Your approach should be:',
   CAST('[{"code":"A","label":"Tell them to figure it out themselves"},{"code":"B","label":"Listen to both sides, identify shared goals, find common ground, and propose a fair compromise"},{"code":"C","label":"Give the entire budget to the louder group"},{"code":"D","label":"Split the budget exactly in half regardless of needs"}]' AS JSON),
   'B',
   4,
   'POST_12', 'EVALUATE', 'MEDIUM',
   1,
   'A=AVOIDANT;B=SKILLED_MEDIATOR;C=POWER_BIASED;D=MECHANICAL',
   'BOOST_LEADERSHIP+SOCIAL+COMMUNICATION',
   'Effective mediation involves active listening, identifying underlying interests (not just stated positions), finding shared goals, and crafting solutions that address core needs of both parties. Equal splits ignore different needs. Power-based decisions create resentment. This is a core conflict resolution skill.',
   90,
   'ACTIVE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  sequence_no = VALUES(sequence_no), question_text = VALUES(question_text),
  options_json = VALUES(options_json), correct_option = VALUES(correct_option),
  weightage = VALUES(weightage), grade_level = VALUES(grade_level),
  bloom_level = VALUES(bloom_level), difficulty = VALUES(difficulty),
  is_behavioral = VALUES(is_behavioral), career_cluster_map = VALUES(career_cluster_map),
  adaptive_trigger = VALUES(adaptive_trigger), explanation = VALUES(explanation),
  time_limit_secs = VALUES(time_limit_secs), status = 'ACTIVE', updated_at = NOW();

-- Humanities stream complete: 18 questions (seq 103-120)

COMMIT;
