USE robodynamics_db;
SET SQL_SAFE_UPDATES=0;
START TRANSACTION;
SET @course_name='CBSE Grade 12 Physics (NCERT) - Part 1';
SET @import_tag='import_cbse_grade_12_physics_part_1_2026_03_04';
INSERT INTO rd_courses (course_category_id,course_name,course_description,shortDescription,course_level,course_status,grade_range,category,is_featured,tier_level,tier_order,reviews_count,is_active)
SELECT 14,@course_name,'NCERT Class 12 Physics chapters imported from docs/course_materials/cbse_grade_12_physics_part_1.','Auto-imported from leph1ps.pdf table of contents and chapter PDFs.','12','ACTIVE','SENIOR_SECONDARY','Physics',0,'beginner',1,0,1
WHERE NOT EXISTS (SELECT 1 FROM rd_courses WHERE course_name=@course_name);
SET @course_id=(SELECT course_id FROM rd_courses WHERE course_name=@course_name ORDER BY course_id DESC LIMIT 1);
DELETE d FROM rd_course_session_details d JOIN rd_course_sessions s ON s.course_session_id=d.course_session_id WHERE s.course_id=@course_id AND COALESCE(s.session_description,'')=@import_tag;
DELETE FROM rd_course_sessions WHERE course_id=@course_id AND COALESCE(session_description,'')=@import_tag;
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,1,'Chapter 1: Electric Charges And Fields',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',1);
SET @s1=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 1: Electric Charges And Fields',CURDATE(),1,@course_id,@s1,'pdf','leph101.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,2,'Chapter 2: Electrostatic Potential And Capacitance',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',2);
SET @s2=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 2: Electrostatic Potential And Capacitance',CURDATE(),1,@course_id,@s2,'pdf','leph102.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,3,'Chapter 3: Current Electricity',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',3);
SET @s3=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 3: Current Electricity',CURDATE(),1,@course_id,@s3,'pdf','leph103.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,4,'Chapter 4: Moving Charges And Magnetism',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',4);
SET @s4=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 4: Moving Charges And Magnetism',CURDATE(),1,@course_id,@s4,'pdf','leph104.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,5,'Chapter 5: Magnetism And Matter',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',5);
SET @s5=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 5: Magnetism And Matter',CURDATE(),1,@course_id,@s5,'pdf','leph105.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,6,'Chapter 6: Electromagnetic Induction',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',6);
SET @s6=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 6: Electromagnetic Induction',CURDATE(),1,@course_id,@s6,'pdf','leph106.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,7,'Chapter 7: Alternating Current',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',7);
SET @s7=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 7: Alternating Current',CURDATE(),1,@course_id,@s7,'pdf','leph107.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,8,'Chapter 8: Electromagnetic Waves',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',8);
SET @s8=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 8: Electromagnetic Waves',CURDATE(),1,@course_id,@s8,'pdf','leph108.pdf',1,'BEGINNER',1,0,0);
COMMIT;
SELECT @course_id AS course_id;
SELECT COUNT(*) AS imported_sessions FROM rd_course_sessions WHERE course_id=@course_id AND COALESCE(session_description,'')=@import_tag;
SELECT COUNT(*) AS imported_pdf_details FROM rd_course_session_details d JOIN rd_course_sessions s ON s.course_session_id=d.course_session_id WHERE s.course_id=@course_id AND COALESCE(s.session_description,'')=@import_tag AND LOWER(COALESCE(d.type,''))='pdf';
SELECT s.session_id,s.session_title,d.file FROM rd_course_sessions s LEFT JOIN rd_course_session_details d ON d.course_session_id=s.course_session_id AND LOWER(COALESCE(d.type,''))='pdf' WHERE s.course_id=@course_id AND COALESCE(s.session_description,'')=@import_tag ORDER BY s.session_id;
