USE robodynamics_db;
SET SQL_SAFE_UPDATES=0;
START TRANSACTION;
SET @course_name='CBSE Grade 10 Science (NCERT)';
SET @import_tag='import_cbse_grade_10_science_2026_03_04';
INSERT INTO rd_courses (course_category_id,course_name,course_description,shortDescription,course_level,course_status,grade_range,category,is_featured,tier_level,tier_order,reviews_count,is_active)
SELECT 15,@course_name,'NCERT Class 10 Science chapters imported from docs/course_materials/cbse_grade_10_science.','Auto-imported from jesc1ps.pdf table of contents and chapter PDFs.','10','ACTIVE','HIGH_SCHOOL_10_12','Science',0,'beginner',1,0,1
WHERE NOT EXISTS (SELECT 1 FROM rd_courses WHERE course_name=@course_name);
SET @course_id=(SELECT course_id FROM rd_courses WHERE course_name=@course_name ORDER BY course_id DESC LIMIT 1);
DELETE d FROM rd_course_session_details d JOIN rd_course_sessions s ON s.course_session_id=d.course_session_id WHERE s.course_id=@course_id AND COALESCE(s.session_description,'')=@import_tag;
DELETE FROM rd_course_sessions WHERE course_id=@course_id AND COALESCE(session_description,'')=@import_tag;
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,1,'Chapter 1: Chemical Reactions and Equations',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',1);
SET @s1=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 1: Chemical Reactions and Equations',CURDATE(),1,@course_id,@s1,'pdf','jesc101.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,2,'Chapter 2: Acids, Bases and Salts',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',2);
SET @s2=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 2: Acids, Bases and Salts',CURDATE(),1,@course_id,@s2,'pdf','jesc102.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,3,'Chapter 3: Metals and Non-metals',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',3);
SET @s3=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 3: Metals and Non-metals',CURDATE(),1,@course_id,@s3,'pdf','jesc103.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,4,'Chapter 4: Carbon and its Compounds',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',4);
SET @s4=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 4: Carbon and its Compounds',CURDATE(),1,@course_id,@s4,'pdf','jesc104.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,5,'Chapter 5: Life Processes',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',5);
SET @s5=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 5: Life Processes',CURDATE(),1,@course_id,@s5,'pdf','jesc105.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,6,'Chapter 6: Control and Coordination',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',6);
SET @s6=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 6: Control and Coordination',CURDATE(),1,@course_id,@s6,'pdf','jesc106.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,7,'Chapter 7: How do Organisms Reproduce?',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',7);
SET @s7=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 7: How do Organisms Reproduce?',CURDATE(),1,@course_id,@s7,'pdf','jesc107.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,8,'Chapter 8: Heredity',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',8);
SET @s8=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 8: Heredity',CURDATE(),1,@course_id,@s8,'pdf','jesc108.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,9,'Chapter 9: Light - Reflection and Refraction',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',9);
SET @s9=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 9: Light - Reflection and Refraction',CURDATE(),1,@course_id,@s9,'pdf','jesc109.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,10,'Chapter 10: The Human Eye and the Colourful World',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',10);
SET @s10=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 10: The Human Eye and the Colourful World',CURDATE(),1,@course_id,@s10,'pdf','jesc110.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,11,'Chapter 11: Electricity',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',11);
SET @s11=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 11: Electricity',CURDATE(),1,@course_id,@s11,'pdf','jesc111.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,12,'Chapter 12: Magnetic Effects of Electric Current',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',12);
SET @s12=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 12: Magnetic Effects of Electric Current',CURDATE(),1,@course_id,@s12,'pdf','jesc112.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,13,'Chapter 13: Our Environment',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',13);
SET @s13=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 13: Our Environment',CURDATE(),1,@course_id,@s13,'pdf','jesc113.pdf',1,'BEGINNER',1,0,0);
COMMIT;
SELECT @course_id AS course_id;
SELECT COUNT(*) AS imported_sessions FROM rd_course_sessions WHERE course_id=@course_id AND COALESCE(session_description,'')=@import_tag;
SELECT COUNT(*) AS imported_pdf_details FROM rd_course_session_details d JOIN rd_course_sessions s ON s.course_session_id=d.course_session_id WHERE s.course_id=@course_id AND COALESCE(s.session_description,'')=@import_tag AND LOWER(COALESCE(d.type,''))='pdf';
SELECT s.session_id,s.session_title,d.file FROM rd_course_sessions s LEFT JOIN rd_course_session_details d ON d.course_session_id=s.course_session_id AND LOWER(COALESCE(d.type,''))='pdf' WHERE s.course_id=@course_id AND COALESCE(s.session_description,'')=@import_tag ORDER BY s.session_id;
