const fs = require('fs');
const path = 'C:/roboworkspace/robodynamics/ai-tutor/web/app/ai-tutor/tutor/TutorClient.tsx';
let content = fs.readFileSync(path, 'utf8');
const nl = content.includes('\r\n') ? '\r\n' : '\n';
const j = (lines) => lines.join(nl);

function replaceRegex(label, pattern, replacement) {
  if (!pattern.test(content)) {
    throw new Error(`Replacement target not found: ${label}`);
  }
  content = content.replace(pattern, replacement);
}

replaceRegex(
  'minimal focus ternary',
  /                    \{stageSceneMode === "coach" \? \([\s\S]*?                    \)\}[\r\n]+[\r\n]+                    \{check \? \(/,
  j([
    '                    {stageSceneMode === "coach" ? (',
    '                      <>',
    '                        {showInlineBoard ? (',
    '                          <div className="vedic-inline-board vedic-focus-board">',
    '                            <AnimatedBoard',
    '                              steps={boardSteps}',
    '                              runId={boardRunId}',
    '                              showPrompt={isTeachingBoard}',
    '                            />',
    '                          </div>',
    '                        ) : null}',
    '                        <div className="vedic-focus-actions">',
    '                          {showWorkedBoardSupport && !showInlineBoard ? (',
    '                            <button className="button secondary" type="button" onClick={() => void teachOnBoard()} disabled={isTeachingBoard || isSpeaking}>',
    '                              Show Steps',
    '                            </button>',
    '                          ) : null}',
    '                          <button',
    '                            className="button vedic-primary-btn"',
    '                            type="button"',
    '                            onClick={() => {',
    '                              stopListeningSession();',
    '                              setAwaitingStudentResponse(true);',
    '                            }}',
    '                            disabled={sessionProgress.livesDepleted}',
    '                          >',
    '                            Try It',
    '                          </button>',
    '                        </div>',
    '                      </>',
    '                    ) : (',
    '                      <>',
    '                        <div className="vedic-focus-panel question student">',
    '                          <span className="vedic-prompt-label">Try this</span>',
    '                          <p className="udemy-question-text"><strong>{question.questionText}</strong></p>',
    '                          {question.visual?.svg ? (',
    '                            <div className="udemy-visual panel" dangerouslySetInnerHTML={{ __html: question.visual.svg }} />',
    '                          ) : null}',
    '                        </div>',
    '                        <div className="vedic-answer-block vedic-answer-block-inline">',
    '                          <label',
    '                            htmlFor="answerInput"',
    '                            className="udemy-answer-label"',
    '                            style={{ color: awaitingStudentResponse ? "#166534" : "#334155" }}',
    '                          >',
    '                            Your Answer',
    '                          </label>',
    '                          <input',
    '                            id="answerInput"',
    '                            ref={answerInputRef}',
    '                            disabled={!canAttemptAnswer}',
    '                            value={answer}',
    '                            onChange={(e) => {',
    '                              setAnswer(e.target.value);',
    '                              setLastAnswerMode("typed");',
    '                            }}',
    '                            onKeyDown={(e) => {',
    '                              if (e.key === "Enter") {',
    '                                e.preventDefault();',
    '                                void checkAnswer();',
    '                              }',
    '                            }}',
    '                            placeholder="Type your answer"',
    '                            className="vedic-answer-input"',
    '                          />',
    '                          <p className="muted udemy-hint">Answer the question above.</p>',
    '                          {micPermission === "denied" ? (',
    '                            <p className="muted" style={{ marginTop: "0.35rem", marginBottom: 0 }}>',
    '                              Microphone access is blocked. Use text input.',
    '                            </p>',
    '                          ) : null}',
    '                          {sessionProgress.livesDepleted ? (',
    '                            <p className="vedic-alert">No hearts left. Do a review round to continue. {reviewLoopPrompt}</p>',
    '                          ) : null}',
    '',
    '                          <div className="vedic-action-row">',
    '                            <button className="button vedic-primary-btn" onClick={() => void checkAnswer()} disabled={isEvaluatingAnswer || !canAttemptAnswer}>',
    '                              {isEvaluatingAnswer ? "Checking..." : "Check"}',
    '                            </button>',
    '                            <button',
    '                              className="button secondary"',
    '                              type="button"',
    '                              onClick={listenAnswer}',
    '                              disabled={isEvaluatingAnswer || isListening || micPermission === "denied" || !canAttemptAnswer}',
    '                            >',
    '                              {micPermission === "denied" ? "Mic Blocked" : isListening ? "Listening..." : "Speak"}',
    '                            </button>',
    '                            {isListening ? (',
    '                              <button',
    '                                className="button secondary"',
    '                                type="button"',
    '                                onClick={() => {',
    '                                  stopListeningSession();',
    '                                  setAwaitingStudentResponse(true);',
    '                                  addConversationTurn("system", "system", "Voice listening stopped by student.", { source: "listen_stop" });',
    '                                }}',
    '                              >',
    '                                Stop',
    '                              </button>',
    '                            ) : null}',
    '                            <button className="button secondary" onClick={() => { void nextQuestion({ directToStudent: true, source: "skip" }); }}>Skip</button>',
    '                          </div>',
    '                        </div>',
    '                      </>',
    '                    )}',
    '',
    '                    {check ? (',
  ])
);

replaceRegex(
  'minimal support block removal',
  /\r?\n              \{showWorkedBoardSupport \|\| showHelpDrawer \? \([\s\S]*?              \) : null\}/,
  ''
);

fs.writeFileSync(path, content, 'utf8');
