/**
 * Kaveri Level 3 — ಒತ್ತಕ್ಷರ (Ottakshara / Consonant Conjuncts)
 * 38 lessons · 3 chapters
 *
 * C01: ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ (Doubled consonants)  — 14 lessons
 *      ಕ್ಕ ಗ್ಗ ಚ್ಚ ಟ್ಟ ತ್ತ ದ್ದ ಪ್ಪ ಬ್ಬ ಮ್ಮ ಲ್ಲ ಣ್ಣ ನ್ನ ಡ್ಡ + Review
 * C02: ರ/ಲ ಒತ್ತಕ್ಷರ (Clusters with ra / la)   — 12 lessons
 *      ಕ್ರ ಗ್ರ ಪ್ರ ಬ್ರ ತ್ರ ದ್ರ ಶ್ರ ಕ್ಲ ಪ್ಲ ಬ್ಲ ಗ್ಲ + Review
 * C03: ವಿಶೇಷ ಒತ್ತಕ್ಷರ (Special conjuncts)     — 12 lessons
 *      ಕ್ಷ ಜ್ಞ ಸ್ನ ಸ್ಕ ಸ್ಪ ನ್ಯ ತ್ಯ ಧ್ಯ ಕ್ತ ಸ್ಮ ಸ್ತ + Review
 */

export interface Level3Seed {
  id: string;
  chapterId: string;
  chapterTitle: string;
  title: string;
  category: string;
  skill: string;
  consonant1: string;
  consonant1SoundRoman?: string;
  consonant2: string;
  consonant2SoundRoman?: string;
  combinedChar: string;
  combinedSoundRoman?: string;
  halantForm: string;
  wordKannada: string;
  wordEnglish: string;
  wordRoman: string;
  assetPath: string;
  durationMin?: number;
  summary: string;
  prompt: string;
}

// ============================================================
// CHAPTER C01 — ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ (Doubled consonants) — 14 lessons
// ============================================================

export const LEVEL_3_DATA: Level3Seed[] = [

  {
    id: "L3-C01-L01",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ಕ್ಕ — ಅಕ್ಕ (Elder Sister)",
    category: "Doubled Consonant",
    skill: "Ottakshara Introduction",
    consonant1: "ಕ",
    consonant1SoundRoman: "ka",
    consonant2: "ಕ",
    consonant2SoundRoman: "ka",
    combinedChar: "ಕ್ಕ",
    combinedSoundRoman: "kka",
    halantForm: "ಕ್",
    wordKannada: "ಅಕ್ಕ",
    wordEnglish: "Elder Sister",
    wordRoman: "akka",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_akka_kka.png",
    summary: "When ಕ meets ಕ with a virama, it doubles into ಕ್ಕ — say it strong!",
    prompt: "ಕ + ್ + ಕ = ಕ್ಕ! ಅಕ್ಕ means 'elder sister' — do you have one?",
  },
  {
    id: "L3-C01-L02",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ಗ್ಗ — ಮಗ್ಗ (Loom)",
    category: "Doubled Consonant",
    skill: "Doubled-G Sound",
    consonant1: "ಗ",
    consonant1SoundRoman: "ga",
    consonant2: "ಗ",
    consonant2SoundRoman: "ga",
    combinedChar: "ಗ್ಗ",
    combinedSoundRoman: "gga",
    halantForm: "ಗ್",
    wordKannada: "ಮಗ್ಗ",
    wordEnglish: "Loom",
    wordRoman: "magga",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_magga_gga.png",
    summary: "ಗ + ್ + ಗ = ಗ್ಗ — the sound deepens when consonants double up.",
    prompt: "ಮಗ್ಗ is a weaving loom — feel the heavy 'gga' sound!",
  },
  {
    id: "L3-C01-L03",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ಚ್ಚ — ಹೆಚ್ಚು (More)",
    category: "Doubled Consonant",
    skill: "Doubled-CH Sound",
    consonant1: "ಚ",
    consonant1SoundRoman: "cha",
    consonant2: "ಚ",
    consonant2SoundRoman: "cha",
    combinedChar: "ಚ್ಚ",
    combinedSoundRoman: "ccha",
    halantForm: "ಚ್",
    wordKannada: "ಹೆಚ್ಚು",
    wordEnglish: "More",
    wordRoman: "hechchu",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_hechchu_ccha.png",
    summary: "ಚ + ್ + ಚ = ಚ್ಚ — double the consonant, double the emphasis!",
    prompt: "ಹೆಚ್ಚು means 'more' — say it with a crisp 'ccha' sound!",
  },
  {
    id: "L3-C01-L04",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ಟ್ಟ — ಮೊಟ್ಟೆ (Egg)",
    category: "Doubled Consonant",
    skill: "Retroflex Doubled-T",
    consonant1: "ಟ",
    consonant1SoundRoman: "ta",
    consonant2: "ಟ",
    consonant2SoundRoman: "ta",
    combinedChar: "ಟ್ಟ",
    combinedSoundRoman: "tta",
    halantForm: "ಟ್",
    wordKannada: "ಮೊಟ್ಟೆ",
    wordEnglish: "Egg",
    wordRoman: "motte",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_motte_tta.png",
    summary: "ಟ + ್ + ಟ = ಟ್ಟ — a strong retroflex double stop.",
    prompt: "ಮೊಟ್ಟೆ is an egg! Curl your tongue back for the 'tta' sound.",
  },
  {
    id: "L3-C01-L05",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ತ್ತ — ಹತ್ತು (Ten)",
    category: "Doubled Consonant",
    skill: "Dental Doubled-T",
    consonant1: "ತ",
    consonant1SoundRoman: "ta",
    consonant2: "ತ",
    consonant2SoundRoman: "ta",
    combinedChar: "ತ್ತ",
    combinedSoundRoman: "tta",
    halantForm: "ತ್",
    wordKannada: "ಹತ್ತು",
    wordEnglish: "Ten",
    wordRoman: "hattu",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_hattu_tta.png",
    summary: "ತ + ್ + ತ = ತ್ತ — the dental double is softer than the retroflex ಟ್ಟ.",
    prompt: "ಹತ್ತು means ten! Count ten things and say 'hattu'!",
  },
  {
    id: "L3-C01-L06",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ದ್ದ — ಮದ್ದು (Medicine)",
    category: "Doubled Consonant",
    skill: "Doubled-D Sound",
    consonant1: "ದ",
    consonant1SoundRoman: "da",
    consonant2: "ದ",
    consonant2SoundRoman: "da",
    combinedChar: "ದ್ದ",
    combinedSoundRoman: "dda",
    halantForm: "ದ್",
    wordKannada: "ಮದ್ದು",
    wordEnglish: "Medicine",
    wordRoman: "maddu",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_maddu_dda.png",
    summary: "ದ + ್ + ದ = ದ್ದ — a deep doubled dental sound.",
    prompt: "ಮದ್ದು is medicine — the 'dda' keeps the sound firm!",
  },
  {
    id: "L3-C01-L07",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ಪ್ಪ — ಅಪ್ಪ (Father)",
    category: "Doubled Consonant",
    skill: "Doubled-P Sound",
    consonant1: "ಪ",
    consonant1SoundRoman: "pa",
    consonant2: "ಪ",
    consonant2SoundRoman: "pa",
    combinedChar: "ಪ್ಪ",
    combinedSoundRoman: "ppa",
    halantForm: "ಪ್",
    wordKannada: "ಅಪ್ಪ",
    wordEnglish: "Father",
    wordRoman: "appa",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_appa_ppa.png",
    summary: "ಪ + ್ + ಪ = ಪ್ಪ — your beloved ಅಪ್ಪ is one of the first words in Kannada!",
    prompt: "ಅಪ್ಪ means dad — say it warmly with a strong 'ppa'!",
  },
  {
    id: "L3-C01-L08",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ಬ್ಬ — ಹಬ್ಬ (Festival)",
    category: "Doubled Consonant",
    skill: "Doubled-B Sound",
    consonant1: "ಬ",
    consonant1SoundRoman: "ba",
    consonant2: "ಬ",
    consonant2SoundRoman: "ba",
    combinedChar: "ಬ್ಬ",
    combinedSoundRoman: "bba",
    halantForm: "ಬ್",
    wordKannada: "ಹಬ್ಬ",
    wordEnglish: "Festival",
    wordRoman: "habba",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_habba_bba.png",
    summary: "ಬ + ್ + ಬ = ಬ್ಬ — festivals are doubly joyful!",
    prompt: "ಹಬ್ಬ is a festival! Say it with celebration in your voice!",
  },
  {
    id: "L3-C01-L09",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ಮ್ಮ — ಅಮ್ಮ (Mother)",
    category: "Doubled Consonant",
    skill: "Doubled-M Sound",
    consonant1: "ಮ",
    consonant1SoundRoman: "ma",
    consonant2: "ಮ",
    consonant2SoundRoman: "ma",
    combinedChar: "ಮ್ಮ",
    combinedSoundRoman: "mma",
    halantForm: "ಮ್",
    wordKannada: "ಅಮ್ಮ",
    wordEnglish: "Mother",
    wordRoman: "amma",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_amma_mma.png",
    summary: "ಮ + ್ + ಮ = ಮ್ಮ — ಅಮ್ಮ is the warmest word in Kannada!",
    prompt: "ಅಮ್ಮ means mum — say it with love, nice and warm!",
  },
  {
    id: "L3-C01-L10",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ಲ್ಲ — ಹಲ್ಲು (Tooth)",
    category: "Doubled Consonant",
    skill: "Doubled-L Sound",
    consonant1: "ಲ",
    consonant1SoundRoman: "la",
    consonant2: "ಲ",
    consonant2SoundRoman: "la",
    combinedChar: "ಲ್ಲ",
    combinedSoundRoman: "lla",
    halantForm: "ಲ್",
    wordKannada: "ಹಲ್ಲು",
    wordEnglish: "Tooth",
    wordRoman: "hallu",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_hallu_lla.png",
    summary: "ಲ + ್ + ಲ = ಲ್ಲ — roll the tongue lightly for this liquid double.",
    prompt: "ಹಲ್ಲು is a tooth! Smile wide and say 'hallu'!",
  },
  {
    id: "L3-C01-L11",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ಣ್ಣ — ಕಣ್ಣು (Eye)",
    category: "Doubled Consonant",
    skill: "Retroflex Doubled-N",
    consonant1: "ಣ",
    consonant1SoundRoman: "na",
    consonant2: "ಣ",
    consonant2SoundRoman: "na",
    combinedChar: "ಣ್ಣ",
    combinedSoundRoman: "nna",
    halantForm: "ಣ್",
    wordKannada: "ಕಣ್ಣು",
    wordEnglish: "Eye",
    wordRoman: "kannu",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_kannu_nna.png",
    summary: "ಣ + ್ + ಣ = ಣ್ಣ — retroflex nasal doubled, deep and resonant.",
    prompt: "ಕಣ್ಣು means eye — open wide and say 'kannu'!",
  },
  {
    id: "L3-C01-L12",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ನ್ನ — ಅನ್ನ (Rice)",
    category: "Doubled Consonant",
    skill: "Dental Doubled-N",
    consonant1: "ನ",
    consonant1SoundRoman: "na",
    consonant2: "ನ",
    consonant2SoundRoman: "na",
    combinedChar: "ನ್ನ",
    combinedSoundRoman: "nna",
    halantForm: "ನ್",
    wordKannada: "ಅನ್ನ",
    wordEnglish: "Rice",
    wordRoman: "anna",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_anna_nna.png",
    summary: "ನ + ್ + ನ = ನ್ನ — a soft dental nasal double that appears in many everyday words.",
    prompt: "ಅನ್ನ is rice — the staple food! Say 'anna' with a soft nasal!",
  },
  {
    id: "L3-C01-L13",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "ಡ್ಡ — ಕಡ್ಡಿ (Matchstick)",
    category: "Doubled Consonant",
    skill: "Retroflex Doubled-D",
    consonant1: "ಡ",
    consonant1SoundRoman: "da",
    consonant2: "ಡ",
    consonant2SoundRoman: "da",
    combinedChar: "ಡ್ಡ",
    combinedSoundRoman: "dda",
    halantForm: "ಡ್",
    wordKannada: "ಕಡ್ಡಿ",
    wordEnglish: "Matchstick",
    wordRoman: "kaddi",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_kaddi_dda.png",
    summary: "ಡ + ್ + ಡ = ಡ್ಡ — retroflex doubled D, strong and sharp.",
    prompt: "ಕಡ್ಡಿ is a matchstick — thin but important! Snap your tongue for 'dda'!",
  },
  {
    id: "L3-C01-L14",
    chapterId: "C01",
    chapterTitle: "ದ್ವಿತ್ವ ಒತ್ತಕ್ಷರ",
    title: "Chapter 1 Review — Doubled Consonants",
    category: "Consolidation",
    skill: "Doubled Conjunct Mastery",
    consonant1: "ಕ",
    consonant1SoundRoman: "ka",
    consonant2: "ಕ",
    consonant2SoundRoman: "ka",
    combinedChar: "ಕ್ಕ",
    combinedSoundRoman: "kka",
    halantForm: "ಕ್",
    wordKannada: "ಅಕ್ಕ",
    wordEnglish: "Elder Sister",
    wordRoman: "akka",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_review_c01.png",
    summary: "You've learned 13 doubled consonant ottakshara — ಅಪ್ಪ, ಅಮ್ಮ, ಅಕ್ಕ and more!",
    prompt: "Can you recall all the doubled ottakshara you've learned?",
  },

  // ============================================================
  // CHAPTER C02 — ರ/ಲ ಒತ್ತಕ್ಷರ (ra/la clusters) — 12 lessons
  // ============================================================

  {
    id: "L3-C02-L01",
    chapterId: "C02",
    chapterTitle: "ರ/ಲ ಒತ್ತಕ್ಷರ",
    title: "ಕ್ರ — ಕ್ರಮ (Order)",
    category: "Ra-La Cluster",
    skill: "Consonant + Ra",
    consonant1: "ಕ",
    consonant1SoundRoman: "ka",
    consonant2: "ರ",
    consonant2SoundRoman: "ra",
    combinedChar: "ಕ್ರ",
    combinedSoundRoman: "kra",
    halantForm: "ಕ್",
    wordKannada: "ಕ್ರಮ",
    wordEnglish: "Order",
    wordRoman: "krama",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_krama_kra.png",
    summary: "ಕ + ್ + ರ = ಕ್ರ — when ರ follows a consonant, you say them in one breath!",
    prompt: "ಕ್ರಮ means 'order' or 'method' — say 'kra' quickly!",
  },
  {
    id: "L3-C02-L02",
    chapterId: "C02",
    chapterTitle: "ರ/ಲ ಒತ್ತಕ್ಷರ",
    title: "ಗ್ರ — ಗ್ರಾಮ (Village)",
    category: "Ra-La Cluster",
    skill: "Consonant + Ra",
    consonant1: "ಗ",
    consonant1SoundRoman: "ga",
    consonant2: "ರ",
    consonant2SoundRoman: "ra",
    combinedChar: "ಗ್ರ",
    combinedSoundRoman: "gra",
    halantForm: "ಗ್",
    wordKannada: "ಗ್ರಾಮ",
    wordEnglish: "Village",
    wordRoman: "grama",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_grama_gra.png",
    summary: "ಗ + ್ + ರ = ಗ್ರ — villages have this sound in their hearts.",
    prompt: "ಗ್ರಾಮ is a village — say 'gra' and feel the earth beneath your feet!",
  },
  {
    id: "L3-C02-L03",
    chapterId: "C02",
    chapterTitle: "ರ/ಲ ಒತ್ತಕ್ಷರ",
    title: "ಪ್ರ — ಪ್ರೀತಿ (Love)",
    category: "Ra-La Cluster",
    skill: "Consonant + Ra",
    consonant1: "ಪ",
    consonant1SoundRoman: "pa",
    consonant2: "ರ",
    consonant2SoundRoman: "ra",
    combinedChar: "ಪ್ರ",
    combinedSoundRoman: "pra",
    halantForm: "ಪ್",
    wordKannada: "ಪ್ರೀತಿ",
    wordEnglish: "Love",
    wordRoman: "preeti",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_preeti_pra.png",
    summary: "ಪ + ್ + ರ = ಪ್ರ — one of the most beautiful conjuncts in Kannada!",
    prompt: "ಪ್ರೀತಿ means love — say 'pra' with warmth in your heart!",
  },
  {
    id: "L3-C02-L04",
    chapterId: "C02",
    chapterTitle: "ರ/ಲ ಒತ್ತಕ್ಷರ",
    title: "ಬ್ರ — ಬ್ರಹ್ಮ (Brahma)",
    category: "Ra-La Cluster",
    skill: "Consonant + Ra",
    consonant1: "ಬ",
    consonant1SoundRoman: "ba",
    consonant2: "ರ",
    consonant2SoundRoman: "ra",
    combinedChar: "ಬ್ರ",
    combinedSoundRoman: "bra",
    halantForm: "ಬ್",
    wordKannada: "ಬ್ರಹ್ಮ",
    wordEnglish: "Brahma (Creator)",
    wordRoman: "brahma",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_brahma_bra.png",
    summary: "ಬ + ್ + ರ = ಬ್ರ — a powerful consonant cluster from ancient Kannada.",
    prompt: "ಬ್ರಹ್ಮ is the creator deity — say 'bra' with power!",
  },
  {
    id: "L3-C02-L05",
    chapterId: "C02",
    chapterTitle: "ರ/ಲ ಒತ್ತಕ್ಷರ",
    title: "ತ್ರ — ತ್ರಿಕೋಣ (Triangle)",
    category: "Ra-La Cluster",
    skill: "Consonant + Ra",
    consonant1: "ತ",
    consonant1SoundRoman: "ta",
    consonant2: "ರ",
    consonant2SoundRoman: "ra",
    combinedChar: "ತ್ರ",
    combinedSoundRoman: "tra",
    halantForm: "ತ್",
    wordKannada: "ತ್ರಿಕೋಣ",
    wordEnglish: "Triangle",
    wordRoman: "trikona",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_trikona_tra.png",
    summary: "ತ + ್ + ರ = ತ್ರ — three sides, three points, and one conjunct!",
    prompt: "ತ್ರಿಕೋಣ is a triangle — three corners, just like ತ + ್ + ರ together!",
  },
  {
    id: "L3-C02-L06",
    chapterId: "C02",
    chapterTitle: "ರ/ಲ ಒತ್ತಕ್ಷರ",
    title: "ದ್ರ — ದ್ರಾಕ್ಷಿ (Grapes)",
    category: "Ra-La Cluster",
    skill: "Consonant + Ra",
    consonant1: "ದ",
    consonant1SoundRoman: "da",
    consonant2: "ರ",
    consonant2SoundRoman: "ra",
    combinedChar: "ದ್ರ",
    combinedSoundRoman: "dra",
    halantForm: "ದ್",
    wordKannada: "ದ್ರಾಕ್ಷಿ",
    wordEnglish: "Grapes",
    wordRoman: "drakshi",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_drakshi_dra.png",
    summary: "ದ + ್ + ರ = ದ್ರ — juicy grapes have a juicy conjunct!",
    prompt: "ದ್ರಾಕ್ಷಿ are grapes — say 'dra' quickly and taste the sweetness!",
  },
  {
    id: "L3-C02-L07",
    chapterId: "C02",
    chapterTitle: "ರ/ಲ ಒತ್ತಕ್ಷರ",
    title: "ಶ್ರ — ಶ್ರಮ (Effort)",
    category: "Ra-La Cluster",
    skill: "Sibilant + Ra",
    consonant1: "ಶ",
    consonant1SoundRoman: "sha",
    consonant2: "ರ",
    consonant2SoundRoman: "ra",
    combinedChar: "ಶ್ರ",
    combinedSoundRoman: "shra",
    halantForm: "ಶ್",
    wordKannada: "ಶ್ರಮ",
    wordEnglish: "Effort",
    wordRoman: "shrama",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_shrama_shra.png",
    summary: "ಶ + ್ + ರ = ಶ್ರ — effort and hard work, expressed in one elegant conjunct.",
    prompt: "ಶ್ರಮ means effort — working hard is ಶ್ರಮ! Say 'shra'!",
  },
  {
    id: "L3-C02-L08",
    chapterId: "C02",
    chapterTitle: "ರ/ಲ ಒತ್ತಕ್ಷರ",
    title: "ಕ್ಲ — ಕ್ಲಾಸ್ (Class)",
    category: "Ra-La Cluster",
    skill: "Consonant + La",
    consonant1: "ಕ",
    consonant1SoundRoman: "ka",
    consonant2: "ಲ",
    consonant2SoundRoman: "la",
    combinedChar: "ಕ್ಲ",
    combinedSoundRoman: "kla",
    halantForm: "ಕ್",
    wordKannada: "ಕ್ಲಾಸ್",
    wordEnglish: "Class",
    wordRoman: "klas",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_klas_kla.png",
    summary: "ಕ + ್ + ಲ = ಕ್ಲ — now ಲ joins the cluster family!",
    prompt: "ಕ್ಲಾಸ್ is where you learn! Say 'kla' and sit up straight!",
  },
  {
    id: "L3-C02-L09",
    chapterId: "C02",
    chapterTitle: "ರ/ಲ ಒತ್ತಕ್ಷರ",
    title: "ಪ್ಲ — ಪ್ಲೇಟ್ (Plate)",
    category: "Ra-La Cluster",
    skill: "Consonant + La",
    consonant1: "ಪ",
    consonant1SoundRoman: "pa",
    consonant2: "ಲ",
    consonant2SoundRoman: "la",
    combinedChar: "ಪ್ಲ",
    combinedSoundRoman: "pla",
    halantForm: "ಪ್",
    wordKannada: "ಪ್ಲೇಟ್",
    wordEnglish: "Plate",
    wordRoman: "plet",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_plet_pla.png",
    summary: "ಪ + ್ + ಲ = ಪ್ಲ — a cluster you'll use every meal time!",
    prompt: "ಪ್ಲೇಟ್ is a plate for your food — say 'pla' and set the table!",
  },
  {
    id: "L3-C02-L10",
    chapterId: "C02",
    chapterTitle: "ರ/ಲ ಒತ್ತಕ್ಷರ",
    title: "ಬ್ಲ — ಬ್ಲ್ಯಾಕ್ (Black)",
    category: "Ra-La Cluster",
    skill: "Consonant + La",
    consonant1: "ಬ",
    consonant1SoundRoman: "ba",
    consonant2: "ಲ",
    consonant2SoundRoman: "la",
    combinedChar: "ಬ್ಲ",
    combinedSoundRoman: "bla",
    halantForm: "ಬ್",
    wordKannada: "ಬ್ಲ್ಯಾಕ್",
    wordEnglish: "Black",
    wordRoman: "blyak",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_blyak_bla.png",
    summary: "ಬ + ್ + ಲ = ಬ್ಲ — modern Kannada borrows words with this cluster too!",
    prompt: "ಬ್ಲ್ಯಾಕ್ is the colour black — dark and bold, just like 'bla'!",
  },
  {
    id: "L3-C02-L11",
    chapterId: "C02",
    chapterTitle: "ರ/ಲ ಒತ್ತಕ್ಷರ",
    title: "ಗ್ಲ — ಗ್ಲಾಸ್ (Glass)",
    category: "Ra-La Cluster",
    skill: "Consonant + La",
    consonant1: "ಗ",
    consonant1SoundRoman: "ga",
    consonant2: "ಲ",
    consonant2SoundRoman: "la",
    combinedChar: "ಗ್ಲ",
    combinedSoundRoman: "gla",
    halantForm: "ಗ್",
    wordKannada: "ಗ್ಲಾಸ್",
    wordEnglish: "Glass",
    wordRoman: "glas",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_glas_gla.png",
    summary: "ಗ + ್ + ಲ = ಗ್ಲ — a loanword cluster you use every day at the table!",
    prompt: "ಗ್ಲಾಸ್ is a drinking glass — pour yourself some water and say 'gla'!",
  },
  {
    id: "L3-C02-L12",
    chapterId: "C02",
    chapterTitle: "ರ/ಲ ಒತ್ತಕ್ಷರ",
    title: "Chapter 2 Review — ರ/ಲ Clusters",
    category: "Consolidation",
    skill: "Ra-La Cluster Mastery",
    consonant1: "ಪ",
    consonant1SoundRoman: "pa",
    consonant2: "ರ",
    consonant2SoundRoman: "ra",
    combinedChar: "ಪ್ರ",
    combinedSoundRoman: "pra",
    halantForm: "ಪ್",
    wordKannada: "ಪ್ರೀತಿ",
    wordEnglish: "Love",
    wordRoman: "preeti",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_review_c02.png",
    summary: "You've learned 11 ರ/ಲ ottakshara — from ಕ್ರ (order) to ಗ್ಲ (glass)!",
    prompt: "Can you spot ರ and ಲ clusters in words around you?",
  },

  // ============================================================
  // CHAPTER C03 — ವಿಶೇಷ ಒತ್ತಕ್ಷರ (Special conjuncts) — 12 lessons
  // ============================================================

  {
    id: "L3-C03-L01",
    chapterId: "C03",
    chapterTitle: "ವಿಶೇಷ ಒತ್ತಕ್ಷರ",
    title: "ಕ್ಷ — ಕ್ಷಮೆ (Forgiveness)",
    category: "Special Conjunct",
    skill: "Classic Kannada Conjunct",
    consonant1: "ಕ",
    consonant1SoundRoman: "ka",
    consonant2: "ಷ",
    consonant2SoundRoman: "sha",
    combinedChar: "ಕ್ಷ",
    combinedSoundRoman: "ksha",
    halantForm: "ಕ್",
    wordKannada: "ಕ್ಷಮೆ",
    wordEnglish: "Forgiveness",
    wordRoman: "kshame",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_kshame_ksha.png",
    summary: "ಕ + ್ + ಷ = ಕ್ಷ — one of Kannada's most classical and graceful conjuncts.",
    prompt: "ಕ್ಷಮೆ means forgiveness — say 'ksha' with a gentle heart!",
  },
  {
    id: "L3-C03-L02",
    chapterId: "C03",
    chapterTitle: "ವಿಶೇಷ ಒತ್ತಕ್ಷರ",
    title: "ಜ್ಞ — ಜ್ಞಾನ (Knowledge)",
    category: "Special Conjunct",
    skill: "Philosophical Conjunct",
    consonant1: "ಜ",
    consonant1SoundRoman: "ja",
    consonant2: "ಞ",
    consonant2SoundRoman: "nya",
    combinedChar: "ಜ್ಞ",
    combinedSoundRoman: "jnya",
    halantForm: "ಜ್",
    wordKannada: "ಜ್ಞಾನ",
    wordEnglish: "Knowledge",
    wordRoman: "jnana",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_jnana_jnya.png",
    summary: "ಜ + ್ + ಞ = ಜ್ಞ — the conjunct of wisdom and deep knowing.",
    prompt: "ಜ್ಞಾನ is knowledge — say 'jnya' and open your mind!",
  },
  {
    id: "L3-C03-L03",
    chapterId: "C03",
    chapterTitle: "ವಿಶೇಷ ಒತ್ತಕ್ಷರ",
    title: "ಸ್ನ — ಸ್ನಾನ (Bath)",
    category: "Special Conjunct",
    skill: "Fricative-Nasal Cluster",
    consonant1: "ಸ",
    consonant1SoundRoman: "sa",
    consonant2: "ನ",
    consonant2SoundRoman: "na",
    combinedChar: "ಸ್ನ",
    combinedSoundRoman: "sna",
    halantForm: "ಸ್",
    wordKannada: "ಸ್ನಾನ",
    wordEnglish: "Bath",
    wordRoman: "snana",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_snana_sna.png",
    summary: "ಸ + ್ + ನ = ಸ್ನ — the morning ritual in one fresh conjunct.",
    prompt: "ಸ್ನಾನ is a bath — say 'sna' and feel clean and fresh!",
  },
  {
    id: "L3-C03-L04",
    chapterId: "C03",
    chapterTitle: "ವಿಶೇಷ ಒತ್ತಕ್ಷರ",
    title: "ಸ್ಕ — ಸ್ಕೂಲ್ (School)",
    category: "Special Conjunct",
    skill: "Fricative-Stop Cluster",
    consonant1: "ಸ",
    consonant1SoundRoman: "sa",
    consonant2: "ಕ",
    consonant2SoundRoman: "ka",
    combinedChar: "ಸ್ಕ",
    combinedSoundRoman: "ska",
    halantForm: "ಸ್",
    wordKannada: "ಸ್ಕೂಲ್",
    wordEnglish: "School",
    wordRoman: "skul",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_skul_ska.png",
    summary: "ಸ + ್ + ಕ = ಸ್ಕ — you go to ಸ್ಕೂಲ್ every day to learn!",
    prompt: "ಸ್ಕೂಲ್ is school — say 'ska' and get ready for class!",
  },
  {
    id: "L3-C03-L05",
    chapterId: "C03",
    chapterTitle: "ವಿಶೇಷ ಒತ್ತಕ್ಷರ",
    title: "ಸ್ಪ — ಸ್ಪಷ್ಟ (Clear)",
    category: "Special Conjunct",
    skill: "Fricative-Stop Cluster",
    consonant1: "ಸ",
    consonant1SoundRoman: "sa",
    consonant2: "ಪ",
    consonant2SoundRoman: "pa",
    combinedChar: "ಸ್ಪ",
    combinedSoundRoman: "spa",
    halantForm: "ಸ್",
    wordKannada: "ಸ್ಪಷ್ಟ",
    wordEnglish: "Clear",
    wordRoman: "spashta",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_spashta_spa.png",
    summary: "ಸ + ್ + ಪ = ಸ್ಪ — say things clearly with a clear conjunct!",
    prompt: "ಸ್ಪಷ್ಟ means clear — speak 'spa' clearly and crisply!",
  },
  {
    id: "L3-C03-L06",
    chapterId: "C03",
    chapterTitle: "ವಿಶೇಷ ಒತ್ತಕ್ಷರ",
    title: "ನ್ಯ — ನ್ಯಾಯ (Justice)",
    category: "Special Conjunct",
    skill: "Nasal-Glide Cluster",
    consonant1: "ನ",
    consonant1SoundRoman: "na",
    consonant2: "ಯ",
    consonant2SoundRoman: "ya",
    combinedChar: "ನ್ಯ",
    combinedSoundRoman: "nya",
    halantForm: "ನ್",
    wordKannada: "ನ್ಯಾಯ",
    wordEnglish: "Justice",
    wordRoman: "nyaya",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_nyaya_nya.png",
    summary: "ನ + ್ + ಯ = ನ್ಯ — justice flows smoothly like this gentle conjunct.",
    prompt: "ನ್ಯಾಯ means justice — say 'nya' softly but with conviction!",
  },
  {
    id: "L3-C03-L07",
    chapterId: "C03",
    chapterTitle: "ವಿಶೇಷ ಒತ್ತಕ್ಷರ",
    title: "ತ್ಯ — ತ್ಯಾಗ (Sacrifice)",
    category: "Special Conjunct",
    skill: "Stop-Glide Cluster",
    consonant1: "ತ",
    consonant1SoundRoman: "ta",
    consonant2: "ಯ",
    consonant2SoundRoman: "ya",
    combinedChar: "ತ್ಯ",
    combinedSoundRoman: "tya",
    halantForm: "ತ್",
    wordKannada: "ತ್ಯಾಗ",
    wordEnglish: "Sacrifice",
    wordRoman: "tyaga",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_tyaga_tya.png",
    summary: "ತ + ್ + ಯ = ತ್ಯ — sacrifice is noble, and so is this graceful conjunct.",
    prompt: "ತ್ಯಾಗ means giving up something for others — say 'tya' with respect!",
  },
  {
    id: "L3-C03-L08",
    chapterId: "C03",
    chapterTitle: "ವಿಶೇಷ ಒತ್ತಕ್ಷರ",
    title: "ಧ್ಯ — ಧ್ಯಾನ (Meditation)",
    category: "Special Conjunct",
    skill: "Aspirate-Glide Cluster",
    consonant1: "ಧ",
    consonant1SoundRoman: "dha",
    consonant2: "ಯ",
    consonant2SoundRoman: "ya",
    combinedChar: "ಧ್ಯ",
    combinedSoundRoman: "dhya",
    halantForm: "ಧ್",
    wordKannada: "ಧ್ಯಾನ",
    wordEnglish: "Meditation",
    wordRoman: "dhyana",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_dhyana_dhya.png",
    summary: "ಧ + ್ + ಯ = ಧ್ಯ — stillness in a consonant cluster.",
    prompt: "ಧ್ಯಾನ is meditation — close your eyes and say 'dhya' slowly...",
  },
  {
    id: "L3-C03-L09",
    chapterId: "C03",
    chapterTitle: "ವಿಶೇಷ ಒತ್ತಕ್ಷರ",
    title: "ಕ್ತ — ಭಕ್ತ (Devotee)",
    category: "Special Conjunct",
    skill: "Stop-Stop Cluster",
    consonant1: "ಕ",
    consonant1SoundRoman: "ka",
    consonant2: "ತ",
    consonant2SoundRoman: "ta",
    combinedChar: "ಕ್ತ",
    combinedSoundRoman: "kta",
    halantForm: "ಕ್",
    wordKannada: "ಭಕ್ತ",
    wordEnglish: "Devotee",
    wordRoman: "bhakta",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_bhakta_kta.png",
    summary: "ಕ + ್ + ತ = ಕ್ತ — two stops joined together, firm and faithful.",
    prompt: "ಭಕ್ತ means a devotee — full of devotion. Say 'kta'!",
  },
  {
    id: "L3-C03-L10",
    chapterId: "C03",
    chapterTitle: "ವಿಶೇಷ ಒತ್ತಕ್ಷರ",
    title: "ಸ್ಮ — ಸ್ಮರಣೆ (Memory)",
    category: "Special Conjunct",
    skill: "Fricative-Nasal Cluster",
    consonant1: "ಸ",
    consonant1SoundRoman: "sa",
    consonant2: "ಮ",
    consonant2SoundRoman: "ma",
    combinedChar: "ಸ್ಮ",
    combinedSoundRoman: "sma",
    halantForm: "ಸ್",
    wordKannada: "ಸ್ಮರಣೆ",
    wordEnglish: "Memory",
    wordRoman: "smarane",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_smarane_sma.png",
    summary: "ಸ + ್ + ಮ = ಸ್ಮ — memories are held in the soft sound of 'sma'.",
    prompt: "ಸ್ಮರಣೆ means memory — remember this conjunct and say 'sma'!",
  },
  {
    id: "L3-C03-L11",
    chapterId: "C03",
    chapterTitle: "ವಿಶೇಷ ಒತ್ತಕ್ಷರ",
    title: "ಸ್ತ — ಸ್ತಂಭ (Pillar)",
    category: "Special Conjunct",
    skill: "Fricative-Stop Cluster",
    consonant1: "ಸ",
    consonant1SoundRoman: "sa",
    consonant2: "ತ",
    consonant2SoundRoman: "ta",
    combinedChar: "ಸ್ತ",
    combinedSoundRoman: "sta",
    halantForm: "ಸ್",
    wordKannada: "ಸ್ತಂಭ",
    wordEnglish: "Pillar",
    wordRoman: "stambha",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_stambha_sta.png",
    summary: "ಸ + ್ + ತ = ಸ್ತ — as strong and upright as a stone pillar.",
    prompt: "ಸ್ತಂಭ is a pillar — stand tall and say 'sta' with strength!",
  },
  {
    id: "L3-C03-L12",
    chapterId: "C03",
    chapterTitle: "ವಿಶೇಷ ಒತ್ತಕ್ಷರ",
    title: "Master Review — All Ottakshara",
    category: "Consolidation",
    skill: "Ottakshara Mastery",
    consonant1: "ಕ",
    consonant1SoundRoman: "ka",
    consonant2: "ಷ",
    consonant2SoundRoman: "sha",
    combinedChar: "ಕ್ಷ",
    combinedSoundRoman: "ksha",
    halantForm: "ಕ್",
    wordKannada: "ಕ್ಷಮೆ",
    wordEnglish: "Forgiveness",
    wordRoman: "kshame",
    assetPath: "/kaveri/assets/gemini/kaveri_l3_review_master.png",
    summary: "You've mastered 38 Kannada ottakshara — doubled, ರ/ಲ clusters, and specials!",
    prompt: "ಒತ್ತಕ್ಷರ are now your strength! You can read complex Kannada words!",
  },
];

// Roman transliteration map for Level 3
export const LEVEL_3_ROMAN_MAP: Record<string, string> = {
  "L3-C01-L01": "akka",
  "L3-C01-L02": "magga",
  "L3-C01-L03": "hechchu",
  "L3-C01-L04": "motte",
  "L3-C01-L05": "hattu",
  "L3-C01-L06": "maddu",
  "L3-C01-L07": "appa",
  "L3-C01-L08": "habba",
  "L3-C01-L09": "amma",
  "L3-C01-L10": "hallu",
  "L3-C01-L11": "kannu",
  "L3-C01-L12": "anna",
  "L3-C01-L13": "kaddi",
  "L3-C01-L14": "akka",
  "L3-C02-L01": "krama",
  "L3-C02-L02": "grama",
  "L3-C02-L03": "preeti",
  "L3-C02-L04": "brahma",
  "L3-C02-L05": "trikona",
  "L3-C02-L06": "drakshi",
  "L3-C02-L07": "shrama",
  "L3-C02-L08": "klas",
  "L3-C02-L09": "plet",
  "L3-C02-L10": "blyak",
  "L3-C02-L11": "glas",
  "L3-C02-L12": "preeti",
  "L3-C03-L01": "kshame",
  "L3-C03-L02": "jnana",
  "L3-C03-L03": "snana",
  "L3-C03-L04": "skul",
  "L3-C03-L05": "spashta",
  "L3-C03-L06": "nyaya",
  "L3-C03-L07": "tyaga",
  "L3-C03-L08": "dhyana",
  "L3-C03-L09": "bhakta",
  "L3-C03-L10": "smarane",
  "L3-C03-L11": "stambha",
  "L3-C03-L12": "kshame",
};

// Re-export for compatibility
export const kaveriLevel3Data = LEVEL_3_DATA;
