/**
 * Kaveri Level 4 — ಬರಹಮಾಲೆ (Barakhadi / Syllabic Matrix)
 * 36 lessons · 6 chapters
 *
 * C01: ಕ-ವರ್ಗ  ಕ ಖ ಗ ಘ + Review          (5 lessons)
 * C02: ಚ-ವರ್ಗ  ಚ ಛ ಜ ಝ + Review          (5 lessons)
 * C03: ಟ-ವರ್ಗ  ಟ ಠ ಡ ಢ ಣ + Review        (6 lessons)
 * C04: ತ-ವರ್ಗ  ತ ಥ ದ ಧ ನ + Review        (6 lessons)
 * C05: ಪ-ವರ್ಗ  ಪ ಫ ಬ ಭ ಮ + Review        (6 lessons)
 * C06: ಶೇಷ-ವರ್ಗ ಯ ರ ಲ ವ ಶ ಸ ಹ ಳ          (8 lessons)
 *
 * Each lesson teaches: consonant + 12 gunita forms = 12 syllables
 */

export interface Level4Seed {
  id: string;
  chapterId: string;
  chapterTitle: string;
  title: string;
  category: string;
  skill: string;
  consonant: string;
  consonantRoman: string;
  barakhadiRow: Array<{ syllable: string; sound: string; matra: string }>;
  exampleWords: Array<{ hindi: string; english: string; roman: string }>;
  wordKannada: string;
  wordEnglish: string;
  wordRoman: string;
  assetPath: string;
  durationMin?: number;
  summary: string;
  prompt: string;
}

export const LEVEL_4_DATA: Level4Seed[] = [

  // ============================================================
  // CHAPTER C01 — ಕ-ವರ್ಗ (5 lessons)
  // ============================================================

  {
    id: "L4-C01-L01",
    chapterId: "C01",
    chapterTitle: "ಕ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಕ ಬರಹಮಾಲೆ — Ka Barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "ಕ",
    consonantRoman: "ka",
    barakhadiRow: [
      { syllable: "ಕ",  sound: "ka",  matra: "ಅ" },
      { syllable: "ಕಾ", sound: "kaa", matra: "ಾ" },
      { syllable: "ಕಿ", sound: "ki",  matra: "ಿ" },
      { syllable: "ಕೀ", sound: "kee", matra: "ೀ" },
      { syllable: "ಕು", sound: "ku",  matra: "ು" },
      { syllable: "ಕೂ", sound: "koo", matra: "ೂ" },
      { syllable: "ಕೆ", sound: "ke",  matra: "ೆ" },
      { syllable: "ಕೇ", sound: "kae", matra: "ೇ" },
      { syllable: "ಕೈ", sound: "kai", matra: "ೈ" },
      { syllable: "ಕೊ", sound: "ko",  matra: "ೊ" },
      { syllable: "ಕೋ", sound: "koo", matra: "ೋ" },
      { syllable: "ಕೌ", sound: "kau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಕಮಲ",   english: "Lotus",  roman: "kamala" },
      { hindi: "ಕಾಗೆ",  english: "Crow",   roman: "kaage"  },
      { hindi: "ಕಿಟಕಿ", english: "Window", roman: "kitaki" },
    ],
    wordKannada: "ಕಮಲ",
    wordEnglish: "Lotus",
    wordRoman: "kamala",
    assetPath: "/assets/gemini/kaveri_l4_ka_barakhadi.png",
    summary: "ಕ with all 12 gunita — from ಕ to ಕೌ, master the full grid!",
    prompt: "ಕ is the foundation! Tap each syllable and say it aloud.",
  },
  {
    id: "L4-C01-L02",
    chapterId: "C01",
    chapterTitle: "ಕ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಖ ಬರಹಮಾಲೆ — Kha Barakhadi",
    category: "Syllable Matrix",
    skill: "Aspirated Velar Mastery",
    consonant: "ಖ",
    consonantRoman: "kha",
    barakhadiRow: [
      { syllable: "ಖ",  sound: "kha",  matra: "ಅ" },
      { syllable: "ಖಾ", sound: "khaa", matra: "ಾ" },
      { syllable: "ಖಿ", sound: "khi",  matra: "ಿ" },
      { syllable: "ಖೀ", sound: "khee", matra: "ೀ" },
      { syllable: "ಖು", sound: "khu",  matra: "ು" },
      { syllable: "ಖೂ", sound: "khoo", matra: "ೂ" },
      { syllable: "ಖೆ", sound: "khe",  matra: "ೆ" },
      { syllable: "ಖೇ", sound: "khae", matra: "ೇ" },
      { syllable: "ಖೈ", sound: "khai", matra: "ೈ" },
      { syllable: "ಖೊ", sound: "kho",  matra: "ೊ" },
      { syllable: "ಖೋ", sound: "khoo", matra: "ೋ" },
      { syllable: "ಖೌ", sound: "khau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಖಡ್ಗ",  english: "Sword",  roman: "khadga" },
      { hindi: "ಖಾಲಿ",  english: "Empty",  roman: "khali"  },
      { hindi: "ಖ್ಯಾತಿ", english: "Fame",   roman: "khyati" },
    ],
    wordKannada: "ಖಡ್ಗ",
    wordEnglish: "Sword",
    wordRoman: "khadga",
    assetPath: "/assets/gemini/kaveri_l4_kha_barakhadi.png",
    summary: "ಖ is ಕ with a breath — aspirated velar. Feel the extra puff!",
    prompt: "ಖ sounds like 'kha' — more air than ಕ. Try it!",
  },
  {
    id: "L4-C01-L03",
    chapterId: "C01",
    chapterTitle: "ಕ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಗ ಬರಹಮಾಲೆ — Ga Barakhadi",
    category: "Syllable Matrix",
    skill: "Voiced Velar Mastery",
    consonant: "ಗ",
    consonantRoman: "ga",
    barakhadiRow: [
      { syllable: "ಗ",  sound: "ga",  matra: "ಅ" },
      { syllable: "ಗಾ", sound: "gaa", matra: "ಾ" },
      { syllable: "ಗಿ", sound: "gi",  matra: "ಿ" },
      { syllable: "ಗೀ", sound: "gee", matra: "ೀ" },
      { syllable: "ಗು", sound: "gu",  matra: "ು" },
      { syllable: "ಗೂ", sound: "goo", matra: "ೂ" },
      { syllable: "ಗೆ", sound: "ge",  matra: "ೆ" },
      { syllable: "ಗೇ", sound: "gae", matra: "ೇ" },
      { syllable: "ಗೈ", sound: "gai", matra: "ೈ" },
      { syllable: "ಗೊ", sound: "go",  matra: "ೊ" },
      { syllable: "ಗೋ", sound: "goo", matra: "ೋ" },
      { syllable: "ಗೌ", sound: "gau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಗಾಡಿ",  english: "Vehicle", roman: "gaadi"  },
      { hindi: "ಗಿಳಿ",  english: "Parrot",  roman: "gili"   },
      { hindi: "ಗೋಡೆ",  english: "Wall",    roman: "gode"   },
    ],
    wordKannada: "ಗಾಡಿ",
    wordEnglish: "Vehicle",
    wordRoman: "gaadi",
    assetPath: "/assets/gemini/kaveri_l4_ga_barakhadi.png",
    summary: "ಗ is the voiced partner of ಕ — voice box vibrates!",
    prompt: "ಗ sounds warm and voiced — feel your throat buzz!",
  },
  {
    id: "L4-C01-L04",
    chapterId: "C01",
    chapterTitle: "ಕ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಘ ಬರಹಮಾಲೆ — Gha Barakhadi",
    category: "Syllable Matrix",
    skill: "Aspirated Voiced Velar",
    consonant: "ಘ",
    consonantRoman: "gha",
    barakhadiRow: [
      { syllable: "ಘ",  sound: "gha",  matra: "ಅ" },
      { syllable: "ಘಾ", sound: "ghaa", matra: "ಾ" },
      { syllable: "ಘಿ", sound: "ghi",  matra: "ಿ" },
      { syllable: "ಘೀ", sound: "ghee", matra: "ೀ" },
      { syllable: "ಘು", sound: "ghu",  matra: "ು" },
      { syllable: "ಘೂ", sound: "ghoo", matra: "ೂ" },
      { syllable: "ಘೆ", sound: "ghe",  matra: "ೆ" },
      { syllable: "ಘೇ", sound: "ghae", matra: "ೇ" },
      { syllable: "ಘೈ", sound: "ghai", matra: "ೈ" },
      { syllable: "ಘೊ", sound: "gho",  matra: "ೊ" },
      { syllable: "ಘೋ", sound: "ghoo", matra: "ೋ" },
      { syllable: "ಘೌ", sound: "ghau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಘಂಟೆ", english: "Bell",      roman: "ghante" },
      { hindi: "ಘೋರ",  english: "Terrible",  roman: "ghora"  },
      { hindi: "ಘಾಯ",  english: "Wound",     roman: "ghaaya" },
    ],
    wordKannada: "ಘಂಟೆ",
    wordEnglish: "Bell",
    wordRoman: "ghante",
    assetPath: "/assets/gemini/kaveri_l4_gha_barakhadi.png",
    summary: "ಘ is ಗ with more breath — aspirated and voiced together!",
    prompt: "ಘಂಟೆ is a bell — deep and resonant like 'gha'!",
  },
  {
    id: "L4-C01-L05",
    chapterId: "C01",
    chapterTitle: "ಕ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಕ-ವರ್ಗ Review",
    category: "Review Practice",
    skill: "Velar Mastery",
    consonant: "ಕ & ಖ & ಗ & ಘ",
    consonantRoman: "ka-kha-ga-gha",
    barakhadiRow: [
      { syllable: "ಕ",  sound: "ka",  matra: "ಅ" },
      { syllable: "ಕಾ", sound: "kaa", matra: "ಾ" },
      { syllable: "ಕಿ", sound: "ki",  matra: "ಿ" },
      { syllable: "ಕೀ", sound: "kee", matra: "ೀ" },
      { syllable: "ಕು", sound: "ku",  matra: "ು" },
      { syllable: "ಕೂ", sound: "koo", matra: "ೂ" },
      { syllable: "ಕೆ", sound: "ke",  matra: "ೆ" },
      { syllable: "ಕೇ", sound: "kae", matra: "ೇ" },
      { syllable: "ಕೈ", sound: "kai", matra: "ೈ" },
      { syllable: "ಕೊ", sound: "ko",  matra: "ೊ" },
      { syllable: "ಕೋ", sound: "koo", matra: "ೋ" },
      { syllable: "ಕೌ", sound: "kau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಕಮಲ",  english: "Lotus",   roman: "kamala" },
      { hindi: "ಗಾಡಿ",  english: "Vehicle", roman: "gaadi"  },
      { hindi: "ಘಂಟೆ",  english: "Bell",    roman: "ghante" },
    ],
    wordKannada: "ಕಮಲ",
    wordEnglish: "Lotus",
    wordRoman: "kamala",
    assetPath: "/assets/gemini/kaveri_l4_review_c01.png",
    summary: "Review ಕ ಖ ಗ ಘ — four velar consonants mastered!",
    prompt: "Can you tell ಕ from ಖ, and ಗ from ಘ? Test yourself!",
  },

  // ============================================================
  // CHAPTER C02 — ಚ-ವರ್ಗ (5 lessons)
  // ============================================================

  {
    id: "L4-C02-L01",
    chapterId: "C02",
    chapterTitle: "ಚ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಚ ಬರಹಮಾಲೆ — Cha Barakhadi",
    category: "Syllable Matrix",
    skill: "Palatal Affricate Mastery",
    consonant: "ಚ",
    consonantRoman: "cha",
    barakhadiRow: [
      { syllable: "ಚ",  sound: "cha",  matra: "ಅ" },
      { syllable: "ಚಾ", sound: "chaa", matra: "ಾ" },
      { syllable: "ಚಿ", sound: "chi",  matra: "ಿ" },
      { syllable: "ಚೀ", sound: "chee", matra: "ೀ" },
      { syllable: "ಚು", sound: "chu",  matra: "ು" },
      { syllable: "ಚೂ", sound: "choo", matra: "ೂ" },
      { syllable: "ಚೆ", sound: "che",  matra: "ೆ" },
      { syllable: "ಚೇ", sound: "chae", matra: "ೇ" },
      { syllable: "ಚೈ", sound: "chai", matra: "ೈ" },
      { syllable: "ಚೊ", sound: "cho",  matra: "ೊ" },
      { syllable: "ಚೋ", sound: "choo", matra: "ೋ" },
      { syllable: "ಚೌ", sound: "chau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಚಂದ್ರ", english: "Moon",    roman: "chandra" },
      { hindi: "ಚಾಕು",  english: "Knife",   roman: "chaaku"  },
      { hindi: "ಚಿತ್ರ", english: "Picture", roman: "chitra"  },
    ],
    wordKannada: "ಚಂದ್ರ",
    wordEnglish: "Moon",
    wordRoman: "chandra",
    assetPath: "/assets/gemini/kaveri_l4_cha_barakhadi.png",
    summary: "ಚ is a soft palatal — tongue meets the roof of your mouth!",
    prompt: "ಚಂದ್ರ is the moon — bright and beautiful like 'cha'!",
  },
  {
    id: "L4-C02-L02",
    chapterId: "C02",
    chapterTitle: "ಚ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಛ ಬರಹಮಾಲೆ — Chha Barakhadi",
    category: "Syllable Matrix",
    skill: "Aspirated Palatal Mastery",
    consonant: "ಛ",
    consonantRoman: "chha",
    barakhadiRow: [
      { syllable: "ಛ",  sound: "chha",  matra: "ಅ" },
      { syllable: "ಛಾ", sound: "chhaa", matra: "ಾ" },
      { syllable: "ಛಿ", sound: "chhi",  matra: "ಿ" },
      { syllable: "ಛೀ", sound: "chhee", matra: "ೀ" },
      { syllable: "ಛು", sound: "chhu",  matra: "ು" },
      { syllable: "ಛೂ", sound: "chhoo", matra: "ೂ" },
      { syllable: "ಛೆ", sound: "chhe",  matra: "ೆ" },
      { syllable: "ಛೇ", sound: "chhae", matra: "ೇ" },
      { syllable: "ಛೈ", sound: "chhai", matra: "ೈ" },
      { syllable: "ಛೊ", sound: "chho",  matra: "ೊ" },
      { syllable: "ಛೋ", sound: "chhoo", matra: "ೋ" },
      { syllable: "ಛೌ", sound: "chhau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಛತ್ರಿ", english: "Umbrella", roman: "chhatri" },
      { hindi: "ಛಾಯೆ",  english: "Shadow",   roman: "chhaaye" },
      { hindi: "ಛಲ",    english: "Deceit",   roman: "chala"   },
    ],
    wordKannada: "ಛತ್ರಿ",
    wordEnglish: "Umbrella",
    wordRoman: "chhatri",
    assetPath: "/assets/gemini/kaveri_l4_chha_barakhadi.png",
    summary: "ಛ is the aspirated ಚ — a sharp puff of air!",
    prompt: "ಛತ್ರಿ keeps the rain away — say 'chha' sharply!",
  },
  {
    id: "L4-C02-L03",
    chapterId: "C02",
    chapterTitle: "ಚ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಜ ಬರಹಮಾಲೆ — Ja Barakhadi",
    category: "Syllable Matrix",
    skill: "Voiced Palatal Mastery",
    consonant: "ಜ",
    consonantRoman: "ja",
    barakhadiRow: [
      { syllable: "ಜ",  sound: "ja",  matra: "ಅ" },
      { syllable: "ಜಾ", sound: "jaa", matra: "ಾ" },
      { syllable: "ಜಿ", sound: "ji",  matra: "ಿ" },
      { syllable: "ಜೀ", sound: "jee", matra: "ೀ" },
      { syllable: "ಜು", sound: "ju",  matra: "ು" },
      { syllable: "ಜೂ", sound: "joo", matra: "ೂ" },
      { syllable: "ಜೆ", sound: "je",  matra: "ೆ" },
      { syllable: "ಜೇ", sound: "jae", matra: "ೇ" },
      { syllable: "ಜೈ", sound: "jai", matra: "ೈ" },
      { syllable: "ಜೊ", sound: "jo",  matra: "ೊ" },
      { syllable: "ಜೋ", sound: "joo", matra: "ೋ" },
      { syllable: "ಜೌ", sound: "jau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಜಲ",   english: "Water",  roman: "jala"   },
      { hindi: "ಜೇನು", english: "Honey",  roman: "jeenu"  },
      { hindi: "ಜೀವ",  english: "Life",   roman: "jeeva"  },
    ],
    wordKannada: "ಜಲ",
    wordEnglish: "Water",
    wordRoman: "jala",
    assetPath: "/assets/gemini/kaveri_l4_ja_barakhadi.png",
    summary: "ಜ is the voiced palatal — your voice box vibrates for this one!",
    prompt: "ಜಲ is water — flowing freely like the 'ja' sound!",
  },
  {
    id: "L4-C02-L04",
    chapterId: "C02",
    chapterTitle: "ಚ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಝ ಬರಹಮಾಲೆ — Jha Barakhadi",
    category: "Syllable Matrix",
    skill: "Aspirated Voiced Palatal",
    consonant: "ಝ",
    consonantRoman: "jha",
    barakhadiRow: [
      { syllable: "ಝ",  sound: "jha",  matra: "ಅ" },
      { syllable: "ಝಾ", sound: "jhaa", matra: "ಾ" },
      { syllable: "ಝಿ", sound: "jhi",  matra: "ಿ" },
      { syllable: "ಝೀ", sound: "jhee", matra: "ೀ" },
      { syllable: "ಝು", sound: "jhu",  matra: "ು" },
      { syllable: "ಝೂ", sound: "jhoo", matra: "ೂ" },
      { syllable: "ಝೆ", sound: "jhe",  matra: "ೆ" },
      { syllable: "ಝೇ", sound: "jhae", matra: "ೇ" },
      { syllable: "ಝೈ", sound: "jhai", matra: "ೈ" },
      { syllable: "ಝೊ", sound: "jho",  matra: "ೊ" },
      { syllable: "ಝೋ", sound: "jhoo", matra: "ೋ" },
      { syllable: "ಝೌ", sound: "jhau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಝರಿ",   english: "Waterfall", roman: "jhari"  },
      { hindi: "ಝಗಳ",   english: "Quarrel",   roman: "jhagala"},
      { hindi: "ಝಲಕ",   english: "Glimpse",   roman: "jhalaka"},
    ],
    wordKannada: "ಝರಿ",
    wordEnglish: "Waterfall",
    wordRoman: "jhari",
    assetPath: "/assets/gemini/kaveri_l4_jha_barakhadi.png",
    summary: "ಝ is ಜ with extra breath — voiced and aspirated!",
    prompt: "ಝರಿ is a waterfall — rushing and breathy like 'jha'!",
  },
  {
    id: "L4-C02-L05",
    chapterId: "C02",
    chapterTitle: "ಚ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಚ-ವರ್ಗ Review",
    category: "Review Practice",
    skill: "Palatal Mastery",
    consonant: "ಚ & ಛ & ಜ & ಝ",
    consonantRoman: "cha-chha-ja-jha",
    barakhadiRow: [
      { syllable: "ಚ",  sound: "cha",  matra: "ಅ" },
      { syllable: "ಚಾ", sound: "chaa", matra: "ಾ" },
      { syllable: "ಚಿ", sound: "chi",  matra: "ಿ" },
      { syllable: "ಚೀ", sound: "chee", matra: "ೀ" },
      { syllable: "ಚು", sound: "chu",  matra: "ು" },
      { syllable: "ಚೂ", sound: "choo", matra: "ೂ" },
      { syllable: "ಚೆ", sound: "che",  matra: "ೆ" },
      { syllable: "ಚೇ", sound: "chae", matra: "ೇ" },
      { syllable: "ಚೈ", sound: "chai", matra: "ೈ" },
      { syllable: "ಚೊ", sound: "cho",  matra: "ೊ" },
      { syllable: "ಚೋ", sound: "choo", matra: "ೋ" },
      { syllable: "ಚೌ", sound: "chau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಚಂದ್ರ", english: "Moon",      roman: "chandra" },
      { hindi: "ಜಲ",    english: "Water",     roman: "jala"    },
      { hindi: "ಝರಿ",   english: "Waterfall", roman: "jhari"   },
    ],
    wordKannada: "ಚಂದ್ರ",
    wordEnglish: "Moon",
    wordRoman: "chandra",
    assetPath: "/assets/gemini/kaveri_l4_review_c02.png",
    summary: "Review ಚ ಛ ಜ ಝ — four palatal consonants mastered!",
    prompt: "Can you hear the difference between ಚ (soft) and ಛ (sharp)?",
  },

  // ============================================================
  // CHAPTER C03 — ಟ-ವರ್ಗ (6 lessons)
  // ============================================================

  {
    id: "L4-C03-L01",
    chapterId: "C03",
    chapterTitle: "ಟ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಟ ಬರಹಮಾಲೆ — Ta (retroflex) Barakhadi",
    category: "Syllable Matrix",
    skill: "Retroflex Stop Mastery",
    consonant: "ಟ",
    consonantRoman: "ta",
    barakhadiRow: [
      { syllable: "ಟ",  sound: "ta",  matra: "ಅ" },
      { syllable: "ಟಾ", sound: "taa", matra: "ಾ" },
      { syllable: "ಟಿ", sound: "ti",  matra: "ಿ" },
      { syllable: "ಟೀ", sound: "tee", matra: "ೀ" },
      { syllable: "ಟು", sound: "tu",  matra: "ು" },
      { syllable: "ಟೂ", sound: "too", matra: "ೂ" },
      { syllable: "ಟೆ", sound: "te",  matra: "ೆ" },
      { syllable: "ಟೇ", sound: "tae", matra: "ೇ" },
      { syllable: "ಟೈ", sound: "tai", matra: "ೈ" },
      { syllable: "ಟೊ", sound: "to",  matra: "ೊ" },
      { syllable: "ಟೋ", sound: "too", matra: "ೋ" },
      { syllable: "ಟೌ", sound: "tau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಟೊಪ್ಪಿ", english: "Cap",   roman: "toppi"  },
      { hindi: "ಟೇಬಲ್",  english: "Table", roman: "tebal"  },
      { hindi: "ಟ್ರಕ್",  english: "Truck", roman: "trak"   },
    ],
    wordKannada: "ಟೊಪ್ಪಿ",
    wordEnglish: "Cap",
    wordRoman: "toppi",
    assetPath: "/assets/gemini/kaveri_l4_ta_retro_barakhadi.png",
    summary: "ಟ is retroflex — curl your tongue back for this sound!",
    prompt: "ಟೊಪ್ಪಿ is a cap — curl your tongue back and say 'ta'!",
  },
  {
    id: "L4-C03-L02",
    chapterId: "C03",
    chapterTitle: "ಟ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಠ ಬರಹಮಾಲೆ — Tha (retroflex) Barakhadi",
    category: "Syllable Matrix",
    skill: "Aspirated Retroflex Mastery",
    consonant: "ಠ",
    consonantRoman: "tha",
    barakhadiRow: [
      { syllable: "ಠ",  sound: "tha",  matra: "ಅ" },
      { syllable: "ಠಾ", sound: "thaa", matra: "ಾ" },
      { syllable: "ಠಿ", sound: "thi",  matra: "ಿ" },
      { syllable: "ಠೀ", sound: "thee", matra: "ೀ" },
      { syllable: "ಠು", sound: "thu",  matra: "ು" },
      { syllable: "ಠೂ", sound: "thoo", matra: "ೂ" },
      { syllable: "ಠೆ", sound: "the",  matra: "ೆ" },
      { syllable: "ಠೇ", sound: "thae", matra: "ೇ" },
      { syllable: "ಠೈ", sound: "thai", matra: "ೈ" },
      { syllable: "ಠೊ", sound: "tho",  matra: "ೊ" },
      { syllable: "ಠೋ", sound: "thoo", matra: "ೋ" },
      { syllable: "ಠೌ", sound: "thau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಠಾಣೆ", english: "Police Station", roman: "thaane" },
      { hindi: "ಠೀವಿ",  english: "Pride",          roman: "theevi" },
      { hindi: "ಠಕ್ಕ",  english: "Cheat",          roman: "thakka" },
    ],
    wordKannada: "ಠಾಣೆ",
    wordEnglish: "Police Station",
    wordRoman: "thaane",
    assetPath: "/assets/gemini/kaveri_l4_tha_retro_barakhadi.png",
    summary: "ಠ is ಟ with extra air — aspirated retroflex!",
    prompt: "ಠಾಣೆ is a police station — say 'tha' firmly!",
  },
  {
    id: "L4-C03-L03",
    chapterId: "C03",
    chapterTitle: "ಟ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಡ ಬರಹಮಾಲೆ — Da (retroflex) Barakhadi",
    category: "Syllable Matrix",
    skill: "Voiced Retroflex Mastery",
    consonant: "ಡ",
    consonantRoman: "da",
    barakhadiRow: [
      { syllable: "ಡ",  sound: "da",  matra: "ಅ" },
      { syllable: "ಡಾ", sound: "daa", matra: "ಾ" },
      { syllable: "ಡಿ", sound: "di",  matra: "ಿ" },
      { syllable: "ಡೀ", sound: "dee", matra: "ೀ" },
      { syllable: "ಡು", sound: "du",  matra: "ು" },
      { syllable: "ಡೂ", sound: "doo", matra: "ೂ" },
      { syllable: "ಡೆ", sound: "de",  matra: "ೆ" },
      { syllable: "ಡೇ", sound: "dae", matra: "ೇ" },
      { syllable: "ಡೈ", sound: "dai", matra: "ೈ" },
      { syllable: "ಡೊ", sound: "do",  matra: "ೊ" },
      { syllable: "ಡೋ", sound: "doo", matra: "ೋ" },
      { syllable: "ಡೌ", sound: "dau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಡಬ್ಬ",   english: "Tin Box",  roman: "dabba"   },
      { hindi: "ಡಾಕ್ಟರ್", english: "Doctor",   roman: "daaktar" },
      { hindi: "ಡಮರು",   english: "Drum",     roman: "damaru"  },
    ],
    wordKannada: "ಡಬ್ಬ",
    wordEnglish: "Tin Box",
    wordRoman: "dabba",
    assetPath: "/assets/gemini/kaveri_l4_da_retro_barakhadi.png",
    summary: "ಡ is the voiced retroflex — tongue curled, voice on!",
    prompt: "ಡಬ್ಬ is a tin box — solid and round like 'da'!",
  },
  {
    id: "L4-C03-L04",
    chapterId: "C03",
    chapterTitle: "ಟ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಢ ಬರಹಮಾಲೆ — Dha (retroflex) Barakhadi",
    category: "Syllable Matrix",
    skill: "Aspirated Voiced Retroflex",
    consonant: "ಢ",
    consonantRoman: "dha",
    barakhadiRow: [
      { syllable: "ಢ",  sound: "dha",  matra: "ಅ" },
      { syllable: "ಢಾ", sound: "dhaa", matra: "ಾ" },
      { syllable: "ಢಿ", sound: "dhi",  matra: "ಿ" },
      { syllable: "ಢೀ", sound: "dhee", matra: "ೀ" },
      { syllable: "ಢು", sound: "dhu",  matra: "ು" },
      { syllable: "ಢೂ", sound: "dhoo", matra: "ೂ" },
      { syllable: "ಢೆ", sound: "dhe",  matra: "ೆ" },
      { syllable: "ಢೇ", sound: "dhae", matra: "ೇ" },
      { syllable: "ಢೈ", sound: "dhai", matra: "ೈ" },
      { syllable: "ಢೊ", sound: "dho",  matra: "ೊ" },
      { syllable: "ಢೋ", sound: "dhoo", matra: "ೋ" },
      { syllable: "ಢೌ", sound: "dhau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಢಕ್ಕೆ", english: "Drum",   roman: "dhakke" },
      { hindi: "ಢಾಲು",  english: "Shield", roman: "dhaalu" },
      { hindi: "ಢೇಗ",   english: "Pigeon", roman: "dhega"  },
    ],
    wordKannada: "ಢಕ್ಕೆ",
    wordEnglish: "Drum",
    wordRoman: "dhakke",
    assetPath: "/assets/gemini/kaveri_l4_dha_retro_barakhadi.png",
    summary: "ಢ is the aspirated voiced retroflex — the deepest drum!",
    prompt: "ಢಕ್ಕೆ is a drum — beat it and say 'dha'!",
  },
  {
    id: "L4-C03-L05",
    chapterId: "C03",
    chapterTitle: "ಟ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಣ ಬರಹಮಾಲೆ — Na (retroflex) Barakhadi",
    category: "Syllable Matrix",
    skill: "Retroflex Nasal Mastery",
    consonant: "ಣ",
    consonantRoman: "na",
    barakhadiRow: [
      { syllable: "ಣ",  sound: "na",  matra: "ಅ" },
      { syllable: "ಣಾ", sound: "naa", matra: "ಾ" },
      { syllable: "ಣಿ", sound: "ni",  matra: "ಿ" },
      { syllable: "ಣೀ", sound: "nee", matra: "ೀ" },
      { syllable: "ಣು", sound: "nu",  matra: "ು" },
      { syllable: "ಣೂ", sound: "noo", matra: "ೂ" },
      { syllable: "ಣೆ", sound: "ne",  matra: "ೆ" },
      { syllable: "ಣೇ", sound: "nae", matra: "ೇ" },
      { syllable: "ಣೈ", sound: "nai", matra: "ೈ" },
      { syllable: "ಣೊ", sound: "no",  matra: "ೊ" },
      { syllable: "ಣೋ", sound: "noo", matra: "ೋ" },
      { syllable: "ಣೌ", sound: "nau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಕಣ್ಣು", english: "Eye",    roman: "kannu"  },
      { hindi: "ಬಾಣ",   english: "Arrow",  roman: "baana"  },
      { hindi: "ಗಣ",    english: "Group",  roman: "gana"   },
    ],
    wordKannada: "ಕಣ್ಣು",
    wordEnglish: "Eye",
    wordRoman: "kannu",
    assetPath: "/assets/gemini/kaveri_l4_na_retro_barakhadi.png",
    summary: "ಣ is the retroflex nasal — deep in the throat, tongue curled!",
    prompt: "ಣ often appears inside words — like ಕಣ್ಣು (eye)! Say 'na' curling your tongue!",
  },
  {
    id: "L4-C03-L06",
    chapterId: "C03",
    chapterTitle: "ಟ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಟ-ವರ್ಗ Review",
    category: "Review Practice",
    skill: "Retroflex Mastery",
    consonant: "ಟ & ಠ & ಡ & ಢ & ಣ",
    consonantRoman: "ta-tha-da-dha-na",
    barakhadiRow: [
      { syllable: "ಟ",  sound: "ta",  matra: "ಅ" },
      { syllable: "ಟಾ", sound: "taa", matra: "ಾ" },
      { syllable: "ಟಿ", sound: "ti",  matra: "ಿ" },
      { syllable: "ಟೀ", sound: "tee", matra: "ೀ" },
      { syllable: "ಟು", sound: "tu",  matra: "ು" },
      { syllable: "ಟೂ", sound: "too", matra: "ೂ" },
      { syllable: "ಟೆ", sound: "te",  matra: "ೆ" },
      { syllable: "ಟೇ", sound: "tae", matra: "ೇ" },
      { syllable: "ಟೈ", sound: "tai", matra: "ೈ" },
      { syllable: "ಟೊ", sound: "to",  matra: "ೊ" },
      { syllable: "ಟೋ", sound: "too", matra: "ೋ" },
      { syllable: "ಟೌ", sound: "tau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಟೊಪ್ಪಿ", english: "Cap",   roman: "toppi"  },
      { hindi: "ಡಬ್ಬ",   english: "Box",   roman: "dabba"  },
      { hindi: "ಕಣ್ಣು",  english: "Eye",   roman: "kannu"  },
    ],
    wordKannada: "ಟೊಪ್ಪಿ",
    wordEnglish: "Cap",
    wordRoman: "toppi",
    assetPath: "/assets/gemini/kaveri_l4_review_c03.png",
    summary: "Review ಟ ಠ ಡ ಢ ಣ — five retroflex consonants mastered!",
    prompt: "All five retroflexes use a curled tongue — can you feel the difference?",
  },

  // ============================================================
  // CHAPTER C04 — ತ-ವರ್ಗ (6 lessons)
  // ============================================================

  {
    id: "L4-C04-L01",
    chapterId: "C04",
    chapterTitle: "ತ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ತ ಬರಹಮಾಲೆ — Ta (dental) Barakhadi",
    category: "Syllable Matrix",
    skill: "Dental Stop Mastery",
    consonant: "ತ",
    consonantRoman: "ta",
    barakhadiRow: [
      { syllable: "ತ",  sound: "ta",  matra: "ಅ" },
      { syllable: "ತಾ", sound: "taa", matra: "ಾ" },
      { syllable: "ತಿ", sound: "ti",  matra: "ಿ" },
      { syllable: "ತೀ", sound: "tee", matra: "ೀ" },
      { syllable: "ತು", sound: "tu",  matra: "ು" },
      { syllable: "ತೂ", sound: "too", matra: "ೂ" },
      { syllable: "ತೆ", sound: "te",  matra: "ೆ" },
      { syllable: "ತೇ", sound: "tae", matra: "ೇ" },
      { syllable: "ತೈ", sound: "tai", matra: "ೈ" },
      { syllable: "ತೊ", sound: "to",  matra: "ೊ" },
      { syllable: "ತೋ", sound: "too", matra: "ೋ" },
      { syllable: "ತೌ", sound: "tau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ತಾಯಿ",    english: "Mother",     roman: "tayi"     },
      { hindi: "ತರಕಾರಿ",  english: "Vegetables", roman: "tarakari" },
      { hindi: "ತಿಂಗಳು",  english: "Month",      roman: "thingalu" },
    ],
    wordKannada: "ತಾಯಿ",
    wordEnglish: "Mother",
    wordRoman: "tayi",
    assetPath: "/assets/gemini/kaveri_l4_ta_dental_barakhadi.png",
    summary: "ತ is the dental 't' — tongue tip touches the teeth!",
    prompt: "ತಾಯಿ is mother — say 'ta' softly with your tongue on your teeth!",
  },
  {
    id: "L4-C04-L02",
    chapterId: "C04",
    chapterTitle: "ತ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಥ ಬರಹಮಾಲೆ — Tha (dental aspirate) Barakhadi",
    category: "Syllable Matrix",
    skill: "Aspirated Dental Mastery",
    consonant: "ಥ",
    consonantRoman: "tha",
    barakhadiRow: [
      { syllable: "ಥ",  sound: "tha",  matra: "ಅ" },
      { syllable: "ಥಾ", sound: "thaa", matra: "ಾ" },
      { syllable: "ಥಿ", sound: "thi",  matra: "ಿ" },
      { syllable: "ಥೀ", sound: "thee", matra: "ೀ" },
      { syllable: "ಥು", sound: "thu",  matra: "ು" },
      { syllable: "ಥೂ", sound: "thoo", matra: "ೂ" },
      { syllable: "ಥೆ", sound: "the",  matra: "ೆ" },
      { syllable: "ಥೇ", sound: "thae", matra: "ೇ" },
      { syllable: "ಥೈ", sound: "thai", matra: "ೈ" },
      { syllable: "ಥೊ", sound: "tho",  matra: "ೊ" },
      { syllable: "ಥೋ", sound: "thoo", matra: "ೋ" },
      { syllable: "ಥೌ", sound: "thau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಥಾಲಿ",  english: "Plate",       roman: "thaali"  },
      { hindi: "ಥಟ್ಟನೆ", english: "Suddenly",    roman: "thattane"},
      { hindi: "ಥಾಕು",   english: "Tired",       roman: "thaaku"  },
    ],
    wordKannada: "ಥಾಲಿ",
    wordEnglish: "Plate",
    wordRoman: "thaali",
    assetPath: "/assets/gemini/kaveri_l4_tha_dental_barakhadi.png",
    summary: "ಥ is ತ with breath — aspirated dental stop!",
    prompt: "ಥಾಲಿ is a plate — say 'tha' with a puff!",
  },
  {
    id: "L4-C04-L03",
    chapterId: "C04",
    chapterTitle: "ತ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ದ ಬರಹಮಾಲೆ — Da (dental) Barakhadi",
    category: "Syllable Matrix",
    skill: "Voiced Dental Mastery",
    consonant: "ದ",
    consonantRoman: "da",
    barakhadiRow: [
      { syllable: "ದ",  sound: "da",  matra: "ಅ" },
      { syllable: "ದಾ", sound: "daa", matra: "ಾ" },
      { syllable: "ದಿ", sound: "di",  matra: "ಿ" },
      { syllable: "ದೀ", sound: "dee", matra: "ೀ" },
      { syllable: "ದು", sound: "du",  matra: "ು" },
      { syllable: "ದೂ", sound: "doo", matra: "ೂ" },
      { syllable: "ದೆ", sound: "de",  matra: "ೆ" },
      { syllable: "ದೇ", sound: "dae", matra: "ೇ" },
      { syllable: "ದೈ", sound: "dai", matra: "ೈ" },
      { syllable: "ದೊ", sound: "do",  matra: "ೊ" },
      { syllable: "ದೋ", sound: "doo", matra: "ೋ" },
      { syllable: "ದೌ", sound: "dau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ದೇಶ",  english: "Country", roman: "desha" },
      { hindi: "ದೀಪ",  english: "Lamp",    roman: "deepa" },
      { hindi: "ದರ",   english: "Rate",    roman: "dara"  },
    ],
    wordKannada: "ದೇಶ",
    wordEnglish: "Country",
    wordRoman: "desha",
    assetPath: "/assets/gemini/kaveri_l4_da_dental_barakhadi.png",
    summary: "ದ is the voiced dental — voice on, tongue on teeth!",
    prompt: "ದೇಶ is country — say 'da' with your voice buzzing!",
  },
  {
    id: "L4-C04-L04",
    chapterId: "C04",
    chapterTitle: "ತ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಧ ಬರಹಮಾಲೆ — Dha (dental aspirate) Barakhadi",
    category: "Syllable Matrix",
    skill: "Aspirated Voiced Dental",
    consonant: "ಧ",
    consonantRoman: "dha",
    barakhadiRow: [
      { syllable: "ಧ",  sound: "dha",  matra: "ಅ" },
      { syllable: "ಧಾ", sound: "dhaa", matra: "ಾ" },
      { syllable: "ಧಿ", sound: "dhi",  matra: "ಿ" },
      { syllable: "ಧೀ", sound: "dhee", matra: "ೀ" },
      { syllable: "ಧು", sound: "dhu",  matra: "ು" },
      { syllable: "ಧೂ", sound: "dhoo", matra: "ೂ" },
      { syllable: "ಧೆ", sound: "dhe",  matra: "ೆ" },
      { syllable: "ಧೇ", sound: "dhae", matra: "ೇ" },
      { syllable: "ಧೈ", sound: "dhai", matra: "ೈ" },
      { syllable: "ಧೊ", sound: "dho",  matra: "ೊ" },
      { syllable: "ಧೋ", sound: "dhoo", matra: "ೋ" },
      { syllable: "ಧೌ", sound: "dhau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಧರ್ಮ",  english: "Virtue",     roman: "dharma"  },
      { hindi: "ಧ್ಯಾನ",  english: "Meditation", roman: "dhyana"  },
      { hindi: "ಧರೆ",   english: "Earth",      roman: "dhare"   },
    ],
    wordKannada: "ಧರ್ಮ",
    wordEnglish: "Virtue",
    wordRoman: "dharma",
    assetPath: "/assets/gemini/kaveri_l4_dha_dental_barakhadi.png",
    summary: "ಧ is ದ with breath — aspirated voiced dental!",
    prompt: "ಧರ್ಮ is virtue — say 'dha' with noble intention!",
  },
  {
    id: "L4-C04-L05",
    chapterId: "C04",
    chapterTitle: "ತ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ನ ಬರಹಮಾಲೆ — Na (dental) Barakhadi",
    category: "Syllable Matrix",
    skill: "Dental Nasal Mastery",
    consonant: "ನ",
    consonantRoman: "na",
    barakhadiRow: [
      { syllable: "ನ",  sound: "na",  matra: "ಅ" },
      { syllable: "ನಾ", sound: "naa", matra: "ಾ" },
      { syllable: "ನಿ", sound: "ni",  matra: "ಿ" },
      { syllable: "ನೀ", sound: "nee", matra: "ೀ" },
      { syllable: "ನು", sound: "nu",  matra: "ು" },
      { syllable: "ನೂ", sound: "noo", matra: "ೂ" },
      { syllable: "ನೆ", sound: "ne",  matra: "ೆ" },
      { syllable: "ನೇ", sound: "nae", matra: "ೇ" },
      { syllable: "ನೈ", sound: "nai", matra: "ೈ" },
      { syllable: "ನೊ", sound: "no",  matra: "ೊ" },
      { syllable: "ನೋ", sound: "noo", matra: "ೋ" },
      { syllable: "ನೌ", sound: "nau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ನಾಯಿ",    english: "Dog",   roman: "nayi"      },
      { hindi: "ನೀರು",    english: "Water", roman: "neeru"     },
      { hindi: "ನಕ್ಷತ್ರ", english: "Star",  roman: "nakshathra"},
    ],
    wordKannada: "ನಾಯಿ",
    wordEnglish: "Dog",
    wordRoman: "nayi",
    assetPath: "/assets/gemini/kaveri_l4_na_dental_barakhadi.png",
    summary: "ನ is the soft dental nasal — gentle hum through the nose!",
    prompt: "ನಾಯಿ is a dog — say 'na' with a warm nasal hum!",
  },
  {
    id: "L4-C04-L06",
    chapterId: "C04",
    chapterTitle: "ತ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ತ-ವರ್ಗ Review",
    category: "Review Practice",
    skill: "Dental Mastery",
    consonant: "ತ & ಥ & ದ & ಧ & ನ",
    consonantRoman: "ta-tha-da-dha-na",
    barakhadiRow: [
      { syllable: "ತ",  sound: "ta",  matra: "ಅ" },
      { syllable: "ತಾ", sound: "taa", matra: "ಾ" },
      { syllable: "ತಿ", sound: "ti",  matra: "ಿ" },
      { syllable: "ತೀ", sound: "tee", matra: "ೀ" },
      { syllable: "ತು", sound: "tu",  matra: "ು" },
      { syllable: "ತೂ", sound: "too", matra: "ೂ" },
      { syllable: "ತೆ", sound: "te",  matra: "ೆ" },
      { syllable: "ತೇ", sound: "tae", matra: "ೇ" },
      { syllable: "ತೈ", sound: "tai", matra: "ೈ" },
      { syllable: "ತೊ", sound: "to",  matra: "ೊ" },
      { syllable: "ತೋ", sound: "too", matra: "ೋ" },
      { syllable: "ತೌ", sound: "tau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ತಾಯಿ", english: "Mother",  roman: "tayi"  },
      { hindi: "ದೇಶ",  english: "Country", roman: "desha" },
      { hindi: "ನಾಯಿ", english: "Dog",     roman: "nayi"  },
    ],
    wordKannada: "ತಾಯಿ",
    wordEnglish: "Mother",
    wordRoman: "tayi",
    assetPath: "/assets/gemini/kaveri_l4_review_c04.png",
    summary: "Review ತ ಥ ದ ಧ ನ — five dental consonants mastered!",
    prompt: "ತ vs ಟ — can you feel the difference? Teeth vs curled tongue!",
  },

  // ============================================================
  // CHAPTER C05 — ಪ-ವರ್ಗ (6 lessons)
  // ============================================================

  {
    id: "L4-C05-L01",
    chapterId: "C05",
    chapterTitle: "ಪ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಪ ಬರಹಮಾಲೆ — Pa Barakhadi",
    category: "Syllable Matrix",
    skill: "Bilabial Stop Mastery",
    consonant: "ಪ",
    consonantRoman: "pa",
    barakhadiRow: [
      { syllable: "ಪ",  sound: "pa",  matra: "ಅ" },
      { syllable: "ಪಾ", sound: "paa", matra: "ಾ" },
      { syllable: "ಪಿ", sound: "pi",  matra: "ಿ" },
      { syllable: "ಪೀ", sound: "pee", matra: "ೀ" },
      { syllable: "ಪು", sound: "pu",  matra: "ು" },
      { syllable: "ಪೂ", sound: "poo", matra: "ೂ" },
      { syllable: "ಪೆ", sound: "pe",  matra: "ೆ" },
      { syllable: "ಪೇ", sound: "pae", matra: "ೇ" },
      { syllable: "ಪೈ", sound: "pai", matra: "ೈ" },
      { syllable: "ಪೊ", sound: "po",  matra: "ೊ" },
      { syllable: "ಪೋ", sound: "poo", matra: "ೋ" },
      { syllable: "ಪೌ", sound: "pau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಪಕ್ಷಿ", english: "Bird",    roman: "pakshi" },
      { hindi: "ಪಾಠ",   english: "Lesson",  roman: "paatha" },
      { hindi: "ಪೂಜೆ",  english: "Prayer",  roman: "pooje"  },
    ],
    wordKannada: "ಪಕ್ಷಿ",
    wordEnglish: "Bird",
    wordRoman: "pakshi",
    assetPath: "/assets/gemini/kaveri_l4_pa_barakhadi.png",
    summary: "ಪ is the bilabial stop — both lips come together!",
    prompt: "ಪಕ್ಷಿ is a bird — press your lips together and say 'pa'!",
  },
  {
    id: "L4-C05-L02",
    chapterId: "C05",
    chapterTitle: "ಪ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಫ ಬರಹಮಾಲೆ — Pha Barakhadi",
    category: "Syllable Matrix",
    skill: "Aspirated Bilabial Mastery",
    consonant: "ಫ",
    consonantRoman: "pha",
    barakhadiRow: [
      { syllable: "ಫ",  sound: "pha",  matra: "ಅ" },
      { syllable: "ಫಾ", sound: "phaa", matra: "ಾ" },
      { syllable: "ಫಿ", sound: "phi",  matra: "ಿ" },
      { syllable: "ಫೀ", sound: "phee", matra: "ೀ" },
      { syllable: "ಫು", sound: "phu",  matra: "ು" },
      { syllable: "ಫೂ", sound: "phoo", matra: "ೂ" },
      { syllable: "ಫೆ", sound: "phe",  matra: "ೆ" },
      { syllable: "ಫೇ", sound: "phae", matra: "ೇ" },
      { syllable: "ಫೈ", sound: "phai", matra: "ೈ" },
      { syllable: "ಫೊ", sound: "pho",  matra: "ೊ" },
      { syllable: "ಫೋ", sound: "phoo", matra: "ೋ" },
      { syllable: "ಫೌ", sound: "phau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಫಲ",   english: "Fruit",  roman: "phala"  },
      { hindi: "ಫಲಕ",  english: "Board",  roman: "phalaka"},
      { hindi: "ಫೋನ",  english: "Phone",  roman: "phona"  },
    ],
    wordKannada: "ಫಲ",
    wordEnglish: "Fruit",
    wordRoman: "phala",
    assetPath: "/assets/gemini/kaveri_l4_pha_barakhadi.png",
    summary: "ಫ is ಪ with a puff — aspirated bilabial!",
    prompt: "ಫಲ is fruit — say 'pha' with a breath like blowing on fruit!",
  },
  {
    id: "L4-C05-L03",
    chapterId: "C05",
    chapterTitle: "ಪ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಬ ಬರಹಮಾಲೆ — Ba Barakhadi",
    category: "Syllable Matrix",
    skill: "Voiced Bilabial Mastery",
    consonant: "ಬ",
    consonantRoman: "ba",
    barakhadiRow: [
      { syllable: "ಬ",  sound: "ba",  matra: "ಅ" },
      { syllable: "ಬಾ", sound: "baa", matra: "ಾ" },
      { syllable: "ಬಿ", sound: "bi",  matra: "ಿ" },
      { syllable: "ಬೀ", sound: "bee", matra: "ೀ" },
      { syllable: "ಬು", sound: "bu",  matra: "ು" },
      { syllable: "ಬೂ", sound: "boo", matra: "ೂ" },
      { syllable: "ಬೆ", sound: "be",  matra: "ೆ" },
      { syllable: "ಬೇ", sound: "bae", matra: "ೇ" },
      { syllable: "ಬೈ", sound: "bai", matra: "ೈ" },
      { syllable: "ಬೊ", sound: "bo",  matra: "ೊ" },
      { syllable: "ಬೋ", sound: "boo", matra: "ೋ" },
      { syllable: "ಬೌ", sound: "bau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಬೆಂಕಿ",  english: "Fire",   roman: "benki"  },
      { hindi: "ಬಾಗಿಲು", english: "Door",   roman: "baagilu"},
      { hindi: "ಬಣ್ಣ",   english: "Colour", roman: "banna"  },
    ],
    wordKannada: "ಬೆಂಕಿ",
    wordEnglish: "Fire",
    wordRoman: "benki",
    assetPath: "/assets/gemini/kaveri_l4_ba_barakhadi.png",
    summary: "ಬ is the voiced bilabial — like ಪ but with your voice on!",
    prompt: "ಬೆಂಕಿ is fire — warm and bright like 'ba'!",
  },
  {
    id: "L4-C05-L04",
    chapterId: "C05",
    chapterTitle: "ಪ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಭ ಬರಹಮಾಲೆ — Bha Barakhadi",
    category: "Syllable Matrix",
    skill: "Aspirated Voiced Bilabial",
    consonant: "ಭ",
    consonantRoman: "bha",
    barakhadiRow: [
      { syllable: "ಭ",  sound: "bha",  matra: "ಅ" },
      { syllable: "ಭಾ", sound: "bhaa", matra: "ಾ" },
      { syllable: "ಭಿ", sound: "bhi",  matra: "ಿ" },
      { syllable: "ಭೀ", sound: "bhee", matra: "ೀ" },
      { syllable: "ಭು", sound: "bhu",  matra: "ು" },
      { syllable: "ಭೂ", sound: "bhoo", matra: "ೂ" },
      { syllable: "ಭೆ", sound: "bhe",  matra: "ೆ" },
      { syllable: "ಭೇ", sound: "bhae", matra: "ೇ" },
      { syllable: "ಭೈ", sound: "bhai", matra: "ೈ" },
      { syllable: "ಭೊ", sound: "bho",  matra: "ೊ" },
      { syllable: "ಭೋ", sound: "bhoo", matra: "ೋ" },
      { syllable: "ಭೌ", sound: "bhau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಭೂಮಿ", english: "Earth",    roman: "bhoomi"  },
      { hindi: "ಭಾಷೆ",  english: "Language", roman: "bhashe"  },
      { hindi: "ಭವನ",  english: "Building",  roman: "bhavana" },
    ],
    wordKannada: "ಭೂಮಿ",
    wordEnglish: "Earth",
    wordRoman: "bhoomi",
    assetPath: "/assets/gemini/kaveri_l4_bha_barakhadi.png",
    summary: "ಭ is ಬ with breath — voiced and aspirated bilabial!",
    prompt: "ಭೂಮಿ is the earth beneath your feet — say 'bha' with full breath!",
  },
  {
    id: "L4-C05-L05",
    chapterId: "C05",
    chapterTitle: "ಪ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಮ ಬರಹಮಾಲೆ — Ma Barakhadi",
    category: "Syllable Matrix",
    skill: "Bilabial Nasal Mastery",
    consonant: "ಮ",
    consonantRoman: "ma",
    barakhadiRow: [
      { syllable: "ಮ",  sound: "ma",  matra: "ಅ" },
      { syllable: "ಮಾ", sound: "maa", matra: "ಾ" },
      { syllable: "ಮಿ", sound: "mi",  matra: "ಿ" },
      { syllable: "ಮೀ", sound: "mee", matra: "ೀ" },
      { syllable: "ಮು", sound: "mu",  matra: "ು" },
      { syllable: "ಮೂ", sound: "moo", matra: "ೂ" },
      { syllable: "ಮೆ", sound: "me",  matra: "ೆ" },
      { syllable: "ಮೇ", sound: "mae", matra: "ೇ" },
      { syllable: "ಮೈ", sound: "mai", matra: "ೈ" },
      { syllable: "ಮೊ", sound: "mo",  matra: "ೊ" },
      { syllable: "ಮೋ", sound: "moo", matra: "ೋ" },
      { syllable: "ಮೌ", sound: "mau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಮನೆ",  english: "House", roman: "mane"  },
      { hindi: "ಮರ",   english: "Tree",  roman: "mara"  },
      { hindi: "ಮೀನು", english: "Fish",  roman: "meenu" },
    ],
    wordKannada: "ಮನೆ",
    wordEnglish: "House",
    wordRoman: "mane",
    assetPath: "/assets/gemini/kaveri_l4_ma_barakhadi.png",
    summary: "ಮ is the bilabial nasal — hum 'mmm' through your lips!",
    prompt: "ಮನೆ is home — warm and welcoming like 'ma'!",
  },
  {
    id: "L4-C05-L06",
    chapterId: "C05",
    chapterTitle: "ಪ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಪ-ವರ್ಗ Review",
    category: "Review Practice",
    skill: "Bilabial Mastery",
    consonant: "ಪ & ಫ & ಬ & ಭ & ಮ",
    consonantRoman: "pa-pha-ba-bha-ma",
    barakhadiRow: [
      { syllable: "ಪ",  sound: "pa",  matra: "ಅ" },
      { syllable: "ಪಾ", sound: "paa", matra: "ಾ" },
      { syllable: "ಪಿ", sound: "pi",  matra: "ಿ" },
      { syllable: "ಪೀ", sound: "pee", matra: "ೀ" },
      { syllable: "ಪು", sound: "pu",  matra: "ು" },
      { syllable: "ಪೂ", sound: "poo", matra: "ೂ" },
      { syllable: "ಪೆ", sound: "pe",  matra: "ೆ" },
      { syllable: "ಪೇ", sound: "pae", matra: "ೇ" },
      { syllable: "ಪೈ", sound: "pai", matra: "ೈ" },
      { syllable: "ಪೊ", sound: "po",  matra: "ೊ" },
      { syllable: "ಪೋ", sound: "poo", matra: "ೋ" },
      { syllable: "ಪೌ", sound: "pau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಪಕ್ಷಿ", english: "Bird",  roman: "pakshi" },
      { hindi: "ಬೆಂಕಿ", english: "Fire",  roman: "benki"  },
      { hindi: "ಮನೆ",   english: "House", roman: "mane"   },
    ],
    wordKannada: "ಪಕ್ಷಿ",
    wordEnglish: "Bird",
    wordRoman: "pakshi",
    assetPath: "/assets/gemini/kaveri_l4_review_c05.png",
    summary: "Review ಪ ಫ ಬ ಭ ಮ — five bilabial consonants mastered!",
    prompt: "All five bilabials use your lips — can you feel them?",
  },

  // ============================================================
  // CHAPTER C06 — ಶೇಷ-ವರ್ಗ (8 lessons)
  // ============================================================

  {
    id: "L4-C06-L01",
    chapterId: "C06",
    chapterTitle: "ಶೇಷ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಯ ಬರಹಮಾಲೆ — Ya Barakhadi",
    category: "Syllable Matrix",
    skill: "Palatal Semivowel",
    consonant: "ಯ",
    consonantRoman: "ya",
    barakhadiRow: [
      { syllable: "ಯ",  sound: "ya",  matra: "ಅ" },
      { syllable: "ಯಾ", sound: "yaa", matra: "ಾ" },
      { syllable: "ಯಿ", sound: "yi",  matra: "ಿ" },
      { syllable: "ಯೀ", sound: "yee", matra: "ೀ" },
      { syllable: "ಯು", sound: "yu",  matra: "ು" },
      { syllable: "ಯೂ", sound: "yoo", matra: "ೂ" },
      { syllable: "ಯೆ", sound: "ye",  matra: "ೆ" },
      { syllable: "ಯೇ", sound: "yae", matra: "ೇ" },
      { syllable: "ಯೈ", sound: "yai", matra: "ೈ" },
      { syllable: "ಯೊ", sound: "yo",  matra: "ೊ" },
      { syllable: "ಯೋ", sound: "yoo", matra: "ೋ" },
      { syllable: "ಯೌ", sound: "yau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಯಾತ್ರೆ", english: "Journey", roman: "yaatre" },
      { hindi: "ಯಶ",     english: "Fame",    roman: "yasha"  },
      { hindi: "ಯೋಗ",    english: "Yoga",    roman: "yoga"   },
    ],
    wordKannada: "ಯಾತ್ರೆ",
    wordEnglish: "Journey",
    wordRoman: "yaatre",
    assetPath: "/assets/gemini/kaveri_l4_ya_barakhadi.png",
    summary: "ಯ is the palatal semivowel — gliding smoothly like a journey!",
    prompt: "ಯಾತ್ರೆ is a journey — say 'ya' and set off!",
  },
  {
    id: "L4-C06-L02",
    chapterId: "C06",
    chapterTitle: "ಶೇಷ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ರ ಬರಹಮಾಲೆ — Ra Barakhadi",
    category: "Syllable Matrix",
    skill: "Flap/Trill Mastery",
    consonant: "ರ",
    consonantRoman: "ra",
    barakhadiRow: [
      { syllable: "ರ",  sound: "ra",  matra: "ಅ" },
      { syllable: "ರಾ", sound: "raa", matra: "ಾ" },
      { syllable: "ರಿ", sound: "ri",  matra: "ಿ" },
      { syllable: "ರೀ", sound: "ree", matra: "ೀ" },
      { syllable: "ರು", sound: "ru",  matra: "ು" },
      { syllable: "ರೂ", sound: "roo", matra: "ೂ" },
      { syllable: "ರೆ", sound: "re",  matra: "ೆ" },
      { syllable: "ರೇ", sound: "rae", matra: "ೇ" },
      { syllable: "ರೈ", sound: "rai", matra: "ೈ" },
      { syllable: "ರೊ", sound: "ro",  matra: "ೊ" },
      { syllable: "ರೋ", sound: "roo", matra: "ೋ" },
      { syllable: "ರೌ", sound: "rau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ರಾಜ",  english: "King",  roman: "raaja" },
      { hindi: "ರಸ",   english: "Juice", roman: "rasa"  },
      { hindi: "ರಸ್ತೆ", english: "Road",  roman: "raste" },
    ],
    wordKannada: "ರಾಜ",
    wordEnglish: "King",
    wordRoman: "raaja",
    assetPath: "/assets/gemini/kaveri_l4_ra_barakhadi.png",
    summary: "ರ is the rolling liquid consonant — let your tongue flutter!",
    prompt: "ರಾಜ is a king — say 'ra' with a royal roll!",
  },
  {
    id: "L4-C06-L03",
    chapterId: "C06",
    chapterTitle: "ಶೇಷ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಲ ಬರಹಮಾಲೆ — La Barakhadi",
    category: "Syllable Matrix",
    skill: "Lateral Liquid Mastery",
    consonant: "ಲ",
    consonantRoman: "la",
    barakhadiRow: [
      { syllable: "ಲ",  sound: "la",  matra: "ಅ" },
      { syllable: "ಲಾ", sound: "laa", matra: "ಾ" },
      { syllable: "ಲಿ", sound: "li",  matra: "ಿ" },
      { syllable: "ಲೀ", sound: "lee", matra: "ೀ" },
      { syllable: "ಲು", sound: "lu",  matra: "ು" },
      { syllable: "ಲೂ", sound: "loo", matra: "ೂ" },
      { syllable: "ಲೆ", sound: "le",  matra: "ೆ" },
      { syllable: "ಲೇ", sound: "lae", matra: "ೇ" },
      { syllable: "ಲೈ", sound: "lai", matra: "ೈ" },
      { syllable: "ಲೊ", sound: "lo",  matra: "ೊ" },
      { syllable: "ಲೋ", sound: "loo", matra: "ೋ" },
      { syllable: "ಲೌ", sound: "lau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಲೋಕ",  english: "World",  roman: "loka"  },
      { hindi: "ಲಾಭ",  english: "Profit", roman: "laabha"},
      { hindi: "ಲಿಂಬೆ", english: "Lemon",  roman: "limbe" },
    ],
    wordKannada: "ಲೋಕ",
    wordEnglish: "World",
    wordRoman: "loka",
    assetPath: "/assets/gemini/kaveri_l4_la_barakhadi.png",
    summary: "ಲ is the lateral liquid — air flows around the sides of the tongue!",
    prompt: "ಲೋಕ is the world — say 'la' lightly and let the air flow!",
  },
  {
    id: "L4-C06-L04",
    chapterId: "C06",
    chapterTitle: "ಶೇಷ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ವ ಬರಹಮಾಲೆ — Va Barakhadi",
    category: "Syllable Matrix",
    skill: "Labiodental Semivowel",
    consonant: "ವ",
    consonantRoman: "va",
    barakhadiRow: [
      { syllable: "ವ",  sound: "va",  matra: "ಅ" },
      { syllable: "ವಾ", sound: "vaa", matra: "ಾ" },
      { syllable: "ವಿ", sound: "vi",  matra: "ಿ" },
      { syllable: "ವೀ", sound: "vee", matra: "ೀ" },
      { syllable: "ವು", sound: "vu",  matra: "ು" },
      { syllable: "ವೂ", sound: "voo", matra: "ೂ" },
      { syllable: "ವೆ", sound: "ve",  matra: "ೆ" },
      { syllable: "ವೇ", sound: "vae", matra: "ೇ" },
      { syllable: "ವೈ", sound: "vai", matra: "ೈ" },
      { syllable: "ವೊ", sound: "vo",  matra: "ೊ" },
      { syllable: "ವೋ", sound: "voo", matra: "ೋ" },
      { syllable: "ವೌ", sound: "vau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ವರ್ಷ",  english: "Rain/Year",  roman: "varsha" },
      { hindi: "ವಿದ್ಯೆ", english: "Education",  roman: "vidye"  },
      { hindi: "ವಸ್ತ್ರ", english: "Cloth",      roman: "vastra" },
    ],
    wordKannada: "ವರ್ಷ",
    wordEnglish: "Rain",
    wordRoman: "varsha",
    assetPath: "/assets/gemini/kaveri_l4_va_barakhadi.png",
    summary: "ವ is the voiced labiodental semivowel — gentle friction!",
    prompt: "ವರ್ಷ is rain — refreshing like the soft 'va' sound!",
  },
  {
    id: "L4-C06-L05",
    chapterId: "C06",
    chapterTitle: "ಶೇಷ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಶ ಬರಹಮಾಲೆ — Sha Barakhadi",
    category: "Syllable Matrix",
    skill: "Palatal Sibilant Mastery",
    consonant: "ಶ",
    consonantRoman: "sha",
    barakhadiRow: [
      { syllable: "ಶ",  sound: "sha",  matra: "ಅ" },
      { syllable: "ಶಾ", sound: "shaa", matra: "ಾ" },
      { syllable: "ಶಿ", sound: "shi",  matra: "ಿ" },
      { syllable: "ಶೀ", sound: "shee", matra: "ೀ" },
      { syllable: "ಶು", sound: "shu",  matra: "ು" },
      { syllable: "ಶೂ", sound: "shoo", matra: "ೂ" },
      { syllable: "ಶೆ", sound: "she",  matra: "ೆ" },
      { syllable: "ಶೇ", sound: "shae", matra: "ೇ" },
      { syllable: "ಶೈ", sound: "shai", matra: "ೈ" },
      { syllable: "ಶೊ", sound: "sho",  matra: "ೊ" },
      { syllable: "ಶೋ", sound: "shoo", matra: "ೋ" },
      { syllable: "ಶೌ", sound: "shau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಶಾಲೆ",  english: "School", roman: "shaale" },
      { hindi: "ಶಕ್ತಿ",  english: "Power",  roman: "shakti" },
      { hindi: "ಶಾಂತಿ",  english: "Peace",  roman: "shaanti"},
    ],
    wordKannada: "ಶಾಲೆ",
    wordEnglish: "School",
    wordRoman: "shaale",
    assetPath: "/assets/gemini/kaveri_l4_sha_barakhadi.png",
    summary: "ಶ is the palatal sibilant — a soft 'shh' sound!",
    prompt: "ಶಾಲೆ is school — say 'sha' quietly like in a library!",
  },
  {
    id: "L4-C06-L06",
    chapterId: "C06",
    chapterTitle: "ಶೇಷ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಸ ಬರಹಮಾಲೆ — Sa Barakhadi",
    category: "Syllable Matrix",
    skill: "Dental Sibilant Mastery",
    consonant: "ಸ",
    consonantRoman: "sa",
    barakhadiRow: [
      { syllable: "ಸ",  sound: "sa",  matra: "ಅ" },
      { syllable: "ಸಾ", sound: "saa", matra: "ಾ" },
      { syllable: "ಸಿ", sound: "si",  matra: "ಿ" },
      { syllable: "ಸೀ", sound: "see", matra: "ೀ" },
      { syllable: "ಸು", sound: "su",  matra: "ು" },
      { syllable: "ಸೂ", sound: "soo", matra: "ೂ" },
      { syllable: "ಸೆ", sound: "se",  matra: "ೆ" },
      { syllable: "ಸೇ", sound: "sae", matra: "ೇ" },
      { syllable: "ಸೈ", sound: "sai", matra: "ೈ" },
      { syllable: "ಸೊ", sound: "so",  matra: "ೊ" },
      { syllable: "ಸೋ", sound: "soo", matra: "ೋ" },
      { syllable: "ಸೌ", sound: "sau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಸೂರ್ಯ",  english: "Sun",   roman: "surya"   },
      { hindi: "ಸಮಯ",    english: "Time",  roman: "samaya"  },
      { hindi: "ಸಂಗೀತ",  english: "Music", roman: "sangeeta"},
    ],
    wordKannada: "ಸೂರ್ಯ",
    wordEnglish: "Sun",
    wordRoman: "surya",
    assetPath: "/assets/gemini/kaveri_l4_sa_barakhadi.png",
    summary: "ಸ is the dental sibilant — sharp 's' like the sun's rays!",
    prompt: "ಸೂರ್ಯ is the sun — bright and crisp like 'sa'!",
  },
  {
    id: "L4-C06-L07",
    chapterId: "C06",
    chapterTitle: "ಶೇಷ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಹ ಬರಹಮಾಲೆ — Ha Barakhadi",
    category: "Syllable Matrix",
    skill: "Glottal Fricative Mastery",
    consonant: "ಹ",
    consonantRoman: "ha",
    barakhadiRow: [
      { syllable: "ಹ",  sound: "ha",  matra: "ಅ" },
      { syllable: "ಹಾ", sound: "haa", matra: "ಾ" },
      { syllable: "ಹಿ", sound: "hi",  matra: "ಿ" },
      { syllable: "ಹೀ", sound: "hee", matra: "ೀ" },
      { syllable: "ಹು", sound: "hu",  matra: "ು" },
      { syllable: "ಹೂ", sound: "hoo", matra: "ೂ" },
      { syllable: "ಹೆ", sound: "he",  matra: "ೆ" },
      { syllable: "ಹೇ", sound: "hae", matra: "ೇ" },
      { syllable: "ಹೈ", sound: "hai", matra: "ೈ" },
      { syllable: "ಹೊ", sound: "ho",  matra: "ೊ" },
      { syllable: "ಹೋ", sound: "hoo", matra: "ೋ" },
      { syllable: "ಹೌ", sound: "hau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಹಾಲು",  english: "Milk",  roman: "haalu" },
      { hindi: "ಹಣ್ಣು", english: "Fruit", roman: "hannu" },
      { hindi: "ಹೂವು",  english: "Flower",roman: "hooovu"},
    ],
    wordKannada: "ಹಾಲು",
    wordEnglish: "Milk",
    wordRoman: "haalu",
    assetPath: "/assets/gemini/kaveri_l4_ha_barakhadi.png",
    summary: "ಹ is the breathy glottal — air rushing from deep in the throat!",
    prompt: "ಹಾಲು is milk — pure and fresh like a gentle 'ha'!",
  },
  {
    id: "L4-C06-L08",
    chapterId: "C06",
    chapterTitle: "ಶೇಷ-ವರ್ಗ ಬರಹಮಾಲೆ",
    title: "ಳ ಬರಹಮಾಲೆ — Lla Barakhadi (Kannada Special)",
    category: "Syllable Matrix",
    skill: "Kannada Unique Lateral",
    consonant: "ಳ",
    consonantRoman: "lla",
    barakhadiRow: [
      { syllable: "ಳ",  sound: "lla",  matra: "ಅ" },
      { syllable: "ಳಾ", sound: "llaa", matra: "ಾ" },
      { syllable: "ಳಿ", sound: "lli",  matra: "ಿ" },
      { syllable: "ಳೀ", sound: "llee", matra: "ೀ" },
      { syllable: "ಳು", sound: "llu",  matra: "ು" },
      { syllable: "ಳೂ", sound: "lloo", matra: "ೂ" },
      { syllable: "ಳೆ", sound: "lle",  matra: "ೆ" },
      { syllable: "ಳೇ", sound: "llae", matra: "ೇ" },
      { syllable: "ಳೈ", sound: "llai", matra: "ೈ" },
      { syllable: "ಳೊ", sound: "llo",  matra: "ೊ" },
      { syllable: "ಳೋ", sound: "lloo", matra: "ೋ" },
      { syllable: "ಳೌ", sound: "llau", matra: "ೌ" },
    ],
    exampleWords: [
      { hindi: "ಹಳ್ಳಿ", english: "Village", roman: "halli" },
      { hindi: "ಬಳೆ",   english: "Bangle",  roman: "bale"  },
      { hindi: "ಮಳೆ",   english: "Rain",    roman: "male"  },
    ],
    wordKannada: "ಹಳ್ಳಿ",
    wordEnglish: "Village",
    wordRoman: "halli",
    assetPath: "/assets/gemini/kaveri_l4_lla_barakhadi.png",
    summary: "ಳ is uniquely Kannada — a retroflex lateral found nowhere else! Curl and touch!",
    prompt: "ಳ is Kannada's special letter! ಹಳ್ಳಿ (village) — curl your tongue!",
  },
];

// Roman transliteration map for Level 4
export const LEVEL_4_ROMAN_MAP: Record<string, string> = {
  "L4-C01-L01": "kamala",
  "L4-C01-L02": "khadga",
  "L4-C01-L03": "gaadi",
  "L4-C01-L04": "ghante",
  "L4-C01-L05": "kamala",
  "L4-C02-L01": "chandra",
  "L4-C02-L02": "chhatri",
  "L4-C02-L03": "jala",
  "L4-C02-L04": "jhari",
  "L4-C02-L05": "chandra",
  "L4-C03-L01": "toppi",
  "L4-C03-L02": "thaane",
  "L4-C03-L03": "dabba",
  "L4-C03-L04": "dhakke",
  "L4-C03-L05": "kannu",
  "L4-C03-L06": "toppi",
  "L4-C04-L01": "tayi",
  "L4-C04-L02": "thaali",
  "L4-C04-L03": "desha",
  "L4-C04-L04": "dharma",
  "L4-C04-L05": "nayi",
  "L4-C04-L06": "tayi",
  "L4-C05-L01": "pakshi",
  "L4-C05-L02": "phala",
  "L4-C05-L03": "benki",
  "L4-C05-L04": "bhoomi",
  "L4-C05-L05": "mane",
  "L4-C05-L06": "pakshi",
  "L4-C06-L01": "yaatre",
  "L4-C06-L02": "raaja",
  "L4-C06-L03": "loka",
  "L4-C06-L04": "varsha",
  "L4-C06-L05": "shaale",
  "L4-C06-L06": "surya",
  "L4-C06-L07": "haalu",
  "L4-C06-L08": "halli",
};

// Re-export for compatibility
export const kaveriLevel4Data = LEVEL_4_DATA;
