/**
 * Kaveri Level 2 — ಗುಣಿತಾಕ್ಷರ (Gunita / Vowel Markers)
 * 36 lessons · 3 chapters · 12 vowel-marker forms each
 *
 * C01: ಕ (ka) + 12 gunita  → ಕಾ ಕಿ ಕೀ ಕು ಕೂ ಕೃ ಕೆ ಕೇ ಕೈ ಕೊ ಕೋ ಕೌ
 * C02: ಗ (ga) + 12 gunita  → ಗಾ ಗಿ ಗೀ ಗು ಗೂ ಗೃ ಗೆ ಗೇ ಗೈ ಗೊ ಗೋ ಗೌ
 * C03: ಪ (pa) + 12 gunita  → ಪಾ ಪಿ ಪೀ ಪು ಪೂ ಪೃ ಪೆ ಪೇ ಪೈ ಪೊ ಪೋ ಪೌ
 */

export interface Level2Seed {
  id: string;
  chapterId: string;
  chapterTitle: string;
  title: string;
  category: string;
  skill: string;
  baseChar: string;           // consonant, e.g. ಕ
  baseSoundRoman: string;     // "ka"
  matra: string;              // gunita mark, e.g. ಾ
  matraSoundRoman: string;    // "aa"
  modifiedChar: string;       // base + matra, e.g. ಕಾ
  modifiedSoundRoman: string; // "kaa"
  wordKannada: string;        // anchor word, e.g. ಕಾಗೆ
  wordEnglish: string;        // "Crow"
  wordRoman: string;          // "kaage"
  assetPath: string;
  durationMin?: number;
  summary: string;
  prompt: string;
}

// ============================================================
// CHAPTER C01 — ಕ (ka) + all 12 gunita  (12 lessons)
// ============================================================

export const LEVEL_2_DATA: Level2Seed[] = [

  {
    id: "L2-C01-L01",
    chapterId: "C01",
    chapterTitle: "ಕ + ಗುಣಿತ",
    title: "ಕಾ — ಕಾಗೆ (Crow)",
    category: "Gunita",
    skill: "Long A Sound",
    baseChar: "ಕ",
    baseSoundRoman: "ka",
    matra: "ಾ",
    matraSoundRoman: "aa",
    modifiedChar: "ಕಾ",
    modifiedSoundRoman: "kaa",
    wordKannada: "ಕಾಗೆ",
    wordEnglish: "Crow",
    wordRoman: "kaage",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_kaage_kaa.png",
    summary: "Add ಾ to ಕ and the short 'ka' stretches into a long 'kaa' — just like a crow's call!",
    prompt: "ಕ + ಾ = ಕಾ! Crows call 'ಕಾ ಕಾ' — say it with a nice long sound!",
  },
  {
    id: "L2-C01-L02",
    chapterId: "C01",
    chapterTitle: "ಕ + ಗುಣಿತ",
    title: "ಕಿ — ಕಿಟಕಿ (Window)",
    category: "Gunita",
    skill: "Short I Sound",
    baseChar: "ಕ",
    baseSoundRoman: "ka",
    matra: "ಿ",
    matraSoundRoman: "i",
    modifiedChar: "ಕಿ",
    modifiedSoundRoman: "ki",
    wordKannada: "ಕಿಟಕಿ",
    wordEnglish: "Window",
    wordRoman: "kitaki",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_kitaki_ki.png",
    summary: "The ಿ mark sits before the letter — it makes a short, quick 'ki' sound.",
    prompt: "ಕ + ಿ = ಕಿ! Notice the small curved mark? ಕಿಟಕಿ has 'ಕಿ' twice — quick and light!",
  },
  {
    id: "L2-C01-L03",
    chapterId: "C01",
    chapterTitle: "ಕ + ಗುಣಿತ",
    title: "ಕೀ — ಕೀ (Key)",
    category: "Gunita",
    skill: "Long II Sound",
    baseChar: "ಕ",
    baseSoundRoman: "ka",
    matra: "ೀ",
    matraSoundRoman: "ii",
    modifiedChar: "ಕೀ",
    modifiedSoundRoman: "kee",
    wordKannada: "ಕೀ",
    wordEnglish: "Key",
    wordRoman: "kee",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_kee_key.png",
    summary: "The ೀ mark is the long version of ಿ — hold the 'ee' sound a little longer.",
    prompt: "ಕ + ೀ = ಕೀ! Stretch it: 'keeee' — like the sound a door key makes when it turns!",
  },
  {
    id: "L2-C01-L04",
    chapterId: "C01",
    chapterTitle: "ಕ + ಗುಣಿತ",
    title: "ಕು — ಕುದುರೆ (Horse)",
    category: "Gunita",
    skill: "Short U Sound",
    baseChar: "ಕ",
    baseSoundRoman: "ka",
    matra: "ು",
    matraSoundRoman: "u",
    modifiedChar: "ಕು",
    modifiedSoundRoman: "ku",
    wordKannada: "ಕುದುರೆ",
    wordEnglish: "Horse",
    wordRoman: "kudure",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_kudure_ku.png",
    summary: "The ು mark hangs below the letter, rounding your lips for a short 'ku' sound.",
    prompt: "ಕ + ು = ಕು! Round your lips gently — the horse ಕುದುರೆ gallops with a 'ku' start!",
  },
  {
    id: "L2-C01-L05",
    chapterId: "C01",
    chapterTitle: "ಕ + ಗುಣಿತ",
    title: "ಕೂ — ಕೂಗು (Shout)",
    category: "Gunita",
    skill: "Long UU Sound",
    baseChar: "ಕ",
    baseSoundRoman: "ka",
    matra: "ೂ",
    matraSoundRoman: "uu",
    modifiedChar: "ಕೂ",
    modifiedSoundRoman: "koo",
    wordKannada: "ಕೂಗು",
    wordEnglish: "Shout / Call",
    wordRoman: "kogu",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_kogu_koo.png",
    summary: "ೂ is the long version of ು — hold the 'oo' sound like you are calling out loud.",
    prompt: "ಕ + ೂ = ಕೂ! ಕೂಗು means shout — cup your hands and call 'ಕೂ!' across the field!",
  },
  {
    id: "L2-C01-L06",
    chapterId: "C01",
    chapterTitle: "ಕ + ಗುಣಿತ",
    title: "ಕೃ — ಕೃಷಿ (Farming)",
    category: "Gunita",
    skill: "Vocalic R Sound",
    baseChar: "ಕ",
    baseSoundRoman: "ka",
    matra: "ೃ",
    matraSoundRoman: "ru",
    modifiedChar: "ಕೃ",
    modifiedSoundRoman: "kru",
    wordKannada: "ಕೃಷಿ",
    wordEnglish: "Farming",
    wordRoman: "krushi",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_krushi_kru.png",
    summary: "The ೃ mark creates a special vocalic-r blend — say 'k' and 'ri' together fast.",
    prompt: "ಕ + ೃ = ಕೃ! Blend 'k' and 'ri' quickly: 'kru'. ಕೃಷಿ feeds our whole country!",
  },
  {
    id: "L2-C01-L07",
    chapterId: "C01",
    chapterTitle: "ಕ + ಗುಣಿತ",
    title: "ಕೆ — ಕೆರೆ (Pond)",
    category: "Gunita",
    skill: "Short E Sound",
    baseChar: "ಕ",
    baseSoundRoman: "ka",
    matra: "ೆ",
    matraSoundRoman: "e",
    modifiedChar: "ಕೆ",
    modifiedSoundRoman: "ke",
    wordKannada: "ಕೆರೆ",
    wordEnglish: "Pond / Lake",
    wordRoman: "kere",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_kere_ke.png",
    summary: "The ೆ mark gives a short, crisp 'ke' sound — like a quick splash in a pond.",
    prompt: "ಕ + ೆ = ಕೆ! Short and clear — ಕೆರೆ (pond) appears in many Karnataka village names!",
  },
  {
    id: "L2-C01-L08",
    chapterId: "C01",
    chapterTitle: "ಕ + ಗುಣಿತ",
    title: "ಕೇ — ಕೇಳು (Listen)",
    category: "Gunita",
    skill: "Long EE Sound",
    baseChar: "ಕ",
    baseSoundRoman: "ka",
    matra: "ೇ",
    matraSoundRoman: "ee",
    modifiedChar: "ಕೇ",
    modifiedSoundRoman: "kae",
    wordKannada: "ಕೇಳು",
    wordEnglish: "Listen / Ask",
    wordRoman: "kaelu",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_kaelu_kae.png",
    summary: "The ೇ mark stretches the e-sound — ಕೇಳು means listen, so cup your ear and tune in!",
    prompt: "ಕ + ೇ = ಕೇ! Longer than ಕೆ — hold it: 'kaae'. ಕೇಳು — listen carefully!",
  },
  {
    id: "L2-C01-L09",
    chapterId: "C01",
    chapterTitle: "ಕ + ಗುಣಿತ",
    title: "ಕೈ — ಕೈ (Hand)",
    category: "Gunita",
    skill: "AI Diphthong",
    baseChar: "ಕ",
    baseSoundRoman: "ka",
    matra: "ೈ",
    matraSoundRoman: "ai",
    modifiedChar: "ಕೈ",
    modifiedSoundRoman: "kai",
    wordKannada: "ಕೈ",
    wordEnglish: "Hand",
    wordRoman: "kai",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_kai_hand.png",
    summary: "ೈ creates the 'ai' diphthong — two vowel sounds gliding together. ಕೈ is your hand!",
    prompt: "ಕ + ೈ = ಕೈ! Raise your hand and say it — 'kai'! Your own ಕೈ shows you this sound.",
  },
  {
    id: "L2-C01-L10",
    chapterId: "C01",
    chapterTitle: "ಕ + ಗುಣಿತ",
    title: "ಕೊ — ಕೊಡ (Pot)",
    category: "Gunita",
    skill: "Short O Sound",
    baseChar: "ಕ",
    baseSoundRoman: "ka",
    matra: "ೊ",
    matraSoundRoman: "o",
    modifiedChar: "ಕೊ",
    modifiedSoundRoman: "ko",
    wordKannada: "ಕೊಡ",
    wordEnglish: "Clay Pot",
    wordRoman: "koda",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_koda_ko.png",
    summary: "The ೊ mark wraps around the base to make a short 'ko' sound — round like a pot!",
    prompt: "ಕ + ೊ = ಕೊ! Shape your mouth like a round pot: 'ko'. ಕೊಡ carries water home.",
  },
  {
    id: "L2-C01-L11",
    chapterId: "C01",
    chapterTitle: "ಕ + ಗುಣಿತ",
    title: "ಕೋ — ಕೋಗಿಲೆ (Cuckoo)",
    category: "Gunita",
    skill: "Long OO Sound",
    baseChar: "ಕ",
    baseSoundRoman: "ka",
    matra: "ೋ",
    matraSoundRoman: "oo",
    modifiedChar: "ಕೋ",
    modifiedSoundRoman: "koo",
    wordKannada: "ಕೋಗಿಲೆ",
    wordEnglish: "Cuckoo / Koel",
    wordRoman: "kogile",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_kogile_koo.png",
    summary: "ೋ stretches the o-sound long — the Indian Koel sings 'ಕೋ ಕೋ' in spring!",
    prompt: "ಕ + ೋ = ಕೋ! Longer than ಕೊ — hold the 'koo' like the cuckoo's sweet call!",
  },
  {
    id: "L2-C01-L12",
    chapterId: "C01",
    chapterTitle: "ಕ + ಗುಣಿತ",
    title: "ಕೌ — ಕೌಶಲ (Skill)",
    category: "Gunita",
    skill: "AU Diphthong",
    baseChar: "ಕ",
    baseSoundRoman: "ka",
    matra: "ೌ",
    matraSoundRoman: "au",
    modifiedChar: "ಕೌ",
    modifiedSoundRoman: "kau",
    wordKannada: "ಕೌಶಲ",
    wordEnglish: "Skill",
    wordRoman: "koushala",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_koushala_kau.png",
    summary: "ೌ blends 'a' and 'u' into a broad diphthong — learning ಕ gunita is your ಕೌಶಲ!",
    prompt: "ಕ + ೌ = ಕೌ! Blend 'ka' and 'u' in one sweep: 'kau'. ಕೌಶಲ means you have mastered a skill!",
  },

  // ============================================================
  // CHAPTER C02 — ಗ (ga) + all 12 gunita  (12 lessons)
  // ============================================================

  {
    id: "L2-C02-L01",
    chapterId: "C02",
    chapterTitle: "ಗ + ಗುಣಿತ",
    title: "ಗಾ — ಗಾಳಿ (Wind)",
    category: "Gunita",
    skill: "Long A Sound",
    baseChar: "ಗ",
    baseSoundRoman: "ga",
    matra: "ಾ",
    matraSoundRoman: "aa",
    modifiedChar: "ಗಾ",
    modifiedSoundRoman: "gaa",
    wordKannada: "ಗಾಳಿ",
    wordEnglish: "Wind",
    wordRoman: "gaali",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_gaali_gaa.png",
    summary: "Now the same ಾ mark works on ಗ — ಗಾ has a softer start than ಕಾ.",
    prompt: "ಗ + ಾ = ಗಾ! The wind ಗಾಳಿ blows with a gentle 'gaa' — softer than ಕಾ!",
  },
  {
    id: "L2-C02-L02",
    chapterId: "C02",
    chapterTitle: "ಗ + ಗುಣಿತ",
    title: "ಗಿ — ಗಿಳಿ (Parrot)",
    category: "Gunita",
    skill: "Short I Sound",
    baseChar: "ಗ",
    baseSoundRoman: "ga",
    matra: "ಿ",
    matraSoundRoman: "i",
    modifiedChar: "ಗಿ",
    modifiedSoundRoman: "gi",
    wordKannada: "ಗಿಳಿ",
    wordEnglish: "Parrot",
    wordRoman: "gili",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_gili_gi.png",
    summary: "ಗ + ಿ = ಗಿ — a quick, bright 'gi' sound, just like a chatty parrot!",
    prompt: "ಗ + ಿ = ಗಿ! The parrot ಗಿಳಿ says words quickly — 'gi' is short and bright!",
  },
  {
    id: "L2-C02-L03",
    chapterId: "C02",
    chapterTitle: "ಗ + ಗುಣಿತ",
    title: "ಗೀ — ಗೀತೆ (Song)",
    category: "Gunita",
    skill: "Long II Sound",
    baseChar: "ಗ",
    baseSoundRoman: "ga",
    matra: "ೀ",
    matraSoundRoman: "ii",
    modifiedChar: "ಗೀ",
    modifiedSoundRoman: "gee",
    wordKannada: "ಗೀತೆ",
    wordEnglish: "Song / Poem",
    wordRoman: "geethe",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_geethe_gee.png",
    summary: "Stretching ಿ into ೀ gives the long 'gee' sound — a held musical note!",
    prompt: "ಗ + ೀ = ಗೀ! Hold the note: 'geeee' — like singing the first word of a ಗೀತೆ!",
  },
  {
    id: "L2-C02-L04",
    chapterId: "C02",
    chapterTitle: "ಗ + ಗುಣಿತ",
    title: "ಗು — ಗುಡ್ಡ (Hill)",
    category: "Gunita",
    skill: "Short U Sound",
    baseChar: "ಗ",
    baseSoundRoman: "ga",
    matra: "ು",
    matraSoundRoman: "u",
    modifiedChar: "ಗು",
    modifiedSoundRoman: "gu",
    wordKannada: "ಗುಡ್ಡ",
    wordEnglish: "Hill",
    wordRoman: "gudda",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_gudda_gu.png",
    summary: "ಗ + ು = ಗು — round your lips gently, like you are saying 'good' in English.",
    prompt: "ಗ + ು = ಗು! Round lips, soft sound — climb the ಗುಡ್ಡ hill with a 'gu' step!",
  },
  {
    id: "L2-C02-L05",
    chapterId: "C02",
    chapterTitle: "ಗ + ಗುಣಿತ",
    title: "ಗೂ — ಗೂಬೆ (Owl)",
    category: "Gunita",
    skill: "Long UU Sound",
    baseChar: "ಗ",
    baseSoundRoman: "ga",
    matra: "ೂ",
    matraSoundRoman: "uu",
    modifiedChar: "ಗೂ",
    modifiedSoundRoman: "goo",
    wordKannada: "ಗೂಬೆ",
    wordEnglish: "Owl",
    wordRoman: "goobe",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_goobe_goo.png",
    summary: "ಗ + ೂ = ಗೂ — the owl calls 'ಗೂ ಗೂ' at night with a long hooting sound!",
    prompt: "ಗ + ೂ = ಗೂ! The owl ಗೂಬೆ hoots at night — 'gooo' — nice and long!",
  },
  {
    id: "L2-C02-L06",
    chapterId: "C02",
    chapterTitle: "ಗ + ಗುಣಿತ",
    title: "ಗೃ — ಗೃಹ (Home)",
    category: "Gunita",
    skill: "Vocalic R Sound",
    baseChar: "ಗ",
    baseSoundRoman: "ga",
    matra: "ೃ",
    matraSoundRoman: "ru",
    modifiedChar: "ಗೃ",
    modifiedSoundRoman: "gru",
    wordKannada: "ಗೃಹ",
    wordEnglish: "Home / House",
    wordRoman: "gruha",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_gruha_gru.png",
    summary: "The rare ೃ mark on ಗ — 'gru' — is found in Sanskrit-origin Kannada words like ಗೃಹ.",
    prompt: "ಗ + ೃ = ಗೃ! Blend fast: 'g + ri = gri'. ಗೃಹ is a formal, warm word for home!",
  },
  {
    id: "L2-C02-L07",
    chapterId: "C02",
    chapterTitle: "ಗ + ಗುಣಿತ",
    title: "ಗೆ — ಗೆಲ್ಲು (Win)",
    category: "Gunita",
    skill: "Short E Sound",
    baseChar: "ಗ",
    baseSoundRoman: "ga",
    matra: "ೆ",
    matraSoundRoman: "e",
    modifiedChar: "ಗೆ",
    modifiedSoundRoman: "ge",
    wordKannada: "ಗೆಲ್ಲು",
    wordEnglish: "Win / Succeed",
    wordRoman: "gellu",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_gellu_ge.png",
    summary: "ಗ + ೆ = ಗೆ — a crisp 'ge' sound. ಗೆಲ್ಲು means win, and you will win this lesson!",
    prompt: "ಗ + ೆ = ಗೆ! Short and snappy — ಗೆಲ್ಲು! You can win by learning every gunita!",
  },
  {
    id: "L2-C02-L08",
    chapterId: "C02",
    chapterTitle: "ಗ + ಗುಣಿತ",
    title: "ಗೇ — ಗೇಟು (Gate)",
    category: "Gunita",
    skill: "Long EE Sound",
    baseChar: "ಗ",
    baseSoundRoman: "ga",
    matra: "ೇ",
    matraSoundRoman: "ee",
    modifiedChar: "ಗೇ",
    modifiedSoundRoman: "gae",
    wordKannada: "ಗೇಟು",
    wordEnglish: "Gate",
    wordRoman: "gaetu",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_gaetu_gae.png",
    summary: "ಗ + ೇ = ಗೇ — the long e-sound, like pushing open a squeaky ಗೇಟು!",
    prompt: "ಗ + ೇ = ಗೇ! Hold the 'gae' sound — swing open the big ಗೇಟು as you say it!",
  },
  {
    id: "L2-C02-L09",
    chapterId: "C02",
    chapterTitle: "ಗ + ಗುಣಿತ",
    title: "ಗೈ — ಗೈರು (Absent)",
    category: "Gunita",
    skill: "AI Diphthong",
    baseChar: "ಗ",
    baseSoundRoman: "ga",
    matra: "ೈ",
    matraSoundRoman: "ai",
    modifiedChar: "ಗೈ",
    modifiedSoundRoman: "gai",
    wordKannada: "ಗೈರು",
    wordEnglish: "Absent",
    wordRoman: "gairu",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_gairu_gai.png",
    summary: "ಗ + ೈ = ಗೈ — the 'gai' diphthong glides smoothly. ಗೈರು is called in school roll-call!",
    prompt: "ಗ + ೈ = ಗೈ! Glide from 'g' to 'ai' in one move. Don't be ಗೈರು — be present!",
  },
  {
    id: "L2-C02-L10",
    chapterId: "C02",
    chapterTitle: "ಗ + ಗುಣಿತ",
    title: "ಗೊ — ಗೊಂಬೆ (Doll)",
    category: "Gunita",
    skill: "Short O Sound",
    baseChar: "ಗ",
    baseSoundRoman: "ga",
    matra: "ೊ",
    matraSoundRoman: "o",
    modifiedChar: "ಗೊ",
    modifiedSoundRoman: "go",
    wordKannada: "ಗೊಂಬೆ",
    wordEnglish: "Doll / Puppet",
    wordRoman: "gombe",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_gombe_go.png",
    summary: "ಗ + ೊ = ಗೊ — a short, round 'go' sound. The ಗೊಂಬೆ doll has a cute rounded shape too!",
    prompt: "ಗ + ೊ = ಗೊ! Round your mouth quickly — 'go'. Hold up a ಗೊಂಬೆ and say it!",
  },
  {
    id: "L2-C02-L11",
    chapterId: "C02",
    chapterTitle: "ಗ + ಗುಣಿತ",
    title: "ಗೋ — ಗೋವು (Cow)",
    category: "Gunita",
    skill: "Long OO Sound",
    baseChar: "ಗ",
    baseSoundRoman: "ga",
    matra: "ೋ",
    matraSoundRoman: "oo",
    modifiedChar: "ಗೋ",
    modifiedSoundRoman: "goo",
    wordKannada: "ಗೋವು",
    wordEnglish: "Cow",
    wordRoman: "govu",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_govu_goo.png",
    summary: "ಗ + ೋ = ಗೋ — the long 'goo' sound. The sacred ಗೋವು is honoured in Kannada culture!",
    prompt: "ಗ + ೋ = ಗೋ! Longer than ಗೊ — hold the 'goo' sound. ಗೋವು moos back at you!",
  },
  {
    id: "L2-C02-L12",
    chapterId: "C02",
    chapterTitle: "ಗ + ಗುಣಿತ",
    title: "ಗೌ — ಗೌರವ (Respect)",
    category: "Gunita",
    skill: "AU Diphthong",
    baseChar: "ಗ",
    baseSoundRoman: "ga",
    matra: "ೌ",
    matraSoundRoman: "au",
    modifiedChar: "ಗೌ",
    modifiedSoundRoman: "gau",
    wordKannada: "ಗೌರವ",
    wordEnglish: "Respect",
    wordRoman: "gourava",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_gourava_gau.png",
    summary: "ಗ + ೌ = ಗೌ — the broad 'gau' diphthong. ಗೌರವ means respect — a value to learn forever!",
    prompt: "ಗ + ೌ = ಗೌ! Sweep from 'g' to 'au'. Show ಗೌರವ to everyone you meet!",
  },

  // ============================================================
  // CHAPTER C03 — ಪ (pa) + all 12 gunita  (12 lessons)
  // ============================================================

  {
    id: "L2-C03-L01",
    chapterId: "C03",
    chapterTitle: "ಪ + ಗುಣಿತ",
    title: "ಪಾ — ಪಾಠ (Lesson)",
    category: "Gunita",
    skill: "Long A Sound",
    baseChar: "ಪ",
    baseSoundRoman: "pa",
    matra: "ಾ",
    matraSoundRoman: "aa",
    modifiedChar: "ಪಾ",
    modifiedSoundRoman: "paa",
    wordKannada: "ಪಾಠ",
    wordEnglish: "Lesson",
    wordRoman: "paatha",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_paatha_paa.png",
    summary: "ಪ + ಾ = ಪಾ — you are in the middle of a ಪಾಠ right now! A lesson you will never forget.",
    prompt: "ಪ + ಾ = ಪಾ! ಪಾಠ means lesson — and this lesson is teaching you gunita! Meta!",
  },
  {
    id: "L2-C03-L02",
    chapterId: "C03",
    chapterTitle: "ಪ + ಗುಣಿತ",
    title: "ಪಿ — ಪಿಟೀಲು (Violin)",
    category: "Gunita",
    skill: "Short I Sound",
    baseChar: "ಪ",
    baseSoundRoman: "pa",
    matra: "ಿ",
    matraSoundRoman: "i",
    modifiedChar: "ಪಿ",
    modifiedSoundRoman: "pi",
    wordKannada: "ಪಿಟೀಲು",
    wordEnglish: "Violin",
    wordRoman: "piteelu",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_piteelu_pi.png",
    summary: "ಪ + ಿ = ಪಿ — a high, quick sound like the first note of a violin.",
    prompt: "ಪ + ಿ = ಪಿ! Crisp and fast — 'pi'. Strum an imaginary ಪಿಟೀಲು as you say it!",
  },
  {
    id: "L2-C03-L03",
    chapterId: "C03",
    chapterTitle: "ಪ + ಗುಣಿತ",
    title: "ಪೀ — ಪೀಠ (Throne)",
    category: "Gunita",
    skill: "Long II Sound",
    baseChar: "ಪ",
    baseSoundRoman: "pa",
    matra: "ೀ",
    matraSoundRoman: "ii",
    modifiedChar: "ಪೀ",
    modifiedSoundRoman: "pee",
    wordKannada: "ಪೀಠ",
    wordEnglish: "Throne / Seat",
    wordRoman: "peetha",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_peetha_pee.png",
    summary: "ಪ + ೀ = ಪೀ — the long ii sound. The ಪೀಠ throne is high up, just like the held 'pee' sound.",
    prompt: "ಪ + ೀ = ಪೀ! Sit tall on a ಪೀಠ throne and say 'peeee' with royal confidence!",
  },
  {
    id: "L2-C03-L04",
    chapterId: "C03",
    chapterTitle: "ಪ + ಗುಣಿತ",
    title: "ಪು — ಪುಸ್ತಕ (Book)",
    category: "Gunita",
    skill: "Short U Sound",
    baseChar: "ಪ",
    baseSoundRoman: "pa",
    matra: "ು",
    matraSoundRoman: "u",
    modifiedChar: "ಪು",
    modifiedSoundRoman: "pu",
    wordKannada: "ಪುಸ್ತಕ",
    wordEnglish: "Book",
    wordRoman: "pustaka",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_pustaka_pu.png",
    summary: "ಪ + ು = ಪು — a small rounded sound. ಪುಸ್ತಕ (book) is the most important 'pu' word!",
    prompt: "ಪ + ು = ಪು! Round lips gently — 'pu'. Open your ಪುಸ್ತಕ and read! You are already doing it!",
  },
  {
    id: "L2-C03-L05",
    chapterId: "C03",
    chapterTitle: "ಪ + ಗುಣಿತ",
    title: "ಪೂ — ಪೂಜೆ (Prayer)",
    category: "Gunita",
    skill: "Long UU Sound",
    baseChar: "ಪ",
    baseSoundRoman: "pa",
    matra: "ೂ",
    matraSoundRoman: "uu",
    modifiedChar: "ಪೂ",
    modifiedSoundRoman: "poo",
    wordKannada: "ಪೂಜೆ",
    wordEnglish: "Prayer / Worship",
    wordRoman: "pooje",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_pooje_poo.png",
    summary: "ಪ + ೂ = ಪೂ — the long 'poo' sound. ಪೂಜೆ fills the house with flowers and fragrance.",
    prompt: "ಪ + ೂ = ಪೂ! Fold your hands for ಪೂಜೆ and say 'poo' with a long, peaceful breath.",
  },
  {
    id: "L2-C03-L06",
    chapterId: "C03",
    chapterTitle: "ಪ + ಗುಣಿತ",
    title: "ಪೃ — ಪೃಥ್ವಿ (Earth)",
    category: "Gunita",
    skill: "Vocalic R Sound",
    baseChar: "ಪ",
    baseSoundRoman: "pa",
    matra: "ೃ",
    matraSoundRoman: "ru",
    modifiedChar: "ಪೃ",
    modifiedSoundRoman: "pru",
    wordKannada: "ಪೃಥ್ವಿ",
    wordEnglish: "Earth",
    wordRoman: "pruthvi",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_pruthvi_pru.png",
    summary: "ಪ + ೃ = ಪೃ — the vocalic-r blend gives a grand sound, perfect for the whole Earth!",
    prompt: "ಪ + ೃ = ಪೃ! Blend 'p' + 'ri' quickly: 'pri/pru'. ಪೃಥ್ವಿ — our amazing planet!",
  },
  {
    id: "L2-C03-L07",
    chapterId: "C03",
    chapterTitle: "ಪ + ಗುಣಿತ",
    title: "ಪೆ — ಪೆಟ್ಟಿಗೆ (Box)",
    category: "Gunita",
    skill: "Short E Sound",
    baseChar: "ಪ",
    baseSoundRoman: "pa",
    matra: "ೆ",
    matraSoundRoman: "e",
    modifiedChar: "ಪೆ",
    modifiedSoundRoman: "pe",
    wordKannada: "ಪೆಟ್ಟಿಗೆ",
    wordEnglish: "Box / Suitcase",
    wordRoman: "pettige",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_pettige_pe.png",
    summary: "ಪ + ೆ = ಪೆ — short and crisp. ಪೆಟ್ಟಿಗೆ is a box — square and compact like the sound.",
    prompt: "ಪ + ೆ = ಪೆ! Sharp and quick — 'pe'. Pack your ಪೆಟ್ಟಿಗೆ and say it clearly!",
  },
  {
    id: "L2-C03-L08",
    chapterId: "C03",
    chapterTitle: "ಪ + ಗುಣಿತ",
    title: "ಪೇ — ಪೇಟೆ (Market)",
    category: "Gunita",
    skill: "Long EE Sound",
    baseChar: "ಪ",
    baseSoundRoman: "pa",
    matra: "ೇ",
    matraSoundRoman: "ee",
    modifiedChar: "ಪೇ",
    modifiedSoundRoman: "pae",
    wordKannada: "ಪೇಟೆ",
    wordEnglish: "Market / Town",
    wordRoman: "paete",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_paete_pae.png",
    summary: "ಪ + ೇ = ಪೇ — a long, open 'pae' sound, as busy as a market town.",
    prompt: "ಪ + ೇ = ಪೇ! Stretch it: 'paae'. Walk through the busy ಪೇಟೆ market calling out names!",
  },
  {
    id: "L2-C03-L09",
    chapterId: "C03",
    chapterTitle: "ಪ + ಗುಣಿತ",
    title: "ಪೈ — ಪೈಸಾ (Coin)",
    category: "Gunita",
    skill: "AI Diphthong",
    baseChar: "ಪ",
    baseSoundRoman: "pa",
    matra: "ೈ",
    matraSoundRoman: "ai",
    modifiedChar: "ಪೈ",
    modifiedSoundRoman: "pai",
    wordKannada: "ಪೈಸಾ",
    wordEnglish: "Money / Coin",
    wordRoman: "paisa",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_paisa_pai.png",
    summary: "ಪ + ೈ = ಪೈ — the 'pai' diphthong glides like a coin spinning on a table!",
    prompt: "ಪ + ೈ = ಪೈ! Glide from 'p' to 'ai' in one smooth spin — just like a ಪೈಸಾ coin!",
  },
  {
    id: "L2-C03-L10",
    chapterId: "C03",
    chapterTitle: "ಪ + ಗುಣಿತ",
    title: "ಪೊ — ಪೊದೆ (Bush)",
    category: "Gunita",
    skill: "Short O Sound",
    baseChar: "ಪ",
    baseSoundRoman: "pa",
    matra: "ೊ",
    matraSoundRoman: "o",
    modifiedChar: "ಪೊ",
    modifiedSoundRoman: "po",
    wordKannada: "ಪೊದೆ",
    wordEnglish: "Bush / Shrub",
    wordRoman: "pode",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_pode_po.png",
    summary: "ಪ + ೊ = ಪೊ — a short, rounded 'po' sound like a small round bush.",
    prompt: "ಪ + ೊ = ಪೊ! Quick round mouth — 'po'. Peek inside a ಪೊದೆ bush as you say it!",
  },
  {
    id: "L2-C03-L11",
    chapterId: "C03",
    chapterTitle: "ಪ + ಗುಣಿತ",
    title: "ಪೋ — ಪೋಲೀಸ್ (Police)",
    category: "Gunita",
    skill: "Long OO Sound",
    baseChar: "ಪ",
    baseSoundRoman: "pa",
    matra: "ೋ",
    matraSoundRoman: "oo",
    modifiedChar: "ಪೋ",
    modifiedSoundRoman: "poo",
    wordKannada: "ಪೋಲೀಸ್",
    wordEnglish: "Police",
    wordRoman: "polees",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_polees_poo.png",
    summary: "ಪ + ೋ = ಪೋ — the long 'poo' sound. ಪೋಲೀಸ್ (police) is a word every child knows!",
    prompt: "ಪ + ೋ = ಪೋ! Long 'pooo' — ಪೋಲೀಸ್ patrol with a confident, long sound!",
  },
  {
    id: "L2-C03-L12",
    chapterId: "C03",
    chapterTitle: "ಪ + ಗುಣಿತ",
    title: "ಪೌ — ಪೌಷ್ಟಿಕ (Nutritious)",
    category: "Gunita",
    skill: "AU Diphthong",
    baseChar: "ಪ",
    baseSoundRoman: "pa",
    matra: "ೌ",
    matraSoundRoman: "au",
    modifiedChar: "ಪೌ",
    modifiedSoundRoman: "pau",
    wordKannada: "ಪೌಷ್ಟಿಕ",
    wordEnglish: "Nutritious",
    wordRoman: "poushtika",
    assetPath: "/kaveri/assets/gemini/kaveri_l2_poushtika_pau.png",
    summary: "ಪ + ೌ = ಪೌ — the broad diphthong. Eat ಪೌಷ್ಟಿಕ food every day for a strong body!",
    prompt: "ಪ + ೌ = ಪೌ! Sweep from 'p' to 'au'. ಪೌಷ್ಟಿಕ ahara — eat well and grow well!",
  },
];

// ── Roman transliteration map (lesson ID → word roman) ────────────────────────
export const LEVEL_2_ROMAN_MAP: Record<string, string> = {
  "L2-C01-L01": "kaage",
  "L2-C01-L02": "kitaki",
  "L2-C01-L03": "kee",
  "L2-C01-L04": "kudure",
  "L2-C01-L05": "kogu",
  "L2-C01-L06": "krushi",
  "L2-C01-L07": "kere",
  "L2-C01-L08": "kaelu",
  "L2-C01-L09": "kai",
  "L2-C01-L10": "koda",
  "L2-C01-L11": "kogile",
  "L2-C01-L12": "koushala",
  "L2-C02-L01": "gaali",
  "L2-C02-L02": "gili",
  "L2-C02-L03": "geethe",
  "L2-C02-L04": "gudda",
  "L2-C02-L05": "goobe",
  "L2-C02-L06": "gruha",
  "L2-C02-L07": "gellu",
  "L2-C02-L08": "gaetu",
  "L2-C02-L09": "gairu",
  "L2-C02-L10": "gombe",
  "L2-C02-L11": "govu",
  "L2-C02-L12": "gourava",
  "L2-C03-L01": "paatha",
  "L2-C03-L02": "piteelu",
  "L2-C03-L03": "peetha",
  "L2-C03-L04": "pustaka",
  "L2-C03-L05": "pooje",
  "L2-C03-L06": "pruthvi",
  "L2-C03-L07": "pettige",
  "L2-C03-L08": "paete",
  "L2-C03-L09": "paisa",
  "L2-C03-L10": "pode",
  "L2-C03-L11": "polees",
  "L2-C03-L12": "poushtika",
};

// Re-export alias used by KaveriLessonClient
export const kaveriLevel2Data = LEVEL_2_DATA;
