// ─────────────────────────────────────────────────────────────────────────────
// NEET AI Tutor — Chapter & Unit Catalog
// Based on NMC NEET UG 2025 Syllabus (NCERT Class 11 + 12)
// 35-year PYQ frequency weights included (neetWeight 1-5)
// ─────────────────────────────────────────────────────────────────────────────

export type NeetSubject = "physics" | "chemistry" | "biology";

export type NeetChapter = {
  chapterCode: string;
  title: string;
  subject: NeetSubject;
  ncertClass: "11" | "12";
  ncertChapter: string;
  neetWeight: 1 | 2 | 3 | 4 | 5; // 5 = asked every year, 1 = rare
  avgQuestionsPerYear: number;
  estimatedMinutes: number;
  subtopics: string[];
  keyFormulas?: string[];
  highYieldTags: string[];
  diagrams?: Array<{
    id: string;
    title: string;
    src: string;
    caption: string;
    topic: string;
  }>;
};

// ─── PHYSICS (45 Questions in NEET) ──────────────────────────────────────────
export const PHYSICS_CHAPTERS: NeetChapter[] = [
  {
    chapterCode: "PHY_KINEMATICS",
    title: "Kinematics",
    subject: "physics",
    ncertClass: "11",
    ncertChapter: "3-4",
    neetWeight: 3,
    avgQuestionsPerYear: 2.5,
    estimatedMinutes: 40,
    subtopics: [
      "Motion in a Straight Line",
      "Motion in a Plane",
      "Projectile Motion",
      "Relative Motion",
      "Graphs: v-t, x-t, a-t",
    ],
    keyFormulas: ["v = u + at", "s = ut + ½at²", "v² = u² + 2as", "Range = u²sin2θ/g"],
    highYieldTags: ["projectile motion", "relative velocity", "v-t graphs"],
  },
  {
    chapterCode: "PHY_LAWS_MOTION",
    title: "Laws of Motion",
    subject: "physics",
    ncertClass: "11",
    ncertChapter: "5",
    neetWeight: 4,
    avgQuestionsPerYear: 3.2,
    estimatedMinutes: 45,
    subtopics: [
      "Newton's Three Laws",
      "Friction: Static, Kinetic, Rolling",
      "Free Body Diagrams",
      "Connected Bodies and Pulleys",
      "Circular Motion and Banking",
    ],
    keyFormulas: ["F = ma", "f = μN", "T in Atwood = 2m₁m₂g/(m₁+m₂)"],
    highYieldTags: ["friction", "pulley problems", "pseudo force"],
  },
  {
    chapterCode: "PHY_WORK_ENERGY",
    title: "Work, Energy and Power",
    subject: "physics",
    ncertClass: "11",
    ncertChapter: "6",
    neetWeight: 3,
    avgQuestionsPerYear: 2.1,
    estimatedMinutes: 35,
    subtopics: [
      "Work Done by Constant and Variable Force",
      "Kinetic and Potential Energy",
      "Work-Energy Theorem",
      "Conservation of Energy",
      "Collisions: Elastic, Inelastic",
    ],
    keyFormulas: ["W = Fs cosθ", "KE = ½mv²", "P = Fv"],
    highYieldTags: ["elastic collision", "spring PE", "work-energy theorem"],
  },
  {
    chapterCode: "PHY_ROTATIONAL",
    title: "Rotational Motion & Gravitation",
    subject: "physics",
    ncertClass: "11",
    ncertChapter: "7-8",
    neetWeight: 3,
    avgQuestionsPerYear: 2.8,
    estimatedMinutes: 45,
    subtopics: [
      "Torque and Angular Momentum",
      "Moment of Inertia",
      "Rolling Motion",
      "Universal Law of Gravitation",
      "Orbital Velocity, Escape Velocity",
      "Satellites and Kepler's Laws",
    ],
    keyFormulas: ["τ = Iα", "L = Iω", "v_orbital = √(GM/r)", "v_escape = √(2GM/R)"],
    highYieldTags: ["escape velocity", "Kepler laws", "rolling without slipping"],
  },
  {
    chapterCode: "PHY_WAVES",
    title: "Oscillations and Waves",
    subject: "physics",
    ncertClass: "11",
    ncertChapter: "14-15",
    neetWeight: 4,
    avgQuestionsPerYear: 3.5,
    estimatedMinutes: 45,
    subtopics: [
      "Simple Harmonic Motion (SHM)",
      "Spring-Mass System and Simple Pendulum",
      "Wave Motion: Transverse and Longitudinal",
      "Superposition: Beats, Standing Waves",
      "Doppler Effect",
    ],
    keyFormulas: ["T = 2π√(l/g)", "T = 2π√(m/k)", "f_beats = |f₁-f₂|", "v_sound = √(γP/ρ)"],
    highYieldTags: ["SHM", "Doppler effect", "beats", "standing waves"],
  },
  {
    chapterCode: "PHY_THERMODYNAMICS",
    title: "Thermodynamics and Kinetic Theory",
    subject: "physics",
    ncertClass: "11",
    ncertChapter: "12-13",
    neetWeight: 3,
    avgQuestionsPerYear: 2.4,
    estimatedMinutes: 40,
    subtopics: [
      "Zeroth, First and Second Laws of Thermodynamics",
      "Heat Engines, Refrigerators, Carnot Cycle",
      "Kinetic Theory of Gases",
      "Mean Free Path, RMS Speed",
      "Degrees of Freedom, Equipartition",
    ],
    keyFormulas: ["η_Carnot = 1 - T₂/T₁", "PV = nRT", "v_rms = √(3RT/M)"],
    highYieldTags: ["Carnot engine", "first law", "degrees of freedom"],
  },
  {
    chapterCode: "PHY_ELECTROSTATICS",
    title: "Electrostatics",
    subject: "physics",
    ncertClass: "12",
    ncertChapter: "1-2",
    neetWeight: 5,
    avgQuestionsPerYear: 5.1,
    estimatedMinutes: 55,
    subtopics: [
      "Coulomb's Law and Electric Field",
      "Electric Potential and Potential Energy",
      "Gauss's Law and Applications",
      "Capacitors: Series, Parallel, Energy",
      "Dielectrics and Polarisation",
    ],
    keyFormulas: ["F = kq₁q₂/r²", "E = kq/r²", "V = kq/r", "C = ε₀A/d", "U = ½CV²"],
    highYieldTags: ["Gauss law", "capacitor combinations", "electric field due to shell"],
  },
  {
    chapterCode: "PHY_CURRENT_ELECTRICITY",
    title: "Current Electricity",
    subject: "physics",
    ncertClass: "12",
    ncertChapter: "3",
    neetWeight: 4,
    avgQuestionsPerYear: 4.0,
    estimatedMinutes: 50,
    subtopics: [
      "Ohm's Law and Resistance",
      "Kirchhoff's Laws (KVL, KCL)",
      "Wheatstone Bridge and Potentiometer",
      "Cells in Series and Parallel",
      "Heating Effect: Power Dissipation",
    ],
    keyFormulas: ["V = IR", "P = V²/R = I²R", "R_series = R₁+R₂", "1/R_parallel = 1/R₁+1/R₂"],
    highYieldTags: ["Kirchhoff laws", "potentiometer", "Wheatstone bridge"],
  },
  {
    chapterCode: "PHY_MAGNETISM",
    title: "Magnetic Effects of Current and Magnetism",
    subject: "physics",
    ncertClass: "12",
    ncertChapter: "4-5",
    neetWeight: 4,
    avgQuestionsPerYear: 3.8,
    estimatedMinutes: 50,
    subtopics: [
      "Biot-Savart Law and Ampere's Law",
      "Force on Charged Particle in Magnetic Field",
      "Solenoid and Toroid",
      "Electromagnetic Induction, Faraday's Law, Lenz's Law",
      "AC Circuits: LCR, Resonance, Power Factor",
    ],
    keyFormulas: ["F = qv×B", "B = μ₀nI (solenoid)", "EMF = -dΦ/dt", "Z = √(R²+(XL-XC)²)"],
    highYieldTags: ["Lenz's law", "cyclotron", "LCR resonance", "transformer"],
  },
  {
    chapterCode: "PHY_OPTICS",
    title: "Optics",
    subject: "physics",
    ncertClass: "12",
    ncertChapter: "9-10",
    neetWeight: 5,
    avgQuestionsPerYear: 5.3,
    estimatedMinutes: 55,
    subtopics: [
      "Reflection: Mirrors (Concave, Convex)",
      "Refraction: Snell's Law, TIR, Prism",
      "Lenses: Thin Lens Formula, Lens Maker's Equation",
      "Optical Instruments: Microscope, Telescope",
      "Wave Optics: Interference (Young's experiment), Diffraction, Polarisation",
    ],
    keyFormulas: ["1/v - 1/u = 1/f", "n = sin i / sin r", "β = λD/d (fringe width)", "Brewster: tan i_B = n"],
    highYieldTags: ["mirror formula", "Young's double slit", "TIR", "resolving power"],
    diagrams: [
      { id: "ydse", title: "YDSE — Fringe Pattern", src: "/neet/diagrams/ydse.svg", caption: "β = λD/d | Bright: Δ=nλ | Dark: Δ=(2n-1)λ/2 | In water: β decreases", topic: "Wave Optics: Interference" },
    ],
  },
  {
    chapterCode: "PHY_MODERN_PHYSICS",
    title: "Modern Physics",
    subject: "physics",
    ncertClass: "12",
    ncertChapter: "11-14",
    neetWeight: 5,
    avgQuestionsPerYear: 4.8,
    estimatedMinutes: 55,
    subtopics: [
      "Dual Nature: Photoelectric Effect, de Broglie Hypothesis",
      "Atomic Models: Bohr's Model, Hydrogen Spectrum",
      "Nuclei: Radioactivity, Half-life, Nuclear Reactions",
      "Semiconductors: p-n junction, Diode, Transistor",
      "Logic Gates",
    ],
    keyFormulas: ["E = hf", "KE_max = hf - φ", "λ = h/mv", "T½ = 0.693/λ", "E_n = -13.6/n² eV"],
    highYieldTags: ["photoelectric effect", "Bohr model", "half-life", "semiconductors"],
  },
];

// ─── CHEMISTRY (45 Questions in NEET) ────────────────────────────────────────
export const CHEMISTRY_CHAPTERS: NeetChapter[] = [
  {
    chapterCode: "CHEM_BASIC_CONCEPTS",
    title: "Some Basic Concepts of Chemistry",
    subject: "chemistry",
    ncertClass: "11",
    ncertChapter: "1",
    neetWeight: 2,
    avgQuestionsPerYear: 1.5,
    estimatedMinutes: 30,
    subtopics: ["Mole Concept", "Molarity and Molality", "Stoichiometry", "Limiting Reagent"],
    highYieldTags: ["mole concept", "empirical formula", "stoichiometry"],
  },
  {
    chapterCode: "CHEM_ATOMIC_STRUCTURE",
    title: "Structure of Atom",
    subject: "chemistry",
    ncertClass: "11",
    ncertChapter: "2",
    neetWeight: 3,
    avgQuestionsPerYear: 2.5,
    estimatedMinutes: 40,
    subtopics: [
      "Bohr's Model and Quantum Numbers",
      "Electronic Configuration (Aufbau, Hund's, Pauli)",
      "de Broglie and Heisenberg Uncertainty",
      "Shapes of Orbitals (s, p, d)",
    ],
    highYieldTags: ["quantum numbers", "electronic configuration", "Heisenberg"],
  },
  {
    chapterCode: "CHEM_BONDING",
    title: "Chemical Bonding and Molecular Structure",
    subject: "chemistry",
    ncertClass: "11",
    ncertChapter: "4",
    neetWeight: 5,
    avgQuestionsPerYear: 4.8,
    estimatedMinutes: 50,
    subtopics: [
      "Ionic Bond: Lattice Energy, Born-Haber cycle",
      "Covalent Bond: Lewis Structures, Octet Rule",
      "VSEPR Theory and Molecular Geometry",
      "Hybridisation: sp, sp², sp³, sp³d, sp³d²",
      "Molecular Orbital Theory (MOT)",
      "Hydrogen Bonding and van der Waals Forces",
      "Resonance and Formal Charge",
    ],
    highYieldTags: ["VSEPR", "hybridisation", "bond angle", "MOT bond order", "hydrogen bond"],
  },
  {
    chapterCode: "CHEM_STATES_MATTER",
    title: "States of Matter and Thermodynamics",
    subject: "chemistry",
    ncertClass: "11",
    ncertChapter: "5-6",
    neetWeight: 3,
    avgQuestionsPerYear: 2.8,
    estimatedMinutes: 40,
    subtopics: [
      "Gas Laws: Boyle, Charles, Gay-Lussac",
      "Ideal Gas Equation, Dalton's Law",
      "van der Waals Equation",
      "Thermodynamic Functions: ΔH, ΔS, ΔG",
      "Hess's Law, Bond Enthalpies",
      "Spontaneity and Gibbs Energy",
    ],
    highYieldTags: ["Gibbs energy", "Hess law", "bond enthalpy", "van der Waals"],
  },
  {
    chapterCode: "CHEM_EQUILIBRIUM",
    title: "Equilibrium",
    subject: "chemistry",
    ncertClass: "11",
    ncertChapter: "7",
    neetWeight: 4,
    avgQuestionsPerYear: 3.9,
    estimatedMinutes: 50,
    subtopics: [
      "Law of Mass Action, Kc and Kp",
      "Le Chatelier's Principle",
      "Acids and Bases: Arrhenius, Brønsted-Lowry, Lewis",
      "pH, pOH, Buffer Solutions",
      "Ionic Equilibrium: Solubility Product (Ksp)",
      "Common Ion Effect",
    ],
    highYieldTags: ["Kc Kp relation", "buffer pH", "Ksp", "Le Chatelier"],
  },
  {
    chapterCode: "CHEM_REDOX_SBLOCK",
    title: "Redox Reactions and s-Block Elements",
    subject: "chemistry",
    ncertClass: "11",
    ncertChapter: "8-10",
    neetWeight: 3,
    avgQuestionsPerYear: 2.2,
    estimatedMinutes: 35,
    subtopics: [
      "Oxidation Number and Balancing by Ion-electron Method",
      "Alkali Metals (Group 1): Properties, Anomalous behaviour of Li",
      "Alkaline Earth Metals (Group 2): Properties, Anomalous behaviour of Be",
      "Important Compounds: NaOH, Na₂CO₃, CaO, CaCO₃",
    ],
    highYieldTags: ["oxidation number", "diagonal relationship", "group 1 and 2 anomalies"],
  },
  {
    chapterCode: "CHEM_PBLOCK",
    title: "p-Block Elements",
    subject: "chemistry",
    ncertClass: "12",
    ncertChapter: "7",
    neetWeight: 5,
    avgQuestionsPerYear: 4.9,
    estimatedMinutes: 55,
    subtopics: [
      "Group 15: N, P — Allotropes, Compounds (NH₃, HNO₃, PCl₅)",
      "Group 16: O, S — Allotropes, Compounds (SO₂, SO₃, H₂SO₄)",
      "Group 17: Halogens — Reactivity, Interhalogen compounds",
      "Group 18: Noble Gases — Properties and Uses",
      "Ozone and its Reactions",
    ],
    highYieldTags: ["allotropes of P and S", "interhalogen", "oxoacids of N and P", "bleaching powder"],
  },
  {
    chapterCode: "CHEM_DBLOCK_COORD",
    title: "d-Block Elements and Coordination Compounds",
    subject: "chemistry",
    ncertClass: "12",
    ncertChapter: "8-9",
    neetWeight: 4,
    avgQuestionsPerYear: 4.1,
    estimatedMinutes: 50,
    subtopics: [
      "d-Block: General Properties, Variable Oxidation States",
      "Important Compounds: KMnO₄, K₂Cr₂O₇",
      "Coordination Compounds: IUPAC Nomenclature",
      "Isomerism in Coordination Compounds",
      "Crystal Field Theory (CFT): High/Low spin",
      "Spectrochemical Series",
    ],
    highYieldTags: ["IUPAC nomenclature", "EAN rule", "CFT", "isomerism", "KMnO₄ reactions"],
  },
  {
    chapterCode: "CHEM_ELECTROCHEMISTRY",
    title: "Electrochemistry and Chemical Kinetics",
    subject: "chemistry",
    ncertClass: "12",
    ncertChapter: "3-4",
    neetWeight: 4,
    avgQuestionsPerYear: 3.7,
    estimatedMinutes: 50,
    subtopics: [
      "Galvanic Cells, Standard Electrode Potential",
      "Nernst Equation, EMF Calculation",
      "Electrolytic Cells: Faraday's Laws",
      "Rate Laws and Order of Reaction",
      "Integrated Rate Equations (Zero, First, Second Order)",
      "Arrhenius Equation and Activation Energy",
    ],
    keyFormulas: ["E_cell = E°_cell - (RT/nF)lnQ", "t½ = 0.693/k (first order)", "k = Ae^(-Ea/RT)"],
    highYieldTags: ["Nernst equation", "Faraday law", "half-life first order", "Arrhenius"],
  },
  {
    chapterCode: "CHEM_ORGANIC",
    title: "Organic Chemistry: Mechanisms to Named Reactions",
    subject: "chemistry",
    ncertClass: "12",
    ncertChapter: "10-16",
    neetWeight: 5,
    avgQuestionsPerYear: 5.5,
    estimatedMinutes: 65,
    subtopics: [
      "Haloalkanes: SN1, SN2, Elimination Reactions",
      "Alcohols, Phenols, Ethers",
      "Aldehydes & Ketones: Nucleophilic Addition, Aldol, Cannizzaro",
      "Carboxylic Acids and Derivatives",
      "Amines: Basicity Order, Diazonium Salt Reactions",
      "Biomolecules: Carbohydrates, Proteins, Nucleic Acids, Vitamins",
      "Polymers: Types, Named Polymers",
    ],
    highYieldTags: ["SN1 vs SN2", "aldol condensation", "Cannizzaro", "diazonium", "reducing sugars"],
  },
];

// ─── BIOLOGY (90 Questions in NEET) ──────────────────────────────────────────
export const BIOLOGY_CHAPTERS: NeetChapter[] = [
  {
    chapterCode: "BIO_DIVERSITY",
    title: "Diversity in Living World",
    subject: "biology",
    ncertClass: "11",
    ncertChapter: "1-4",
    neetWeight: 4,
    avgQuestionsPerYear: 4.5,
    estimatedMinutes: 45,
    subtopics: [
      "Taxonomy and Systematics",
      "Binomial Nomenclature (ICBN / ICZN)",
      "Five Kingdom Classification",
      "Monera, Protista, Fungi — Key Characters",
      "Plant Kingdom: Algae, Bryophyta, Pteridophyta, Gymnosperms, Angiosperms",
      "Animal Kingdom: Basis of Classification, All Major Phyla",
    ],
    highYieldTags: ["five kingdom", "binomial nomenclature", "animal phyla", "plant kingdom"],
  },
  {
    chapterCode: "BIO_STRUCTURAL_ORG",
    title: "Structural Organisation in Animals and Plants",
    subject: "biology",
    ncertClass: "11",
    ncertChapter: "5-7",
    neetWeight: 3,
    avgQuestionsPerYear: 2.8,
    estimatedMinutes: 40,
    subtopics: [
      "Morphology of Flowering Plants",
      "Anatomy of Plants: Root, Stem, Leaf tissues",
      "Structural Organisation in Animals: Earthworm, Cockroach, Frog",
    ],
    highYieldTags: ["monocot vs dicot anatomy", "earthworm anatomy", "cockroach"],
  },
  {
    chapterCode: "BIO_CELL",
    title: "Cell: Structure and Functions",
    subject: "biology",
    ncertClass: "11",
    ncertChapter: "8-10",
    neetWeight: 5,
    avgQuestionsPerYear: 6.2,
    estimatedMinutes: 55,
    subtopics: [
      "Cell Theory and Prokaryote vs Eukaryote",
      "Cell Organelles: ER, Golgi, Mitochondria, Chloroplast, Lysosome, Ribosome",
      "Nucleus: Structure, Nuclear envelope, Chromosomes",
      "Biomolecules: Carbohydrates, Proteins, Lipids, Nucleic Acids, Enzymes",
      "Cell Division: Mitosis (Phases) and Meiosis (Crossing over)",
    ],
    highYieldTags: ["mitosis vs meiosis", "organelle function", "enzyme inhibition", "cell cycle checkpoints"],
  },
  {
    chapterCode: "BIO_PLANT_PHYSIO",
    title: "Plant Physiology",
    subject: "biology",
    ncertClass: "11",
    ncertChapter: "11-15",
    neetWeight: 5,
    avgQuestionsPerYear: 7.1,
    estimatedMinutes: 55,
    subtopics: [
      "Transport in Plants: Osmosis, Plasmolysis, Water Potential, Ascent of sap",
      "Mineral Nutrition: Macro and Micronutrients, Deficiency symptoms",
      "Photosynthesis: Pigments, Light reactions (Z-scheme, Photophosphorylation), Calvin Cycle",
      "C4 Pathway (Hatch-Slack), CAM Plants, Photorespiration",
      "Respiration: Glycolysis, Krebs Cycle, ETC, ATP Yield, Fermentation",
      "Plant Growth: Phytohormones (Auxin, GA, Cytokinin, ABA, Ethylene)",
    ],
    highYieldTags: ["Z-scheme", "Calvin cycle", "C3 vs C4", "Krebs cycle ATP yield", "auxin vs GA"],
  },
  {
    chapterCode: "BIO_HUMAN_PHYSIO",
    title: "Human Physiology",
    subject: "biology",
    ncertClass: "11",
    ncertChapter: "16-22",
    neetWeight: 5,
    avgQuestionsPerYear: 11.3,
    estimatedMinutes: 65,
    subtopics: [
      "Digestion: Enzymes, Absorption (small intestine), GI hormones",
      "Respiration: Lung volumes, Oxygen dissociation curve, CO₂ transport",
      "Circulation: Heart chambers, Cardiac cycle, ECG, Blood groups (ABO, Rh)",
      "Excretion: Nephron structure, Urine formation (GFR, reabsorption, secretion), ADH",
      "Locomotion: Muscle types, Sliding filament theory, Bone and Joint types",
      "Neural Control: Neuron types, Synapse, Reflex arc, Brain regions",
      "Endocrine System: All glands, hormones, feedback loops",
    ],
    highYieldTags: ["nephron", "cardiac cycle", "oxygen dissociation curve", "sliding filament", "neurotransmitters"],
    diagrams: [
      { id: "nephron", title: "Nephron — Urine Formation", src: "/neet/diagrams/nephron.svg", caption: "Bowman's capsule → PCT → Loop of Henle → DCT → Collecting duct", topic: "Excretory Products and Elimination" },
      { id: "ecg-waves", title: "ECG — Cardiac Waves", src: "/neet/diagrams/ecg-waves.svg", caption: "P (atrial depolarisation) → QRS (ventricular depolarisation) → T (repolarisation)", topic: "Body Fluids and Circulation" },
    ],
  },
  {
    chapterCode: "BIO_REPRODUCTION",
    title: "Reproduction",
    subject: "biology",
    ncertClass: "12",
    ncertChapter: "1-4",
    neetWeight: 5,
    avgQuestionsPerYear: 7.4,
    estimatedMinutes: 55,
    subtopics: [
      "Asexual Reproduction: Vegetative, Sporulation, Budding",
      "Sexual Reproduction in Flowering Plants: Microsporogenesis, Megasporogenesis, Pollination, Double Fertilisation",
      "Embryo Development in Plants: Seed and Fruit Formation",
      "Human Reproductive System: Male and Female anatomy",
      "Gametogenesis: Spermatogenesis, Oogenesis",
      "Menstrual Cycle and Implantation",
      "Reproductive Health: Contraception, STDs, Infertility, ART",
    ],
    highYieldTags: ["double fertilisation", "oogenesis vs spermatogenesis", "menstrual cycle", "ART methods"],
  },
  {
    chapterCode: "BIO_GENETICS",
    title: "Genetics and Evolution",
    subject: "biology",
    ncertClass: "12",
    ncertChapter: "5-7",
    neetWeight: 5,
    avgQuestionsPerYear: 14.2,
    estimatedMinutes: 70,
    subtopics: [
      "Mendelian Laws and Deviations (Incomplete dominance, Codominance, Epistasis)",
      "Chromosomal Theory: Linkage, Crossing Over, Sex Linkage",
      "Sex Determination: XY, ZW, XO systems",
      "Pedigree Analysis: Autosomal and X-linked traits",
      "DNA: Watson-Crick model, Replication (Meselson-Stahl)",
      "Transcription, Translation, Genetic Code (codons, exceptions)",
      "Gene Regulation: Lac Operon (Inducible), Tryptophan Operon (Repressible)",
      "Human Genome Project, DNA Fingerprinting",
      "Origin of Life: Oparin-Haldane, Miller-Urey",
      "Evolution: Darwinism, Neo-Darwinism, Hardy-Weinberg law, Speciation",
    ],
    highYieldTags: ["dihybrid ratio", "pedigree", "central dogma", "lac operon", "Hardy-Weinberg"],
    diagrams: [
      { id: "lac-operon", title: "Lac Operon — Gene Regulation", src: "/neet/diagrams/lac-operon.svg", caption: "State 1: Repressed (no lactose) | State 2: Induced (allolactose present)", topic: "Molecular Basis of Inheritance" },
    ],
  },
  {
    chapterCode: "BIO_HUMAN_WELFARE",
    title: "Biology and Human Welfare",
    subject: "biology",
    ncertClass: "12",
    ncertChapter: "8-9",
    neetWeight: 3,
    avgQuestionsPerYear: 3.1,
    estimatedMinutes: 35,
    subtopics: [
      "Microbes in Human Welfare: Fermentation (cheese, curd, bread), Antibiotics, Biogas",
      "Microbes in Sewage Treatment: Primary and Secondary treatment",
      "Immunity: Innate (Non-specific), Acquired (Active, Passive)",
      "Vaccines, Monoclonal Antibodies",
      "Common Diseases: Typhoid, Pneumonia, Common cold, Malaria, Amoebiasis, Ascariasis, Filariasis, Dengue",
      "Cancer: Types, Oncogenes",
      "AIDS: HIV lifecycle, Transmission",
      "Drugs and Alcohol Abuse",
    ],
    highYieldTags: ["malaria lifecycle", "HIV", "innate vs adaptive immunity", "biogas plant"],
  },
  {
    chapterCode: "BIO_BIOTECHNOLOGY",
    title: "Biotechnology and Its Applications",
    subject: "biology",
    ncertClass: "12",
    ncertChapter: "10-11",
    neetWeight: 4,
    avgQuestionsPerYear: 4.3,
    estimatedMinutes: 45,
    subtopics: [
      "Tools of rDNA Technology: Restriction enzymes, Vectors (Plasmids, Bacteriophages, BAC, YAC)",
      "Steps in rDNA Technology: Isolation, Ligation, Transformation, Selection",
      "PCR: Denaturation, Annealing, Extension",
      "Gel Electrophoresis, Southern and Northern Blotting",
      "Applications: Transgenic plants (Bt cotton, Golden Rice), Transgenic animals",
      "Gene Therapy: ADA deficiency case",
      "Biopatent, Biosafety, GMO ethics",
    ],
    highYieldTags: ["restriction enzyme", "PCR steps", "Bt cotton", "gene therapy ADA", "gel electrophoresis"],
  },
  {
    chapterCode: "BIO_ECOLOGY",
    title: "Ecology and Environment",
    subject: "biology",
    ncertClass: "12",
    ncertChapter: "12-16",
    neetWeight: 4,
    avgQuestionsPerYear: 5.2,
    estimatedMinutes: 50,
    subtopics: [
      "Organisms and Populations: Adaptations (xerophytes, hydrophytes), Population attributes",
      "Population Growth Models: Exponential (J-curve), Logistic (S-curve, Verhulst-Pearl)",
      "Interspecific Interactions: Mutualism, Predation, Competition, Parasitism, Amensalism, Commensalism",
      "Ecosystem: Components, Food chains, Food webs, Energy flow (10% law)",
      "Ecological Pyramids: Energy, Biomass, Number",
      "Biogeochemical Cycles: Carbon, Nitrogen",
      "Biodiversity: Types, Hotspots (India: Western Ghats, E. Himalayas)",
      "Conservation: In-situ (National parks, Biosphere reserves), Ex-situ (Zoos, Seed banks)",
      "Environmental Issues: Air, Water, Soil pollution, Ozone depletion, Global warming",
    ],
    highYieldTags: ["logistic growth", "10% energy law", "biodiversity hotspots", "ozone depletion", "nitrogen cycle"],
  },
];

// ─── Combined catalog ─────────────────────────────────────────────────────────
export const ALL_NEET_CHAPTERS: NeetChapter[] = [
  ...PHYSICS_CHAPTERS,
  ...CHEMISTRY_CHAPTERS,
  ...BIOLOGY_CHAPTERS,
];

export const CHAPTER_BY_CODE: Record<string, NeetChapter> = Object.fromEntries(
  ALL_NEET_CHAPTERS.map((c) => [c.chapterCode, c])
);

// NEET 2027 exam constants
export const NEET_EXAM_CONFIG = {
  totalQuestions: 180,
  totalMarks: 720,
  duration: 200, // minutes
  markPerCorrect: 4,
  negativeMarkPerWrong: -1,
  subjects: {
    physics: { questions: 45, marks: 180 },
    chemistry: { questions: 45, marks: 180 },
    biology: { questions: 90, marks: 360 },
  },
  targetDate: "2027-05-01", // approximate NEET 2027 date
} as const;

export type SubjectConfig = {
  id: NeetSubject;
  label: string;
  emoji: string;
  color: string;
  bgGradient: string;
  questions: number;
  marks: number;
  chapters: NeetChapter[];
};

export const SUBJECT_CONFIG: SubjectConfig[] = [
  {
    id: "physics",
    label: "Physics",
    emoji: "⚡",
    color: "#3B82F6",
    bgGradient: "linear-gradient(135deg, #1D4ED8, #3B82F6)",
    questions: 45,
    marks: 180,
    chapters: PHYSICS_CHAPTERS,
  },
  {
    id: "chemistry",
    label: "Chemistry",
    emoji: "🧪",
    color: "#10B981",
    bgGradient: "linear-gradient(135deg, #047857, #10B981)",
    questions: 45,
    marks: 180,
    chapters: CHEMISTRY_CHAPTERS,
  },
  {
    id: "biology",
    label: "Biology",
    emoji: "🌿",
    color: "#8B5CF6",
    bgGradient: "linear-gradient(135deg, #6D28D9, #8B5CF6)",
    questions: 90,
    marks: 360,
    chapters: BIOLOGY_CHAPTERS,
  },
];
