import type { YamunaLessonPayload } from "./yamunaLessonTypes";
import type { AppSession } from "./appSession";
import {
  buildIntroHook,
  buildConceptCard,
  buildCodeWalkthrough,
  buildConceptCheck,
  buildBugHunt,
  buildOutputPrediction,
  buildJavaChallenge,
  buildRecapSummary,
} from "./yamunaAssetLibrary";

// ─── LESSON 1: Classes & Objects ─────────────────────────────────────────────
export function get_JV_L2_01_CLASS_LESSON(theme: "junior" | "professional"): YamunaLessonPayload {
  const isJunior = theme === "junior";
  return {
    product: { id: "yamuna", name: "Yamuna Java AI Tutor" },
    course: { id: "java_core", levelId: "L2", levelSlug: "level-2", title: "Yamuna Java Core" },
    lesson: {
      id: "JV_L2_01_CLASS",
      order: 1,
      title: "Classes & Objects",
      sutra: "Blueprint Sutra",
      objective:
        "Understand the class-as-blueprint metaphor, declare fields and methods inside a class, create objects with the new keyword, and access object state through dot notation.",
      durationMin: 50,
      difficulty: 2,
      xpReward: 120,
    },
    progress: { currentStepIndex: 0, totalSteps: 7 },
    helpActions: [{ id: "help", label: "I need a hint" }],
    steps: [
      buildIntroHook({
        stepLabel: isJunior ? "Build Your Own Blueprints!" : "Classes: The Core of Java OOP",
        tutorText: isJunior
          ? "In the real world, a dog blueprint describes what every dog looks like and what it can do — name, breed, bark! Java classes work exactly the same way. A class is the blueprint; an object is the actual dog you create from it. Today you learn to write your own blueprints!"
          : "Object-Oriented Programming in Java is built on the class construct. A class encapsulates both state (fields) and behaviour (methods) into a single reusable unit. Objects are runtime instances of that class, each with its own copy of the fields.",
        headline: isJunior ? "Class = Blueprint, Object = Real Thing" : "Classes & Object Instantiation",
        emoji: "🐾",
        example: isJunior
          ? "class Dog { } → Dog fido = new Dog(); // fido is the real dog!"
          : "class Dog { String name; void bark() { } } → Dog d = new Dog();",
        goal: isJunior
          ? "Write a class with fields and a method, then create objects from it."
          : "Define a class with instance fields and methods, instantiate it with new, and invoke members via dot notation.",
      }),
      buildConceptCard({
        stepLabel: "Fields, Methods & the new Keyword",
        tutorText: isJunior
          ? "A class is made of two things: fields (the data it remembers) and methods (the actions it can perform). When you type 'new ClassName()' Java builds a fresh copy of that blueprint in memory — that copy is your object!"
          : "A class body declares instance fields (state), instance methods (behaviour), and constructors (initialisation). The new keyword allocates an object on the heap, runs its constructor, and returns a reference. Fields and methods are accessed through the dot (.) operator on the reference.",
        title: isJunior ? "The Parts of a Class" : "Class Members & Object Creation",
        emoji: "🏗️",
        points: isJunior
          ? [
              "Fields store data — e.g., String name; or int age;",
              "Methods define behaviour — e.g., void bark() { System.out.println(\"Woof!\"); }",
              "new ClassName() creates a fresh object from the class blueprint.",
              "Dot notation accesses fields and methods — e.g., fido.name or fido.bark();",
              "Each object has its own separate copy of every field.",
            ]
          : [
              "Instance fields declared at class scope hold per-object state (heap-allocated).",
              "Instance methods implicitly receive the object reference via this.",
              "new Type() allocates memory, zero-initialises fields, then runs the constructor.",
              "Dot notation: objectRef.fieldName and objectRef.methodName() navigate the object.",
              "Unassigned reference variables hold null — dereferencing null throws NullPointerException.",
            ],
        explanationTitle: "Stack vs Heap",
        explanationBody:
          "When you write Dog fido = new Dog(), the variable fido lives on the stack and holds a reference (memory address). The actual Dog object lives on the heap. Multiple references can point to the same heap object — modifying through one affects all of them.",
      }),
      buildCodeWalkthrough({
        stepLabel: "The Dog Class",
        tutorText:
          "Let us trace a complete class definition and two object instantiations. Notice that each object has its own name field — changing one does not affect the other. The bark() method reads the name from whichever object it is called on.",
        expression: "Defining and using a Dog class",
        codeSteps: [
          "class Dog {",
          "    String name;",
          "    String breed;",
          "",
          "    void bark() {",
          "        System.out.println(name + \" says: Woof!\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Dog fido = new Dog();",
          "        fido.name = \"Fido\";",
          "        fido.breed = \"Labrador\";",
          "",
          "        Dog rex = new Dog();",
          "        rex.name = \"Rex\";",
          "        rex.breed = \"Poodle\";",
          "",
          "        fido.bark();",
          "        rex.bark();",
          "        System.out.println(fido.breed);",
          "    }",
          "}",
        ],
        result: "Prints \"Fido says: Woof!\", \"Rex says: Woof!\", then \"Labrador\".",
      }),
      buildConceptCheck({
        stepLabel: "Object Creation Quiz",
        tutorText:
          "Before you write your own class, confirm your understanding of the new keyword. Read the question carefully — only one answer describes the correct Java syntax for creating a new object.",
        headline: "Which line correctly creates a new Dog object?",
        question: "Which statement correctly creates a new Dog object and assigns it to a variable?",
        options: [
          "Dog fido = Dog();",
          "Dog fido = new Dog();",
          "new Dog fido = Dog();",
          "fido = Dog.new();",
        ],
        correctIndex: 1,
        explanation:
          "The correct syntax is: TypeName variableName = new TypeName(); The new keyword is required to allocate the object. new Dog() calls the default constructor and returns a reference which is assigned to fido.",
      }),
      buildBugHunt({
        stepLabel: "Missing new Bug",
        tutorText: isJunior
          ? "A student forgot the new keyword and tried to access a field on an uninitialised variable! Java will throw a NullPointerException at runtime. Find the bug and fix it so the program prints correctly."
          : "The code below declares a Cat reference but never allocates an object. Accessing the name field will throw NullPointerException. Identify and correct the missing instantiation.",
        headline: "Fix the NullPointerException Bug",
        buggyCode: [
          "class Cat {",
          "    String name;",
          "    void meow() {",
          "        System.out.println(name + \" says: Meow!\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Cat whiskers;",
          "        whiskers.name = \"Whiskers\";",
          "        whiskers.meow();",
          "    }",
          "}",
        ].join("\n"),
        fixedCode: [
          "class Cat {",
          "    String name;",
          "    void meow() {",
          "        System.out.println(name + \" says: Meow!\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Cat whiskers = new Cat();",
          "        whiskers.name = \"Whiskers\";",
          "        whiskers.meow();",
          "    }",
          "}",
        ].join("\n"),
        explanation:
          "Cat whiskers; only declares a reference variable — it does not create an object. The variable holds null. Accessing whiskers.name on null causes a NullPointerException. The fix is Cat whiskers = new Cat(); which allocates the object before use.",
        hints: [
          "Does the Cat variable ever have new called on it?",
          "A declared-but-unassigned reference holds null.",
          "Change Cat whiskers; to Cat whiskers = new Cat();",
        ],
      }),
      buildJavaChallenge({
        stepLabel: isJunior ? "Build a Car Class!" : "Car Class Exercise",
        tutorText: isJunior
          ? "Time to write your own class! Create a Car class with three fields — make, model, and year — and a method called describe() that prints all three values. Then in main, create two different Car objects with different values and call describe() on each."
          : "Define a Car class with three instance fields (String make, String model, int year) and an instance method describe() that prints the car details. In main, instantiate two Car objects with distinct values and invoke describe() on each.",
        boardTitle: isJunior ? "Car Blueprint Builder" : "Car Class Definition",
        prompt:
          "Define a Car class with make, model, year fields and a describe() method. Create two objects in main and call describe() on each.",
        starterCode: [
          "class Car {",
          "    // Declare fields: make (String), model (String), year (int)",
          "",
          "    // Write the describe() method",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        // Create two Car objects and call describe() on each",
          "    }",
          "}",
        ].join("\n"),
        solutionCode: [
          "class Car {",
          "    String make;",
          "    String model;",
          "    int year;",
          "",
          "    void describe() {",
          "        System.out.println(year + \" \" + make + \" \" + model);",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Car c1 = new Car();",
          "        c1.make = \"Toyota\";",
          "        c1.model = \"Corolla\";",
          "        c1.year = 2022;",
          "        c1.describe();",
          "",
          "        Car c2 = new Car();",
          "        c2.make = \"Honda\";",
          "        c2.model = \"Civic\";",
          "        c2.year = 2021;",
          "        c2.describe();",
          "    }",
          "}",
        ].join("\n"),
        hints: [
          "Declare fields inside the class body but outside any method: String make;",
          "The describe() method should call System.out.println with the three fields combined.",
          "Create objects with: Car c1 = new Car();",
          "Assign fields with dot notation: c1.make = \"Toyota\";",
          "Call the method with: c1.describe();",
        ],
        openEnded: false,
      }),
      buildRecapSummary({
        stepLabel: "Classes Mastered",
        tutorText: isJunior
          ? "Incredible! You have just written your own Java class from scratch. You know the difference between a blueprint and the real thing — and that is the core idea behind all of Object-Oriented Programming!"
          : "Solid work. You have practised the complete object lifecycle: class definition with fields and methods, heap allocation via new, and member access through dot notation. This foundation underpins every OOP concept in the rest of Level 2.",
        title: isJunior ? "Classes & Objects — Mastered! 🏆" : "OOP Foundations Established 🏆",
        keyPoints: [
          "A class is a blueprint that combines fields (state) and methods (behaviour) into one reusable unit.",
          "new ClassName() allocates an object on the heap and returns a reference to it.",
          "Dot notation (objectRef.member) accesses fields and calls methods on a specific object instance.",
        ],
        badgeReward: "Blueprint Architect 🏗️",
        nextLesson: "JV_L2_02_CONSTRUCT",
      }),
    ],
  };
}

// ─── LESSON 2: Constructors & Method Overloading ──────────────────────────────
export function get_JV_L2_02_CONSTRUCT_LESSON(theme: "junior" | "professional"): YamunaLessonPayload {
  const isJunior = theme === "junior";
  return {
    product: { id: "yamuna", name: "Yamuna Java AI Tutor" },
    course: { id: "java_core", levelId: "L2", levelSlug: "level-2", title: "Yamuna Java Core" },
    lesson: {
      id: "JV_L2_02_CONSTRUCT",
      order: 2,
      title: "Constructors & Method Overloading",
      sutra: "Constructor Sutra",
      objective:
        "Write default and parameterised constructors, chain them with this(), and define multiple overloaded methods that differ by parameter signature.",
      durationMin: 50,
      difficulty: 2,
      xpReward: 120,
    },
    progress: { currentStepIndex: 0, totalSteps: 7 },
    helpActions: [{ id: "help", label: "I need a hint" }],
    steps: [
      buildIntroHook({
        stepLabel: isJunior ? "Automatic Setup with Constructors!" : "Constructors & Overloading",
        tutorText: isJunior
          ? "Right now, after creating an object you have to set every field manually — that is tedious! Constructors solve this: they are special methods that run automatically the moment you write new ClassName(...) and can set up all the fields for you in one shot."
          : "The constructor is the designated initialisation method invoked by new. Java supports constructor overloading — multiple constructors differentiated by their parameter list. Method overloading applies equally to regular methods: the compiler selects the best-matching signature at compile time.",
        headline: isJunior ? "Constructor = Automatic Setup" : "Constructors & Compile-Time Overload Resolution",
        emoji: "🔧",
        example: isJunior
          ? "new Person(\"Riya\", 17) → constructor runs, name and age set instantly!"
          : "Person(String name, int age) vs Person() — compiler picks by argument count/type",
        goal: isJunior
          ? "Write constructors so objects are fully initialised the moment they are created."
          : "Implement default and parameterised constructors and demonstrate overload resolution.",
      }),
      buildConceptCard({
        stepLabel: "Default, Parameterised & this() Chaining",
        tutorText: isJunior
          ? "Java lets you have more than one constructor — just like a restaurant menu! Each constructor has different parameters. The special this(...) call lets one constructor reuse another one's logic so you never repeat yourself."
          : "Java performs overload resolution by matching the argument list at the call site to the parameter list signatures. this() as the first statement in a constructor delegates to another constructor in the same class, enabling DRY initialisation. If you define no constructor, the compiler inserts a no-arg default; once you add any constructor, the default is suppressed.",
        title: isJunior ? "Three Constructor Patterns" : "Constructor Overloading & Delegation",
        emoji: "⚙️",
        points: isJunior
          ? [
              "Default constructor: no parameters — Person() { name = \"Unknown\"; }",
              "Parameterised constructor: accepts arguments — Person(String n, int a) { name = n; age = a; }",
              "this(args) inside a constructor calls another constructor in the same class.",
              "The constructor name must exactly match the class name.",
              "Constructors have no return type — not even void.",
            ]
          : [
              "Constructor syntax: ClassName(params) { } — no return type, name matches class.",
              "Overloading resolution: compiler matches argument types and count to the correct signature.",
              "this(args) — constructor delegation; must be the very first statement in the constructor body.",
              "Java only supplies a default no-arg constructor when the class declares no constructors at all.",
              "Method overloading (same name, different parameter lists) applies to regular methods identically.",
            ],
        explanationTitle: "Why No Return Type on a Constructor?",
        explanationBody:
          "Constructors are invoked implicitly by the new expression, which always returns the newly created object. Adding a return type would make the signature look like a regular method, causing ambiguity. The absence of a return type is the compiler's signal that this is a constructor.",
      }),
      buildCodeWalkthrough({
        stepLabel: "Person Class with Three Constructors",
        tutorText:
          "Let us trace a Person class that has three overloaded constructors and one overloaded greet() method. Notice how the single-argument constructor delegates to the full constructor via this() — the full constructor is the only one that actually assigns the fields.",
        expression: "Constructor overloading and this() chaining",
        codeSteps: [
          "class Person {",
          "    String name;",
          "    int age;",
          "",
          "    // Default constructor delegates to full constructor",
          "    Person() { this(\"Unknown\", 0); }",
          "",
          "    // Single-arg constructor delegates",
          "    Person(String name) { this(name, 0); }",
          "",
          "    // Full parameterised constructor",
          "    Person(String name, int age) {",
          "        this.name = name;",
          "        this.age = age;",
          "    }",
          "",
          "    void greet() {",
          "        System.out.println(\"Hi, I am \" + name);",
          "    }",
          "",
          "    void greet(String greeting) {",
          "        System.out.println(greeting + \", I am \" + name);",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Person p1 = new Person();",
          "        Person p2 = new Person(\"Arjun\", 18);",
          "        p1.greet();",
          "        p2.greet(\"Namaste\");",
          "    }",
          "}",
        ],
        result: "Prints \"Hi, I am Unknown\" then \"Namaste, I am Arjun\".",
      }),
      buildConceptCheck({
        stepLabel: "Default Constructor Quiz",
        tutorText:
          "Understanding when Java provides a default constructor is a common exam question. Read the scenario carefully and pick the correct answer.",
        headline: "When does Java provide a free default constructor?",
        question:
          "Class MyClass has one constructor: MyClass(int x) { }. Which call compiles successfully?",
        options: [
          "MyClass obj = new MyClass();",
          "MyClass obj = new MyClass(42);",
          "Both compile fine.",
          "Neither compiles.",
        ],
        correctIndex: 1,
        explanation:
          "Once you declare any constructor (even a single parameterised one), Java no longer provides the free no-arg default. new MyClass() would fail to compile because no matching no-arg constructor exists. new MyClass(42) matches MyClass(int x) and compiles successfully.",
      }),
      buildBugHunt({
        stepLabel: "Constructor Name Mismatch Bug",
        tutorText: isJunior
          ? "A student wrote a constructor but gave it the wrong name — it has a void return type, making Java treat it as a regular method, not a constructor! Find the bug and fix it so the object initialises correctly."
          : "The constructor below has a void return type, which makes Java treat it as a regular method named Book rather than a constructor. Java will reject new Book(...) at compile time. Remove the void to fix it.",
        headline: "Fix the Constructor Name Bug",
        buggyCode: [
          "class Book {",
          "    String title;",
          "    int pages;",
          "",
          "    // Intended to be a constructor",
          "    void Book(String title, int pages) {",
          "        this.title = title;",
          "        this.pages = pages;",
          "    }",
          "",
          "    void describe() {",
          "        System.out.println(title + \" (\" + pages + \" pages)\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Book b = new Book(\"Clean Code\", 431);",
          "        b.describe();",
          "    }",
          "}",
        ].join("\n"),
        fixedCode: [
          "class Book {",
          "    String title;",
          "    int pages;",
          "",
          "    Book(String title, int pages) {",
          "        this.title = title;",
          "        this.pages = pages;",
          "    }",
          "",
          "    void describe() {",
          "        System.out.println(title + \" (\" + pages + \" pages)\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Book b = new Book(\"Clean Code\", 431);",
          "        b.describe();",
          "    }",
          "}",
        ].join("\n"),
        explanation:
          "void Book(...) declares a regular method named Book that returns void — it is NOT a constructor. A constructor must have no return type at all (not even void) and its name must exactly match the class name. Removing void makes it a proper constructor.",
        hints: [
          "Constructors never have a return type — not even void.",
          "The constructor name must match the class name exactly.",
          "Remove the word void from before Book(String title, int pages).",
        ],
      }),
      buildJavaChallenge({
        stepLabel: isJunior ? "Person with 3 Constructors!" : "Constructor Overloading Exercise",
        tutorText: isJunior
          ? "Build a Person class with three constructors: one with no arguments, one with just a name, and one with both a name and age. Use this() chaining so the full constructor is the only one that assigns fields. Create one object using each constructor!"
          : "Implement a Person class with three overloaded constructors: no-arg, name-only, and name+age. Use this() delegation so field assignment happens only in the full constructor. Instantiate one object per constructor and print each person's name and age.",
        boardTitle: isJunior ? "Person Constructor Builder" : "Constructor Overloading Exercise",
        prompt:
          "Create Person class with 3 constructors (no-arg, name-only, name+age) using this() chaining. Instantiate all three variants and print name and age for each.",
        starterCode: [
          "class Person {",
          "    String name;",
          "    int age;",
          "",
          "    // No-arg constructor — use this() to delegate",
          "",
          "    // Name-only constructor — use this() to delegate",
          "",
          "    // Full constructor — assign fields here",
          "",
          "    void print() {",
          "        System.out.println(name + \", age \" + age);",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        // Create one object per constructor variant",
          "    }",
          "}",
        ].join("\n"),
        solutionCode: [
          "class Person {",
          "    String name;",
          "    int age;",
          "",
          "    Person() { this(\"Unknown\", 0); }",
          "    Person(String name) { this(name, 0); }",
          "    Person(String name, int age) {",
          "        this.name = name;",
          "        this.age = age;",
          "    }",
          "",
          "    void print() {",
          "        System.out.println(name + \", age \" + age);",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Person p1 = new Person();",
          "        Person p2 = new Person(\"Priya\");",
          "        Person p3 = new Person(\"Rohan\", 20);",
          "        p1.print();",
          "        p2.print();",
          "        p3.print();",
          "    }",
          "}",
        ].join("\n"),
        hints: [
          "Person() { this(\"Unknown\", 0); } — the no-arg delegates to the full constructor.",
          "Person(String name) { this(name, 0); } — name-only delegates with default age 0.",
          "The full constructor uses this.name = name; to distinguish the field from the parameter.",
          "this() must be the very first statement in the constructor body.",
          "Constructors have no return type — not even void.",
        ],
        openEnded: false,
      }),
      buildRecapSummary({
        stepLabel: "Constructors Mastered",
        tutorText: isJunior
          ? "You are now a constructor expert! Your objects can set themselves up the instant they are created. And with overloading, callers get to choose exactly how much detail they want to provide — how flexible is that!"
          : "Constructors and overloading are central to idiomatic Java API design. The this() delegation pattern keeps initialisation logic in one place and prevents field-assignment duplication as classes grow.",
        title: isJunior ? "Constructors — Mastered! 🏆" : "Constructors & Overloading Mastered 🏆",
        keyPoints: [
          "A constructor has no return type, its name matches the class, and it runs automatically when new is called.",
          "Java only provides a free no-arg default constructor if the class declares no constructors at all.",
          "this(args) as the first statement in a constructor delegates to another constructor, enabling DRY initialisation across overloads.",
        ],
        badgeReward: "Constructor Craftsman ⚙️",
        nextLesson: "JV_L2_03_ENCAP",
      }),
    ],
  };
}

// ─── LESSON 3: Encapsulation ──────────────────────────────────────────────────
export function get_JV_L2_03_ENCAP_LESSON(theme: "junior" | "professional"): YamunaLessonPayload {
  const isJunior = theme === "junior";
  return {
    product: { id: "yamuna", name: "Yamuna Java AI Tutor" },
    course: { id: "java_core", levelId: "L2", levelSlug: "level-2", title: "Yamuna Java Core" },
    lesson: {
      id: "JV_L2_03_ENCAP",
      order: 3,
      title: "Encapsulation",
      sutra: "Encapsulation Sutra",
      objective:
        "Declare private fields, write public getter and setter methods with validation logic, and explain why direct field access is an anti-pattern in OOP.",
      durationMin: 50,
      difficulty: 2,
      xpReward: 120,
    },
    progress: { currentStepIndex: 0, totalSteps: 7 },
    helpActions: [{ id: "help", label: "I need a hint" }],
    steps: [
      buildIntroHook({
        stepLabel: isJunior ? "Protecting Your Data!" : "Encapsulation: Information Hiding",
        tutorText: isJunior
          ? "Imagine a bank account where anyone could just reach in and set the balance to any number — even a negative one! Encapsulation stops that. By marking fields private, only the class itself can change them, and you can add rules (like 'balance must never go below zero') inside special setter methods."
          : "Encapsulation — one of the four OOP pillars — restricts direct field access by making fields private. Public accessor methods (getters/setters) become the single controlled pathway to read or mutate state. This is the Java Bean convention and underpins frameworks from Spring to Hibernate.",
        headline: isJunior ? "private = Protected Data" : "private Fields + public Accessors",
        emoji: "🔒",
        example: isJunior
          ? "private double balance; → nobody can set it to -999 from outside!"
          : "private int age; + public void setAge(int a) { if (a >= 0) age = a; }",
        goal: isJunior
          ? "Mark fields private and write getters/setters with validation rules."
          : "Implement a fully encapsulated class with validated mutators and explain the design rationale.",
      }),
      buildConceptCard({
        stepLabel: "private, Getters & Setters",
        tutorText: isJunior
          ? "The keyword private means 'only this class can touch me'. To allow reading or writing from outside, you write special get/set methods that act as secure doors. The setter can check for invalid values before allowing a change!"
          : "The Java Bean convention: declare all fields private, provide a public getX() that returns the field, and a public setX(T value) that validates then assigns. Validation in setters is the primary benefit — it enforces business rules at the boundary. Getters for immutable state can omit setters entirely.",
        title: isJunior ? "private + Getters + Setters" : "Access Modifiers & Bean Convention",
        emoji: "🚪",
        points: isJunior
          ? [
              "private fieldName; — the field can only be accessed from inside the same class.",
              "public Type getFieldName() { return fieldName; } — getter lets others read the value.",
              "public void setFieldName(Type value) { ... } — setter lets others change the value (with rules).",
              "Inside the setter you can validate: if (value < 0) return; stops bad data.",
              "This pattern is called the Java Bean convention and is used everywhere.",
            ]
          : [
              "private — restricts access to the declaring class; compile error if accessed elsewhere.",
              "Getter: public Type getX() { return x; } — read-only exposure of private state.",
              "Setter: public void setX(Type v) { if (valid(v)) x = v; } — gated write with invariant enforcement.",
              "Encapsulation decouples the internal representation from the public API — you can change the storage type without breaking callers.",
              "public (accessible everywhere), private (class only), protected (package + subclasses), default (package only).",
            ],
        explanationTitle: "Why Not Just Make Fields public?",
        explanationBody:
          "Public fields expose the internal representation directly. Any caller can set balance = -1_000_000. When you later want to add validation or change the field type, every caller breaks. Private fields with controlled accessors let you change the internals without touching external code — this is the Open/Closed principle in action.",
      }),
      buildCodeWalkthrough({
        stepLabel: "BankAccount: Encapsulated",
        tutorText:
          "Let us trace a BankAccount class where balance is private. The deposit and withdraw methods enforce business rules — you cannot deposit a negative amount and you cannot withdraw more than the current balance. External code can only interact through these safe methods.",
        expression: "Encapsulated BankAccount with validation",
        codeSteps: [
          "class BankAccount {",
          "    private double balance;",
          "",
          "    BankAccount(double initialBalance) {",
          "        if (initialBalance >= 0) balance = initialBalance;",
          "    }",
          "",
          "    public double getBalance() { return balance; }",
          "",
          "    public void deposit(double amount) {",
          "        if (amount > 0) balance += amount;",
          "    }",
          "",
          "    public void withdraw(double amount) {",
          "        if (amount > 0 && amount <= balance) balance -= amount;",
          "        else System.out.println(\"Insufficient funds or invalid amount.\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        BankAccount acc = new BankAccount(1000);",
          "        acc.deposit(500);",
          "        acc.withdraw(200);",
          "        System.out.println(acc.getBalance());",
          "        acc.withdraw(2000);",
          "    }",
          "}",
        ],
        result: "Prints 1300.0, then \"Insufficient funds or invalid amount.\"",
      }),
      buildConceptCheck({
        stepLabel: "Encapsulation Quiz",
        tutorText:
          "Pick the statement that best explains why encapsulation is good software design. Think about what happens when the internal representation of a class needs to change.",
        headline: "Why should fields be private?",
        question:
          "A class has a private int age field and a public setAge(int a) method that validates a >= 0. Why is this better than declaring age as public?",
        options: [
          "private fields run faster than public fields.",
          "It prevents the class from being inherited.",
          "Validation in setAge ensures age can never be set to an invalid value from outside.",
          "private fields use less memory.",
        ],
        correctIndex: 2,
        explanation:
          "The primary benefit is controlled mutation. A public field lets any caller write obj.age = -5 with no validation. A private field with a setter forces all writes through setAge(), where you can enforce age >= 0. This is the encapsulation guarantee.",
      }),
      buildBugHunt({
        stepLabel: "Direct Field Access Bug",
        tutorText: isJunior
          ? "A student bypassed the setter and tried to set the private temperature field directly from outside the class. Java will refuse to compile this — private means private! Fix the code so it always goes through the setter."
          : "The code below accesses the private field directly from outside the class — this is a compile error. Rewrite the problematic line to use the correct public setter API.",
        headline: "Fix the Encapsulation Violation",
        buggyCode: [
          "class Thermometer {",
          "    private double temperature;",
          "",
          "    public double getTemperature() { return temperature; }",
          "",
          "    public void setTemperature(double t) {",
          "        if (t >= -273.15) temperature = t;",
          "        else System.out.println(\"Temperature below absolute zero!\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Thermometer th = new Thermometer();",
          "        th.temperature = -999;  // bypasses validation!",
          "        System.out.println(th.getTemperature());",
          "    }",
          "}",
        ].join("\n"),
        fixedCode: [
          "class Thermometer {",
          "    private double temperature;",
          "",
          "    public double getTemperature() { return temperature; }",
          "",
          "    public void setTemperature(double t) {",
          "        if (t >= -273.15) temperature = t;",
          "        else System.out.println(\"Temperature below absolute zero!\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Thermometer th = new Thermometer();",
          "        th.setTemperature(-999);  // goes through validated setter",
          "        System.out.println(th.getTemperature());",
          "    }",
          "}",
        ].join("\n"),
        explanation:
          "th.temperature = -999 directly accesses the private field from outside Thermometer — this is a compile error. The correct approach is th.setTemperature(-999) which routes through the setter, triggers the validation check, prints the warning, and leaves temperature unchanged at its default 0.0.",
        hints: [
          "Can you access a private field from a different class?",
          "Replace th.temperature = -999 with the public method that sets the temperature.",
          "The validated setter is named setTemperature — use it.",
        ],
      }),
      buildJavaChallenge({
        stepLabel: isJunior ? "Temperature Class Challenge!" : "Temperature Encapsulation Exercise",
        tutorText: isJunior
          ? "Build a Temperature class with a private Celsius field. Write a setter that rejects temperatures below -273.15 (absolute zero), a getCelsius() getter, and a getFahrenheit() method that converts and returns the equivalent Fahrenheit value. Test it in main!"
          : "Implement a Temperature class: private double celsius field; setTemperature(double t) that rejects t < -273.15; getCelsius() getter; getFahrenheit() that returns celsius * 9.0/5 + 32. Demonstrate valid and invalid set calls in main.",
        boardTitle: isJunior ? "Temperature Class Builder" : "Temperature Encapsulation",
        prompt:
          "Create Temperature class with private celsius, validated setter, getCelsius() getter, and getFahrenheit() conversion. Test with valid and invalid values.",
        starterCode: [
          "class Temperature {",
          "    // Declare private celsius field",
          "",
          "    // setTemperature(double t): reject if below -273.15",
          "",
          "    // getCelsius(): return celsius",
          "",
          "    // getFahrenheit(): return celsius * 9.0/5 + 32",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Temperature t = new Temperature();",
          "        // Test valid and invalid values",
          "    }",
          "}",
        ].join("\n"),
        solutionCode: [
          "class Temperature {",
          "    private double celsius;",
          "",
          "    public void setTemperature(double t) {",
          "        if (t >= -273.15) celsius = t;",
          "        else System.out.println(\"Below absolute zero!\");",
          "    }",
          "",
          "    public double getCelsius() { return celsius; }",
          "",
          "    public double getFahrenheit() { return celsius * 9.0 / 5 + 32; }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Temperature t = new Temperature();",
          "        t.setTemperature(100);",
          "        System.out.println(t.getCelsius());",
          "        System.out.println(t.getFahrenheit());",
          "        t.setTemperature(-300);",
          "    }",
          "}",
        ].join("\n"),
        hints: [
          "private double celsius; — declare the field private.",
          "In setTemperature: if (t >= -273.15) celsius = t; else print an error.",
          "getCelsius() just returns celsius.",
          "getFahrenheit() formula: celsius * 9.0 / 5 + 32 — use 9.0 to avoid int division.",
          "Test with 100 (valid) and -300 (invalid) to see both paths.",
        ],
        openEnded: false,
      }),
      buildRecapSummary({
        stepLabel: "Encapsulation Mastered",
        tutorText: isJunior
          ? "You have locked down your class data like a pro! Private fields with validated setters is one of the most important habits in Java — it means your objects can never get into an impossible state."
          : "Encapsulation is the disciplined separation of an object's interface from its implementation. Private fields combined with validated accessors are the mechanism that makes Java objects both safe and maintainable at scale.",
        title: isJunior ? "Encapsulation — Mastered! 🏆" : "Encapsulation Mastered 🏆",
        keyPoints: [
          "private fields are inaccessible from outside the class — all reads and writes go through public accessor methods.",
          "Setters enforce invariants by validating input before modifying the field — this prevents objects from entering invalid states.",
          "Encapsulation decouples the internal representation from the public API, letting you change internals without breaking callers.",
        ],
        badgeReward: "Encapsulation Guardian 🔒",
        nextLesson: "JV_L2_04_INHERIT",
      }),
    ],
  };
}

// ─── LESSON 4: Inheritance ────────────────────────────────────────────────────
export function get_JV_L2_04_INHERIT_LESSON(theme: "junior" | "professional"): YamunaLessonPayload {
  const isJunior = theme === "junior";
  return {
    product: { id: "yamuna", name: "Yamuna Java AI Tutor" },
    course: { id: "java_core", levelId: "L2", levelSlug: "level-2", title: "Yamuna Java Core" },
    lesson: {
      id: "JV_L2_04_INHERIT",
      order: 4,
      title: "Inheritance",
      sutra: "Inheritance Sutra",
      objective:
        "Use the extends keyword to create subclasses, call parent constructors with super(), override inherited methods with @Override, and design a simple class hierarchy.",
      durationMin: 55,
      difficulty: 2,
      xpReward: 130,
    },
    progress: { currentStepIndex: 0, totalSteps: 7 },
    helpActions: [{ id: "help", label: "I need a hint" }],
    steps: [
      buildIntroHook({
        stepLabel: isJunior ? "Inherit Superpowers!" : "Inheritance & the is-a Relationship",
        tutorText: isJunior
          ? "Every dog is an animal — so a Dog class should automatically have everything an Animal class has! Inheritance lets a child class receive all the fields and methods of a parent class for free, and then add its own special features on top. It is code reuse at its most powerful!"
          : "Inheritance models the is-a relationship in Java using the extends keyword. A subclass inherits all non-private members of its superclass, can override methods to specialise behaviour, and must call super() to initialise the inherited state. Java supports single-class inheritance only.",
        headline: isJunior ? "extends = Inherit Everything!" : "extends, super() & @Override",
        emoji: "🧬",
        example: isJunior
          ? "class Dog extends Animal { } → Dog automatically has Animal's fields and methods!"
          : "class Dog extends Animal { @Override void sound() { System.out.println(\"Woof\"); } }",
        goal: isJunior
          ? "Create a parent class, extend it into a child class, and override a method."
          : "Implement a two-level hierarchy with super() constructor chaining and verified method overrides.",
      }),
      buildConceptCard({
        stepLabel: "extends, super() & @Override",
        tutorText: isJunior
          ? "Three keywords rule inheritance. 'extends' creates the parent-child link. 'super()' in the child constructor calls the parent constructor first. '@Override' is a label you put on a method when you want to replace the parent's version with your own."
          : "extends establishes the inheritance link at compile time. super() must be the first statement in the subclass constructor if the superclass lacks a no-arg constructor — omitting it causes a compile error. @Override is a compile-time annotation that instructs the compiler to verify the method actually overrides a superclass method, preventing typo bugs.",
        title: isJunior ? "Three Keywords of Inheritance" : "extends / super() / @Override",
        emoji: "🔗",
        points: isJunior
          ? [
              "class Child extends Parent { } — Child inherits all public/protected members of Parent.",
              "super(args) in the constructor — must be first; calls the parent class constructor.",
              "@Override above a method — tells Java 'I am replacing my parent's version of this method'.",
              "Child classes can add new fields and methods on top of what they inherit.",
              "Java only allows extending one class (single inheritance).",
            ]
          : [
              "class Sub extends Super — Sub inherits public and protected fields and methods (not private).",
              "super(args) as the first statement in Sub's constructor initialises the inherited Super state.",
              "@Override annotation causes a compile error if the signature does not match any superclass method.",
              "Method overriding: same name, same parameter list, same or covariant return type, not narrower visibility.",
              "final class cannot be extended; final method cannot be overridden.",
            ],
        explanationTitle: "Overriding vs Overloading",
        explanationBody:
          "Overriding replaces a superclass method with the same signature in the subclass — resolved at runtime (dynamic dispatch). Overloading provides multiple methods with the same name but different parameter lists in the same class — resolved at compile time. @Override only applies to overriding, not overloading.",
      }),
      buildCodeWalkthrough({
        stepLabel: "Animal → Dog Hierarchy",
        tutorText:
          "Let us trace an Animal superclass with a makeSound() method, then a Dog subclass that overrides it. Notice how super(name) in Dog's constructor initialises the inherited name field. When makeSound() is called on a Dog reference, Java runs Dog's version, not Animal's.",
        expression: "Two-level inheritance with method override",
        codeSteps: [
          "class Animal {",
          "    String name;",
          "",
          "    Animal(String name) { this.name = name; }",
          "",
          "    void makeSound() {",
          "        System.out.println(name + \" makes a sound.\");",
          "    }",
          "}",
          "",
          "class Dog extends Animal {",
          "    String breed;",
          "",
          "    Dog(String name, String breed) {",
          "        super(name);       // call Animal's constructor",
          "        this.breed = breed;",
          "    }",
          "",
          "    @Override",
          "    void makeSound() {",
          "        System.out.println(name + \" barks!\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Animal a = new Animal(\"Generic Animal\");",
          "        Dog d = new Dog(\"Rex\", \"Labrador\");",
          "        a.makeSound();",
          "        d.makeSound();",
          "    }",
          "}",
        ],
        result: "Prints \"Generic Animal makes a sound.\" then \"Rex barks!\"",
      }),
      buildConceptCheck({
        stepLabel: "super() Quiz",
        tutorText:
          "The super() call rule is one of the most common sources of compile errors in early OOP code. Pick the correct statement about super().",
        headline: "What does super() do in a subclass constructor?",
        question: "When must you explicitly call super(args) in a subclass constructor?",
        options: [
          "Always — Java never inserts it automatically.",
          "When the superclass has no constructor at all.",
          "When the superclass has no no-arg constructor — you must call the matching parameterised one.",
          "Never — super() is only used inside methods.",
        ],
        correctIndex: 2,
        explanation:
          "If the superclass defines only parameterised constructors (no no-arg constructor), the compiler cannot insert a default super() call. You must explicitly call super(correctArgs) as the first statement in the subclass constructor. If the superclass has a no-arg constructor, Java inserts super() automatically when you omit it.",
      }),
      buildBugHunt({
        stepLabel: "Missing super() & Wrong Override Bug",
        tutorText: isJunior
          ? "A student wrote a Cat class extending Animal but forgot to call super() in the constructor — so name never gets set! They also added an extra parameter to the override method, breaking the override. Find both bugs and fix them."
          : "The Cat subclass has two bugs: the constructor does not call super() to initialise the inherited name field, and the override method has an extra parameter making it an overload instead. Identify and fix both issues.",
        headline: "Fix Missing super() and Override Signature",
        buggyCode: [
          "class Animal {",
          "    String name;",
          "    Animal(String name) { this.name = name; }",
          "    void makeSound() { System.out.println(name + \" makes a sound.\"); }",
          "}",
          "",
          "class Cat extends Animal {",
          "    Cat(String name) {",
          "        // forgot super(name)",
          "        System.out.println(\"Creating Cat\");",
          "    }",
          "",
          "    @Override",
          "    void makeSound(String extra) {  // wrong signature!",
          "        System.out.println(name + \" meows!\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Cat c = new Cat(\"Whiskers\");",
          "        c.makeSound();",
          "    }",
          "}",
        ].join("\n"),
        fixedCode: [
          "class Animal {",
          "    String name;",
          "    Animal(String name) { this.name = name; }",
          "    void makeSound() { System.out.println(name + \" makes a sound.\"); }",
          "}",
          "",
          "class Cat extends Animal {",
          "    Cat(String name) {",
          "        super(name);",
          "    }",
          "",
          "    @Override",
          "    void makeSound() {",
          "        System.out.println(name + \" meows!\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Cat c = new Cat(\"Whiskers\");",
          "        c.makeSound();",
          "    }",
          "}",
        ].join("\n"),
        explanation:
          "Bug 1: Without super(name), the Animal constructor never runs and name stays null. super(name) must be the first statement in Cat's constructor. Bug 2: @Override void makeSound(String extra) does not match Animal's void makeSound() — it is an overload, not an override. Remove the extra parameter to make it a true override.",
        hints: [
          "Animal has a parameterised constructor — Cat must call super(name) first.",
          "The overriding method must have exactly the same parameter list as the parent method.",
          "Remove String extra from Cat's makeSound parameter list.",
        ],
      }),
      buildJavaChallenge({
        stepLabel: isJunior ? "Vehicle → Car & Truck!" : "Vehicle Hierarchy Exercise",
        tutorText: isJunior
          ? "Build a Vehicle superclass with a brand field and a describe() method. Then create Car (adds doors field) and Truck (adds payload field) subclasses that each override describe() to include their unique detail. Use super() in both constructors!"
          : "Implement: Vehicle(String brand) with describe(); Car extends Vehicle with int doors, overriding describe() to include doors; Truck extends Vehicle with double payload, overriding describe() to include payload. Use super() in each subclass constructor. Instantiate one Car and one Truck and call describe() on each.",
        boardTitle: isJunior ? "Vehicle Hierarchy Builder" : "Vehicle Inheritance Exercise",
        prompt:
          "Create Vehicle with brand and describe(). Extend Car (adds doors) and Truck (adds payload), both overriding describe(). Use super() in subclass constructors.",
        starterCode: [
          "class Vehicle {",
          "    String brand;",
          "    Vehicle(String brand) { this.brand = brand; }",
          "    void describe() { System.out.println(\"Vehicle: \" + brand); }",
          "}",
          "",
          "// Define Car extending Vehicle",
          "// Car has: int doors, constructor using super(), @Override describe()",
          "",
          "// Define Truck extending Vehicle",
          "// Truck has: double payload, constructor using super(), @Override describe()",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        // Create one Car and one Truck, call describe() on each",
          "    }",
          "}",
        ].join("\n"),
        solutionCode: [
          "class Vehicle {",
          "    String brand;",
          "    Vehicle(String brand) { this.brand = brand; }",
          "    void describe() { System.out.println(\"Vehicle: \" + brand); }",
          "}",
          "",
          "class Car extends Vehicle {",
          "    int doors;",
          "    Car(String brand, int doors) {",
          "        super(brand);",
          "        this.doors = doors;",
          "    }",
          "    @Override",
          "    void describe() { System.out.println(\"Car: \" + brand + \", \" + doors + \" doors\"); }",
          "}",
          "",
          "class Truck extends Vehicle {",
          "    double payload;",
          "    Truck(String brand, double payload) {",
          "        super(brand);",
          "        this.payload = payload;",
          "    }",
          "    @Override",
          "    void describe() { System.out.println(\"Truck: \" + brand + \", payload \" + payload + \" tons\"); }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Car c = new Car(\"Toyota\", 4);",
          "        Truck t = new Truck(\"Tata\", 10.5);",
          "        c.describe();",
          "        t.describe();",
          "    }",
          "}",
        ].join("\n"),
        hints: [
          "class Car extends Vehicle — the extends keyword links the classes.",
          "Car's constructor: super(brand); then this.doors = doors;",
          "Add @Override on the line before void describe() in each subclass.",
          "The overriding describe() should print brand (inherited) plus the subclass-specific field.",
          "Truck follows the same pattern — super(brand) first, then this.payload = payload;",
        ],
        openEnded: false,
      }),
      buildRecapSummary({
        stepLabel: "Inheritance Mastered",
        tutorText: isJunior
          ? "You can now build whole family trees of classes! Every child class inherits from its parent for free, and you can customise individual methods with @Override. That is the power of code reuse through inheritance."
          : "Inheritance models real-world is-a relationships and enables reuse of superclass logic. Disciplined use of super(), @Override, and single inheritance keeps hierarchies understandable and maintainable.",
        title: isJunior ? "Inheritance — Mastered! 🏆" : "Inheritance Mastered 🏆",
        keyPoints: [
          "extends links a subclass to a superclass; the subclass inherits all public and protected members.",
          "super(args) as the first statement in the subclass constructor initialises the inherited superclass state.",
          "@Override verifies at compile time that the annotated method genuinely overrides a superclass method.",
        ],
        badgeReward: "Inheritance Architect 🧬",
        nextLesson: "JV_L2_05_POLY",
      }),
    ],
  };
}

// ─── LESSON 5: Polymorphism & Interfaces ──────────────────────────────────────
export function get_JV_L2_05_POLY_LESSON(theme: "junior" | "professional"): YamunaLessonPayload {
  const isJunior = theme === "junior";
  return {
    product: { id: "yamuna", name: "Yamuna Java AI Tutor" },
    course: { id: "java_core", levelId: "L2", levelSlug: "level-2", title: "Yamuna Java Core" },
    lesson: {
      id: "JV_L2_05_POLY",
      order: 5,
      title: "Polymorphism & Interfaces",
      sutra: "Polymorphism Sutra",
      objective:
        "Define Java interfaces, implement them in multiple classes, use polymorphic references to invoke methods at runtime, and understand that a class can implement multiple interfaces.",
      durationMin: 55,
      difficulty: 3,
      xpReward: 140,
    },
    progress: { currentStepIndex: 0, totalSteps: 7 },
    helpActions: [{ id: "help", label: "I need a hint" }],
    steps: [
      buildIntroHook({
        stepLabel: isJunior ? "One Command, Many Behaviours!" : "Polymorphism & Interface Contracts",
        tutorText: isJunior
          ? "Imagine pressing 'play' on a music app — it plays a song, a podcast, or a video depending on what is selected. Same button, different behaviour! That is polymorphism. In Java, interfaces let you write one method call that works on many different object types, as long as they all promise to implement the same method."
          : "Polymorphism ('many forms') allows a single interface reference to invoke different implementations at runtime via dynamic dispatch. Java interfaces define a contract — a set of method signatures — that any implementing class must fulfil. A class can implement multiple interfaces, sidestepping Java's single-inheritance constraint.",
        headline: isJunior ? "Interface = Contract, implements = Promise" : "Interfaces & Runtime Polymorphism",
        emoji: "🎭",
        example: isJunior
          ? "interface Drawable { void draw(); } → Circle and Rectangle both draw differently!"
          : "Drawable d = new Circle(); d.draw(); // Circle's draw() runs at runtime",
        goal: isJunior
          ? "Write an interface, implement it in two classes, and call methods polymorphically."
          : "Define an interface, implement it in two classes, and demonstrate runtime method dispatch through interface references.",
      }),
      buildConceptCard({
        stepLabel: "interface, implements & Polymorphic References",
        tutorText: isJunior
          ? "An interface is like a job description — it says 'you must have these methods', but does not say how to do them. A class that takes the job (implements the interface) has to fill in all the details. The cool part: you can store any implementing object in an interface-type variable!"
          : "An interface declares method signatures (and constants) without implementation bodies (Java 8+ default methods aside). implements creates a compile-time obligation to provide all declared methods. A polymorphic reference of type InterfaceName can hold any implementing object; the JVM uses the actual runtime type for dispatch (late binding).",
        title: isJunior ? "Interfaces & implements" : "Interface Contracts & Dynamic Dispatch",
        emoji: "📋",
        points: isJunior
          ? [
              "interface Drawable { void draw(); } — declares what implementors must do.",
              "class Circle implements Drawable { public void draw() { ... } } — fulfils the contract.",
              "Drawable d = new Circle(); — an interface reference can hold any implementing object.",
              "A class can implement multiple interfaces: class X implements A, B, C { }",
              "Calling d.draw() runs Circle's version — the right behaviour at the right time!",
            ]
          : [
              "interface methods are implicitly public abstract; fields are implicitly public static final.",
              "implements binds a class to the interface contract — missing method = compile error.",
              "InterfaceName ref = new ConcreteClass(); — ref holds a reference polymorphically.",
              "Runtime dispatch: JVM calls the method of the actual object type, not the reference type.",
              "Multiple interface implementation: class Foo implements Bar, Baz { } — both contracts must be fulfilled.",
            ],
        explanationTitle: "interface vs abstract class",
        explanationBody:
          "An interface is a pure contract (no state, all abstract methods by default). An abstract class can have state, concrete methods, and constructors. Prefer interfaces when you want to define a capability (Drawable, Comparable) that unrelated classes can adopt. Use abstract classes when you want to share implementation among closely related classes.",
      }),
      buildCodeWalkthrough({
        stepLabel: "Drawable: Circle & Rectangle",
        tutorText:
          "Let us trace the Drawable interface implemented by Circle and Rectangle. Notice the polymorphic array — we loop over Drawable references and call draw() without knowing the concrete type. Java looks up the real type at runtime and calls the right method.",
        expression: "Interface polymorphism with two implementing classes",
        codeSteps: [
          "interface Drawable {",
          "    void draw();",
          "}",
          "",
          "class Circle implements Drawable {",
          "    double radius;",
          "    Circle(double r) { radius = r; }",
          "    @Override",
          "    public void draw() {",
          "        System.out.println(\"Drawing circle with radius \" + radius);",
          "    }",
          "}",
          "",
          "class Rectangle implements Drawable {",
          "    double width, height;",
          "    Rectangle(double w, double h) { width = w; height = h; }",
          "    @Override",
          "    public void draw() {",
          "        System.out.println(\"Drawing rectangle \" + width + \"x\" + height);",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Drawable[] shapes = {",
          "            new Circle(5.0),",
          "            new Rectangle(3.0, 4.0),",
          "            new Circle(2.5)",
          "        };",
          "        for (Drawable d : shapes) {",
          "            d.draw();  // correct implementation called at runtime",
          "        }",
          "    }",
          "}",
        ],
        result:
          "Prints: Drawing circle with radius 5.0 / Drawing rectangle 3.0x4.0 / Drawing circle with radius 2.5",
      }),
      buildConceptCheck({
        stepLabel: "Multiple Interfaces Quiz",
        tutorText:
          "This question tests a key difference between Java interfaces and inheritance. Read carefully before answering.",
        headline: "Can a class implement multiple interfaces?",
        question: "Which statement about Java interfaces is correct?",
        options: [
          "A class can extend multiple classes but implement only one interface.",
          "A class can implement multiple interfaces but extend only one class.",
          "A class can extend multiple classes and implement multiple interfaces.",
          "A class can implement only one interface and extend only one class.",
        ],
        correctIndex: 1,
        explanation:
          "Java supports single-class inheritance only — a class can extend exactly one superclass. However, a class can implement any number of interfaces. This is why interfaces are preferred for defining capabilities: class Amphibian implements Swimmable, Walkable is valid; class Amphibian extends Fish, Land is not.",
      }),
      buildBugHunt({
        stepLabel: "Missing Interface Method Bug",
        tutorText: isJunior
          ? "A student created a Triangle class that claims to implement Drawable, but forgot to write the draw() method! Java refuses to compile a class that does not fulfil its interface contract. Find what is missing and add the correct draw() method."
          : "The Triangle class declares implements Drawable but does not implement the draw() method. This is a compile error: unimplemented interface method. Add the missing implementation.",
        headline: "Fix the Missing Interface Method",
        buggyCode: [
          "interface Drawable {",
          "    void draw();",
          "}",
          "",
          "class Triangle implements Drawable {",
          "    double base, height;",
          "",
          "    Triangle(double base, double height) {",
          "        this.base = base;",
          "        this.height = height;",
          "    }",
          "    // draw() is missing!",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Drawable t = new Triangle(3.0, 4.0);",
          "        t.draw();",
          "    }",
          "}",
        ].join("\n"),
        fixedCode: [
          "interface Drawable {",
          "    void draw();",
          "}",
          "",
          "class Triangle implements Drawable {",
          "    double base, height;",
          "",
          "    Triangle(double base, double height) {",
          "        this.base = base;",
          "        this.height = height;",
          "    }",
          "",
          "    @Override",
          "    public void draw() {",
          "        System.out.println(\"Drawing triangle: base=\" + base + \", height=\" + height);",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Drawable t = new Triangle(3.0, 4.0);",
          "        t.draw();",
          "    }",
          "}",
        ].join("\n"),
        explanation:
          "implements Drawable is a compile-time promise to provide all methods declared in Drawable. Drawable declares void draw(), so Triangle must have a public void draw() method. Without it, the compiler reports 'Triangle is not abstract and does not override abstract method draw() in Drawable'. Adding the implementation fulfils the contract.",
        hints: [
          "What method does the Drawable interface require?",
          "Add public void draw() { } inside the Triangle class body.",
          "Use @Override to confirm you are implementing the interface method.",
          "Interface methods are implicitly public — your implementation must also be public.",
        ],
      }),
      buildJavaChallenge({
        stepLabel: isJunior ? "Printable Interface Challenge!" : "Printable Interface Exercise",
        tutorText: isJunior
          ? "Create a Printable interface with a single print() method. Then write two classes — Invoice and Report — that implement Printable. Each should print something different in its print() method. Store both in a Printable array and loop over it calling print()!"
          : "Define interface Printable with void print(). Implement in class Invoice (prints invoice number) and class Report (prints report title). In main, create a Printable[] containing one of each and iterate, calling print() polymorphically.",
        boardTitle: isJunior ? "Printable Interface Builder" : "Printable Interface Exercise",
        prompt:
          "Define Printable interface with print(). Implement in Invoice and Report classes. Iterate a Printable array and call print() on each element.",
        starterCode: [
          "// Define the Printable interface",
          "",
          "// Implement Invoice with a number field",
          "",
          "// Implement Report with a title field",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        // Create a Printable array with one Invoice and one Report",
          "        // Loop and call print() on each",
          "    }",
          "}",
        ].join("\n"),
        solutionCode: [
          "interface Printable {",
          "    void print();",
          "}",
          "",
          "class Invoice implements Printable {",
          "    int number;",
          "    Invoice(int number) { this.number = number; }",
          "    @Override",
          "    public void print() {",
          "        System.out.println(\"Invoice #\" + number);",
          "    }",
          "}",
          "",
          "class Report implements Printable {",
          "    String title;",
          "    Report(String title) { this.title = title; }",
          "    @Override",
          "    public void print() {",
          "        System.out.println(\"Report: \" + title);",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Printable[] docs = {",
          "            new Invoice(1001),",
          "            new Report(\"Annual Summary\")",
          "        };",
          "        for (Printable p : docs) {",
          "            p.print();",
          "        }",
          "    }",
          "}",
        ].join("\n"),
        hints: [
          "interface Printable { void print(); } — just the signature, no body.",
          "class Invoice implements Printable — then add @Override public void print().",
          "class Report implements Printable — same pattern with a String title field.",
          "Printable[] docs = { new Invoice(1001), new Report(\"...\") };",
          "for (Printable p : docs) { p.print(); } — loops polymorphically.",
        ],
        openEnded: false,
      }),
      buildRecapSummary({
        stepLabel: "Polymorphism Mastered",
        tutorText: isJunior
          ? "You have unlocked one of the most powerful ideas in programming! With interfaces and polymorphism, you can write code that works with objects you have not even invented yet — as long as they fulfil the contract."
          : "Interfaces and polymorphism are the cornerstones of extensible Java design. Writing to interfaces rather than concrete types decouples components, enables testing with mock implementations, and allows systems to grow without modifying existing code — the Open/Closed principle in practice.",
        title: isJunior ? "Polymorphism — Mastered! 🏆" : "Interfaces & Polymorphism Mastered 🏆",
        keyPoints: [
          "An interface declares a contract (method signatures) that implementing classes must fulfil — all interface methods are implicitly public abstract.",
          "A class can implement multiple interfaces, allowing it to be used polymorphically in multiple contexts.",
          "An interface-type reference can hold any implementing object; the JVM dispatches to the correct implementation at runtime (dynamic dispatch).",
        ],
        badgeReward: "Polymorphism Master 🎭",
        nextLesson: "JV_L2_06_ABSTRACT",
      }),
    ],
  };
}

// ─── LESSON 6: Abstract Classes & Enums ──────────────────────────────────────
export function get_JV_L2_06_ABSTRACT_LESSON(theme: "junior" | "professional"): YamunaLessonPayload {
  const isJunior = theme === "junior";
  return {
    product: { id: "yamuna", name: "Yamuna Java AI Tutor" },
    course: { id: "java_core", levelId: "L2", levelSlug: "level-2", title: "Yamuna Java Core" },
    lesson: {
      id: "JV_L2_06_ABSTRACT",
      order: 6,
      title: "Abstract Classes & Enums",
      sutra: "Abstraction Sutra",
      objective:
        "Declare abstract classes with abstract methods, extend them in concrete subclasses, define enums with fields and methods, and understand when to prefer an abstract class over an interface.",
      durationMin: 55,
      difficulty: 3,
      xpReward: 140,
    },
    progress: { currentStepIndex: 0, totalSteps: 7 },
    helpActions: [{ id: "help", label: "I need a hint" }],
    steps: [
      buildIntroHook({
        stepLabel: isJunior ? "Templates with Gaps & Named Constants!" : "Abstract Classes & Enums",
        tutorText: isJunior
          ? "An abstract class is like a half-finished recipe — it has some instructions already written, but certain steps are left blank for each specific cook to fill in. An enum is like a menu with a fixed list of choices, but each choice can also carry extra data and even know how to do things. Together, they make your programs much smarter!"
          : "Abstract classes sit between interfaces and concrete classes: they can have state, constructors, concrete methods, and abstract method declarations. They are the right tool when related classes share implementation but each must specialise certain operations. Enums extend this further — they are type-safe singleton constants that can carry fields and methods, replacing int-constant antipatterns.",
        headline: isJunior ? "abstract = Template; enum = Smart Constants" : "Abstract Classes & Enum Power",
        emoji: "🧩",
        example: isJunior
          ? "abstract class Shape { abstract double area(); } → Circle and Square fill in area()"
          : "abstract double area(); must be overridden; enum Day { MON, TUE; boolean isWeekend() { } }",
        goal: isJunior
          ? "Write an abstract class, extend it, and build an enum with a method."
          : "Define an abstract class hierarchy, implement concrete subclasses, and create a feature-rich enum.",
      }),
      buildConceptCard({
        stepLabel: "abstract class, abstract methods & enum",
        tutorText: isJunior
          ? "An abstract class uses the 'abstract' keyword. Any method marked 'abstract' has no body — subclasses are forced to provide it. You cannot create an object directly from an abstract class; it is only used as a parent. Enums list all possible values and can store data and methods right inside each constant!"
          : "abstract class prevents direct instantiation via new. abstract methods declare a signature without a body; every concrete subclass must provide an implementation or be declared abstract itself. enum types compile to classes extending java.lang.Enum; each constant is a public static final instance. Enum constants can have fields (set in their constructor) and methods.",
        title: isJunior ? "abstract & enum Keywords" : "Abstract Classes vs Interfaces; Enum Internals",
        emoji: "🔮",
        points: isJunior
          ? [
              "abstract class Shape { } — cannot be instantiated directly with new.",
              "abstract double area(); — no body; every concrete subclass must implement it.",
              "class Circle extends Shape { double area() { return Math.PI * r * r; } }",
              "enum Season { SPRING, SUMMER, AUTUMN, WINTER } — four safe, named constants.",
              "Enum constants can carry methods: enum Day { SAT, SUN; boolean isWeekend() { return true; } }",
            ]
          : [
              "abstract class: can have constructors, fields, concrete methods, and abstract methods.",
              "abstract method: method signature without a body; forces subclass to override.",
              "Cannot new an abstract class — compile error; must subclass and implement all abstract methods.",
              "Prefer abstract class over interface when subclasses share significant implementation code.",
              "enum: type-safe set of named constants; each constant is a singleton instance of the enum type.",
            ],
        explanationTitle: "abstract class vs interface — when to use which?",
        explanationBody:
          "Use an interface when you want to define a capability that unrelated classes can adopt (Serializable, Comparable). Use an abstract class when you have a family of related classes that share state or concrete behaviour and you want to enforce that a specific method is customised per subclass. In Java 8+, interfaces can have default methods, blurring the line, but abstract classes still win when shared state is needed.",
      }),
      buildCodeWalkthrough({
        stepLabel: "Abstract Shape Hierarchy",
        tutorText:
          "Let us trace an abstract Shape class with an abstract area() method and a concrete describe() method. Circle and Square each extend Shape and provide their own area() formula. Notice that describe() in Shape can call area() — the subclass version runs at runtime.",
        expression: "Abstract class with concrete and abstract methods",
        codeSteps: [
          "abstract class Shape {",
          "    String colour;",
          "",
          "    Shape(String colour) { this.colour = colour; }",
          "",
          "    abstract double area();   // subclasses must implement",
          "",
          "    void describe() {         // concrete — shared by all shapes",
          "        System.out.println(colour + \" shape, area = \" + area());",
          "    }",
          "}",
          "",
          "class Circle extends Shape {",
          "    double radius;",
          "    Circle(String colour, double radius) {",
          "        super(colour);",
          "        this.radius = radius;",
          "    }",
          "    @Override",
          "    double area() { return Math.PI * radius * radius; }",
          "}",
          "",
          "class Square extends Shape {",
          "    double side;",
          "    Square(String colour, double side) {",
          "        super(colour);",
          "        this.side = side;",
          "    }",
          "    @Override",
          "    double area() { return side * side; }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Shape c = new Circle(\"red\", 5);",
          "        Shape s = new Square(\"blue\", 4);",
          "        c.describe();",
          "        s.describe();",
          "    }",
          "}",
        ],
        result: "Prints: red shape, area = 78.53981633974483 / blue shape, area = 16.0",
      }),
      buildConceptCheck({
        stepLabel: "Abstract Class Instantiation Quiz",
        tutorText:
          "This is one of the most common Java interview questions. Think carefully about what abstract means before picking your answer.",
        headline: "Can you instantiate an abstract class?",
        question:
          "Given: abstract class Vehicle { abstract void move(); }  Which statement is true?",
        options: [
          "Vehicle v = new Vehicle(); is valid because Vehicle has no fields.",
          "You cannot create a new Vehicle() directly — abstract classes cannot be instantiated.",
          "You can instantiate Vehicle only if move() has a default implementation.",
          "Vehicle v = new Vehicle() { }; creates a valid anonymous Vehicle instance.",
        ],
        correctIndex: 1,
        explanation:
          "abstract classes cannot be instantiated with new directly — attempting to do so is a compile error regardless of whether the abstract methods have bodies. You must create a concrete subclass that overrides all abstract methods, then instantiate the subclass. Anonymous class syntax (option D) would require implementing move(), making it a concrete anonymous subclass, not a direct Vehicle instantiation.",
      }),
      buildBugHunt({
        stepLabel: "Instantiating Abstract Class Bug",
        tutorText: isJunior
          ? "A student tried to create an object directly from an abstract class — Java will not allow it! Also, the concrete subclass forgot to implement the abstract method. Find both bugs and fix them."
          : "The code below has two errors: it tries to instantiate the abstract class directly, and the concrete subclass does not implement the required abstract method. Fix both issues.",
        headline: "Fix the Abstract Class Bugs",
        buggyCode: [
          "abstract class Animal {",
          "    String name;",
          "    Animal(String name) { this.name = name; }",
          "    abstract void speak();",
          "}",
          "",
          "class Parrot extends Animal {",
          "    Parrot(String name) { super(name); }",
          "    // forgot to implement speak()",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Animal a = new Animal(\"Generic\");  // cannot instantiate abstract!",
          "        Animal p = new Parrot(\"Polly\");",
          "        p.speak();",
          "    }",
          "}",
        ].join("\n"),
        fixedCode: [
          "abstract class Animal {",
          "    String name;",
          "    Animal(String name) { this.name = name; }",
          "    abstract void speak();",
          "}",
          "",
          "class Parrot extends Animal {",
          "    Parrot(String name) { super(name); }",
          "    @Override",
          "    void speak() {",
          "        System.out.println(name + \" says: Squawk!\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        Animal p = new Parrot(\"Polly\");",
          "        p.speak();",
          "    }",
          "}",
        ].join("\n"),
        explanation:
          "Bug 1: new Animal(\"Generic\") tries to instantiate an abstract class — compile error. Remove that line. Bug 2: Parrot extends Animal but does not implement speak() — compile error. Add @Override void speak() { } inside Parrot with the appropriate body.",
        hints: [
          "You cannot call new on an abstract class — remove or replace that line.",
          "Parrot must provide void speak() to satisfy the abstract method contract.",
          "Add @Override void speak() { System.out.println(...); } inside Parrot.",
        ],
      }),
      buildJavaChallenge({
        stepLabel: isJunior ? "enum Day + abstract Report!" : "Enum & Abstract Class Exercise",
        tutorText: isJunior
          ? "Two challenges in one! First, create an enum Day with all 7 days and an isWeekend() method that returns true for SATURDAY and SUNDAY. Second, create an abstract Report class with an abstract generate() method, then extend it in SalesReport and InventoryReport, each printing different output. Test everything in main!"
          : "Part A: enum Day with constants MON-SUN; method boolean isWeekend() returns true for SAT/SUN. Part B: abstract class Report with abstract void generate(); concrete SalesReport and InventoryReport each override generate(). In main, demonstrate isWeekend() on two Day values and call generate() on both reports polymorphically.",
        boardTitle: isJunior ? "Day Enum + Report Hierarchy" : "Enum & Abstract Class Exercise",
        prompt:
          "Create enum Day with isWeekend() method. Create abstract Report with generate(); implement SalesReport and InventoryReport. Test both in main.",
        starterCode: [
          "// Define enum Day with MONDAY through SUNDAY",
          "// Add boolean isWeekend() that returns true for SATURDAY and SUNDAY",
          "",
          "// Define abstract class Report",
          "// Add abstract void generate();",
          "",
          "// SalesReport extends Report — generate() prints a sales message",
          "",
          "// InventoryReport extends Report — generate() prints an inventory message",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        // Test Day.SATURDAY.isWeekend() and Day.MONDAY.isWeekend()",
          "        // Create Report[] with one SalesReport and one InventoryReport",
          "        // Loop and call generate() on each",
          "    }",
          "}",
        ].join("\n"),
        solutionCode: [
          "enum Day {",
          "    MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY;",
          "",
          "    public boolean isWeekend() {",
          "        return this == SATURDAY || this == SUNDAY;",
          "    }",
          "}",
          "",
          "abstract class Report {",
          "    abstract void generate();",
          "}",
          "",
          "class SalesReport extends Report {",
          "    @Override",
          "    void generate() {",
          "        System.out.println(\"Generating sales report...\");",
          "    }",
          "}",
          "",
          "class InventoryReport extends Report {",
          "    @Override",
          "    void generate() {",
          "        System.out.println(\"Generating inventory report...\");",
          "    }",
          "}",
          "",
          "public class Main {",
          "    public static void main(String[] args) {",
          "        System.out.println(Day.SATURDAY.isWeekend());  // true",
          "        System.out.println(Day.MONDAY.isWeekend());    // false",
          "",
          "        Report[] reports = { new SalesReport(), new InventoryReport() };",
          "        for (Report r : reports) {",
          "            r.generate();",
          "        }",
          "    }",
          "}",
        ].join("\n"),
        hints: [
          "enum Day { MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY; }",
          "Inside isWeekend(): return this == SATURDAY || this == SUNDAY;",
          "abstract class Report { abstract void generate(); } — no body on generate.",
          "SalesReport extends Report { @Override void generate() { ... } }",
          "Report[] reports = { new SalesReport(), new InventoryReport() }; then loop with generate().",
        ],
        openEnded: false,
      }),
      buildRecapSummary({
        stepLabel: "Level 2 Complete",
        tutorText: isJunior
          ? "You have completed the entire OOP level! You now know how to design classes, protect data, share code through inheritance, write flexible interfaces, and use abstract classes and enums like a real Java developer. That is an enormous achievement!"
          : "Congratulations on completing Level 2. You have mastered all four OOP pillars — encapsulation, inheritance, polymorphism, and abstraction — plus Java's type-safe enum construct. These patterns form the architectural vocabulary of every serious Java codebase.",
        title: isJunior ? "OOP Level 2 — Complete! 🏆" : "Java OOP Mastered 🏆",
        keyPoints: [
          "abstract class prevents direct instantiation and can mix concrete and abstract methods; concrete subclasses must implement all abstract methods.",
          "You cannot instantiate an abstract class with new — only its concrete subclasses can be instantiated.",
          "enum defines a fixed set of type-safe named constants; each constant is a singleton that can carry fields and methods, replacing error-prone int-constant patterns.",
        ],
        badgeReward: "OOP Architect 🧩",
        nextLesson: "JV_L3_01_COLLECTIONS",
      }),
    ],
  };
}
