USE robodynamics_db;
SET SQL_SAFE_UPDATES=0;
START TRANSACTION;
SET @course_name='CBSE Grade 9 Mathematics (NCERT)';
SET @import_tag='import_cbse_grade_9_maths_2026_03_04';
INSERT INTO rd_courses (course_category_id,course_name,course_description,shortDescription,course_level,course_status,grade_range,category,is_featured,tier_level,tier_order,reviews_count,is_active)
SELECT 11,@course_name,'NCERT Class 9 Mathematics chapters imported from docs/course_materials/cbse_grade_9_maths.','Auto-imported from iemh1ps.pdf table of contents and chapter PDFs.','9','ACTIVE','MIDDLE_SCHOOL_7_9','Mathematics',0,'beginner',1,0,1
WHERE NOT EXISTS (SELECT 1 FROM rd_courses WHERE course_name=@course_name);
SET @course_id=(SELECT course_id FROM rd_courses WHERE course_name=@course_name ORDER BY course_id DESC LIMIT 1);
DELETE d FROM rd_course_session_details d JOIN rd_course_sessions s ON s.course_session_id=d.course_session_id WHERE s.course_id=@course_id AND COALESCE(s.session_description,'')=@import_tag;
DELETE FROM rd_course_sessions WHERE course_id=@course_id AND COALESCE(session_description,'')=@import_tag;
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,1,'Chapter 1: Number Systems',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',1);
SET @s1=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 1: Number Systems',CURDATE(),1,@course_id,@s1,'pdf','iemh101.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,2,'Chapter 2: Polynomials',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',2);
SET @s2=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 2: Polynomials',CURDATE(),1,@course_id,@s2,'pdf','iemh102.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,3,'Chapter 3: Coordinate Geometry',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',3);
SET @s3=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 3: Coordinate Geometry',CURDATE(),1,@course_id,@s3,'pdf','iemh103.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,4,'Chapter 4: Linear Equations In Two Variables',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',4);
SET @s4=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 4: Linear Equations In Two Variables',CURDATE(),1,@course_id,@s4,'pdf','iemh104.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,5,'Chapter 5: Introduction To Euclid''s Geometry',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',5);
SET @s5=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 5: Introduction To Euclid''s Geometry',CURDATE(),1,@course_id,@s5,'pdf','iemh105.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,6,'Chapter 6: Lines And Angles',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',6);
SET @s6=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 6: Lines And Angles',CURDATE(),1,@course_id,@s6,'pdf','iemh106.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,7,'Chapter 7: Triangles',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',7);
SET @s7=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 7: Triangles',CURDATE(),1,@course_id,@s7,'pdf','iemh107.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,8,'Chapter 8: Quadrilaterals',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',8);
SET @s8=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 8: Quadrilaterals',CURDATE(),1,@course_id,@s8,'pdf','iemh108.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,9,'Chapter 9: Circles',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',9);
SET @s9=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 9: Circles',CURDATE(),1,@course_id,@s9,'pdf','iemh109.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,10,'Chapter 10: Heron''s Formula',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',10);
SET @s10=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 10: Heron''s Formula',CURDATE(),1,@course_id,@s10,'pdf','iemh110.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,11,'Chapter 11: Surface Areas And Volumes',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',11);
SET @s11=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 11: Surface Areas And Volumes',CURDATE(),1,@course_id,@s11,'pdf','iemh111.pdf',1,'BEGINNER',1,0,0);
INSERT INTO rd_course_sessions (course_id,session_id,session_title,creation_date,version,completed,progress,session_type,session_description,tier_level,tier_order) VALUES (@course_id,12,'Chapter 12: Statistics',CURDATE(),1,0,0.00,'session',@import_tag,'BEGINNER',12);
SET @s12=LAST_INSERT_ID();
INSERT INTO rd_course_session_details (topic,creation_date,version,course_id,course_session_id,type,file,session_detail_id,tier_level,tier_order,has_animation,assignment) VALUES ('Chapter 12: Statistics',CURDATE(),1,@course_id,@s12,'pdf','iemh112.pdf',1,'BEGINNER',1,0,0);
COMMIT;
SELECT @course_id AS course_id;
SELECT COUNT(*) AS imported_sessions FROM rd_course_sessions WHERE course_id=@course_id AND COALESCE(session_description,'')=@import_tag;
SELECT COUNT(*) AS imported_pdf_details FROM rd_course_session_details d JOIN rd_course_sessions s ON s.course_session_id=d.course_session_id WHERE s.course_id=@course_id AND COALESCE(s.session_description,'')=@import_tag AND LOWER(COALESCE(d.type,''))='pdf';
SELECT s.session_id,s.session_title,d.file FROM rd_course_sessions s LEFT JOIN rd_course_session_details d ON d.course_session_id=s.course_session_id AND LOWER(COALESCE(d.type,''))='pdf' WHERE s.course_id=@course_id AND COALESCE(s.session_description,'')=@import_tag ORDER BY s.session_id;

