export const MINDSUTRA_DEMO_CHAPTERS = {
  "4": "VM_G4_L1_FAST_ADDITION",
  "5": "VM_G5_L1_NIKHILAM_NEAR100",
  "6": "VM_G6_L1_VINCULUM",
  "7": "VM_G7_L1_SQUARING_NEAR_BASE",
  "8": "VM_G8_L1_SQUARE_ROOTS",
} as const;
export const MINDSUTRA_DEMO_CHAPTERS_BY_SLUG = {
  "grade-4": MINDSUTRA_DEMO_CHAPTERS["4"],
  "grade-5": MINDSUTRA_DEMO_CHAPTERS["5"],
  "grade-6": MINDSUTRA_DEMO_CHAPTERS["6"],
  "grade-7": MINDSUTRA_DEMO_CHAPTERS["7"],
  "grade-8": MINDSUTRA_DEMO_CHAPTERS["8"],
} as const;
