"""Add G/H/I questions to L6, L8, L13, L15 which only had A-F groups."""
import json
import pathlib
import collections

BASE = pathlib.Path("C:/roboworkspace/robodynamics/ai-tutor/tutor-api/content-template/vedic_math/chapter")

NEW_QUESTIONS = {
  "L6_NIKHILAM_BASE_10_100": [
    {"questionId":"L6_G_REV_7173","exerciseGroup":"G","subtopic":"Review: Addition by splitting","skill":"Splitting addition review","difficulty":"medium","type":"short_answer","questionText":"What is 3456 + 3717 by splitting after two digits?","hint":"Split as 34/56 and 37/17, add each part.","solution":"34+37=71, 56+17=73. Merge: 7173.","expectedAnswer":"7173"},
    {"questionId":"L6_G_REV_2891","exerciseGroup":"G","subtopic":"Review: Addition by splitting","skill":"Splitting addition review","difficulty":"easy","type":"short_answer","questionText":"What is 1234 + 1657 by splitting after two digits?","hint":"Split as 12/34 and 16/57.","solution":"12+16=28, 34+57=91. Merge: 2891.","expectedAnswer":"2891"},
    {"questionId":"L6_G_REV_SUB3333","exerciseGroup":"G","subtopic":"Review: Subtraction by splitting","skill":"Splitting subtraction review","difficulty":"medium","type":"short_answer","questionText":"What is 5678 - 2345 by splitting?","hint":"Split as 56/78 and 23/45.","solution":"56-23=33, 78-45=33. Merge: 3333.","expectedAnswer":"3333"},
    {"questionId":"L6_G_REV_MUL936","exerciseGroup":"G","subtopic":"Review: Multiplication by splitting","skill":"Splitting multiplication review","difficulty":"medium","type":"short_answer","questionText":"What is 312 * 3 by splitting as 3/12?","hint":"Multiply each part: 3*3 and 12*3.","solution":"3*3=9, 12*3=36. Merge: 936.","expectedAnswer":"936"},
    {"questionId":"L6_H_CHAL_12482","exerciseGroup":"H","subtopic":"Challenge: Larger addition split","skill":"Advanced splitting","difficulty":"hard","type":"short_answer","questionText":"What is 5678 + 6804 by splitting after two digits?","hint":"Split as 56/78 and 68/04.","solution":"56+68=124, 78+04=82. Merge: 12482.","expectedAnswer":"12482"},
    {"questionId":"L6_H_CHAL_3156","exerciseGroup":"H","subtopic":"Challenge: Multiplication by splitting","skill":"Advanced multiplication split","difficulty":"hard","type":"short_answer","questionText":"What is 526 * 6 by splitting as 5/26?","hint":"5*6=30, 26*6=156.","solution":"5*6=30, 26*6=156. Merge: 3156.","expectedAnswer":"3156"},
    {"questionId":"L6_H_CHAL_4482","exerciseGroup":"H","subtopic":"Challenge: Division by splitting","skill":"Advanced division split","difficulty":"hard","type":"short_answer","questionText":"What is 8964 / 2 by splitting as 8000 and 964?","hint":"Divide each part: 8000/2 and 964/2.","solution":"8000/2=4000, 964/2=482. Total: 4482.","expectedAnswer":"4482"},
    {"questionId":"L6_H_CHAL_REASON","exerciseGroup":"H","subtopic":"Challenge: Choosing the split","skill":"Conceptual challenge","difficulty":"medium","type":"short_answer","questionText":"Why do we choose the split point to avoid carries?","hint":"Think about what makes the arithmetic simpler.","solution":"A split at a point without a carry keeps each chunk independent, making the mental arithmetic faster and less error-prone.","expectedAnswer":"To keep each chunk independent and avoid carry propagation"},
    {"questionId":"L6_I_MASTERY_9467","exerciseGroup":"I","subtopic":"Mastery: Addition splitting","skill":"Mastery check","difficulty":"medium","type":"short_answer","questionText":"What is 4523 + 4944?","hint":"Split after two digits: 45/23 and 49/44.","solution":"45+49=94, 23+44=67. Merge: 9467.","expectedAnswer":"9467"},
    {"questionId":"L6_I_MASTERY_1924","exerciseGroup":"I","subtopic":"Mastery: Subtraction splitting","skill":"Mastery check","difficulty":"medium","type":"short_answer","questionText":"What is 3243 - 1319?","hint":"Split as 32/43 and 13/19.","solution":"32-13=19, 43-19=24. Merge: 1924.","expectedAnswer":"1924"},
    {"questionId":"L6_I_MASTERY_2604","exerciseGroup":"I","subtopic":"Mastery: Multiplication splitting","skill":"Mastery check","difficulty":"medium","type":"short_answer","questionText":"What is 434 * 6 by splitting as 4/34?","hint":"4*6=24, 34*6=204.","solution":"4*6=24, 34*6=204. Merge: 2604.","expectedAnswer":"2604"},
    {"questionId":"L6_I_MASTERY_WHEN","exerciseGroup":"I","subtopic":"Mastery: Conceptual","skill":"Mastery check","difficulty":"easy","type":"short_answer","questionText":"When is number splitting most useful?","hint":"Think about the size of numbers involved.","solution":"Number splitting is most useful when dealing with large numbers where direct mental arithmetic is difficult.","expectedAnswer":"When numbers are too large to compute mentally in one step"},
  ],
  "L8_YAVADUNAM": [
    {"questionId":"L8_G_REV_DS_CHECK","exerciseGroup":"G","subtopic":"Review: Digit-sum check","skill":"Digit-sum review","difficulty":"medium","type":"short_answer","questionText":"Using digit sums, check whether 123 * 9 = 1107.","hint":"Digit sum of 123 is 6; digit sum of 9 is 9.","solution":"LHS digit sum: 6*9=54 -> 9. RHS 1107 -> 9. Both match.","expectedAnswer":"Yes, the digit-sum check passes"},
    {"questionId":"L8_G_REV_LASTDIG","exerciseGroup":"G","subtopic":"Review: Last-digit check","skill":"Last-digit review","difficulty":"easy","type":"short_answer","questionText":"What is the last digit of 237 * 348?","hint":"Multiply only the last digits: 7 * 8.","solution":"7*8=56, so the last digit is 6.","expectedAnswer":"6"},
    {"questionId":"L8_G_REV_FIRST_EST","exerciseGroup":"G","subtopic":"Review: First-by-first estimate","skill":"Estimation review","difficulty":"easy","type":"short_answer","questionText":"Give a first-by-first estimate for 47 * 82.","hint":"Multiply only the leading digits: 4 * 8.","solution":"4*8=32, so the estimate is about 3200.","expectedAnswer":"about 3200"},
    {"questionId":"L8_G_REV_DIV4_CHK","exerciseGroup":"G","subtopic":"Review: Divisibility by 4","skill":"Divisibility review","difficulty":"easy","type":"short_answer","questionText":"Does 7348 pass the divisibility-by-4 test?","hint":"Check the last two digits: 48.","solution":"48/4=12, so yes, 7348 is divisible by 4.","expectedAnswer":"Yes"},
    {"questionId":"L8_H_CHAL_DIV11","exerciseGroup":"H","subtopic":"Challenge: Divisibility by 11","skill":"Divisibility by 11","difficulty":"hard","type":"short_answer","questionText":"Does 89375 pass the divisibility-by-11 test?","hint":"Alternating sum: 5-7+3-9+8.","solution":"5-7+3-9+8=0. Since 0 is divisible by 11, yes.","expectedAnswer":"Yes"},
    {"questionId":"L8_H_CHAL_DSCHECK","exerciseGroup":"H","subtopic":"Challenge: Digit-sum multiplication check","skill":"Digit-sum check","difficulty":"medium","type":"short_answer","questionText":"Use digit sums to check: 56 * 34 = 1904.","hint":"Digit sums: 56 -> 2, 34 -> 7. Product: 2*7=14 -> 5. Check RHS.","solution":"56->2; 34->7; 2*7=14->5. RHS 1904->14->5. Both 5 - check passes.","expectedAnswer":"Yes, the check passes"},
    {"questionId":"L8_H_CHAL_LASTPOW","exerciseGroup":"H","subtopic":"Challenge: Last digit of power","skill":"Last-digit reasoning","difficulty":"medium","type":"short_answer","questionText":"What is the last digit of 3 raised to the power 8?","hint":"The last digits of powers of 3 cycle: 3,9,7,1 repeating.","solution":"3^4 ends in 1; 3^8=(3^4)^2 ends in 1*1=1.","expectedAnswer":"1"},
    {"questionId":"L8_H_CHAL_DIV8","exerciseGroup":"H","subtopic":"Challenge: Divisibility by 8","skill":"Divisibility by 8","difficulty":"hard","type":"short_answer","questionText":"Is 54312 divisible by 8?","hint":"Check the last three digits: 312.","solution":"312/8=39. Yes, 54312 is divisible by 8.","expectedAnswer":"Yes"},
    {"questionId":"L8_I_MASTERY_EST","exerciseGroup":"I","subtopic":"Mastery: Estimation","skill":"Mastery check","difficulty":"medium","type":"short_answer","questionText":"Give a first-by-first estimate for 643 * 78.","hint":"Leading digits: 6 * 7.","solution":"6*7=42, so estimate is about 42000.","expectedAnswer":"about 42000"},
    {"questionId":"L8_I_MASTERY_LASTD","exerciseGroup":"I","subtopic":"Mastery: Last-digit check","skill":"Mastery check","difficulty":"easy","type":"short_answer","questionText":"What is the last digit of 456 * 789?","hint":"Multiply the last digits: 6 * 9.","solution":"6*9=54, last digit is 4.","expectedAnswer":"4"},
    {"questionId":"L8_I_MASTERY_DS","exerciseGroup":"I","subtopic":"Mastery: Digit-sum check","skill":"Mastery check","difficulty":"medium","type":"short_answer","questionText":"Use digit sums to verify 43 * 21 = 903.","hint":"Digit sums: 43->7, 21->3. 7*3=21->3. Check RHS.","solution":"43->7, 21->3, 7*3=21->3. RHS 903->12->3. Both 3 - check passes.","expectedAnswer":"Yes, the check passes"},
    {"questionId":"L8_I_MASTERY_DIV4","exerciseGroup":"I","subtopic":"Mastery: Divisibility","skill":"Mastery check","difficulty":"easy","type":"short_answer","questionText":"Is 4536 divisible by 4?","hint":"Check only the last two digits: 36.","solution":"36/4=9. Yes, 4536 is divisible by 4.","expectedAnswer":"Yes"},
  ],
  "L13_ALGEBRAIC_IDENTITIES": [
    {"questionId":"L13_G_REV_ONE_16","exerciseGroup":"G","subtopic":"Review: One-step equations","skill":"One-step equation review","difficulty":"easy","type":"short_answer","questionText":"What is x if x + 14 = 30?","hint":"Transpose 14 to the right side.","solution":"x = 30-14 = 16.","expectedAnswer":"16"},
    {"questionId":"L13_G_REV_MUL_9","exerciseGroup":"G","subtopic":"Review: One-step multiplication","skill":"One-step equation review","difficulty":"easy","type":"short_answer","questionText":"What is x if 5x = 45?","hint":"Divide both sides by 5.","solution":"x = 45/5 = 9.","expectedAnswer":"9"},
    {"questionId":"L13_G_REV_TWO_5","exerciseGroup":"G","subtopic":"Review: Two-step equations","skill":"Two-step equation review","difficulty":"medium","type":"short_answer","questionText":"What is x if 4x - 3 = 17?","hint":"Add 3 to both sides first, then divide by 4.","solution":"4x=20, x=5.","expectedAnswer":"5"},
    {"questionId":"L13_G_REV_FRAC_15","exerciseGroup":"G","subtopic":"Review: Equation with fraction","skill":"Fractional equation review","difficulty":"medium","type":"short_answer","questionText":"What is x if x/3 + 2 = 7?","hint":"Subtract 2 first, then multiply by 3.","solution":"x/3=5, x=15.","expectedAnswer":"15"},
    {"questionId":"L13_H_CHAL_BRK_3","exerciseGroup":"H","subtopic":"Challenge: Bracket equation","skill":"Bracket equation","difficulty":"hard","type":"short_answer","questionText":"Solve: 3(x + 5) = 24.","hint":"Expand the bracket then solve.","solution":"3x+15=24, 3x=9, x=3.","expectedAnswer":"3"},
    {"questionId":"L13_H_CHAL_TWOBR_4","exerciseGroup":"H","subtopic":"Challenge: Two-bracket equation","skill":"Two-bracket equation","difficulty":"hard","type":"short_answer","questionText":"Solve: 2(x + 3) = x + 10.","hint":"Expand, then collect x terms on one side.","solution":"2x+6=x+10, x=4.","expectedAnswer":"4"},
    {"questionId":"L13_H_CHAL_FRAC_7","exerciseGroup":"H","subtopic":"Challenge: Fractional equation","skill":"Fractional equation","difficulty":"hard","type":"short_answer","questionText":"What is x if (2x + 4) / 3 = 6?","hint":"Multiply both sides by 3 first.","solution":"2x+4=18, 2x=14, x=7.","expectedAnswer":"7"},
    {"questionId":"L13_H_CHAL_DEC_12","exerciseGroup":"H","subtopic":"Challenge: Decimal equation","skill":"Decimal equation","difficulty":"medium","type":"short_answer","questionText":"What is x if x - 3.5 = 8.5?","hint":"Add 3.5 to both sides.","solution":"x = 8.5+3.5 = 12.","expectedAnswer":"12"},
    {"questionId":"L13_I_MASTERY_8","exerciseGroup":"I","subtopic":"Mastery: Multi-step equation","skill":"Mastery check","difficulty":"hard","type":"short_answer","questionText":"Solve: 5(x - 2) = 3x + 6.","hint":"Expand, then collect x terms.","solution":"5x-10=3x+6, 2x=16, x=8.","expectedAnswer":"8"},
    {"questionId":"L13_I_MASTERY_15","exerciseGroup":"I","subtopic":"Mastery: Division equation","skill":"Mastery check","difficulty":"medium","type":"short_answer","questionText":"What is x if (x + 3) / 6 = 3?","hint":"Multiply both sides by 6 first.","solution":"x+3=18, x=15.","expectedAnswer":"15"},
    {"questionId":"L13_I_MASTERY_11","exerciseGroup":"I","subtopic":"Mastery: Two-step","skill":"Mastery check","difficulty":"medium","type":"short_answer","questionText":"What is x if 3x + 4 = 37?","hint":"Subtract 4 first, then divide by 3.","solution":"3x=33, x=11.","expectedAnswer":"11"},
    {"questionId":"L13_I_MASTERY_CHECK","exerciseGroup":"I","subtopic":"Mastery: Checking a solution","skill":"Mastery check","difficulty":"easy","type":"short_answer","questionText":"Check whether x=4 satisfies 2x + 5 = 13.","hint":"Substitute x=4 into the equation.","solution":"2*4+5=8+5=13. Yes, x=4 is correct.","expectedAnswer":"Yes"},
  ],
  "L15_SQUARES_NEAR_BASE": [
    {"questionId":"L15_G_REV_DIV9_6","exerciseGroup":"G","subtopic":"Review: Division by 9","skill":"Division by 9 review","difficulty":"easy","type":"short_answer","questionText":"What is 54 / 9?","hint":"Running digit sums: 5, 5+4=9.","solution":"Running: 5; 5+4=9 (0 remainder). Quotient: 6.","expectedAnswer":"6"},
    {"questionId":"L15_G_REV_DIV9_26","exerciseGroup":"G","subtopic":"Review: Division by 9","skill":"Division by 9 review","difficulty":"medium","type":"short_answer","questionText":"What is 234 / 9?","hint":"Running sums: 2, 2+3=5, 5+4=9.","solution":"2, 5, 9. Quotient 26, remainder 0.","expectedAnswer":"26"},
    {"questionId":"L15_G_REV_DIV7_12","exerciseGroup":"G","subtopic":"Review: Division by 7","skill":"Division by 7 review","difficulty":"medium","type":"short_answer","questionText":"What is 84 / 7?","hint":"Use repeated subtraction or the Vedic column method.","solution":"84/7 = 12.","expectedAnswer":"12"},
    {"questionId":"L15_G_REV_DIV99_57","exerciseGroup":"G","subtopic":"Review: Division by 99","skill":"Division by 99 review","difficulty":"medium","type":"short_answer","questionText":"What is 5643 / 99?","hint":"Group as 56|43 and use running totals.","solution":"56, 56+43=99. Quotient 57, remainder 0.","expectedAnswer":"57"},
    {"questionId":"L15_H_CHAL_DIV8_19","exerciseGroup":"H","subtopic":"Challenge: Division by 8","skill":"Division by 8","difficulty":"hard","type":"short_answer","questionText":"What is 152 / 8?","hint":"Halve three times: 152 -> 76 -> 38 -> 19.","solution":"152/2=76, 76/2=38, 38/2=19. Answer: 19.","expectedAnswer":"19"},
    {"questionId":"L15_H_CHAL_DIV98_50","exerciseGroup":"H","subtopic":"Challenge: Division by 98","skill":"Division by 98","difficulty":"hard","type":"short_answer","questionText":"What is 4900 / 98?","hint":"Verify: 98 * 50 = 4900.","solution":"98*50=4900. Answer: 50.","expectedAnswer":"50"},
    {"questionId":"L15_H_CHAL_DIV9_507","exerciseGroup":"H","subtopic":"Challenge: Division by 9","skill":"Division by 9 challenge","difficulty":"medium","type":"short_answer","questionText":"What is 4563 / 9?","hint":"Running sums and carries through the digits.","solution":"4563 / 9 = 507.","expectedAnswer":"507"},
    {"questionId":"L15_H_CHAL_REM_14r2","exerciseGroup":"H","subtopic":"Challenge: Division with remainder","skill":"Division with remainder","difficulty":"medium","type":"short_answer","questionText":"What is 100 / 7?","hint":"7 * 14 = 98.","solution":"7*14=98. Remainder: 100-98=2. Answer: 14 remainder 2.","expectedAnswer":"14 remainder 2"},
    {"questionId":"L15_I_MASTERY_D9_111","exerciseGroup":"I","subtopic":"Mastery: Division by 9","skill":"Mastery check","difficulty":"medium","type":"short_answer","questionText":"What is 999 / 9?","hint":"All digit sums lead directly to the answer.","solution":"999/9 = 111.","expectedAnswer":"111"},
    {"questionId":"L15_I_MASTERY_D7_23","exerciseGroup":"I","subtopic":"Mastery: Division by 7","skill":"Mastery check","difficulty":"medium","type":"short_answer","questionText":"What is 161 / 7?","hint":"7 * 23 = 161.","solution":"161/7 = 23.","expectedAnswer":"23"},
    {"questionId":"L15_I_MASTERY_D99_101","exerciseGroup":"I","subtopic":"Mastery: Division by 99","skill":"Mastery check","difficulty":"hard","type":"short_answer","questionText":"What is 9999 / 99?","hint":"Group as 99|99 and use running totals.","solution":"99, 99+99=198. Quotient 101, remainder 0.","expectedAnswer":"101"},
    {"questionId":"L15_I_MASTERY_WHY","exerciseGroup":"I","subtopic":"Mastery: Conceptual understanding","skill":"Mastery check","difficulty":"easy","type":"short_answer","questionText":"Why does dividing by 9 work using running digit sums?","hint":"What does 10 equal in terms of 9?","solution":"Because 10 = 9+1, each digit position carries exactly one unit forward, so accumulating the digit sums gives the quotient directly.","expectedAnswer":"Because 10 = 9+1 so each digit carries one unit to the next position"},
  ],
}

for ch, new_qs in NEW_QUESTIONS.items():
    path = BASE / f"{ch}.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    for q in new_qs:
        q["chapterCode"] = ch
    data["questionPool"].extend(new_qs)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    pool = data["questionPool"]
    id_counts = collections.Counter(q.get("questionId", "") for q in pool)
    dups = {k: v for k, v in id_counts.items() if v > 1}
    groups = sorted(set(q.get("exerciseGroup") for q in pool))
    print(f"{ch}: {len(pool)} Qs  groups={groups}  dups={dups or 'none'}")

print("\nDone.")
