/**
 * Vaani Level 5: Sentence Construction (30 lessons)
 * Focus: Simple sentences and word combinations
 * Progression: Single words → Word pairs → Simple sentences
 * Concept: Real-world Hindi communication (2-4 words per sentence)
 * Total: 30 lessons across 2 chapters
 */

export interface Level5Word {
  hindi: string;
  roman: string;
  english: string;
}

export interface Level5Seed {
  id: string;
  chapterId: string;
  chapterTitle: string;
  title: string;
  category: string;
  skill: string;
  sentence: string;
  sentenceRoman: string;
  sentenceEnglish: string;
  words: Level5Word[];
  assetPath: string;
  durationMin?: number;
  summary: string;
  prompt: string;
  mcqs?: Array<{ question: string; options: string[]; answer: string }>;
}

// ============================================
// CHAPTER 1: TWO-WORD SENTENCES (15 LESSONS)
// ============================================

export const LEVEL_5_DATA: Level5Seed[] = [
  {
    id: "L5-C01-L01",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "नमस्ते भाई - Hello brother",
    category: "Greetings",
    skill: "Basic Greeting",
    sentence: "नमस्ते भाई।",
    sentenceRoman: "Namaste bhai.",
    sentenceEnglish: "Hello brother.",
    words: [
      { hindi: "नमस्ते", roman: "namaste", english: "greetings/hello" },
      { hindi: "भाई", roman: "bhai", english: "brother" },
    ],
    assetPath: "/assets/gemini/vaani_l5_namaste_bhai_1777200001.png",
    summary: "Learn the basic 2-word greeting in Hindi.",
    prompt: "नमस्ते is respectful - भाई means brother!",
    mcqs: [
      {
        question: "What does नमस्ते mean?",
        options: ["Goodbye", "Greetings", "Thank you", "Please"],
        answer: "Greetings",
      },
    ],
  },
  {
    id: "L5-C01-L02",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "आप कैसे? - How are you?",
    category: "Polite Questions",
    skill: "Simple Questions",
    sentence: "आप कैसे?",
    sentenceRoman: "Aap kaise?",
    sentenceEnglish: "How are you? (formal)",
    words: [
      { hindi: "आप", roman: "aap", english: "you (formal/respectful)" },
      { hindi: "कैसे", roman: "kaise", english: "how" },
    ],
    assetPath: "/assets/gemini/vaani_l5_aap_kaise_1777200025.png",
    summary: "Ask someone how they are politely.",
    prompt: "आप is respectful - कैसे means how!",
    mcqs: [
      {
        question: "Which word means 'how'?",
        options: ["आप", "कैसे", "क्या", "कहाँ"],
        answer: "कैसे",
      },
    ],
  },
  {
    id: "L5-C01-L03",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "मैं ठीक - I am fine",
    category: "Status Responses",
    skill: "Answering Questions",
    sentence: "मैं ठीक।",
    sentenceRoman: "Main theek.",
    sentenceEnglish: "I am fine.",
    words: [
      { hindi: "मैं", roman: "main", english: "I" },
      { hindi: "ठीक", roman: "theek", english: "fine/okay" },
    ],
    assetPath: "/assets/gemini/vaani_l5_main_theek_1777200049.png",
    summary: "Respond to how-are-you questions.",
    prompt: "मैं means I - ठीक means fine!",
    mcqs: [
      {
        question: "What does ठीक mean?",
        options: ["Sad", "Happy", "Fine/okay", "Angry"],
        answer: "Fine/okay",
      },
    ],
  },
  {
    id: "L5-C01-L04",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "धन्यवाद भाई - Thank you brother",
    category: "Politeness",
    skill: "Gratitude",
    sentence: "धन्यवाद भाई।",
    sentenceRoman: "Dhanyavaad bhai.",
    sentenceEnglish: "Thank you brother.",
    words: [
      { hindi: "धन्यवाद", roman: "dhanyavaad", english: "thank you" },
      { hindi: "भाई", roman: "bhai", english: "brother" },
    ],
    assetPath: "/assets/gemini/vaani_l5_dhanyavaad_bhai_1777200073.png",
    summary: "Express gratitude with respect.",
    prompt: "धन्यवाद means thank you!",
  },
  {
    id: "L5-C01-L05",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "कृपया बैठिए - Please sit",
    category: "Requests",
    skill: "Polite Requests",
    sentence: "कृपया बैठिए।",
    sentenceRoman: "Kripaya baithiye.",
    sentenceEnglish: "Please sit down.",
    words: [
      { hindi: "कृपया", roman: "kripaya", english: "please" },
      { hindi: "बैठिए", roman: "baithiye", english: "sit (formal)" },
    ],
    assetPath: "/assets/gemini/vaani_l5_kripaya_baithiye_1777200097.png",
    summary: "Make polite requests in formal Hindi.",
    prompt: "कृपया makes requests polite!",
  },
  {
    id: "L5-C01-L06",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "मेरा नाम - My name",
    category: "Introduction",
    skill: "Self-Introduction",
    sentence: "मेरा नाम राज।",
    sentenceRoman: "Mera naam Raj.",
    sentenceEnglish: "My name is Raj.",
    words: [
      { hindi: "मेरा", roman: "mera", english: "my" },
      { hindi: "नाम", roman: "naam", english: "name" },
      { hindi: "राज", roman: "raj", english: "Raj (name)" },
    ],
    assetPath: "/assets/gemini/vaani_l5_mera_naam_1777200121.png",
    summary: "Introduce yourself with your name.",
    prompt: "नाम means name!",
  },
  {
    id: "L5-C01-L07",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "आपका नाम - Your name",
    category: "Introduction",
    skill: "Asking Names",
    sentence: "आपका नाम क्या है?",
    sentenceRoman: "Aapka naam kya hai?",
    sentenceEnglish: "What is your name?",
    words: [
      { hindi: "आपका", roman: "aapka", english: "your (formal)" },
      { hindi: "नाम", roman: "naam", english: "name" },
      { hindi: "क्या", roman: "kya", english: "what" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_aapka_naam_1777200145.png",
    summary: "Ask someone's name politely.",
    prompt: "क्या means what!",
  },
  {
    id: "L5-C01-L08",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "मुझे भूख है - I am hungry",
    category: "Needs",
    skill: "Expressing Hunger",
    sentence: "मुझे भूख है।",
    sentenceRoman: "Mujhe bhookh hai.",
    sentenceEnglish: "I am hungry.",
    words: [
      { hindi: "मुझे", roman: "mujhe", english: "me (indirect)" },
      { hindi: "भूख", roman: "bhookh", english: "hunger" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_mujhe_bhookh_1777200169.png",
    summary: "Express basic needs in Hindi.",
    prompt: "भूख means hunger!",
  },
  {
    id: "L5-C01-L09",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "यह एक किताब है - This is a book",
    category: "Objects",
    skill: "Identifying Things",
    sentence: "यह एक किताब है।",
    sentenceRoman: "Yeh ek kitaab hai.",
    sentenceEnglish: "This is a book.",
    words: [
      { hindi: "यह", roman: "yeh", english: "this" },
      { hindi: "एक", roman: "ek", english: "one/a" },
      { hindi: "किताब", roman: "kitaab", english: "book" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_yeh_kitaab_1777200193.png",
    summary: "Identify objects with simple sentences.",
    prompt: "यह means this!",
  },
  {
    id: "L5-C01-L10",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "मुझे पसंद है - I like",
    category: "Preferences",
    skill: "Expressing Likes",
    sentence: "मुझे आम पसंद है।",
    sentenceRoman: "Mujhe aam pasand hai.",
    sentenceEnglish: "I like mangoes.",
    words: [
      { hindi: "मुझे", roman: "mujhe", english: "me" },
      { hindi: "आम", roman: "aam", english: "mango" },
      { hindi: "पसंद", roman: "pasand", english: "liked" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_mujhe_pasand_1777200217.png",
    summary: "Express your preferences in Hindi.",
    prompt: "पसंद means like or enjoy!",
  },
  {
    id: "L5-C01-L11",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "मैं स्कूल जाता हूँ - I go to school",
    category: "Actions",
    skill: "Daily Actions",
    sentence: "मैं स्कूल जाता हूँ।",
    sentenceRoman: "Main school jata hoon.",
    sentenceEnglish: "I go to school. (male)",
    words: [
      { hindi: "मैं", roman: "main", english: "I" },
      { hindi: "स्कूल", roman: "school", english: "school" },
      { hindi: "जाता", roman: "jata", english: "go (masculine)" },
      { hindi: "हूँ", roman: "hoon", english: "am" },
    ],
    assetPath: "/assets/gemini/vaani_l5_main_school_1777200241.png",
    summary: "Describe daily actions and routines.",
    prompt: "जाता means go!",
  },
  {
    id: "L5-C01-L12",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "क्या आप मदद कर सकते हैं? - Can you help me?",
    category: "Requests",
    skill: "Asking for Help",
    sentence: "क्या आप मेरी मदद कर सकते हैं?",
    sentenceRoman: "Kya aap meri madad kar sakte hain?",
    sentenceEnglish: "Can you help me?",
    words: [
      { hindi: "क्या", roman: "kya", english: "can/question" },
      { hindi: "आप", roman: "aap", english: "you (formal)" },
      { hindi: "मेरी", roman: "meri", english: "my" },
      { hindi: "मदद", roman: "madad", english: "help" },
      { hindi: "कर", roman: "kar", english: "do" },
      { hindi: "सकते", roman: "sakte", english: "able/can" },
      { hindi: "हैं", roman: "hain", english: "are" },
    ],
    assetPath: "/assets/gemini/vaani_l5_madad_1777200265.png",
    summary: "Ask for help politely in Hindi.",
    prompt: "मदद means help!",
  },
  {
    id: "L5-C01-L13",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "यह पानी है - This is water",
    category: "Objects",
    skill: "Identifying Liquids",
    sentence: "यह पानी है।",
    sentenceRoman: "Yeh pani hai.",
    sentenceEnglish: "This is water.",
    words: [
      { hindi: "यह", roman: "yeh", english: "this" },
      { hindi: "पानी", roman: "pani", english: "water" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_yeh_pani_1777200289.png",
    summary: "Identify everyday liquids.",
    prompt: "पानी means water!",
  },
  {
    id: "L5-C01-L14",
    chapterId: "C01",
    chapterTitle: "Basic Sentences (2–5 words)",
    title: "मुझे प्यास है - I am thirsty",
    category: "Needs",
    skill: "Expressing Thirst",
    sentence: "मुझे प्यास है।",
    sentenceRoman: "Mujhe pyas hai.",
    sentenceEnglish: "I am thirsty.",
    words: [
      { hindi: "मुझे", roman: "mujhe", english: "me" },
      { hindi: "प्यास", roman: "pyas", english: "thirst" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_mujhe_pyas_1777200313.png",
    summary: "Express the need for water.",
    prompt: "प्यास means thirst!",
  },
  {
    id: "L5-C01-L15",
    chapterId: "C01",
    chapterTitle: "Basic Sentences — Consolidation",
    title: "Review - Simple 2-Word Sentences",
    category: "Consolidation",
    skill: "Basic Mastery",
    sentence: "मैं खुश हूँ।",
    sentenceRoman: "Main khush hoon.",
    sentenceEnglish: "I am happy.",
    words: [
      { hindi: "मैं", roman: "main", english: "I" },
      { hindi: "खुश", roman: "khush", english: "happy" },
      { hindi: "हूँ", roman: "hoon", english: "am" },
    ],
    assetPath: "/assets/gemini/vaani_l5_main_khush_1777200337.png",
    summary: "You've mastered basic 2-word sentences!",
    prompt: "खुश means happy!",
  },

  // ============================================
  // CHAPTER 2: THREE-FOUR WORD SENTENCES (15 LESSONS)
  // ============================================

  {
    id: "L5-C02-L01",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "मेरा नाम राज है - My name is Raj",
    category: "Introduction",
    skill: "Full Introduction",
    sentence: "मेरा नाम राज है।",
    sentenceRoman: "Mera naam Raj hai.",
    sentenceEnglish: "My name is Raj.",
    words: [
      { hindi: "मेरा", roman: "mera", english: "my" },
      { hindi: "नाम", roman: "naam", english: "name" },
      { hindi: "राज", roman: "raj", english: "Raj" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_intro_full_1777200361.png",
    summary: "Complete introduction with name.",
    prompt: "है means is!",
  },
  {
    id: "L5-C02-L02",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "मुझे एक किताब चाहिए - I need a book",
    category: "Requests",
    skill: "Expressing Needs",
    sentence: "मुझे एक किताब चाहिए।",
    sentenceRoman: "Mujhe ek kitaab chahiye.",
    sentenceEnglish: "I need a book.",
    words: [
      { hindi: "मुझे", roman: "mujhe", english: "me" },
      { hindi: "एक", roman: "ek", english: "one/a" },
      { hindi: "किताब", roman: "kitaab", english: "book" },
      { hindi: "चाहिए", roman: "chahiye", english: "need" },
    ],
    assetPath: "/assets/gemini/vaani_l5_need_book_1777200385.png",
    summary: "Express specific needs clearly.",
    prompt: "चाहिए means need!",
  },
  {
    id: "L5-C02-L03",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "राज एक लड़का है - Raj is a boy",
    category: "Description",
    skill: "Describing People",
    sentence: "राज एक लड़का है।",
    sentenceRoman: "Raj ek ladka hai.",
    sentenceEnglish: "Raj is a boy.",
    words: [
      { hindi: "राज", roman: "raj", english: "Raj" },
      { hindi: "एक", roman: "ek", english: "a" },
      { hindi: "लड़का", roman: "ladka", english: "boy" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_raj_boy_1777200409.png",
    summary: "Describe people and their characteristics.",
    prompt: "लड़का means boy!",
  },
  {
    id: "L5-C02-L04",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "यह एक पेड़ है - This is a tree",
    category: "Nature",
    skill: "Identifying Nature",
    sentence: "यह एक पेड़ है।",
    sentenceRoman: "Yeh ek ped hai.",
    sentenceEnglish: "This is a tree.",
    words: [
      { hindi: "यह", roman: "yeh", english: "this" },
      { hindi: "एक", roman: "ek", english: "a" },
      { hindi: "पेड़", roman: "ped", english: "tree" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_ped_1777200433.png",
    summary: "Identify objects in nature.",
    prompt: "पेड़ means tree!",
  },
  {
    id: "L5-C02-L05",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "मुझे केला बहुत पसंद है - I really like bananas",
    category: "Preferences",
    skill: "Emphatic Preference",
    sentence: "मुझे केला बहुत पसंद है।",
    sentenceRoman: "Mujhe kela bahut pasand hai.",
    sentenceEnglish: "I really like bananas.",
    words: [
      { hindi: "मुझे", roman: "mujhe", english: "me" },
      { hindi: "केला", roman: "kela", english: "banana" },
      { hindi: "बहुत", roman: "bahut", english: "very/very much" },
      { hindi: "पसंद", roman: "pasand", english: "liked" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_kela_pasand_1777200457.png",
    summary: "Express strong preferences.",
    prompt: "बहुत means very!",
  },
  {
    id: "L5-C02-L06",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "मैं हर दिन पढ़ता हूँ - I read every day",
    category: "Routine",
    skill: "Daily Routine",
    sentence: "मैं हर दिन पढ़ता हूँ।",
    sentenceRoman: "Main har din padhta hoon.",
    sentenceEnglish: "I read every day.",
    words: [
      { hindi: "मैं", roman: "main", english: "I" },
      { hindi: "हर", roman: "har", english: "every" },
      { hindi: "दिन", roman: "din", english: "day" },
      { hindi: "पढ़ता", roman: "padhta", english: "read" },
      { hindi: "हूँ", roman: "hoon", english: "am" },
    ],
    assetPath: "/assets/gemini/vaani_l5_reading_routine_1777200481.png",
    summary: "Describe daily routines.",
    prompt: "हर means every!",
  },
  {
    id: "L5-C02-L07",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "घर में एक बिल्ली है - There is a cat in the house",
    category: "Location",
    skill: "Location Description",
    sentence: "घर में एक बिल्ली है।",
    sentenceRoman: "Ghar mein ek billi hai.",
    sentenceEnglish: "There is a cat in the house.",
    words: [
      { hindi: "घर", roman: "ghar", english: "house" },
      { hindi: "में", roman: "mein", english: "in" },
      { hindi: "एक", roman: "ek", english: "a" },
      { hindi: "बिल्ली", roman: "billi", english: "cat" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_ghar_billi_1777200505.png",
    summary: "Describe locations and what's in them.",
    prompt: "में means in!",
  },
  {
    id: "L5-C02-L08",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "आप कौन हैं? - Who are you?",
    category: "Identity",
    skill: "Asking Identity",
    sentence: "आप कौन हैं?",
    sentenceRoman: "Aap kaun hain?",
    sentenceEnglish: "Who are you?",
    words: [
      { hindi: "आप", roman: "aap", english: "you (formal)" },
      { hindi: "कौन", roman: "kaun", english: "who" },
      { hindi: "हैं", roman: "hain", english: "are" },
    ],
    assetPath: "/assets/gemini/vaani_l5_kaun_ho_1777200529.png",
    summary: "Ask about someone's identity.",
    prompt: "कौन means who!",
  },
  {
    id: "L5-C02-L09",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "मैं दिल्ली में रहता हूँ - I live in Delhi",
    category: "Location",
    skill: "Telling Location",
    sentence: "मैं दिल्ली में रहता हूँ।",
    sentenceRoman: "Main Delhi mein rehta hoon.",
    sentenceEnglish: "I live in Delhi.",
    words: [
      { hindi: "मैं", roman: "main", english: "I" },
      { hindi: "दिल्ली", roman: "delhi", english: "Delhi" },
      { hindi: "में", roman: "mein", english: "in" },
      { hindi: "रहता", roman: "rehta", english: "live" },
      { hindi: "हूँ", roman: "hoon", english: "am" },
    ],
    assetPath: "/assets/gemini/vaani_l5_delhi_rehta_1777200553.png",
    summary: "Tell where you live.",
    prompt: "रहता means live!",
  },
  {
    id: "L5-C02-L10",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "आज का मौसम ठीक है - Today's weather is nice",
    category: "Weather",
    skill: "Describing Weather",
    sentence: "आज का मौसम ठीक है।",
    sentenceRoman: "Aaj ka mausam theek hai.",
    sentenceEnglish: "Today's weather is nice.",
    words: [
      { hindi: "आज", roman: "aaj", english: "today" },
      { hindi: "का", roman: "ka", english: "'s (possessive)" },
      { hindi: "मौसम", roman: "mausam", english: "weather" },
      { hindi: "ठीक", roman: "theek", english: "nice/okay" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_mausam_1777200577.png",
    summary: "Describe weather and seasons.",
    prompt: "मौसम means weather!",
  },
  {
    id: "L5-C02-L11",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "मेरा दोस्त बहुत अच्छा है - My friend is very good",
    category: "Friendship",
    skill: "Describing Friends",
    sentence: "मेरा दोस्त बहुत अच्छा है।",
    sentenceRoman: "Mera dost bahut acha hai.",
    sentenceEnglish: "My friend is very good.",
    words: [
      { hindi: "मेरा", roman: "mera", english: "my" },
      { hindi: "दोस्त", roman: "dost", english: "friend" },
      { hindi: "बहुत", roman: "bahut", english: "very" },
      { hindi: "अच्छा", roman: "acha", english: "good" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_dost_1777200601.png",
    summary: "Describe your friends.",
    prompt: "दोस्त means friend!",
  },
  {
    id: "L5-C02-L12",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "कल स्कूल की छुट्टी है - School is closed tomorrow",
    category: "Time",
    skill: "Telling Days",
    sentence: "कल स्कूल की छुट्टी है।",
    sentenceRoman: "Kal school ki chhuti hai.",
    sentenceEnglish: "School is closed tomorrow.",
    words: [
      { hindi: "कल", roman: "kal", english: "tomorrow/yesterday" },
      { hindi: "स्कूल", roman: "school", english: "school" },
      { hindi: "की", roman: "ki", english: "'s (possessive fem)" },
      { hindi: "छुट्टी", roman: "chhuti", english: "holiday/closed" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_chhuti_1777200625.png",
    summary: "Tell about holidays and days off.",
    prompt: "कल means tomorrow/yesterday!",
  },
  {
    id: "L5-C02-L13",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "मैं खेलना बहुत पसंद करता हूँ - I really like to play",
    category: "Activities",
    skill: "Expressing Likes",
    sentence: "मैं खेलना बहुत पसंद करता हूँ।",
    sentenceRoman: "Main khalna bahut pasand karta hoon.",
    sentenceEnglish: "I really like to play.",
    words: [
      { hindi: "मैं", roman: "main", english: "I" },
      { hindi: "खेलना", roman: "khalna", english: "to play" },
      { hindi: "बहुत", roman: "bahut", english: "very" },
      { hindi: "पसंद", roman: "pasand", english: "like" },
      { hindi: "करता", roman: "karta", english: "do" },
      { hindi: "हूँ", roman: "hoon", english: "am" },
    ],
    assetPath: "/assets/gemini/vaani_l5_khalna_1777200649.png",
    summary: "Express likes for activities.",
    prompt: "खेलना means to play!",
  },
  {
    id: "L5-C02-L14",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences",
    title: "क्या आप हिंदी बोल सकते हैं? - Can you speak Hindi?",
    category: "Ability",
    skill: "Asking Ability",
    sentence: "क्या आप हिंदी बोल सकते हैं?",
    sentenceRoman: "Kya aap hindi bol sakte hain?",
    sentenceEnglish: "Can you speak Hindi?",
    words: [
      { hindi: "क्या", roman: "kya", english: "can/question" },
      { hindi: "आप", roman: "aap", english: "you (formal)" },
      { hindi: "हिंदी", roman: "hindi", english: "Hindi" },
      { hindi: "बोल", roman: "bol", english: "speak" },
      { hindi: "सकते", roman: "sakte", english: "able" },
      { hindi: "हैं", roman: "hain", english: "are" },
    ],
    assetPath: "/assets/gemini/vaani_l5_hindi_bol_1777200673.png",
    summary: "Ask about language ability.",
    prompt: "बोल means speak!",
  },
  {
    id: "L5-C02-L15",
    chapterId: "C02",
    chapterTitle: "Simple 3-4 Word Sentences - Mastery",
    title: "Mastery - Full Sentences",
    category: "Consolidation",
    skill: "Sentence Mastery",
    sentence: "मेरा परिवार बहुत खुश है।",
    sentenceRoman: "Mera parivaar bahut khush hai.",
    sentenceEnglish: "My family is very happy.",
    words: [
      { hindi: "मेरा", roman: "mera", english: "my" },
      { hindi: "परिवार", roman: "parivaar", english: "family" },
      { hindi: "बहुत", roman: "bahut", english: "very" },
      { hindi: "खुश", roman: "khush", english: "happy" },
      { hindi: "है", roman: "hai", english: "is" },
    ],
    assetPath: "/assets/gemini/vaani_l5_mastery_final_1777200697.png",
    summary: "You've mastered simple sentence construction!",
    prompt: "परिवार means family!",
  },
];

// Roman transliteration map for Level 5
export const LEVEL_5_ROMAN_MAP: Record<string, string> = {
  "L5-C01-L01": "namaste-bhai",
  "L5-C01-L02": "aap-kaise",
  "L5-C01-L03": "main-theek",
  "L5-C01-L04": "dhanyavaad-bhai",
  "L5-C01-L05": "kripaya-baithiye",
  "L5-C01-L06": "mera-naam",
  "L5-C01-L07": "aapka-naam-kya",
  "L5-C01-L08": "mujhe-bhookh",
  "L5-C01-L09": "yeh-kitaab",
  "L5-C01-L10": "mujhe-pasand",
  "L5-C01-L11": "main-school-jata",
  "L5-C01-L12": "kya-madad-kar-sakte",
  "L5-C01-L13": "yeh-pani",
  "L5-C01-L14": "mujhe-pyas",
  "L5-C01-L15": "main-khush",
  "L5-C02-L01": "mera-naam-raj-hai",
  "L5-C02-L02": "mujhe-kitaab-chahiye",
  "L5-C02-L03": "raj-ladka-hai",
  "L5-C02-L04": "yeh-ped-hai",
  "L5-C02-L05": "kela-bahut-pasand",
  "L5-C02-L06": "main-har-din-padhta",
  "L5-C02-L07": "ghar-mein-billi",
  "L5-C02-L08": "aap-kaun-hain",
  "L5-C02-L09": "main-delhi-rehta",
  "L5-C02-L10": "aaj-mausam-theek",
  "L5-C02-L11": "mera-dost-acha",
  "L5-C02-L12": "kal-chhuti-hai",
  "L5-C02-L13": "khalna-pasand-karta",
  "L5-C02-L14": "hindi-bol-sakte",
  "L5-C02-L15": "parivaar-khush",
};

// Re-export for compatibility
export const vaaniLevel5Data = LEVEL_5_DATA;
