/**
 * Vaani Level 3: Consonant Conjuncts (38 lessons)
 * Focus: Two consonants joined together (consonant clusters)
 * Progression: consonant1 + consonant2 = combined character
 * Concept: Halant (्) joins consonants without vowel between them
 * Total: 38 lessons across 3 chapters
 */

export interface Level3Seed {
  id: string;
  chapterId: string;
  chapterTitle: string;
  title: string;
  category: string;
  skill: string;
  consonant1: string;
  consonant1SoundRoman?: string;
  consonant2: string;
  consonant2SoundRoman?: string;
  combinedChar: string;
  combinedSoundRoman?: string;
  halantForm: string;
  wordHindi: string;
  wordEnglish: string;
  wordRoman: string;
  assetPath: string;
  durationMin?: number;
  summary: string;
  prompt: string;
}

// ============================================
// CHAPTER 1: BASIC CONJUNCTS (14 LESSONS)
// ============================================

export const LEVEL_3_DATA: Level3Seed[] = [
  {
    id: "L3-C01-L01",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "क्त - Ka-Ta Conjunct",
    category: "Conjunct Formation",
    skill: "Halant Introduction",
    consonant1: "क",
    consonant1SoundRoman: "ka",
    consonant2: "त",
    consonant2SoundRoman: "ta",
    combinedChar: "क्त",
    combinedSoundRoman: "kta",
    halantForm: "क्",
    wordHindi: "रक्त",
    wordEnglish: "Blood",
    wordRoman: "rakta",
    assetPath: "/assets/gemini/vaani_l3_kta_conjunct_1777155001.png",
    summary: "First conjunct - when consonants touch through halant without a vowel.",
    prompt: "क् + त = क्त. The halant removes the vowel between them!",
  },
  {
    id: "L3-C01-L02",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "न्द - Na-Da Conjunct",
    category: "Conjunct Formation",
    skill: "Nasal Clusters",
    consonant1: "न",
    consonant1SoundRoman: "na",
    consonant2: "द",
    consonant2SoundRoman: "da",
    combinedChar: "न्द",
    combinedSoundRoman: "nda",
    halantForm: "न्",
    wordHindi: "गन्दा",
    wordEnglish: "Dirty",
    wordRoman: "ganda",
    assetPath: "/assets/gemini/vaani_l3_nda_walrus_1777155025.png",
    summary: "Nasal consonants create flowing conjuncts that sound connected.",
    prompt: "न्द flows smoothly - say it as one connected sound!",
  },
  {
    id: "L3-C01-L03",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "म्प - Ma-Pa Conjunct",
    category: "Conjunct Formation",
    skill: "Stop Consonant Pairs",
    consonant1: "म",
    consonant1SoundRoman: "ma",
    consonant2: "प",
    consonant2SoundRoman: "pa",
    combinedChar: "म्प",
    combinedSoundRoman: "mpa",
    halantForm: "म्",
    wordHindi: "सम्पन्न",
    wordEnglish: "Accomplished",
    wordRoman: "sampann",
    assetPath: "/assets/gemini/vaani_l3_mpa_vibration_1777155049.png",
    summary: "Stop consonants blend to create stopping-then-releasing sounds.",
    prompt: "म्प - notice the stop and release in the blend!",
  },
  {
    id: "L3-C01-L04",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "ष्ठ - Sha-Tha Conjunct",
    category: "Conjunct Formation",
    skill: "Retroflex Clusters",
    consonant1: "ष",
    consonant1SoundRoman: "sha",
    consonant2: "ठ",
    consonant2SoundRoman: "tha",
    combinedChar: "ष्ठ",
    combinedSoundRoman: "sthha",
    halantForm: "ष्",
    wordHindi: "श्रेष्ठ",
    wordEnglish: "Superior",
    wordRoman: "shreshtha",
    assetPath: "/assets/gemini/vaani_l3_shtha_rigid_1777155073.png",
    summary: "Retroflex sounds are made with tongue curled back.",
    prompt: "ष्ठ - curl your tongue back for retroflex sounds!",
  },
  {
    id: "L3-C01-L05",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "ल्ल - La-La Conjunct",
    category: "Conjunct Formation",
    skill: "Double Consonants",
    consonant1: "ल",
    consonant1SoundRoman: "la",
    consonant2: "ल",
    consonant2SoundRoman: "la",
    combinedChar: "ल्ल",
    combinedSoundRoman: "lla",
    halantForm: "ल्",
    wordHindi: "उल्लू",
    wordEnglish: "Owl",
    wordRoman: "ulloo",
    assetPath: "/assets/gemini/vaani_l3_lla_cluster_1777155097.png",
    summary: "Same consonant twice creates a doubled sound.",
    prompt: "ल्ल - say it like a long rolling 'l' sound!",
  },
  {
    id: "L3-C01-L06",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "र्ज - Ra-Ja Conjunct",
    category: "Conjunct Formation",
    skill: "Semi-Vowel Blends",
    consonant1: "र",
    consonant1SoundRoman: "ra",
    consonant2: "ज",
    consonant2SoundRoman: "ja",
    combinedChar: "र्ज",
    combinedSoundRoman: "rja",
    halantForm: "र्",
    wordHindi: "अर्जुन",
    wordEnglish: "Name (Archer)",
    wordRoman: "arjun",
    assetPath: "/assets/gemini/vaani_l3_rja_archer_1777155121.png",
    summary: "Semi-vowels like र blend smoothly with stops.",
    prompt: "र्ज flows like a river meeting a stone!",
  },
  {
    id: "L3-C01-L07",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "व्य - Va-Ya Conjunct",
    category: "Conjunct Formation",
    skill: "Glide Combinations",
    consonant1: "व",
    consonant1SoundRoman: "va",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "व्य",
    combinedSoundRoman: "vya",
    halantForm: "व्",
    wordHindi: "व्यक्ति",
    wordEnglish: "Person",
    wordRoman: "vyakti",
    assetPath: "/assets/gemini/vaani_l3_vya_person_1777155145.png",
    summary: "Gliding consonants create smooth transitions.",
    prompt: "व्य slides smoothly from one sound to the next!",
  },
  {
    id: "L3-C01-L08",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "त्र - Ta-Ra Conjunct",
    category: "Conjunct Formation",
    skill: "Three-Part Blends",
    consonant1: "त",
    consonant1SoundRoman: "ta",
    consonant2: "र",
    consonant2SoundRoman: "ra",
    combinedChar: "त्र",
    combinedSoundRoman: "tra",
    halantForm: "त्",
    wordHindi: "त्रिमुखी",
    wordEnglish: "Three-faced",
    wordRoman: "trimukhi",
    assetPath: "/assets/gemini/vaani_l3_tra_threefaced_1777155169.png",
    summary: "त्र is so common it almost feels like a single character!",
    prompt: "त्र - this blend appears in many Hindi words!",
  },
  {
    id: "L3-C01-L09",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "द्र - Da-Ra Conjunct",
    category: "Conjunct Formation",
    skill: "Aspirate Blends",
    consonant1: "द",
    consonant1SoundRoman: "da",
    consonant2: "र",
    consonant2SoundRoman: "ra",
    combinedChar: "द्र",
    combinedSoundRoman: "dra",
    halantForm: "द्",
    wordHindi: "द्रव्य",
    wordEnglish: "Matter",
    wordRoman: "dravya",
    assetPath: "/assets/gemini/vaani_l3_dra_matter_1777155193.png",
    summary: "Aspirates with र create dramatic consonant clusters.",
    prompt: "द्र flows with energy - feel the blend!",
  },
  {
    id: "L3-C01-L10",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "क्ष - Ksha Conjunct",
    category: "Conjunct Formation",
    skill: "Historic Clusters",
    consonant1: "क",
    consonant1SoundRoman: "ka",
    consonant2: "ष",
    consonant2SoundRoman: "sha",
    combinedChar: "क्ष",
    combinedSoundRoman: "ksha",
    halantForm: "क्",
    wordHindi: "क्षेत्र",
    wordEnglish: "Region",
    wordRoman: "kshetra",
    assetPath: "/assets/gemini/vaani_l3_ksha_region_1777155217.png",
    summary: "क्ष is historically significant and appears in many classical words.",
    prompt: "क्ष is a joined sound. Listen for how क् and ष come together.",
  },
  {
    id: "L3-C01-L11",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "ज्ञ - Gya Conjunct",
    category: "Conjunct Formation",
    skill: "Philosophical Sounds",
    consonant1: "ज",
    consonant1SoundRoman: "ja",
    consonant2: "ञ",
    consonant2SoundRoman: "nya",
    combinedChar: "ज्ञ",
    combinedSoundRoman: "gya",
    halantForm: "ज्",
    wordHindi: "ज्ञान",
    wordEnglish: "Knowledge",
    wordRoman: "gyaan",
    assetPath: "/assets/gemini/vaani_l3_gnya_knowledge_1777155241.png",
    summary: "ज्ञ has deep philosophical meaning.",
    prompt: "ज्ञ - the sound of wisdom!",
  },
  {
    id: "L3-C01-L12",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "श्र - Sha-Ra Conjunct",
    category: "Conjunct Formation",
    skill: "Sibilant Blends",
    consonant1: "श",
    consonant1SoundRoman: "sha",
    consonant2: "र",
    consonant2SoundRoman: "ra",
    combinedChar: "श्र",
    combinedSoundRoman: "shra",
    halantForm: "श्",
    wordHindi: "श्रीमान",
    wordEnglish: "Honorable",
    wordRoman: "shriman",
    assetPath: "/assets/gemini/vaani_l3_shra_honorable_1777155265.png",
    summary: "श्र is elegant and formal.",
    prompt: "श्र sounds respectful!",
  },
  {
    id: "L3-C01-L13",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "स्त - Sa-Ta Conjunct",
    category: "Conjunct Formation",
    skill: "Common Blends",
    consonant1: "स",
    consonant1SoundRoman: "sa",
    consonant2: "त",
    consonant2SoundRoman: "ta",
    combinedChar: "स्त",
    combinedSoundRoman: "sta",
    halantForm: "स्",
    wordHindi: "स्तर",
    wordEnglish: "Level",
    wordRoman: "star",
    assetPath: "/assets/gemini/vaani_l3_sta_level_1777155289.png",
    summary: "स्त is a very common conjunct in Hindi.",
    prompt: "स्त - appears in many everyday words!",
  },
  {
    id: "L3-C01-L14",
    chapterId: "C01",
    chapterTitle: "Consonant Blends Basics",
    title: "Conjunct Review Game",
    category: "Consolidation",
    skill: "Basic Mastery",
    consonant1: "क",
    consonant1SoundRoman: "ka",
    consonant2: "त",
    consonant2SoundRoman: "ta",
    combinedChar: "क्त",
    combinedSoundRoman: "kta",
    halantForm: "क्",
    wordHindi: "अक्षर",
    wordEnglish: "Letter",
    wordRoman: "akshar",
    assetPath: "/assets/gemini/vaani_l3_review1_1777155313.png",
    summary: "Practice conjunct recognition and pronunciation.",
    prompt: "Can you identify all the conjuncts?",
  },

  // ============================================
  // CHAPTER 2: ADVANCED CONJUNCTS (12 LESSONS)
  // ============================================

  {
    id: "L3-C02-L01",
    chapterId: "C02",
    chapterTitle: "Advanced Consonant Clusters",
    title: "ञ्च - Nya-Cha Conjunct",
    category: "Complex Conjunct",
    skill: "Nasal Blends",
    consonant1: "ञ",
    consonant1SoundRoman: "nya",
    consonant2: "च",
    consonant2SoundRoman: "cha",
    combinedChar: "ञ्च",
    combinedSoundRoman: "ncha",
    halantForm: "ञ्",
    wordHindi: "अञ्चल",
    wordEnglish: "End of saree",
    wordRoman: "anchal",
    assetPath: "/assets/gemini/vaani_l3_ncha_saree_1777155337.png",
    summary: "Nasal followed by affricate creates soft blends.",
    prompt: "ञ्च - soft and flowing!",
  },
  {
    id: "L3-C02-L02",
    chapterId: "C02",
    chapterTitle: "Advanced Consonant Clusters",
    title: "ण्ड - Na-Da (retroflex) Conjunct",
    category: "Complex Conjunct",
    skill: "Retroflex Blends",
    consonant1: "ण",
    consonant1SoundRoman: "na",
    consonant2: "ड",
    consonant2SoundRoman: "da",
    combinedChar: "ण्ड",
    combinedSoundRoman: "nda",
    halantForm: "ण्",
    wordHindi: "कण्ड",
    wordEnglish: "Section",
    wordRoman: "kand",
    assetPath: "/assets/gemini/vaani_l3_nda_retrofit_1777155361.png",
    summary: "Retroflex nasal creates deep sounds.",
    prompt: "ण्ड - tongue curled back!",
  },
  {
    id: "L3-C02-L03",
    chapterId: "C02",
    chapterTitle: "Advanced Consonant Clusters",
    title: "त्य - Ta-Ya Conjunct",
    category: "Complex Conjunct",
    skill: "Glide Clusters",
    consonant1: "त",
    consonant1SoundRoman: "ta",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "त्य",
    combinedSoundRoman: "tya",
    halantForm: "त्",
    wordHindi: "त्योहार",
    wordEnglish: "Festival",
    wordRoman: "tyohaar",
    assetPath: "/assets/gemini/vaani_l3_tya_festival_1777155385.png",
    summary: "Stops followed by glides create smooth transitions.",
    prompt: "त्य - smooth transition!",
  },
  {
    id: "L3-C02-L04",
    chapterId: "C02",
    chapterTitle: "Advanced Consonant Clusters",
    title: "द्य - Da-Ya Conjunct",
    category: "Complex Conjunct",
    skill: "Glide Clusters",
    consonant1: "द",
    consonant1SoundRoman: "da",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "द्य",
    combinedSoundRoman: "dya",
    halantForm: "द्",
    wordHindi: "अद्य",
    wordEnglish: "Today",
    wordRoman: "adya",
    assetPath: "/assets/gemini/vaani_l3_dya_today_1777155409.png",
    summary: "Aspirated stop with glide.",
    prompt: "द्य - smooth and quick!",
  },
  {
    id: "L3-C02-L05",
    chapterId: "C02",
    chapterTitle: "Advanced Consonant Clusters",
    title: "प्र - Pa-Ra Conjunct",
    category: "Complex Conjunct",
    skill: "Stop-Liquid Blends",
    consonant1: "प",
    consonant1SoundRoman: "pa",
    consonant2: "र",
    consonant2SoundRoman: "ra",
    combinedChar: "प्र",
    combinedSoundRoman: "pra",
    halantForm: "प्",
    wordHindi: "प्रसन्न",
    wordEnglish: "Happy",
    wordRoman: "prasann",
    assetPath: "/assets/gemini/vaani_l3_pra_happy_1777155433.png",
    summary: "Stop-liquid blends are very common.",
    prompt: "प्र - very common in Hindi!",
  },
  {
    id: "L3-C02-L06",
    chapterId: "C02",
    chapterTitle: "Advanced Consonant Clusters",
    title: "ब्र - Ba-Ra Conjunct",
    category: "Complex Conjunct",
    skill: "Stop-Liquid Blends",
    consonant1: "ब",
    consonant1SoundRoman: "ba",
    consonant2: "र",
    consonant2SoundRoman: "ra",
    combinedChar: "ब्र",
    combinedSoundRoman: "bra",
    halantForm: "ब्",
    wordHindi: "ब्रह्म",
    wordEnglish: "Brahma",
    wordRoman: "brahma",
    assetPath: "/assets/gemini/vaani_l3_bra_brahma_1777155457.png",
    summary: "Bilabial with liquid.",
    prompt: "ब्र - powerful blend!",
  },
  {
    id: "L3-C02-L07",
    chapterId: "C02",
    chapterTitle: "Advanced Consonant Clusters",
    title: "म्य - Ma-Ya Conjunct",
    category: "Complex Conjunct",
    skill: "Nasal-Glide Blends",
    consonant1: "म",
    consonant1SoundRoman: "ma",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "म्य",
    combinedSoundRoman: "mya",
    halantForm: "म्",
    wordHindi: "म्यान",
    wordEnglish: "Sheath",
    wordRoman: "myan",
    assetPath: "/assets/gemini/vaani_l3_mya_sheath_1777155481.png",
    summary: "Nasal with glide.",
    prompt: "म्य - soft and flowing!",
  },
  {
    id: "L3-C02-L08",
    chapterId: "C02",
    chapterTitle: "Advanced Consonant Clusters",
    title: "ह्य - Ha-Ya Conjunct",
    category: "Complex Conjunct",
    skill: "Aspirate-Glide Blends",
    consonant1: "ह",
    consonant1SoundRoman: "ha",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "ह्य",
    combinedSoundRoman: "hya",
    halantForm: "ह्",
    wordHindi: "ह्यूमन",
    wordEnglish: "Human",
    wordRoman: "hyuman",
    assetPath: "/assets/gemini/vaani_l3_hya_human_1777155505.png",
    summary: "Aspirate with glide.",
    prompt: "ह्य - light and airy!",
  },
  {
    id: "L3-C02-L09",
    chapterId: "C02",
    chapterTitle: "Advanced Consonant Clusters",
    title: "स्क - Sa-Ka Conjunct",
    category: "Complex Conjunct",
    skill: "Fricative-Stop Blends",
    consonant1: "स",
    consonant1SoundRoman: "sa",
    consonant2: "क",
    consonant2SoundRoman: "ka",
    combinedChar: "स्क",
    combinedSoundRoman: "ska",
    halantForm: "स्",
    wordHindi: "स्कूल",
    wordEnglish: "School",
    wordRoman: "skool",
    assetPath: "/assets/gemini/vaani_l3_ska_school_1777155529.png",
    summary: "Fricative with stop.",
    prompt: "स्क - crisp and clear!",
  },
  {
    id: "L3-C02-L10",
    chapterId: "C02",
    chapterTitle: "Advanced Consonant Clusters",
    title: "स्प - Sa-Pa Conjunct",
    category: "Complex Conjunct",
    skill: "Fricative-Stop Blends",
    consonant1: "स",
    consonant1SoundRoman: "sa",
    consonant2: "प",
    consonant2SoundRoman: "pa",
    combinedChar: "स्प",
    combinedSoundRoman: "spa",
    halantForm: "स्",
    wordHindi: "स्पष्ट",
    wordEnglish: "Clear",
    wordRoman: "spasht",
    assetPath: "/assets/gemini/vaani_l3_spa_clear_1777155553.png",
    summary: "Fricative with bilabial.",
    prompt: "स्प - bright and articulate!",
  },
  {
    id: "L3-C02-L11",
    chapterId: "C02",
    chapterTitle: "Advanced Consonant Clusters",
    title: "ल्य - La-Ya Conjunct",
    category: "Complex Conjunct",
    skill: "Liquid-Glide Blends",
    consonant1: "ल",
    consonant1SoundRoman: "la",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "ल्य",
    combinedSoundRoman: "lya",
    halantForm: "ल्",
    wordHindi: "मूल्य",
    wordEnglish: "Value",
    wordRoman: "mulya",
    assetPath: "/assets/gemini/vaani_l3_lya_various_1777155577.png",
    summary: "Liquid with glide.",
    prompt: "ल्य - smooth combination!",
  },
  {
    id: "L3-C02-L12",
    chapterId: "C02",
    chapterTitle: "Advanced Consonant Clusters",
    title: "Advanced Conjunct Review",
    category: "Consolidation",
    skill: "Advanced Mastery",
    consonant1: "प",
    consonant1SoundRoman: "pa",
    consonant2: "र",
    consonant2SoundRoman: "ra",
    combinedChar: "प्र",
    combinedSoundRoman: "pra",
    halantForm: "प्",
    wordHindi: "प्रेम",
    wordEnglish: "Love",
    wordRoman: "prem",
    assetPath: "/assets/gemini/vaani_l3_review2_1777155601.png",
    summary: "Practice advanced conjunct combinations.",
    prompt: "You've mastered advanced consonant clusters!",
  },

  // ============================================
  // CHAPTER 3: SPECIAL & RARE CONJUNCTS (12 LESSONS)
  // ============================================

  {
    id: "L3-C03-L01",
    chapterId: "C03",
    chapterTitle: "Special Consonant Clusters",
    title: "छ्य - Cha-Ya Conjunct",
    category: "Special Conjunct",
    skill: "Affricate Blends",
    consonant1: "छ",
    consonant1SoundRoman: "cha",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "छ्य",
    combinedSoundRoman: "chya",
    halantForm: "छ्",
    wordHindi: "छ्यामा",
    wordEnglish: "Dark complexioned",
    wordRoman: "chyama",
    assetPath: "/assets/gemini/vaani_l3_chya_dark_1777155625.png",
    summary: "Affricate with glide.",
    prompt: "छ्य - soft whisper!",
  },
  {
    id: "L3-C03-L02",
    chapterId: "C03",
    chapterTitle: "Special Consonant Clusters",
    title: "ट्र - Tra Conjunct (retroflex ट + र)",
    category: "Special Conjunct",
    skill: "Retroflex Blends",
    consonant1: "ट",
    consonant1SoundRoman: "tha",
    consonant2: "र",
    consonant2SoundRoman: "ra",
    combinedChar: "ट्र",
    combinedSoundRoman: "tra",
    halantForm: "ट्",
    wordHindi: "ट्रंक",
    wordEnglish: "Trunk",
    wordRoman: "trunk",
    assetPath: "/assets/gemini/vaani_l3_tra_retrofit_1777155649.png",
    summary: "Retroflex stop with liquid.",
    prompt: "ट्र - tongue curled back!",
  },
  {
    id: "L3-C03-L03",
    chapterId: "C03",
    chapterTitle: "Special Consonant Clusters",
    title: "ड्र - Dra Conjunct (retroflex ड + र)",
    category: "Special Conjunct",
    skill: "Retroflex Blends",
    consonant1: "ड",
    consonant1SoundRoman: "dha",
    consonant2: "र",
    consonant2SoundRoman: "ra",
    combinedChar: "ड्र",
    combinedSoundRoman: "dra",
    halantForm: "ड्",
    wordHindi: "ड्रामा",
    wordEnglish: "Drama",
    wordRoman: "drama",
    assetPath: "/assets/gemini/vaani_l3_dra_retrofit_1777155673.png",
    summary: "Retroflex aspirate with liquid.",
    prompt: "ड्र - deep and sonorous!",
  },
  {
    id: "L3-C03-L04",
    chapterId: "C03",
    chapterTitle: "Special Consonant Clusters",
    title: "ज्य - Ja-Ya Conjunct",
    category: "Special Conjunct",
    skill: "Affricate-Glide Blends",
    consonant1: "ज",
    consonant1SoundRoman: "ja",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "ज्य",
    combinedSoundRoman: "jya",
    halantForm: "ज्",
    wordHindi: "ज्योति",
    wordEnglish: "Light",
    wordRoman: "jyoti",
    assetPath: "/assets/gemini/vaani_l3_jya_light_1777155697.png",
    summary: "Affricate with glide.",
    prompt: "ज्य - glowing and bright!",
  },
  {
    id: "L3-C03-L05",
    chapterId: "C03",
    chapterTitle: "Special Consonant Clusters",
    title: "ध्य - Dha-Ya Conjunct",
    category: "Special Conjunct",
    skill: "Aspirate-Glide Blends",
    consonant1: "ध",
    consonant1SoundRoman: "dha",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "ध्य",
    combinedSoundRoman: "dhya",
    halantForm: "ध्",
    wordHindi: "ध्यान",
    wordEnglish: "Meditation",
    wordRoman: "dhyan",
    assetPath: "/assets/gemini/vaani_l3_dhya_meditation_1777155721.png",
    summary: "Aspirate with glide.",
    prompt: "ध्य - meditative and calm!",
  },
  {
    id: "L3-C03-L06",
    chapterId: "C03",
    chapterTitle: "Special Consonant Clusters",
    title: "भ्र - Bha-Ra Conjunct",
    category: "Special Conjunct",
    skill: "Aspirate-Liquid Blends",
    consonant1: "भ",
    consonant1SoundRoman: "bha",
    consonant2: "र",
    consonant2SoundRoman: "ra",
    combinedChar: "भ्र",
    combinedSoundRoman: "bhra",
    halantForm: "भ्",
    wordHindi: "भ्रम",
    wordEnglish: "Confusion",
    wordRoman: "bhram",
    assetPath: "/assets/gemini/vaani_l3_bhra_confusion_1777155745.png",
    summary: "Aspirate with liquid.",
    prompt: "भ्र - confused and swirling!",
  },
  {
    id: "L3-C03-L07",
    chapterId: "C03",
    chapterTitle: "Special Consonant Clusters",
    title: "भ्य - Bha-Ya Conjunct",
    category: "Special Conjunct",
    skill: "Aspirate-Glide Blends",
    consonant1: "भ",
    consonant1SoundRoman: "bha",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "भ्य",
    combinedSoundRoman: "bhya",
    halantForm: "भ्",
    wordHindi: "भ्यावह",
    wordEnglish: "Terrible",
    wordRoman: "bhyavah",
    assetPath: "/assets/gemini/vaani_l3_bhya_terrible_1777155769.png",
    summary: "Aspirate with glide.",
    prompt: "भ्य - frightening and intense!",
  },
  {
    id: "L3-C03-L08",
    chapterId: "C03",
    chapterTitle: "Special Consonant Clusters",
    title: "ह्न - Ha-Na Conjunct",
    category: "Special Conjunct",
    skill: "Aspirate-Nasal Blends",
    consonant1: "ह",
    consonant1SoundRoman: "ha",
    consonant2: "न",
    consonant2SoundRoman: "na",
    combinedChar: "ह्न",
    combinedSoundRoman: "hna",
    halantForm: "ह्",
    wordHindi: "ह्नास",
    wordEnglish: "Decline",
    wordRoman: "hnas",
    assetPath: "/assets/gemini/vaani_l3_hna_decline_1777155793.png",
    summary: "Aspirate with nasal.",
    prompt: "ह्न - rare and ancient!",
  },
  {
    id: "L3-C03-L09",
    chapterId: "C03",
    chapterTitle: "Special Consonant Clusters",
    title: "स्य - Sa-Ya Conjunct",
    category: "Special Conjunct",
    skill: "Fricative-Glide Blends",
    consonant1: "स",
    consonant1SoundRoman: "sa",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "स्य",
    combinedSoundRoman: "sya",
    halantForm: "स्",
    wordHindi: "स्यूत",
    wordEnglish: "Stitched",
    wordRoman: "syut",
    assetPath: "/assets/gemini/vaani_l3_sya_stitched_1777155817.png",
    summary: "Fricative with glide.",
    prompt: "स्य - rare in modern Hindi!",
  },
  {
    id: "L3-C03-L10",
    chapterId: "C03",
    chapterTitle: "Special Consonant Clusters",
    title: "ग्य - Ga-Ya Conjunct",
    category: "Special Conjunct",
    skill: "Stop-Glide Blends",
    consonant1: "ग",
    consonant1SoundRoman: "ga",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "ग्य",
    combinedSoundRoman: "gya",
    halantForm: "ग्",
    wordHindi: "ग्यारह",
    wordEnglish: "Eleven",
    wordRoman: "gyarah",
    assetPath: "/assets/gemini/vaani_l3_gya_eleven_1777155841.png",
    summary: "Stop with glide.",
    prompt: "ग्य - smooth combination!",
  },
  {
    id: "L3-C03-L11",
    chapterId: "C03",
    chapterTitle: "Special Consonant Clusters",
    title: "घ्य - Gha-Ya Conjunct",
    category: "Special Conjunct",
    skill: "Aspirate-Glide Blends",
    consonant1: "घ",
    consonant1SoundRoman: "gha",
    consonant2: "य",
    consonant2SoundRoman: "ya",
    combinedChar: "घ्य",
    combinedSoundRoman: "ghya",
    halantForm: "घ्",
    wordHindi: "अभिघ्यात",
    wordEnglish: "Well-known",
    wordRoman: "abhighyaat",
    assetPath: "/assets/gemini/vaani_l3_ghya_attention_1777155865.png",
    summary: "Aspirate with glide.",
    prompt: "घ्य - deep and resonant!",
  },
  {
    id: "L3-C03-L12",
    chapterId: "C03",
    chapterTitle: "Special Consonant Clusters",
    title: "Mastery - All Conjuncts",
    category: "Consolidation",
    skill: "Conjunct Mastery",
    consonant1: "क",
    consonant1SoundRoman: "ka",
    consonant2: "त",
    consonant2SoundRoman: "ta",
    combinedChar: "क्त",
    combinedSoundRoman: "kta",
    halantForm: "क्",
    wordHindi: "संभव",
    wordEnglish: "Possible",
    wordRoman: "sambhav",
    assetPath: "/assets/gemini/vaani_l3_review3_1777155889.png",
    summary: "You've mastered 38 conjuncts!",
    prompt: "Conjuncts are now your strength!",
  },
];

// Roman transliteration map for Level 3
export const LEVEL_3_ROMAN_MAP: Record<string, string> = {
  "L3-C01-L01": "akta",
  "L3-C01-L02": "handa",
  "L3-C01-L03": "kampan",
  "L3-C01-L04": "ishttha",
  "L3-C01-L05": "palla",
  "L3-C01-L06": "arjun",
  "L3-C01-L07": "vyakti",
  "L3-C01-L08": "trimukhi",
  "L3-C01-L09": "dravya",
  "L3-C01-L10": "kshetra",
  "L3-C01-L11": "gyaan",
  "L3-C01-L12": "shriman",
  "L3-C01-L13": "star",
  "L3-C01-L14": "akshar",
  "L3-C02-L01": "anchal",
  "L3-C02-L02": "kand",
  "L3-C02-L03": "tyhaar",
  "L3-C02-L04": "adya",
  "L3-C02-L05": "prasann",
  "L3-C02-L06": "brahma",
  "L3-C02-L07": "myan",
  "L3-C02-L08": "hyuman",
  "L3-C02-L09": "skool",
  "L3-C02-L10": "spasht",
  "L3-C02-L11": "lyau",
  "L3-C02-L12": "prem",
  "L3-C03-L01": "chyama",
  "L3-C03-L02": "trunk",
  "L3-C03-L03": "drama",
  "L3-C03-L04": "jyoti",
  "L3-C03-L05": "dhyan",
  "L3-C03-L06": "bhram",
  "L3-C03-L07": "bhyavah",
  "L3-C03-L08": "hnas",
  "L3-C03-L09": "syut",
  "L3-C03-L10": "gyarah",
  "L3-C03-L11": "ghyan",
  "L3-C03-L12": "sambhav",
};

// Re-export for compatibility
export const vaaniLevel3Data = LEVEL_3_DATA;
