/**
 * Vaani Level 2: Matra Mastery (36 lessons)
 * Focus: Vowel modifiers (matras) applied to consonants
 * Progression: Base consonant + Matra mark = Modified character
 * Structure: 36 lessons covering all major matras with multiple consonants
 */

export interface Level2Seed {
  id: string;
  chapterId: string;
  chapterTitle: string;
  title: string;
  category: string;
  skill: string;
  baseChar: string;
  baseSoundRoman?: string;
  matra: string;
  matraSoundRoman?: string;
  modifiedChar: string;
  modifiedSoundRoman?: string;
  wordHindi: string;
  wordEnglish: string;
  wordRoman: string;
  assetPath: string;
  durationMin?: number;
  summary: string;
  prompt: string;
}

// ============================================
// CHAPTER 1: क (KA) WITH ALL MATRAS (12 LESSONS)
// ============================================

export const LEVEL_2_DATA: Level2Seed[] = [
  // का (Ka with आ - long 'a')
  {
    id: "L2-C01-L01",
    chapterId: "C01",
    chapterTitle: "क + All Matras",
    title: "का - Ka with आ matra (long a)",
    category: "Matra Application",
    skill: "Vowel Modifiers",
    baseChar: "क",
    baseSoundRoman: "ka",
    matra: "ा",
    matraSoundRoman: "aa",
    modifiedChar: "का",
    modifiedSoundRoman: "kaa",
    wordHindi: "काला",
    wordEnglish: "Black",
    wordRoman: "kala",
    assetPath: "/assets/gemini/vaani_l2_ka_black_1777140001.png",
    summary: "The आ matra stretches the vowel sound from short 'a' to long 'aa'.",
    prompt: "क + ा = का. This matra makes the sound longer!",
  },
  // कि (Ka with इ - short 'i')
  {
    id: "L2-C01-L02",
    chapterId: "C01",
    chapterTitle: "क + All Matras",
    title: "कि - Ka with इ matra (short i)",
    category: "Matra Application",
    skill: "Vowel Modifiers",
    baseChar: "क",
    baseSoundRoman: "ka",
    matra: "ि",
    matraSoundRoman: "i",
    modifiedChar: "कि",
    modifiedSoundRoman: "ki",
    wordHindi: "किताब",
    wordEnglish: "Book",
    wordRoman: "kitaab",
    assetPath: "/assets/gemini/vaani_l2_ki_book_1777140025.png",
    summary: "The इ matra appears as a mark before the consonant.",
    prompt: "कि sounds like 'key' - notice the small matra mark.",
  },
  // की (Ka with ई - long 'i')
  {
    id: "L2-C01-L03",
    chapterId: "C01",
    chapterTitle: "क + All Matras",
    title: "की - Ka with ई matra (long i)",
    category: "Matra Application",
    skill: "Vowel Modifiers",
    baseChar: "क",
    baseSoundRoman: "ka",
    matra: "ी",
    matraSoundRoman: "ee",
    modifiedChar: "की",
    modifiedSoundRoman: "kee",
    wordHindi: "कीमत",
    wordEnglish: "Price",
    wordRoman: "keemat",
    assetPath: "/assets/gemini/vaani_l2_kee_price_1777140049.png",
    summary: "The long ई matra extends the i-sound - hear the difference!",
    prompt: "की stretches the sound longer - stretch your mouth!",
  },
  // कु (Ka with उ - short 'u')
  {
    id: "L2-C01-L04",
    chapterId: "C01",
    chapterTitle: "क + All Matras",
    title: "कु - Ka with उ matra (short u)",
    category: "Matra Application",
    skill: "Vowel Modifiers",
    baseChar: "क",
    baseSoundRoman: "ka",
    matra: "ु",
    matraSoundRoman: "u",
    modifiedChar: "कु",
    modifiedSoundRoman: "ku",
    wordHindi: "कुत्ता",
    wordEnglish: "Dog",
    wordRoman: "kutta",
    assetPath: "/assets/gemini/vaani_l2_ku_dog_1777140073.png",
    summary: "Round your mouth for the उ matra.",
    prompt: "कु rhymes with 'who' - round your lips!",
  },
  // कू (Ka with ऊ - long 'u')
  {
    id: "L2-C01-L05",
    chapterId: "C01",
    chapterTitle: "क + All Matras",
    title: "कू - Ka with ऊ matra (long u)",
    category: "Matra Application",
    skill: "Vowel Modifiers",
    baseChar: "क",
    baseSoundRoman: "ka",
    matra: "ू",
    matraSoundRoman: "oo",
    modifiedChar: "कू",
    modifiedSoundRoman: "koo",
    wordHindi: "कूद",
    wordEnglish: "Jump",
    wordRoman: "kood",
    assetPath: "/assets/gemini/vaani_l2_koo_jump_1777140097.png",
    summary: "The long ऊ matra extends the u-sound.",
    prompt: "कू is longer than कु - feel the stretch!",
  },
  // के (Ka with ए - short 'e')
  {
    id: "L2-C01-L06",
    chapterId: "C01",
    chapterTitle: "क + All Matras",
    title: "के - Ka with ए matra (short e)",
    category: "Matra Application",
    skill: "Vowel Modifiers",
    baseChar: "क",
    baseSoundRoman: "ka",
    matra: "े",
    matraSoundRoman: "e",
    modifiedChar: "के",
    modifiedSoundRoman: "ke",
    wordHindi: "केला",
    wordEnglish: "Banana",
    wordRoman: "kela",
    assetPath: "/assets/gemini/vaani_l2_ke_banana_1777140121.png",
    summary: "The ए matra appears as a front mark before consonants.",
    prompt: "के sounds like 'kay' - the ए matra is written in front!",
  },
  // कै (Ka with ऐ - long 'ai')
  {
    id: "L2-C01-L07",
    chapterId: "C01",
    chapterTitle: "क + All Matras",
    title: "कै - Ka with ऐ matra (long ai)",
    category: "Matra Application",
    skill: "Vowel Modifiers",
    baseChar: "क",
    baseSoundRoman: "ka",
    matra: "ै",
    matraSoundRoman: "ai",
    modifiedChar: "कै",
    modifiedSoundRoman: "kai",
    wordHindi: "कैसा",
    wordEnglish: "How",
    wordRoman: "kaisa",
    assetPath: "/assets/gemini/vaani_l2_kai_how_1777140145.png",
    summary: "The ऐ matra is a combination - it sounds broader.",
    prompt: "कै sounds like 'kai' - blend the 'a' and 'e' sounds!",
  },
  // को (Ka with ओ - short 'o')
  {
    id: "L2-C01-L08",
    chapterId: "C01",
    chapterTitle: "क + All Matras",
    title: "को - Ka with ओ matra (short o)",
    category: "Matra Application",
    skill: "Vowel Modifiers",
    baseChar: "क",
    baseSoundRoman: "ka",
    matra: "ो",
    matraSoundRoman: "o",
    modifiedChar: "को",
    modifiedSoundRoman: "ko",
    wordHindi: "कोला",
    wordEnglish: "Cola",
    wordRoman: "kola",
    assetPath: "/assets/gemini/vaani_l2_ko_cola_1777140169.png",
    summary: "The ओ matra appears below the base consonant.",
    prompt: "को sounds like 'koh' - the matra wraps underneath!",
  },
  // कौ (Ka with औ - long 'au')
  {
    id: "L2-C01-L09",
    chapterId: "C01",
    chapterTitle: "क + All Matras",
    title: "कौ - Ka with औ matra (long au)",
    category: "Matra Application",
    skill: "Vowel Modifiers",
    baseChar: "क",
    baseSoundRoman: "ka",
    matra: "ौ",
    matraSoundRoman: "au",
    modifiedChar: "कौ",
    modifiedSoundRoman: "kau",
    wordHindi: "कौन",
    wordEnglish: "Who",
    wordRoman: "kaun",
    assetPath: "/assets/gemini/vaani_l2_kau_who_1777140193.png",
    summary: "The औ matra is the broadest o-sound.",
    prompt: "कौ is a deep 'o' sound - let it roll from your throat!",
  },
  // क्र (Ka with Reph)
  {
    id: "L2-C01-L10",
    chapterId: "C01",
    chapterTitle: "क + All Matras",
    title: "क्र - Ka with Reph consonant cluster",
    category: "Matra Application",
    skill: "Vowel Modifiers",
    baseChar: "क",
    baseSoundRoman: "ka",
    matra: "्र",
    matraSoundRoman: "r",
    modifiedChar: "क्र",
    modifiedSoundRoman: "kra",
    wordHindi: "क्रिकेट",
    wordEnglish: "Cricket",
    wordRoman: "kriket",
    assetPath: "/assets/gemini/vaani_l2_kra_cricket_1777140217.png",
    summary: "When र joins with a halant, it blends the sounds.",
    prompt: "क्र makes a blended sound - say it fast!",
  },
  // क्ष (Ka with Vocalic)
  {
    id: "L2-C01-L11",
    chapterId: "C01",
    chapterTitle: "क + All Matras",
    title: "क्ष - Ka with Sha (special cluster)",
    category: "Matra Application",
    skill: "Vowel Modifiers",
    baseChar: "क",
    baseSoundRoman: "ka",
    matra: "्ष",
    matraSoundRoman: "sha",
    modifiedChar: "क्ष",
    modifiedSoundRoman: "ksha",
    wordHindi: "क्षत्रिय",
    wordEnglish: "Warrior",
    wordRoman: "kshatriya",
    assetPath: "/assets/gemini/vaani_l2_ksha_warrior_1777140241.png",
    summary: "क्ष is a special combination where two consonants merge.",
    prompt: "क्ष sounds like 'ksha' - it's a special merged sound!",
  },
  // Matra Review Game
  {
    id: "L2-C01-L12",
    chapterId: "C01",
    chapterTitle: "क + All Matras",
    title: "Matra Review Game",
    category: "Consolidation",
    skill: "Matra Mastery",
    baseChar: "क",
    baseSoundRoman: "ka",
    matra: "ा",
    matraSoundRoman: "aa",
    modifiedChar: "का",
    modifiedSoundRoman: "kaa",
    wordHindi: "खेल",
    wordEnglish: "Game",
    wordRoman: "khel",
    assetPath: "/assets/gemini/vaani_l2_review_game_1777140265.png",
    summary: "Practice all matras with fast recognition.",
    prompt: "Mix and match matras - can you build words quickly?",
  },

  // ============================================
  // CHAPTER 2: ख (KHA) WITH MATRAS (12 LESSONS)
  // ============================================

  {
    id: "L2-C02-L01",
    chapterId: "C02",
    chapterTitle: "ख + All Matras",
    title: "खा - Kha with आ matra",
    category: "Matra Application",
    skill: "Consonant Variations",
    baseChar: "ख",
    baseSoundRoman: "kha",
    matra: "ा",
    matraSoundRoman: "aa",
    modifiedChar: "खा",
    modifiedSoundRoman: "khaa",
    wordHindi: "खाना",
    wordEnglish: "Food",
    wordRoman: "khana",
    assetPath: "/assets/gemini/vaani_l2_kha_food_1777140289.png",
    summary: "Now apply matras to the aspirated consonant ख.",
    prompt: "ख is the aspirated version - add more breath!",
  },
  {
    id: "L2-C02-L02",
    chapterId: "C02",
    chapterTitle: "ख + All Matras",
    title: "खि - Kha with इ matra",
    category: "Matra Application",
    skill: "Consonant Variations",
    baseChar: "ख",
    baseSoundRoman: "kha",
    matra: "ि",
    matraSoundRoman: "i",
    modifiedChar: "खि",
    modifiedSoundRoman: "khi",
    wordHindi: "खिलाड़ी",
    wordEnglish: "Player",
    wordRoman: "khiladi",
    assetPath: "/assets/gemini/vaani_l2_khi_player_1777140313.png",
    summary: "ख with short i matra.",
    prompt: "खि - the i-sound makes it sound quick and light!",
  },
  {
    id: "L2-C02-L03",
    chapterId: "C02",
    chapterTitle: "ख + All Matras",
    title: "की - Kha with ई matra",
    category: "Matra Application",
    skill: "Consonant Variations",
    baseChar: "ख",
    baseSoundRoman: "kha",
    matra: "ी",
    matraSoundRoman: "ee",
    modifiedChar: "खी",
    modifiedSoundRoman: "khee",
    wordHindi: "खीर",
    wordEnglish: "Rice pudding",
    wordRoman: "kheer",
    assetPath: "/assets/gemini/vaani_l2_khee_rice_1777140337.png",
    summary: "ख with long i matra.",
    prompt: "खी - extended e-sound!",
  },
  {
    id: "L2-C02-L04",
    chapterId: "C02",
    chapterTitle: "ख + All Matras",
    title: "खु - Kha with उ matra",
    category: "Matra Application",
    skill: "Consonant Variations",
    baseChar: "ख",
    baseSoundRoman: "kha",
    matra: "ु",
    matraSoundRoman: "u",
    modifiedChar: "खु",
    modifiedSoundRoman: "khu",
    wordHindi: "खुशी",
    wordEnglish: "Happiness",
    wordRoman: "khushi",
    assetPath: "/assets/gemini/vaani_l2_khu_happy_1777140361.png",
    summary: "ख with short u matra.",
    prompt: "खु - rounded mouth for this sound!",
  },
  {
    id: "L2-C02-L05",
    chapterId: "C02",
    chapterTitle: "ख + All Matras",
    title: "खू - Kha with ऊ matra",
    category: "Matra Application",
    skill: "Consonant Variations",
    baseChar: "ख",
    baseSoundRoman: "kha",
    matra: "ू",
    matraSoundRoman: "oo",
    modifiedChar: "खू",
    modifiedSoundRoman: "khoo",
    wordHindi: "खूब",
    wordEnglish: "Very much",
    wordRoman: "khoob",
    assetPath: "/assets/gemini/vaani_l2_khoo_very_1777140385.png",
    summary: "ख with long u matra.",
    prompt: "खू - long 'oo' sound!",
  },
  {
    id: "L2-C02-L06",
    chapterId: "C02",
    chapterTitle: "ख + All Matras",
    title: "खे - Kha with ए matra",
    category: "Matra Application",
    skill: "Consonant Variations",
    baseChar: "ख",
    baseSoundRoman: "kha",
    matra: "े",
    matraSoundRoman: "e",
    modifiedChar: "खे",
    modifiedSoundRoman: "khe",
    wordHindi: "खेत",
    wordEnglish: "Field",
    wordRoman: "khet",
    assetPath: "/assets/gemini/vaani_l2_khe_field_1777140409.png",
    summary: "ख with short e matra.",
    prompt: "खे - front-marked matra!",
  },
  {
    id: "L2-C02-L07",
    chapterId: "C02",
    chapterTitle: "ख + All Matras",
    title: "खै - Kha with ऐ matra",
    category: "Matra Application",
    skill: "Consonant Variations",
    baseChar: "ख",
    baseSoundRoman: "kha",
    matra: "ै",
    matraSoundRoman: "ai",
    modifiedChar: "खै",
    modifiedSoundRoman: "khai",
    wordHindi: "खैर",
    wordEnglish: "Well",
    wordRoman: "khair",
    assetPath: "/assets/gemini/vaani_l2_khai_well_1777140433.png",
    summary: "ख with long ai matra.",
    prompt: "खै - blend a and e sounds!",
  },
  {
    id: "L2-C02-L08",
    chapterId: "C02",
    chapterTitle: "ख + All Matras",
    title: "खो - Kha with ओ matra",
    category: "Matra Application",
    skill: "Consonant Variations",
    baseChar: "ख",
    baseSoundRoman: "kha",
    matra: "ो",
    matraSoundRoman: "o",
    modifiedChar: "खो",
    modifiedSoundRoman: "kho",
    wordHindi: "खोज",
    wordEnglish: "Search",
    wordRoman: "khoj",
    assetPath: "/assets/gemini/vaani_l2_kho_search_1777140457.png",
    summary: "ख with short o matra.",
    prompt: "खो - o-sound below!",
  },
  {
    id: "L2-C02-L09",
    chapterId: "C02",
    chapterTitle: "ख + All Matras",
    title: "खौ - Kha with औ matra",
    category: "Matra Application",
    skill: "Consonant Variations",
    baseChar: "ख",
    baseSoundRoman: "kha",
    matra: "ौ",
    matraSoundRoman: "au",
    modifiedChar: "खौ",
    modifiedSoundRoman: "khau",
    wordHindi: "खौफ",
    wordEnglish: "Fear",
    wordRoman: "khauf",
    assetPath: "/assets/gemini/vaani_l2_khau_fear_1777140481.png",
    summary: "ख with long au matra.",
    prompt: "खौ - deep au-sound!",
  },
  {
    id: "L2-C02-L10",
    chapterId: "C02",
    chapterTitle: "ख + All Matras",
    title: "ख्र - Kha with Reph",
    category: "Matra Application",
    skill: "Consonant Variations",
    baseChar: "ख",
    baseSoundRoman: "kha",
    matra: "्र",
    matraSoundRoman: "r",
    modifiedChar: "ख्र",
    modifiedSoundRoman: "khra",
    wordHindi: "ख्याल",
    wordEnglish: "Idea",
    wordRoman: "khyal",
    assetPath: "/assets/gemini/vaani_l2_khra_idea_1777140505.png",
    summary: "ख with reph consonant cluster.",
    prompt: "ख्र - blend with r-sound!",
  },
  {
    id: "L2-C02-L11",
    chapterId: "C02",
    chapterTitle: "ख + All Matras",
    title: "ख्य - Kha with Ya cluster",
    category: "Matra Application",
    skill: "Consonant Variations",
    baseChar: "ख",
    baseSoundRoman: "kha",
    matra: "्य",
    matraSoundRoman: "y",
    modifiedChar: "ख्य",
    modifiedSoundRoman: "khya",
    wordHindi: "खयाल",
    wordEnglish: "Imagination",
    wordRoman: "khyal",
    assetPath: "/assets/gemini/vaani_l2_khya_imagination_1777140529.png",
    summary: "ख with ya consonant cluster.",
    prompt: "ख्य - y-sound after kh!",
  },
  {
    id: "L2-C02-L12",
    chapterId: "C02",
    chapterTitle: "ख + All Matras",
    title: "Consonant Review - क vs ख",
    category: "Consolidation",
    skill: "Matra Mastery",
    baseChar: "ख",
    baseSoundRoman: "kha",
    matra: "ा",
    matraSoundRoman: "aa",
    modifiedChar: "खा",
    modifiedSoundRoman: "khaa",
    wordHindi: "ख़ैर",
    wordEnglish: "Well",
    wordRoman: "khair",
    assetPath: "/assets/gemini/vaani_l2_review_consonants_1777140553.png",
    summary: "Compare matras across different consonants.",
    prompt: "Same matras, different consonants - notice the pattern!",
  },

  // ============================================
  // CHAPTER 3: ग (GA) & घ (GHA) WITH MATRAS (12 LESSONS)
  // ============================================

  {
    id: "L2-C03-L01",
    chapterId: "C03",
    chapterTitle: "ग & घ Consonants",
    title: "गा - Ga with आ matra",
    category: "Matra Application",
    skill: "More Consonants",
    baseChar: "ग",
    baseSoundRoman: "ga",
    matra: "ा",
    matraSoundRoman: "aa",
    modifiedChar: "गा",
    modifiedSoundRoman: "gaa",
    wordHindi: "गाना",
    wordEnglish: "Singing",
    wordRoman: "gana",
    assetPath: "/assets/gemini/vaani_l2_ga_singing_1777140577.png",
    summary: "ग (unaspirated stop) with matras.",
    prompt: "ग has a softer stop than क - hear the difference!",
  },
  {
    id: "L2-C03-L02",
    chapterId: "C03",
    chapterTitle: "ग & घ Consonants",
    title: "गि - Ga with इ matra",
    category: "Matra Application",
    skill: "More Consonants",
    baseChar: "ग",
    baseSoundRoman: "ga",
    matra: "ि",
    matraSoundRoman: "i",
    modifiedChar: "गि",
    modifiedSoundRoman: "gi",
    wordHindi: "गिलास",
    wordEnglish: "Glass",
    wordRoman: "gilas",
    assetPath: "/assets/gemini/vaani_l2_gi_glass_1777140601.png",
    summary: "ग with short i matra.",
    prompt: "गि - quick and light!",
  },
  {
    id: "L2-C03-L03",
    chapterId: "C03",
    chapterTitle: "ग & घ Consonants",
    title: "गु - Ga with उ matra",
    category: "Matra Application",
    skill: "More Consonants",
    baseChar: "ग",
    baseSoundRoman: "ga",
    matra: "ु",
    matraSoundRoman: "u",
    modifiedChar: "गु",
    modifiedSoundRoman: "gu",
    wordHindi: "गुलाब",
    wordEnglish: "Rose",
    wordRoman: "gulab",
    assetPath: "/assets/gemini/vaani_l2_gu_rose_1777140625.png",
    summary: "ग with short u matra.",
    prompt: "गु - round your mouth!",
  },
  {
    id: "L2-C03-L04",
    chapterId: "C03",
    chapterTitle: "ग & घ Consonants",
    title: "गे - Ga with ए matra",
    category: "Matra Application",
    skill: "More Consonants",
    baseChar: "ग",
    baseSoundRoman: "ga",
    matra: "े",
    matraSoundRoman: "e",
    modifiedChar: "गे",
    modifiedSoundRoman: "ge",
    wordHindi: "गेहूँ",
    wordEnglish: "Wheat",
    wordRoman: "gehun",
    assetPath: "/assets/gemini/vaani_l2_ge_wheat_1777140649.png",
    summary: "ग with short e matra.",
    prompt: "गे - front-marked!",
  },
  {
    id: "L2-C03-L05",
    chapterId: "C03",
    chapterTitle: "ग & घ Consonants",
    title: "गो - Ga with ओ matra",
    category: "Matra Application",
    skill: "More Consonants",
    baseChar: "ग",
    baseSoundRoman: "ga",
    matra: "ो",
    matraSoundRoman: "o",
    modifiedChar: "गो",
    modifiedSoundRoman: "go",
    wordHindi: "गोद",
    wordEnglish: "Lap",
    wordRoman: "god",
    assetPath: "/assets/gemini/vaani_l2_go_lap_1777140673.png",
    summary: "ग with short o matra.",
    prompt: "गो - wrapped below!",
  },
  {
    id: "L2-C03-L06",
    chapterId: "C03",
    chapterTitle: "ग & घ Consonants",
    title: "घा - Gha with आ matra",
    category: "Matra Application",
    skill: "More Consonants",
    baseChar: "घ",
    baseSoundRoman: "gha",
    matra: "ा",
    matraSoundRoman: "aa",
    modifiedChar: "घा",
    modifiedSoundRoman: "ghaa",
    wordHindi: "घर",
    wordEnglish: "House",
    wordRoman: "ghar",
    assetPath: "/assets/gemini/vaani_l2_gha_house_1777140697.png",
    summary: "घ (aspirated stop) with matras.",
    prompt: "घ is the aspirated version of ग - more breath!",
  },
  {
    id: "L2-C03-L07",
    chapterId: "C03",
    chapterTitle: "ग & घ Consonants",
    title: "घि - Gha with इ matra",
    category: "Matra Application",
    skill: "More Consonants",
    baseChar: "घ",
    baseSoundRoman: "gha",
    matra: "ि",
    matraSoundRoman: "i",
    modifiedChar: "घि",
    modifiedSoundRoman: "ghi",
    wordHindi: "घी",
    wordEnglish: "Ghee",
    wordRoman: "ghee",
    assetPath: "/assets/gemini/vaani_l2_ghi_ghee_1777140721.png",
    summary: "घ with short i matra.",
    prompt: "घि - pure and clear!",
  },
  {
    id: "L2-C03-L08",
    chapterId: "C03",
    chapterTitle: "ग & घ Consonants",
    title: "घु - Gha with उ matra",
    category: "Matra Application",
    skill: "More Consonants",
    baseChar: "घ",
    baseSoundRoman: "gha",
    matra: "ु",
    matraSoundRoman: "u",
    modifiedChar: "घु",
    modifiedSoundRoman: "ghu",
    wordHindi: "घुंघरू",
    wordEnglish: "Ankle bells",
    wordRoman: "ghunghru",
    assetPath: "/assets/gemini/vaani_l2_ghu_bells_1777140745.png",
    summary: "घ with short u matra.",
    prompt: "घु - rounded and resonant!",
  },
  {
    id: "L2-C03-L09",
    chapterId: "C03",
    chapterTitle: "ग & घ Consonants",
    title: "घे - Gha with ए matra",
    category: "Matra Application",
    skill: "More Consonants",
    baseChar: "घ",
    baseSoundRoman: "gha",
    matra: "े",
    matraSoundRoman: "e",
    modifiedChar: "घे",
    modifiedSoundRoman: "ghe",
    wordHindi: "घेरा",
    wordEnglish: "Circle",
    wordRoman: "ghera",
    assetPath: "/assets/gemini/vaani_l2_ghe_circle_1777140769.png",
    summary: "घ with short e matra.",
    prompt: "घे - front-marked!",
  },
  {
    id: "L2-C03-L10",
    chapterId: "C03",
    chapterTitle: "ग & घ Consonants",
    title: "घो - Gha with ओ matra",
    category: "Matra Application",
    skill: "More Consonants",
    baseChar: "घ",
    baseSoundRoman: "gha",
    matra: "ो",
    matraSoundRoman: "o",
    modifiedChar: "घो",
    modifiedSoundRoman: "gho",
    wordHindi: "घोड़ा",
    wordEnglish: "Horse",
    wordRoman: "ghoda",
    assetPath: "/assets/gemini/vaani_l2_gho_horse_1777140793.png",
    summary: "घ with short o matra.",
    prompt: "घो - wrapped below!",
  },
  {
    id: "L2-C03-L11",
    chapterId: "C03",
    chapterTitle: "ग & घ Consonants",
    title: "ग्र - Ga with Reph cluster",
    category: "Matra Application",
    skill: "More Consonants",
    baseChar: "ग",
    baseSoundRoman: "ga",
    matra: "्र",
    matraSoundRoman: "r",
    modifiedChar: "ग्र",
    modifiedSoundRoman: "gra",
    wordHindi: "ग्रीन",
    wordEnglish: "Green",
    wordRoman: "green",
    assetPath: "/assets/gemini/vaani_l2_gra_green_1777140817.png",
    summary: "ग with reph consonant cluster.",
    prompt: "ग्र - blend with r!",
  },
  {
    id: "L2-C03-L12",
    chapterId: "C03",
    chapterTitle: "ग & घ Consonants",
    title: "Consolidation - Consonant Families",
    category: "Consolidation",
    skill: "Matra Mastery",
    baseChar: "ग",
    baseSoundRoman: "ga",
    matra: "ा",
    matraSoundRoman: "aa",
    modifiedChar: "गा",
    modifiedSoundRoman: "gaa",
    wordHindi: "गायन",
    wordEnglish: "Singing",
    wordRoman: "gayan",
    assetPath: "/assets/gemini/vaani_l2_consolidation_1777140841.png",
    summary: "Review all consonants with matras learned so far.",
    prompt: "You now know 4 consonants with all matras!",
  },
];

// Roman transliteration map for Level 2
export const LEVEL_2_ROMAN_MAP: Record<string, string> = {
  "L2-C01-L01": "kala",
  "L2-C01-L02": "kitaab",
  "L2-C01-L03": "keemat",
  "L2-C01-L04": "kutta",
  "L2-C01-L05": "kood",
  "L2-C01-L06": "kela",
  "L2-C01-L07": "kaisa",
  "L2-C01-L08": "kola",
  "L2-C01-L09": "kaun",
  "L2-C01-L10": "kriket",
  "L2-C01-L11": "kshatriya",
  "L2-C01-L12": "khel",
  "L2-C02-L01": "khana",
  "L2-C02-L02": "khiladi",
  "L2-C02-L03": "kheer",
  "L2-C02-L04": "khushi",
  "L2-C02-L05": "khoob",
  "L2-C02-L06": "khet",
  "L2-C02-L07": "khair",
  "L2-C02-L08": "khoj",
  "L2-C02-L09": "khauf",
  "L2-C02-L10": "khyal",
  "L2-C02-L11": "khyal",
  "L2-C02-L12": "khair",
  "L2-C03-L01": "gana",
  "L2-C03-L02": "gilas",
  "L2-C03-L03": "gulab",
  "L2-C03-L04": "gehun",
  "L2-C03-L05": "god",
  "L2-C03-L06": "ghar",
  "L2-C03-L07": "ghee",
  "L2-C03-L08": "ghunghru",
  "L2-C03-L09": "ghera",
  "L2-C03-L10": "ghoda",
  "L2-C03-L11": "green",
  "L2-C03-L12": "gayan",
};

// Re-export for compatibility
export const vaaniLevel2Data = LEVEL_2_DATA;
