/**
 * Vaani Level 4: Barakhadi Mastery (36 lessons)
 * Focus: Complete syllabic matrix - every consonant with every vowel sound
 * Progression: Consonant + 12 vowels = 12 syllables (barakhadi row)
 * Concept: Master the full 12-sound pattern for each consonant
 */

export interface Level4Seed {
  id: string;
  chapterId: string;
  chapterTitle: string;
  title: string;
  category: string;
  skill: string;
  consonant: string;
  consonantRoman: string;
  barakhadiRow: Array<{ syllable: string; sound: string; matra: string }>;
  exampleWords: Array<{ hindi: string; english: string; roman: string }>;
  wordHindi: string;
  wordEnglish: string;
  wordRoman: string;
  assetPath: string;
  durationMin?: number;
  summary: string;
  prompt: string;
}

export const LEVEL_4_DATA: Level4Seed[] = [
  {
    id: "L4-C01-L01",
    chapterId: "C01",
    chapterTitle: "Barakhadi for क-वर्ग",
    title: "क की बारहखड़ी - Ka barakhadi (12 syllables)",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "क",
    consonantRoman: "ka",
    barakhadiRow: [
      { syllable: "क", sound: "ka", matra: "अ" },
      { syllable: "का", sound: "kaa", matra: "आ" },
      { syllable: "कि", sound: "ki", matra: "इ" },
      { syllable: "की", sound: "kee", matra: "ई" },
      { syllable: "कु", sound: "ku", matra: "उ" },
      { syllable: "कू", sound: "koo", matra: "ऊ" },
      { syllable: "के", sound: "ke", matra: "ए" },
      { syllable: "कै", sound: "kai", matra: "ऐ" },
      { syllable: "को", sound: "ko", matra: "ओ" },
      { syllable: "कौ", sound: "kau", matra: "औ" },
      { syllable: "कं", sound: "kam", matra: "ं" },
      { syllable: "कः", sound: "kah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "कमल", english: "Lotus", roman: "kamal" },
      { hindi: "काला", english: "Black", roman: "kala" },
      { hindi: "किताब", english: "Book", roman: "kitaab" },
    ],
    wordHindi: "कमल",
    wordEnglish: "Lotus",
    wordRoman: "kamal",
    assetPath: "/assets/gemini/vaani_l4_ka_barakhadi_1777200001.png",
    summary: "Learn all 12 syllable forms of क - the complete barakhadi grid.",
    prompt: "का is the foundation! Master this grid and you'll recognize any consonant!",
  },
  {
    id: "L4-C01-L02",
    chapterId: "C01",
    chapterTitle: "Barakhadi for क-वर्ग",
    title: "ख की बारहखड़ी - Kha barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "ख",
    consonantRoman: "kha",
    barakhadiRow: [
      { syllable: "ख", sound: "kha", matra: "अ" },
      { syllable: "खा", sound: "khaa", matra: "आ" },
      { syllable: "खि", sound: "khi", matra: "इ" },
      { syllable: "खी", sound: "khee", matra: "ई" },
      { syllable: "खु", sound: "khu", matra: "उ" },
      { syllable: "खू", sound: "khoo", matra: "ऊ" },
      { syllable: "खे", sound: "khe", matra: "ए" },
      { syllable: "खै", sound: "khai", matra: "ऐ" },
      { syllable: "खो", sound: "kho", matra: "ओ" },
      { syllable: "खौ", sound: "khau", matra: "औ" },
      { syllable: "खं", sound: "kham", matra: "ं" },
      { syllable: "खः", sound: "khah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "खाना", english: "Food", roman: "khana" },
      { hindi: "खेल", english: "Game", roman: "khel" },
      { hindi: "खुश", english: "Happy", roman: "khush" },
    ],
    wordHindi: "खाना",
    wordEnglish: "Food",
    wordRoman: "khana",
    assetPath: "/assets/gemini/vaani_l4_kha_barakhadi_1777200025.png",
    summary: "The aspirated version of क - notice the breath!",
    prompt: "Same pattern, different sound - aspirated!",
  },
  {
    id: "L4-C01-L03",
    chapterId: "C01",
    chapterTitle: "Barakhadi for क-वर्ग",
    title: "ग की बारहखड़ी - Ga barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "ग",
    consonantRoman: "ga",
    barakhadiRow: [
      { syllable: "ग", sound: "ga", matra: "अ" },
      { syllable: "गा", sound: "gaa", matra: "आ" },
      { syllable: "गि", sound: "gi", matra: "इ" },
      { syllable: "गी", sound: "gee", matra: "ई" },
      { syllable: "गु", sound: "gu", matra: "उ" },
      { syllable: "गू", sound: "goo", matra: "ऊ" },
      { syllable: "गे", sound: "ge", matra: "ए" },
      { syllable: "गै", sound: "gai", matra: "ऐ" },
      { syllable: "गो", sound: "go", matra: "ओ" },
      { syllable: "गौ", sound: "gau", matra: "औ" },
      { syllable: "गं", sound: "gam", matra: "ं" },
      { syllable: "गः", sound: "gah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "गाना", english: "Singing", roman: "gana" },
      { hindi: "गोद", english: "Lap", roman: "god" },
      { hindi: "गुलाब", english: "Rose", roman: "gulab" },
    ],
    wordHindi: "गाना",
    wordEnglish: "Singing",
    wordRoman: "gana",
    assetPath: "/assets/gemini/vaani_l4_ga_barakhadi_1777200049.png",
    summary: "Unaspirated velar stop - softer than क.",
    prompt: "ग is softer - feel the difference!",
  },
  {
    id: "L4-C01-L04",
    chapterId: "C01",
    chapterTitle: "Barakhadi for क-वर्ग",
    title: "घ की बारहखड़ी - Gha barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "घ",
    consonantRoman: "gha",
    barakhadiRow: [
      { syllable: "घ", sound: "gha", matra: "अ" },
      { syllable: "घा", sound: "ghaa", matra: "आ" },
      { syllable: "घि", sound: "ghi", matra: "इ" },
      { syllable: "घी", sound: "ghee", matra: "ई" },
      { syllable: "घु", sound: "ghu", matra: "उ" },
      { syllable: "घू", sound: "ghoo", matra: "ऊ" },
      { syllable: "घे", sound: "ghe", matra: "ए" },
      { syllable: "घै", sound: "ghai", matra: "ऐ" },
      { syllable: "घो", sound: "gho", matra: "ओ" },
      { syllable: "घौ", sound: "ghau", matra: "औ" },
      { syllable: "घं", sound: "gham", matra: "ं" },
      { syllable: "घः", sound: "ghah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "घर", english: "House", roman: "ghar" },
      { hindi: "घी", english: "Ghee", roman: "ghee" },
      { hindi: "घोड़ा", english: "Horse", roman: "ghoda" },
    ],
    wordHindi: "घर",
    wordEnglish: "House",
    wordRoman: "ghar",
    assetPath: "/assets/gemini/vaani_l4_gha_barakhadi_1777200073.png",
    summary: "Aspirated velar - the heavy version!",
    prompt: "घ is aspirated - more breath!",
  },
  {
    id: "L4-C01-L05",
    chapterId: "C01",
    chapterTitle: "Barakhadi for च-वर्ग",
    title: "च की बारहखड़ी - Cha barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "च",
    consonantRoman: "cha",
    barakhadiRow: [
      { syllable: "च", sound: "cha", matra: "अ" },
      { syllable: "चा", sound: "chaa", matra: "आ" },
      { syllable: "चि", sound: "chi", matra: "इ" },
      { syllable: "ची", sound: "chee", matra: "ई" },
      { syllable: "चु", sound: "chu", matra: "उ" },
      { syllable: "चू", sound: "choo", matra: "ऊ" },
      { syllable: "चे", sound: "che", matra: "ए" },
      { syllable: "चै", sound: "chai", matra: "ऐ" },
      { syllable: "चो", sound: "cho", matra: "ओ" },
      { syllable: "चौ", sound: "chau", matra: "औ" },
      { syllable: "चं", sound: "cham", matra: "ं" },
      { syllable: "चः", sound: "chah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "चाय", english: "Tea", roman: "chai" },
      { hindi: "चेहरा", english: "Face", roman: "chehra" },
      { hindi: "चूल्हा", english: "Stove", roman: "chulha" },
    ],
    wordHindi: "चाय",
    wordEnglish: "Tea",
    wordRoman: "chai",
    assetPath: "/assets/gemini/vaani_l4_cha_barakhadi_1777200097.png",
    summary: "Unaspirated palatal affricate.",
    prompt: "च is soft and whispering!",
  },
  {
    id: "L4-C01-L06",
    chapterId: "C01",
    chapterTitle: "Barakhadi for च-वर्ग",
    title: "छ की बारहखड़ी - Cha (aspir) barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "छ",
    consonantRoman: "chha",
    barakhadiRow: [
      { syllable: "छ", sound: "chha", matra: "अ" },
      { syllable: "छा", sound: "chhaa", matra: "आ" },
      { syllable: "छि", sound: "chhi", matra: "इ" },
      { syllable: "छी", sound: "chhee", matra: "ई" },
      { syllable: "छु", sound: "chhu", matra: "उ" },
      { syllable: "छू", sound: "chhoo", matra: "ऊ" },
      { syllable: "छे", sound: "chhe", matra: "ए" },
      { syllable: "छै", sound: "chhai", matra: "ऐ" },
      { syllable: "छो", sound: "chho", matra: "ओ" },
      { syllable: "छौ", sound: "chhau", matra: "औ" },
      { syllable: "छं", sound: "chham", matra: "ं" },
      { syllable: "छः", sound: "chhah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "छत", english: "Roof", roman: "chat" },
      { hindi: "छबि", english: "Image", roman: "chabi" },
      { hindi: "छात्र", english: "Student", roman: "chhatr" },
    ],
    wordHindi: "छत",
    wordEnglish: "Roof",
    wordRoman: "chat",
    assetPath: "/assets/gemini/vaani_l4_chha_barakhadi_1777200121.png",
    summary: "Aspirated palatal affricate.",
    prompt: "छ is sharp and clear!",
  },
  {
    id: "L4-C01-L07",
    chapterId: "C01",
    chapterTitle: "Barakhadi for ट-वर्ग",
    title: "ट की बारहखड़ी - Ta (retroflex) barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "ट",
    consonantRoman: "ta",
    barakhadiRow: [
      { syllable: "ट", sound: "ta", matra: "अ" },
      { syllable: "टा", sound: "taa", matra: "आ" },
      { syllable: "टि", sound: "ti", matra: "इ" },
      { syllable: "टी", sound: "tee", matra: "ई" },
      { syllable: "टु", sound: "tu", matra: "उ" },
      { syllable: "टू", sound: "too", matra: "ऊ" },
      { syllable: "टे", sound: "te", matra: "ए" },
      { syllable: "टै", sound: "tai", matra: "ऐ" },
      { syllable: "टो", sound: "to", matra: "ओ" },
      { syllable: "टौ", sound: "tau", matra: "औ" },
      { syllable: "टं", sound: "tam", matra: "ं" },
      { syllable: "टः", sound: "tah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "टीका", english: "Mark", roman: "tika" },
      { hindi: "टुकड़ा", english: "Piece", roman: "tukda" },
      { hindi: "टोप", english: "Cap", roman: "top" },
    ],
    wordHindi: "टीका",
    wordEnglish: "Mark",
    wordRoman: "tika",
    assetPath: "/assets/gemini/vaani_l4_ta_retrofit_barakhadi_1777200145.png",
    summary: "Retroflex unaspirated stop - tongue curled!",
    prompt: "ट has a clicking sound!",
  },
  {
    id: "L4-C01-L08",
    chapterId: "C01",
    chapterTitle: "Barakhadi for ट-वर्ग",
    title: "ठ की बारहखड़ी - Tha (aspir retroflex) barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "ठ",
    consonantRoman: "tha",
    barakhadiRow: [
      { syllable: "ठ", sound: "tha", matra: "अ" },
      { syllable: "ठा", sound: "thaa", matra: "आ" },
      { syllable: "ठि", sound: "thi", matra: "इ" },
      { syllable: "ठी", sound: "thee", matra: "ई" },
      { syllable: "ठु", sound: "thu", matra: "उ" },
      { syllable: "ठू", sound: "thoo", matra: "ऊ" },
      { syllable: "ठे", sound: "the", matra: "ए" },
      { syllable: "ठै", sound: "thai", matra: "ऐ" },
      { syllable: "ठो", sound: "tho", matra: "ओ" },
      { syllable: "ठौ", sound: "thau", matra: "औ" },
      { syllable: "ठं", sound: "tham", matra: "ं" },
      { syllable: "ठः", sound: "thah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "ठंड", english: "Cold", roman: "thandi" },
      { hindi: "ठाकुर", english: "Lord", roman: "thakur" },
      { hindi: "ठीक", english: "Right", roman: "theek" },
    ],
    wordHindi: "ठंड",
    wordEnglish: "Cold",
    wordRoman: "thandi",
    assetPath: "/assets/gemini/vaani_l4_tha_aspir_retrofit_barakhadi_1777200169.png",
    summary: "Retroflex aspirated stop.",
    prompt: "ठ is deep and strong!",
  },
  {
    id: "L4-C01-L09",
    chapterId: "C01",
    chapterTitle: "Barakhadi for ड-वर्ग",
    title: "ड की बारहखड़ी - Da (retroflex) barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "ड",
    consonantRoman: "da",
    barakhadiRow: [
      { syllable: "ड", sound: "da", matra: "अ" },
      { syllable: "डा", sound: "daa", matra: "आ" },
      { syllable: "डि", sound: "di", matra: "इ" },
      { syllable: "डी", sound: "dee", matra: "ई" },
      { syllable: "डु", sound: "du", matra: "उ" },
      { syllable: "डू", sound: "doo", matra: "ऊ" },
      { syllable: "डे", sound: "de", matra: "ए" },
      { syllable: "डै", sound: "dai", matra: "ऐ" },
      { syllable: "डो", sound: "do", matra: "ओ" },
      { syllable: "डौ", sound: "dau", matra: "औ" },
      { syllable: "डं", sound: "dam", matra: "ं" },
      { syllable: "डः", sound: "dah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "डाक", english: "Mail", roman: "dak" },
      { hindi: "डर", english: "Fear", roman: "dar" },
      { hindi: "डिब्बा", english: "Box", roman: "dibba" },
    ],
    wordHindi: "डाक",
    wordEnglish: "Mail",
    wordRoman: "dak",
    assetPath: "/assets/gemini/vaani_l4_da_retrofit_barakhadi_1777200193.png",
    summary: "Retroflex unaspirated voiced stop.",
    prompt: "ड has a rolling sound!",
  },
  {
    id: "L4-C01-L10",
    chapterId: "C01",
    chapterTitle: "Barakhadi for ड-वर्ग",
    title: "ढ की बारहखड़ी - Dha (aspir retroflex) barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "ढ",
    consonantRoman: "dha",
    barakhadiRow: [
      { syllable: "ढ", sound: "dha", matra: "अ" },
      { syllable: "ढा", sound: "dhaa", matra: "आ" },
      { syllable: "ढि", sound: "dhi", matra: "इ" },
      { syllable: "ढी", sound: "dhee", matra: "ई" },
      { syllable: "ढु", sound: "dhu", matra: "उ" },
      { syllable: "ढू", sound: "dhoo", matra: "ऊ" },
      { syllable: "ढे", sound: "dhe", matra: "ए" },
      { syllable: "ढै", sound: "dhai", matra: "ऐ" },
      { syllable: "ढो", sound: "dho", matra: "ओ" },
      { syllable: "ढौ", sound: "dhau", matra: "औ" },
      { syllable: "ढं", sound: "dham", matra: "ं" },
      { syllable: "ढः", sound: "dhah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "ढाल", english: "Shield", roman: "dhal" },
      { hindi: "ढेर", english: "Heap", roman: "dher" },
      { hindi: "ढोल", english: "Drum", roman: "dhol" },
    ],
    wordHindi: "ढोल",
    wordEnglish: "Drum",
    wordRoman: "dhol",
    assetPath: "/assets/gemini/vaani_l4_dha_aspir_retrofit_barakhadi_1777200217.png",
    summary: "Retroflex aspirated voiced stop.",
    prompt: "ढ is resonant and deep!",
  },
  {
    id: "L4-C01-L11",
    chapterId: "C01",
    chapterTitle: "Barakhadi for त-वर्ग",
    title: "त की बारहखड़ी - Ta (dental) barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "त",
    consonantRoman: "ta",
    barakhadiRow: [
      { syllable: "त", sound: "ta", matra: "अ" },
      { syllable: "ता", sound: "taa", matra: "आ" },
      { syllable: "ति", sound: "ti", matra: "इ" },
      { syllable: "ती", sound: "tee", matra: "ई" },
      { syllable: "तु", sound: "tu", matra: "उ" },
      { syllable: "तू", sound: "too", matra: "ऊ" },
      { syllable: "ते", sound: "te", matra: "ए" },
      { syllable: "तै", sound: "tai", matra: "ऐ" },
      { syllable: "तो", sound: "to", matra: "ओ" },
      { syllable: "तौ", sound: "tau", matra: "औ" },
      { syllable: "तं", sound: "tam", matra: "ं" },
      { syllable: "तः", sound: "tah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "तारा", english: "Star", roman: "tara" },
      { hindi: "तीन", english: "Three", roman: "teen" },
      { hindi: "तोता", english: "Parrot", roman: "tota" },
    ],
    wordHindi: "तारा",
    wordEnglish: "Star",
    wordRoman: "tara",
    assetPath: "/assets/gemini/vaani_l4_ta_dental_barakhadi_1777200241.png",
    summary: "Dental unaspirated stop - different from ट!",
    prompt: "त is dental - notice the tooth placement!",
  },
  {
    id: "L4-C01-L12",
    chapterId: "C01",
    chapterTitle: "Barakhadi for त-वर्ग - Consolidation",
    title: "Barakhadi Consolidation Review",
    category: "Consolidation",
    skill: "Barakhadi Mastery",
    consonant: "क",
    consonantRoman: "ka",
    barakhadiRow: [
      { syllable: "क", sound: "ka", matra: "अ" },
      { syllable: "का", sound: "kaa", matra: "आ" },
      { syllable: "कि", sound: "ki", matra: "इ" },
      { syllable: "की", sound: "kee", matra: "ई" },
      { syllable: "कु", sound: "ku", matra: "उ" },
      { syllable: "कू", sound: "koo", matra: "ऊ" },
      { syllable: "के", sound: "ke", matra: "ए" },
      { syllable: "कै", sound: "kai", matra: "ऐ" },
      { syllable: "को", sound: "ko", matra: "ओ" },
      { syllable: "कौ", sound: "kau", matra: "औ" },
      { syllable: "कं", sound: "kam", matra: "ं" },
      { syllable: "कः", sound: "kah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "पढ़ना", english: "Read", roman: "padhna" },
      { hindi: "समझ", english: "Understand", roman: "samajh" },
      { hindi: "याद", english: "Remember", roman: "yaad" },
    ],
    wordHindi: "पढ़ना",
    wordEnglish: "Read",
    wordRoman: "padhna",
    assetPath: "/assets/gemini/vaani_l4_review_consolidation_1777200265.png",
    summary: "You now understand the barakhadi pattern for all consonants!",
    prompt: "The pattern is your superpower!",
  },

  // Continuing with remaining consonants...
  // (Due to length, showing pattern - add th, dh, d, dh, p, ph, b, bh, m, y, r, l, v, sh, sh, s, h)
  {
    id: "L4-C02-L01",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "थ की बारहखड़ी - Tha (dental aspir) barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "थ",
    consonantRoman: "tha",
    barakhadiRow: [
      { syllable: "थ", sound: "tha", matra: "अ" },
      { syllable: "था", sound: "thaa", matra: "आ" },
      { syllable: "थि", sound: "thi", matra: "इ" },
      { syllable: "थी", sound: "thee", matra: "ई" },
      { syllable: "थु", sound: "thu", matra: "उ" },
      { syllable: "थू", sound: "thoo", matra: "ऊ" },
      { syllable: "थे", sound: "the", matra: "ए" },
      { syllable: "थै", sound: "thai", matra: "ऐ" },
      { syllable: "थो", sound: "tho", matra: "ओ" },
      { syllable: "थौ", sound: "thau", matra: "औ" },
      { syllable: "थं", sound: "tham", matra: "ं" },
      { syllable: "थः", sound: "thah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "थक", english: "Tired", roman: "thak" },
      { hindi: "थाली", english: "Plate", roman: "thali" },
      { hindi: "थूक", english: "Spit", roman: "thook" },
    ],
    wordHindi: "थाली",
    wordEnglish: "Plate",
    wordRoman: "thali",
    assetPath: "/assets/gemini/vaani_l4_tha_dental_aspir_barakhadi_1777200289.png",
    summary: "Dental aspirated stop.",
    prompt: "थ is dental and aspirated!",
  },
  {
    id: "L4-C02-L02",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "द की बारहखड़ी - Da (dental) barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "द",
    consonantRoman: "da",
    barakhadiRow: [
      { syllable: "द", sound: "da", matra: "अ" },
      { syllable: "दा", sound: "daa", matra: "आ" },
      { syllable: "दि", sound: "di", matra: "इ" },
      { syllable: "दी", sound: "dee", matra: "ई" },
      { syllable: "दु", sound: "du", matra: "उ" },
      { syllable: "दू", sound: "doo", matra: "ऊ" },
      { syllable: "दे", sound: "de", matra: "ए" },
      { syllable: "दै", sound: "dai", matra: "ऐ" },
      { syllable: "दो", sound: "do", matra: "ओ" },
      { syllable: "दौ", sound: "dau", matra: "औ" },
      { syllable: "दं", sound: "dam", matra: "ं" },
      { syllable: "दः", sound: "dah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "दाना", english: "Grain", roman: "dana" },
      { hindi: "दिन", english: "Day", roman: "din" },
      { hindi: "दोष", english: "Fault", roman: "dosh" },
    ],
    wordHindi: "दिन",
    wordEnglish: "Day",
    wordRoman: "din",
    assetPath: "/assets/gemini/vaani_l4_da_dental_barakhadi_1777200313.png",
    summary: "Dental unaspirated voiced stop.",
    prompt: "द is dental and voiced!",
  },
  {
    id: "L4-C02-L03",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "ध की बारहखड़ी - Dha (dental aspir) barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "ध",
    consonantRoman: "dha",
    barakhadiRow: [
      { syllable: "ध", sound: "dha", matra: "अ" },
      { syllable: "धा", sound: "dhaa", matra: "आ" },
      { syllable: "धि", sound: "dhi", matra: "इ" },
      { syllable: "धी", sound: "dhee", matra: "ई" },
      { syllable: "धु", sound: "dhu", matra: "उ" },
      { syllable: "धू", sound: "dhoo", matra: "ऊ" },
      { syllable: "धे", sound: "dhe", matra: "ए" },
      { syllable: "धै", sound: "dhai", matra: "ऐ" },
      { syllable: "धो", sound: "dho", matra: "ओ" },
      { syllable: "धौ", sound: "dhau", matra: "औ" },
      { syllable: "धं", sound: "dham", matra: "ं" },
      { syllable: "धः", sound: "dhah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "धन", english: "Money", roman: "dhan" },
      { hindi: "धीर", english: "Patient", roman: "dheer" },
      { hindi: "धोना", english: "Wash", roman: "dhona" },
    ],
    wordHindi: "धन",
    wordEnglish: "Money",
    wordRoman: "dhan",
    assetPath: "/assets/gemini/vaani_l4_dha_dental_aspir_barakhadi_1777200337.png",
    summary: "Dental aspirated voiced stop.",
    prompt: "ध is dental and aspirated!",
  },
  {
    id: "L4-C02-L04",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "प की बारहखड़ी - Pa barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "प",
    consonantRoman: "pa",
    barakhadiRow: [
      { syllable: "प", sound: "pa", matra: "अ" },
      { syllable: "पा", sound: "paa", matra: "आ" },
      { syllable: "पि", sound: "pi", matra: "इ" },
      { syllable: "पी", sound: "pee", matra: "ई" },
      { syllable: "पु", sound: "pu", matra: "उ" },
      { syllable: "पू", sound: "poo", matra: "ऊ" },
      { syllable: "पे", sound: "pe", matra: "ए" },
      { syllable: "पै", sound: "pai", matra: "ऐ" },
      { syllable: "पो", sound: "po", matra: "ओ" },
      { syllable: "पौ", sound: "pau", matra: "औ" },
      { syllable: "पं", sound: "pam", matra: "ं" },
      { syllable: "पः", sound: "pah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "पानी", english: "Water", roman: "pani" },
      { hindi: "पेड़", english: "Tree", roman: "ped" },
      { hindi: "पोता", english: "Grandson", roman: "pota" },
    ],
    wordHindi: "पानी",
    wordEnglish: "Water",
    wordRoman: "pani",
    assetPath: "/assets/gemini/vaani_l4_pa_barakhadi_1777200361.png",
    summary: "Unaspirated bilabial stop.",
    prompt: "प is bilabial!",
  },
  {
    id: "L4-C02-L05",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "फ की बारहखड़ी - Pha barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "फ",
    consonantRoman: "pha",
    barakhadiRow: [
      { syllable: "फ", sound: "pha", matra: "अ" },
      { syllable: "फा", sound: "phaa", matra: "आ" },
      { syllable: "फि", sound: "phi", matra: "इ" },
      { syllable: "फी", sound: "phee", matra: "ई" },
      { syllable: "फु", sound: "phu", matra: "उ" },
      { syllable: "फू", sound: "phoo", matra: "ऊ" },
      { syllable: "फे", sound: "phe", matra: "ए" },
      { syllable: "फै", sound: "phai", matra: "ऐ" },
      { syllable: "फो", sound: "pho", matra: "ओ" },
      { syllable: "फौ", sound: "phau", matra: "औ" },
      { syllable: "फं", sound: "pham", matra: "ं" },
      { syllable: "फः", sound: "phah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "फल", english: "Fruit", roman: "phal" },
      { hindi: "फिर", english: "Again", roman: "phir" },
      { hindi: "फोन", english: "Phone", roman: "fon" },
    ],
    wordHindi: "फल",
    wordEnglish: "Fruit",
    wordRoman: "phal",
    assetPath: "/assets/gemini/vaani_l4_pha_barakhadi_1777200385.png",
    summary: "Aspirated bilabial stop.",
    prompt: "फ is aspirated bilabial!",
  },
  {
    id: "L4-C02-L06",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "ब की बारहखड़ी - Ba barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "ब",
    consonantRoman: "ba",
    barakhadiRow: [
      { syllable: "ब", sound: "ba", matra: "अ" },
      { syllable: "बा", sound: "baa", matra: "आ" },
      { syllable: "बि", sound: "bi", matra: "इ" },
      { syllable: "बी", sound: "bee", matra: "ई" },
      { syllable: "बु", sound: "bu", matra: "उ" },
      { syllable: "बू", sound: "boo", matra: "ऊ" },
      { syllable: "बे", sound: "be", matra: "ए" },
      { syllable: "बै", sound: "bai", matra: "ऐ" },
      { syllable: "बो", sound: "bo", matra: "ओ" },
      { syllable: "बौ", sound: "bau", matra: "औ" },
      { syllable: "बं", sound: "bam", matra: "ं" },
      { syllable: "बः", sound: "bah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "बाजार", english: "Market", roman: "bazaar" },
      { hindi: "बिल्ली", english: "Cat", roman: "billi" },
      { hindi: "बोझ", english: "Burden", roman: "bojh" },
    ],
    wordHindi: "बाजार",
    wordEnglish: "Market",
    wordRoman: "bazaar",
    assetPath: "/assets/gemini/vaani_l4_ba_barakhadi_1777200409.png",
    summary: "Unaspirated bilabial voiced stop.",
    prompt: "ब is voiced bilabial!",
  },
  {
    id: "L4-C02-L07",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "भ की बारहखड़ी - Bha barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "भ",
    consonantRoman: "bha",
    barakhadiRow: [
      { syllable: "भ", sound: "bha", matra: "अ" },
      { syllable: "भा", sound: "bhaa", matra: "आ" },
      { syllable: "भि", sound: "bhi", matra: "इ" },
      { syllable: "भी", sound: "bhee", matra: "ई" },
      { syllable: "भु", sound: "bhu", matra: "उ" },
      { syllable: "भू", sound: "bhoo", matra: "ऊ" },
      { syllable: "भे", sound: "bhe", matra: "ए" },
      { syllable: "भै", sound: "bhai", matra: "ऐ" },
      { syllable: "भो", sound: "bho", matra: "ओ" },
      { syllable: "भौ", sound: "bhau", matra: "औ" },
      { syllable: "भं", sound: "bham", matra: "ं" },
      { syllable: "भः", sound: "bhah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "भाग", english: "Part", roman: "bhag" },
      { hindi: "भीड़", english: "Crowd", roman: "bhid" },
      { hindi: "भोजन", english: "Food", roman: "bhojan" },
    ],
    wordHindi: "भाग",
    wordEnglish: "Part",
    wordRoman: "bhag",
    assetPath: "/assets/gemini/vaani_l4_bha_barakhadi_1777200433.png",
    summary: "Aspirated bilabial voiced stop.",
    prompt: "भ is aspirated voiced bilabial!",
  },
  {
    id: "L4-C02-L08",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "म की बारहखड़ी - Ma barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "म",
    consonantRoman: "ma",
    barakhadiRow: [
      { syllable: "म", sound: "ma", matra: "अ" },
      { syllable: "मा", sound: "maa", matra: "आ" },
      { syllable: "मि", sound: "mi", matra: "इ" },
      { syllable: "मी", sound: "mee", matra: "ई" },
      { syllable: "मु", sound: "mu", matra: "उ" },
      { syllable: "मू", sound: "moo", matra: "ऊ" },
      { syllable: "मे", sound: "me", matra: "ए" },
      { syllable: "मै", sound: "mai", matra: "ऐ" },
      { syllable: "मो", sound: "mo", matra: "ओ" },
      { syllable: "मौ", sound: "mau", matra: "औ" },
      { syllable: "मं", sound: "mam", matra: "ं" },
      { syllable: "मः", sound: "mah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "माता", english: "Mother", roman: "mata" },
      { hindi: "मिठाई", english: "Sweets", roman: "mithai" },
      { hindi: "मोती", english: "Pearl", roman: "moti" },
    ],
    wordHindi: "माता",
    wordEnglish: "Mother",
    wordRoman: "mata",
    assetPath: "/assets/gemini/vaani_l4_ma_barakhadi_1777200457.png",
    summary: "Nasal stop.",
    prompt: "म is nasal!",
  },
  {
    id: "L4-C02-L09",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "य की बारहखड़ी - Ya barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "य",
    consonantRoman: "ya",
    barakhadiRow: [
      { syllable: "य", sound: "ya", matra: "अ" },
      { syllable: "या", sound: "yaa", matra: "आ" },
      { syllable: "यि", sound: "yi", matra: "इ" },
      { syllable: "यी", sound: "yee", matra: "ई" },
      { syllable: "यु", sound: "yu", matra: "उ" },
      { syllable: "यू", sound: "yoo", matra: "ऊ" },
      { syllable: "ये", sound: "ye", matra: "ए" },
      { syllable: "यै", sound: "yai", matra: "ऐ" },
      { syllable: "यो", sound: "yo", matra: "ओ" },
      { syllable: "यौ", sound: "yau", matra: "औ" },
      { syllable: "यं", sound: "yam", matra: "ं" },
      { syllable: "यः", sound: "yah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "यमुना", english: "River", roman: "yamuna" },
      { hindi: "यशस्वी", english: "Successful", roman: "yashasvi" },
      { hindi: "योग", english: "Yoga", roman: "yog" },
    ],
    wordHindi: "योग",
    wordEnglish: "Yoga",
    wordRoman: "yog",
    assetPath: "/assets/gemini/vaani_l4_ya_barakhadi_1777200481.png",
    summary: "Palatal glide.",
    prompt: "य is a glide!",
  },
  {
    id: "L4-C02-L10",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "र की बारहखड़ी - Ra barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "र",
    consonantRoman: "ra",
    barakhadiRow: [
      { syllable: "र", sound: "ra", matra: "अ" },
      { syllable: "रा", sound: "raa", matra: "आ" },
      { syllable: "रि", sound: "ri", matra: "इ" },
      { syllable: "री", sound: "ree", matra: "ई" },
      { syllable: "रु", sound: "ru", matra: "उ" },
      { syllable: "रू", sound: "roo", matra: "ऊ" },
      { syllable: "रे", sound: "re", matra: "ए" },
      { syllable: "रै", sound: "rai", matra: "ऐ" },
      { syllable: "रो", sound: "ro", matra: "ओ" },
      { syllable: "रौ", sound: "rau", matra: "औ" },
      { syllable: "रं", sound: "ram", matra: "ं" },
      { syllable: "रः", sound: "rah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "राजा", english: "King", roman: "raja" },
      { hindi: "रीति", english: "Tradition", roman: "riti" },
      { hindi: "रोग", english: "Disease", roman: "rog" },
    ],
    wordHindi: "राजा",
    wordEnglish: "King",
    wordRoman: "raja",
    assetPath: "/assets/gemini/vaani_l4_ra_barakhadi_1777200505.png",
    summary: "Retroflex approximant.",
    prompt: "र is the rolling liquid!",
  },
  {
    id: "L4-C02-L11",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "ल की बारहखड़ी - La barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "ल",
    consonantRoman: "la",
    barakhadiRow: [
      { syllable: "ल", sound: "la", matra: "अ" },
      { syllable: "ला", sound: "laa", matra: "आ" },
      { syllable: "लि", sound: "li", matra: "इ" },
      { syllable: "ली", sound: "lee", matra: "ई" },
      { syllable: "लु", sound: "lu", matra: "उ" },
      { syllable: "लू", sound: "loo", matra: "ऊ" },
      { syllable: "ले", sound: "le", matra: "ए" },
      { syllable: "लै", sound: "lai", matra: "ऐ" },
      { syllable: "लो", sound: "lo", matra: "ओ" },
      { syllable: "लौ", sound: "lau", matra: "औ" },
      { syllable: "लं", sound: "lam", matra: "ं" },
      { syllable: "लः", sound: "lah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "लड़का", english: "Boy", roman: "ladka" },
      { hindi: "लिखना", english: "Write", roman: "likhna" },
      { hindi: "लोग", english: "People", roman: "log" },
    ],
    wordHindi: "लड़का",
    wordEnglish: "Boy",
    wordRoman: "ladka",
    assetPath: "/assets/gemini/vaani_l4_la_barakhadi_1777200529.png",
    summary: "Alveolar approximant.",
    prompt: "ल is the other liquid!",
  },
  {
    id: "L4-C02-L12",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "व की बारहखड़ी - Va barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "व",
    consonantRoman: "va",
    barakhadiRow: [
      { syllable: "व", sound: "va", matra: "अ" },
      { syllable: "वा", sound: "vaa", matra: "आ" },
      { syllable: "वि", sound: "vi", matra: "इ" },
      { syllable: "वी", sound: "vee", matra: "ई" },
      { syllable: "वु", sound: "vu", matra: "उ" },
      { syllable: "वू", sound: "voo", matra: "ऊ" },
      { syllable: "वे", sound: "ve", matra: "ए" },
      { syllable: "वै", sound: "vai", matra: "ऐ" },
      { syllable: "वो", sound: "vo", matra: "ओ" },
      { syllable: "वौ", sound: "vau", matra: "औ" },
      { syllable: "वं", sound: "vam", matra: "ं" },
      { syllable: "वः", sound: "vah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "वाणी", english: "Speech", roman: "vani" },
      { hindi: "विद्या", english: "Knowledge", roman: "vidya" },
      { hindi: "वोट", english: "Vote", roman: "vote" },
    ],
    wordHindi: "वाणी",
    wordEnglish: "Speech",
    wordRoman: "vani",
    assetPath: "/assets/gemini/vaani_l4_va_barakhadi_1777200554.png",
    summary: "Labiovelar approximant.",
    prompt: "व is a versatile consonant!",
  },
  {
    id: "L4-C02-L13",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "श की बारहखड़ी - Sha barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "श",
    consonantRoman: "sha",
    barakhadiRow: [
      { syllable: "श", sound: "sha", matra: "अ" },
      { syllable: "शा", sound: "shaa", matra: "आ" },
      { syllable: "शि", sound: "shi", matra: "इ" },
      { syllable: "शी", sound: "shee", matra: "ई" },
      { syllable: "शु", sound: "shu", matra: "उ" },
      { syllable: "शू", sound: "shoo", matra: "ऊ" },
      { syllable: "शे", sound: "she", matra: "ए" },
      { syllable: "शै", sound: "shai", matra: "ऐ" },
      { syllable: "शो", sound: "sho", matra: "ओ" },
      { syllable: "शौ", sound: "shau", matra: "औ" },
      { syllable: "शं", sound: "sham", matra: "ं" },
      { syllable: "शः", sound: "shah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "शक्ति", english: "Power", roman: "shakti" },
      { hindi: "शहर", english: "City", roman: "shahar" },
      { hindi: "शांति", english: "Peace", roman: "shanti" },
    ],
    wordHindi: "शक्ति",
    wordEnglish: "Power",
    wordRoman: "shakti",
    assetPath: "/assets/gemini/vaani_l4_sha_barakhadi_1777200555.png",
    summary: "Palatal fricative.",
    prompt: "श brings grace and power!",
  },
  {
    id: "L4-C02-L14",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "ष की बारहखड़ी - Retroflex Sha barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "ष",
    consonantRoman: "sha",
    barakhadiRow: [
      { syllable: "ष", sound: "sha", matra: "अ" },
      { syllable: "षा", sound: "shaa", matra: "आ" },
      { syllable: "षि", sound: "shi", matra: "इ" },
      { syllable: "षी", sound: "shee", matra: "ई" },
      { syllable: "षु", sound: "shu", matra: "उ" },
      { syllable: "षू", sound: "shoo", matra: "ऊ" },
      { syllable: "षे", sound: "she", matra: "ए" },
      { syllable: "षै", sound: "shai", matra: "ऐ" },
      { syllable: "षो", sound: "sho", matra: "ओ" },
      { syllable: "षौ", sound: "shau", matra: "औ" },
      { syllable: "षं", sound: "sham", matra: "ं" },
      { syllable: "षः", sound: "shah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "षष्ठी", english: "Sixth", roman: "shashthi" },
      { hindi: "पषाण", english: "Stone", roman: "pashan" },
      { hindi: "षड़यंत्र", english: "Conspiracy", roman: "shadyantra" },
    ],
    wordHindi: "षष्ठी",
    wordEnglish: "Sixth",
    wordRoman: "shashthi",
    assetPath: "/assets/gemini/vaani_l4_retroflex_sha_barakhadi_1777200556.png",
    summary: "Retroflex fricative.",
    prompt: "ष is the retroflex version of श!",
  },
  {
    id: "L4-C02-L15",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "स की बारहखड़ी - Sa barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "स",
    consonantRoman: "sa",
    barakhadiRow: [
      { syllable: "स", sound: "sa", matra: "अ" },
      { syllable: "सा", sound: "saa", matra: "आ" },
      { syllable: "सि", sound: "si", matra: "इ" },
      { syllable: "सी", sound: "see", matra: "ई" },
      { syllable: "सु", sound: "su", matra: "उ" },
      { syllable: "सू", sound: "soo", matra: "ऊ" },
      { syllable: "से", sound: "se", matra: "ए" },
      { syllable: "सै", sound: "sai", matra: "ऐ" },
      { syllable: "सो", sound: "so", matra: "ओ" },
      { syllable: "सौ", sound: "sau", matra: "औ" },
      { syllable: "सं", sound: "sam", matra: "ं" },
      { syllable: "सः", sound: "sah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "सूरज", english: "Sun", roman: "suraj" },
      { hindi: "समय", english: "Time", roman: "samay" },
      { hindi: "सुंदर", english: "Beautiful", roman: "sundar" },
    ],
    wordHindi: "सूरज",
    wordEnglish: "Sun",
    wordRoman: "suraj",
    assetPath: "/assets/gemini/vaani_l4_sa_barakhadi_1777200557.png",
    summary: "Dental fricative.",
    prompt: "स is the gentle sibilant!",
  },
  {
    id: "L4-C02-L16",
    chapterId: "C02",
    chapterTitle: "Barakhadi for remaining consonants",
    title: "ह की बारहखड़ी - Ha barakhadi",
    category: "Syllable Matrix",
    skill: "Complete Consonant Mastery",
    consonant: "ह",
    consonantRoman: "ha",
    barakhadiRow: [
      { syllable: "ह", sound: "ha", matra: "अ" },
      { syllable: "हा", sound: "haa", matra: "आ" },
      { syllable: "हि", sound: "hi", matra: "इ" },
      { syllable: "ही", sound: "hee", matra: "ई" },
      { syllable: "हु", sound: "hu", matra: "उ" },
      { syllable: "हू", sound: "hoo", matra: "ऊ" },
      { syllable: "हे", sound: "he", matra: "ए" },
      { syllable: "है", sound: "hai", matra: "ऐ" },
      { syllable: "हो", sound: "ho", matra: "ओ" },
      { syllable: "हौ", sound: "hau", matra: "औ" },
      { syllable: "हं", sound: "ham", matra: "ं" },
      { syllable: "हः", sound: "hah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "हाथ", english: "Hand", roman: "hath" },
      { hindi: "हृदय", english: "Heart", roman: "hriday" },
      { hindi: "हँसना", english: "Laugh", roman: "hasna" },
    ],
    wordHindi: "हाथ",
    wordEnglish: "Hand",
    wordRoman: "hath",
    assetPath: "/assets/gemini/vaani_l4_ha_barakhadi_1777200558.png",
    summary: "Glottal fricative.",
    prompt: "ह is the breath of Hindi!",
  },
  {
    id: "L4-C02-L17",
    chapterId: "C02",
    chapterTitle: "Barakhadi Consolidation",
    title: "Consonant Pairs Review - क & ख",
    category: "Review Practice",
    skill: "Barakhadi Mastery",
    consonant: "क & ख",
    consonantRoman: "ka-kha",
    barakhadiRow: [
      { syllable: "क/ख", sound: "ka/kha", matra: "अ" },
      { syllable: "का/खा", sound: "kaa/khaa", matra: "आ" },
      { syllable: "कि/खि", sound: "ki/khi", matra: "इ" },
      { syllable: "की/खी", sound: "kee/khee", matra: "ई" },
      { syllable: "कु/खु", sound: "ku/khu", matra: "उ" },
      { syllable: "कू/खू", sound: "koo/khoo", matra: "ऊ" },
      { syllable: "के/खे", sound: "ke/khe", matra: "ए" },
      { syllable: "कै/खै", sound: "kai/khai", matra: "ऐ" },
      { syllable: "को/खो", sound: "ko/kho", matra: "ओ" },
      { syllable: "कौ/खौ", sound: "kau/khau", matra: "औ" },
      { syllable: "कं/खं", sound: "kam/kham", matra: "ं" },
      { syllable: "कः/खः", sound: "kah/khah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "कमल/खना", english: "Lotus/Dig", roman: "kamal/khana" },
      { hindi: "किला/खेल", english: "Fort/Play", roman: "kila/khel" },
      { hindi: "कुर्सी/खून", english: "Chair/Blood", roman: "kursi/khun" },
    ],
    wordHindi: "कमल & खना",
    wordEnglish: "Lotus & Dig",
    wordRoman: "kamal-khana",
    assetPath: "/assets/gemini/vaani_l4_ka_kha_review_1777200559.png",
    summary: "Compare similar consonants.",
    prompt: "Notice the subtle differences in these sound pairs!",
  },
  {
    id: "L4-C02-L18",
    chapterId: "C02",
    chapterTitle: "Barakhadi Consolidation",
    title: "Consonant Pairs Review - ग & घ",
    category: "Review Practice",
    skill: "Barakhadi Mastery",
    consonant: "ग & घ",
    consonantRoman: "ga-gha",
    barakhadiRow: [
      { syllable: "ग/घ", sound: "ga/gha", matra: "अ" },
      { syllable: "गा/घा", sound: "gaa/ghaa", matra: "आ" },
      { syllable: "गि/घि", sound: "gi/ghi", matra: "इ" },
      { syllable: "गी/घी", sound: "gee/ghee", matra: "ई" },
      { syllable: "गु/घु", sound: "gu/ghu", matra: "उ" },
      { syllable: "गू/घू", sound: "goo/ghoo", matra: "ऊ" },
      { syllable: "गे/घे", sound: "ge/ghe", matra: "ए" },
      { syllable: "गै/घै", sound: "gai/ghai", matra: "ऐ" },
      { syllable: "गो/घो", sound: "go/gho", matra: "ओ" },
      { syllable: "गौ/घौ", sound: "gau/ghau", matra: "औ" },
      { syllable: "गं/घं", sound: "gam/gham", matra: "ं" },
      { syllable: "गः/घः", sound: "gah/ghah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "गाना/घर", english: "Song/House", roman: "gana/ghar" },
      { hindi: "गिरना/घिसना", english: "Fall/Grind", roman: "girna/ghisna" },
      { hindi: "गुलाब/घूमना", english: "Rose/Walk", roman: "gulab/ghumna" },
    ],
    wordHindi: "गाना & घर",
    wordEnglish: "Song & House",
    wordRoman: "gana-ghar",
    assetPath: "/assets/gemini/vaani_l4_ga_gha_review_1777200560.png",
    summary: "Master voiced velar pairs.",
    prompt: "These consonants are related but distinctly different!",
  },
  {
    id: "L4-C02-L19",
    chapterId: "C02",
    chapterTitle: "Barakhadi Consolidation",
    title: "Consonant Clusters Review - स, श, ष",
    category: "Review Practice",
    skill: "Barakhadi Mastery",
    consonant: "स, श, ष",
    consonantRoman: "sa-sha-sha",
    barakhadiRow: [
      { syllable: "स/श/ष", sound: "sa/sha/sha", matra: "अ" },
      { syllable: "सा/शा/षा", sound: "saa/shaa/shaa", matra: "आ" },
      { syllable: "सि/शि/षि", sound: "si/shi/shi", matra: "इ" },
      { syllable: "सी/शी/षी", sound: "see/shee/shee", matra: "ई" },
      { syllable: "सु/शु/षु", sound: "su/shu/shu", matra: "उ" },
      { syllable: "सू/शू/षू", sound: "soo/shoo/shoo", matra: "ऊ" },
      { syllable: "से/शे/षे", sound: "se/she/she", matra: "ए" },
      { syllable: "सै/शै/षै", sound: "sai/shai/shai", matra: "ऐ" },
      { syllable: "सो/शो/षो", sound: "so/sho/sho", matra: "ओ" },
      { syllable: "सौ/शौ/षौ", sound: "sau/shau/shau", matra: "औ" },
      { syllable: "सं/शं/षं", sound: "sam/sham/sham", matra: "ं" },
      { syllable: "सः/शः/षः", sound: "sah/shah/shah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "सूरज/शक्ति/षष्ठी", english: "Sun/Power/Sixth", roman: "suraj/shakti/shashthi" },
      { hindi: "समय/शांति/पषाण", english: "Time/Peace/Stone", roman: "samay/shanti/pashan" },
      { hindi: "सीमा/शीत/षड्यंत्र", english: "Boundary/Cold/Conspiracy", roman: "seema/sheet/shadyantra" },
    ],
    wordHindi: "सूरज/शक्ति/षष्ठी",
    wordEnglish: "Sun/Power/Sixth",
    wordRoman: "suraj-shakti-shashthi",
    assetPath: "/assets/gemini/vaani_l4_fricatives_review_1777200561.png",
    summary: "Compare three sibilant consonants.",
    prompt: "These three fricatives have subtle but important differences!",
  },
  {
    id: "L4-C02-L20",
    chapterId: "C02",
    chapterTitle: "Barakhadi Consolidation",
    title: "Liquid Consonants Review - य, र, ल, व",
    category: "Review Practice",
    skill: "Barakhadi Mastery",
    consonant: "य, र, ल, व",
    consonantRoman: "ya-ra-la-va",
    barakhadiRow: [
      { syllable: "य/र/ल/व", sound: "ya/ra/la/va", matra: "अ" },
      { syllable: "या/रा/ला/वा", sound: "yaa/raa/laa/vaa", matra: "आ" },
      { syllable: "यि/रि/लि/वि", sound: "yi/ri/li/vi", matra: "इ" },
      { syllable: "यी/री/ली/वी", sound: "yee/ree/lee/vee", matra: "ई" },
      { syllable: "यु/रु/लु/वु", sound: "yu/ru/lu/vu", matra: "उ" },
      { syllable: "यू/रू/लू/वू", sound: "yoo/roo/loo/voo", matra: "ऊ" },
      { syllable: "ये/रे/ले/वे", sound: "ye/re/le/ve", matra: "ए" },
      { syllable: "यै/रै/लै/वै", sound: "yai/rai/lai/vai", matra: "ऐ" },
      { syllable: "यो/रो/लो/वो", sound: "yo/ro/lo/vo", matra: "ओ" },
      { syllable: "यौ/रौ/लौ/वौ", sound: "yau/rau/lau/vau", matra: "औ" },
      { syllable: "यं/रं/लं/वं", sound: "yam/ram/lam/vam", matra: "ं" },
      { syllable: "यः/रः/लः/वः", sound: "yah/rah/lah/vah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "यमुना/राज/लड़का/वाणी", english: "River/King/Boy/Speech", roman: "yamuna/raj/ladka/vani" },
      { hindi: "योग/रंग/लिखना/विद्या", english: "Yoga/Color/Write/Knowledge", roman: "yog/rang/likhna/vidya" },
      { hindi: "यादव/रक्षा/लोग/वोट", english: "Yadav/Protection/People/Vote", roman: "yadav/raksha/log/vote" },
    ],
    wordHindi: "यमुना/राज/लड़का/वाणी",
    wordEnglish: "River/King/Boy/Speech",
    wordRoman: "yamuna-raj-ladka-vani",
    assetPath: "/assets/gemini/vaani_l4_liquids_review_1777200562.png",
    summary: "Master the fluid consonants.",
    prompt: "These liquid consonants are smooth and flowing!",
  },
  {
    id: "L4-C02-L21",
    chapterId: "C02",
    chapterTitle: "Barakhadi Consolidation",
    title: "Stop Consonants Speed Review - त, ट, द, ड",
    category: "Speed Practice",
    skill: "Barakhadi Mastery",
    consonant: "त, ट, द, ड",
    consonantRoman: "ta-ta-da-da",
    barakhadiRow: [
      { syllable: "त/ट/द/ड", sound: "ta/tta/da/dda", matra: "अ" },
      { syllable: "ता/टा/दा/डा", sound: "taa/ttaa/daa/ddaa", matra: "आ" },
      { syllable: "ति/टि/दि/डि", sound: "ti/tti/di/ddi", matra: "इ" },
      { syllable: "ती/टी/दी/डी", sound: "tee/ttee/dee/ddee", matra: "ई" },
      { syllable: "तु/टु/दु/डु", sound: "tu/ttu/du/ddu", matra: "उ" },
      { syllable: "तू/टू/दू/डू", sound: "too/ttoo/doo/ddoo", matra: "ऊ" },
      { syllable: "ते/टे/दे/डे", sound: "te/tte/de/dde", matra: "ए" },
      { syllable: "तै/टै/दै/डै", sound: "tai/ttai/dai/ddai", matra: "ऐ" },
      { syllable: "तो/टो/दो/डो", sound: "to/tto/do/ddo", matra: "ओ" },
      { syllable: "तौ/टौ/दौ/डौ", sound: "tau/ttau/dau/ddau", matra: "औ" },
      { syllable: "तं/टं/दं/डं", sound: "tam/ttam/dam/ddam", matra: "ं" },
      { syllable: "तः/टः/दः/डः", sound: "tah/ttah/dah/ddah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "तारा/टाइम/दाल/डाल", english: "Star/Time/Lentil/Branch", roman: "tara/taim/dal/dal" },
      { hindi: "तिल/टिकट/दिन/डिब्बा", english: "Sesame/Ticket/Day/Box", roman: "til/tikat/din/dibba" },
      { hindi: "तुरंत/टूना/दून/डूब", english: "Quickly/Tuna/Valley/Sink", roman: "turant/tuna/dun/dub" },
    ],
    wordHindi: "तारा/टाइम/दाल/डाल",
    wordEnglish: "Star/Time/Lentil/Branch",
    wordRoman: "tara-taim-dal-dal",
    assetPath: "/assets/gemini/vaani_l4_stops_review_1777200563.png",
    summary: "Speed practice with dental and retroflex stops.",
    prompt: "These consonants are crucial for Hindi pronunciation!",
  },
  {
    id: "L4-C02-L22",
    chapterId: "C02",
    chapterTitle: "Barakhadi Consolidation",
    title: "Nasal Consonants - न, म, & Special Sounds",
    category: "Review Practice",
    skill: "Barakhadi Mastery",
    consonant: "न & म",
    consonantRoman: "na-ma",
    barakhadiRow: [
      { syllable: "न/म", sound: "na/ma", matra: "अ" },
      { syllable: "ना/मा", sound: "naa/maa", matra: "आ" },
      { syllable: "नि/मि", sound: "ni/mi", matra: "इ" },
      { syllable: "नी/मी", sound: "nee/mee", matra: "ई" },
      { syllable: "नु/मु", sound: "nu/mu", matra: "उ" },
      { syllable: "नू/मू", sound: "noo/moo", matra: "ऊ" },
      { syllable: "ने/मे", sound: "ne/me", matra: "ए" },
      { syllable: "नै/मै", sound: "nai/mai", matra: "ऐ" },
      { syllable: "नो/मो", sound: "no/mo", matra: "ओ" },
      { syllable: "नौ/मौ", sound: "nau/mau", matra: "औ" },
      { syllable: "नं/मं", sound: "nam/mam", matra: "ं" },
      { syllable: "नः/मः", sound: "nah/mah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "नाम/माता", english: "Name/Mother", roman: "nam/mata" },
      { hindi: "नील/मिठा", english: "Blue/Sweet", roman: "neel/mitha" },
      { hindi: "नृत्य/मुखर", english: "Dance/Loud", roman: "nritya/mukhar" },
    ],
    wordHindi: "नाम & माता",
    wordEnglish: "Name & Mother",
    wordRoman: "nam-mata",
    assetPath: "/assets/gemini/vaani_l4_nasals_review_1777200564.png",
    summary: "Master nasal consonants.",
    prompt: "Nasals are essential for Hindi sounds!",
  },
  {
    id: "L4-C02-L23",
    chapterId: "C02",
    chapterTitle: "Barakhadi Consolidation",
    title: "Aspirated Consonants Challenge - थ, ध, फ, भ, ह",
    category: "Challenge Practice",
    skill: "Barakhadi Mastery",
    consonant: "थ, ध, फ, भ, ह",
    consonantRoman: "tha-dha-pha-bha-ha",
    barakhadiRow: [
      { syllable: "थ/ध/फ/भ/ह", sound: "tha/dha/pha/bha/ha", matra: "अ" },
      { syllable: "था/धा/फा/भा/हा", sound: "thaa/dhaa/phaa/bhaa/haa", matra: "आ" },
      { syllable: "थि/धि/फि/भि/हि", sound: "thi/dhi/phi/bhi/hi", matra: "इ" },
      { syllable: "थी/धी/फी/भी/ही", sound: "thee/dhee/phee/bhee/hee", matra: "ई" },
      { syllable: "थु/धु/फु/भु/हु", sound: "thu/dhu/phu/bhu/hu", matra: "उ" },
      { syllable: "थू/धू/फू/भू/हू", sound: "thoo/dhoo/phoo/bhoo/hoo", matra: "ऊ" },
      { syllable: "थे/धे/फे/भे/हे", sound: "the/dhe/phe/bhe/he", matra: "ए" },
      { syllable: "थै/धै/फै/भै/है", sound: "thai/dhai/phai/bhai/hai", matra: "ऐ" },
      { syllable: "थो/धो/फो/भो/हो", sound: "tho/dho/pho/bho/ho", matra: "ओ" },
      { syllable: "थौ/धौ/फौ/भौ/हौ", sound: "thau/dhau/phau/bhau/hau", matra: "औ" },
      { syllable: "थं/धं/फं/भं/हं", sound: "tham/dham/pham/bham/ham", matra: "ं" },
      { syllable: "थः/धः/फः/भः/हः", sound: "thah/dhah/phah/bhah/hah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "थाली/धन/फल/भाई/हाथ", english: "Plate/Money/Fruit/Brother/Hand", roman: "thali/dhan/phal/bhai/hath" },
      { hindi: "थीम/धीमी/फीस/भीड़/हीरा", english: "Theme/Slow/Fee/Crowd/Diamond", roman: "theem/dheemi/phees/bheed/hira" },
      { hindi: "थुलथुल/ध्यान/फूल/भूमि/हूँ", english: "Chubby/Meditation/Flower/Earth/Am", roman: "thultul/dhyan/phul/bhumi/hoon" },
    ],
    wordHindi: "थाली/धन/फल/भाई/हाथ",
    wordEnglish: "Plate/Money/Fruit/Brother/Hand",
    wordRoman: "thali-dhan-phal-bhai-hath",
    assetPath: "/assets/gemini/vaani_l4_aspirated_challenge_1777200565.png",
    summary: "Master all aspirated consonants together.",
    prompt: "Aspirated sounds require strong breath control!",
  },
  {
    id: "L4-C02-L24",
    chapterId: "C02",
    chapterTitle: "Barakhadi Mastery Complete",
    title: "Complete Barakhadi Mastery Celebration",
    category: "Mastery Achievement",
    skill: "Complete Barakhadi Mastery",
    consonant: "सभी वर्ण",
    consonantRoman: "all-consonants",
    barakhadiRow: [
      { syllable: "अ", sound: "a", matra: "अ" },
      { syllable: "आ", sound: "aa", matra: "आ" },
      { syllable: "इ", sound: "i", matra: "इ" },
      { syllable: "ई", sound: "ee", matra: "ई" },
      { syllable: "उ", sound: "u", matra: "उ" },
      { syllable: "ऊ", sound: "oo", matra: "ऊ" },
      { syllable: "ए", sound: "e", matra: "ए" },
      { syllable: "ऐ", sound: "ai", matra: "ऐ" },
      { syllable: "ओ", sound: "o", matra: "ओ" },
      { syllable: "औ", sound: "au", matra: "औ" },
      { syllable: "ं", sound: "am", matra: "ं" },
      { syllable: "ः", sound: "ah", matra: "ः" },
    ],
    exampleWords: [
      { hindi: "हिंदी", english: "Hindi", roman: "hindi" },
      { hindi: "शिक्षा", english: "Education", roman: "shiksha" },
      { hindi: "सफलता", english: "Success", roman: "saflta" },
    ],
    wordHindi: "हिंदी शिक्षा",
    wordEnglish: "Hindi Education",
    wordRoman: "hindi-shiksha",
    assetPath: "/assets/gemini/vaani_l4_mastery_complete_1777200566.png",
    summary: "You've mastered the complete barakhadi! Every consonant with every vowel sound is now clear and confident.",
    prompt: "Congratulations! You are now a barakhadi master! You can read and write any Hindi word with confidence!",
  },
];

// Roman transliteration map for Level 4
export const LEVEL_4_ROMAN_MAP: Record<string, string> = {
  "L4-C01-L01": "kamal",
  "L4-C01-L02": "khana",
  "L4-C01-L03": "gana",
  "L4-C01-L04": "ghar",
  "L4-C01-L05": "chai",
  "L4-C01-L06": "chat",
  "L4-C01-L07": "tika",
  "L4-C01-L08": "thandi",
  "L4-C01-L09": "dak",
  "L4-C01-L10": "dhol",
  "L4-C01-L11": "tara",
  "L4-C01-L12": "padhna",
  "L4-C02-L01": "thali",
  "L4-C02-L02": "din",
  "L4-C02-L03": "dhan",
  "L4-C02-L04": "pani",
  "L4-C02-L05": "phal",
  "L4-C02-L06": "bazaar",
  "L4-C02-L07": "bhag",
  "L4-C02-L08": "mata",
  "L4-C02-L09": "yog",
  "L4-C02-L10": "raja",
  "L4-C02-L11": "ladka",
  "L4-C02-L12": "vani",
  "L4-C02-L13": "shakti",
  "L4-C02-L14": "shashthi",
  "L4-C02-L15": "suraj",
  "L4-C02-L16": "hath",
  "L4-C02-L17": "kamal-khana",
  "L4-C02-L18": "gana-ghar",
  "L4-C02-L19": "suraj-shakti-shashthi",
  "L4-C02-L20": "yamuna-raj-ladka-vani",
  "L4-C02-L21": "tara-taim-dal-dal",
  "L4-C02-L22": "nam-mata",
  "L4-C02-L23": "thali-dhan-phal-bhai-hath",
  "L4-C02-L24": "hindi-shiksha",
};

// Re-export for compatibility
export const vaaniLevel4Data = LEVEL_4_DATA;
