type LevelOneSeed = {
  id: string;
  chapterId: string;
  chapterTitle: string;
  title: string;
  category: "Vowels" | "Consonants";
  skill: string;
  char: string;
  wordHindi: string;
  wordEnglish: string;
  assetPath: string;
  durationMin?: number;
  summary: string;
  prompt: string;
};

const LEVEL_ONE_SEEDS: LevelOneSeed[] = [
  {
    id: "L1-C01-L01",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "अ for Anar",
    category: "Vowels",
    skill: "Sound Recognition",
    char: "अ",
    wordHindi: "अनार",
    wordEnglish: "Pomegranate",
    assetPath: "/assets/gemini/vaani_l1_anar_a_1777125076703.png",
    summary: "Meet the first Hindi sound through a bright anar visual and tracing practice.",
    prompt: "Say the sound slowly: अ ... अ ... अनार.",
  },
  {
    id: "L1-C01-L02",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "आ for Aam",
    category: "Vowels",
    skill: "Long Vowel Sound",
    char: "आ",
    wordHindi: "आम",
    wordEnglish: "Mango",
    assetPath: "/assets/gemini/vaani_l1_aam_aa_1777125098321.png",
    summary: "Stretch the sound and connect आ with aam.",
    prompt: "Notice how the sound becomes longer than अ.",
  },
  {
    id: "L1-C01-L03",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "इ for Imli",
    category: "Vowels",
    skill: "Letter Association",
    char: "इ",
    wordHindi: "इमली",
    wordEnglish: "Tamarind",
    assetPath: "/assets/gemini/vaani_l1_imli_i_1777125119172.png",
    summary: "Link the short इ sound with the tangy imli visual.",
    prompt: "Say इ quickly and point to the imli.",
  },
  {
    id: "L1-C01-L04",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "ई for Eekh",
    category: "Vowels",
    skill: "Long Vowel Sound",
    char: "ई",
    wordHindi: "ईख",
    wordEnglish: "Sugarcane",
    assetPath: "/assets/gemini/vaani_l1_eekh_ee_1777125139516.png",
    summary: "Practice the long ई sound with sweet eekh.",
    prompt: "Smile and stretch the sound: ईईई.",
  },
  {
    id: "L1-C01-L05",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "उ for Uloo",
    category: "Vowels",
    skill: "Visual Memory",
    char: "उ",
    wordHindi: "उल्लू",
    wordEnglish: "Owl",
    assetPath: "/assets/gemini/vaani_l1_uloo_u_1777125290851.png",
    summary: "Remember उ by pairing it with a curious owl.",
    prompt: "Round your lips softly for the उ sound.",
  },
  {
    id: "L1-C01-L06",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "ऊ for Oon",
    category: "Vowels",
    skill: "Stroke Awareness",
    char: "ऊ",
    wordHindi: "ऊन",
    wordEnglish: "Wool",
    assetPath: "/assets/gemini/vaani_l1_oon_uu_1777125318652.png",
    summary: "Build confidence with ऊ and its longer sound.",
    prompt: "Listen for the longer sound in ऊन.",
  },
  {
    id: "L1-C01-L07",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "ऋ for Rishi",
    category: "Vowels",
    skill: "Special Sound Practice",
    char: "ऋ",
    wordHindi: "ऋषि",
    wordEnglish: "Sage",
    assetPath: "/assets/gemini/vaani_l1_rishi_ri_1777125345133.png",
    summary: "Introduce the special ऋ sound through ऋषि.",
    prompt: "This is a special sound. Say it slowly with the coach.",
  },
  {
    id: "L1-C01-L08",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "ए for Edi",
    category: "Vowels",
    skill: "Picture Mapping",
    char: "ए",
    wordHindi: "एड़ी",
    wordEnglish: "Heel",
    assetPath: "/assets/gemini/vaani_l1_edi_e_1777125373821.png",
    summary: "Use a body-part word to lock in the ए sound.",
    prompt: "Tap your heel and say एड़ी.",
  },
  {
    id: "L1-C01-L09",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "ऐ for Ainak",
    category: "Vowels",
    skill: "Vocabulary Building",
    char: "ऐ",
    wordHindi: "ऐनक",
    wordEnglish: "Glasses",
    assetPath: "/assets/gemini/vaani_l1_ainak_ai_1777125396742.png",
    summary: "Connect the sound ऐ with a familiar object: glasses.",
    prompt: "Can you pretend to wear ऐनक while saying ऐ?",
  },
  {
    id: "L1-C01-L10",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "ओ for Okhli",
    category: "Vowels",
    skill: "Cultural Word Recall",
    char: "ओ",
    wordHindi: "ओखली",
    wordEnglish: "Mortar",
    assetPath: "/assets/gemini/vaani_l1_okhli_o_1777126185580.png",
    summary: "Practice ओ with a traditional household object.",
    prompt: "Open the mouth in a round shape for ओ.",
  },
  {
    id: "L1-C01-L11",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "औ for Aurat",
    category: "Vowels",
    skill: "Word Recognition",
    char: "औ",
    wordHindi: "औरत",
    wordEnglish: "Woman",
    assetPath: "/assets/gemini/vaani_l1_aurat_au_1777126210291.png",
    summary: "Learn the bold औ sound through a familiar word.",
    prompt: "Hear the deeper opening sound in औरत.",
  },
  {
    id: "L1-C01-L12",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "अं for Angoor",
    category: "Vowels",
    skill: "Nasal Sound Practice",
    char: "अं",
    wordHindi: "अंगूर",
    wordEnglish: "Grapes",
    assetPath: "/assets/gemini/vaani_l1_angoor_ang_1777126234634.png",
    summary: "Explore the nasal sound अं with a bunch of grapes.",
    prompt: "Touch your nose and say the sound gently: अं.",
  },
  {
    id: "L1-C01-L13",
    chapterId: "C01",
    chapterTitle: "Swar Foundations",
    title: "अः Sound Discovery",
    category: "Vowels",
    skill: "Breath Sound Awareness",
    char: "अः",
    wordHindi: "विसर्ग",
    wordEnglish: "Breath Sound",
    assetPath: "/assets/gemini/vaani_l1_aha_sound_aha_1777126260955.png",
    summary: "Meet the soft breath-like अः sound in a gentle, low-pressure activity.",
    prompt: "This sound feels like a soft breath after the letter.",
  },
  {
    id: "L1-C02-L01",
    chapterId: "C02",
    chapterTitle: "Vyanjan Discovery",
    title: "ख for Khargosh",
    category: "Consonants",
    skill: "Consonant Sound",
    char: "ख",
    wordHindi: "खरगोश",
    wordEnglish: "Rabbit",
    assetPath: "/assets/l1_vyanjan_kha_khargosh.svg",
    summary: "Jump into consonants with khargosh and the airy ख sound.",
    prompt: "Feel the extra breath in the ख sound.",
  },
  {
    id: "L1-C02-L02",
    chapterId: "C02",
    chapterTitle: "Vyanjan Discovery",
    title: "ग for Gamla",
    category: "Consonants",
    skill: "Object Association",
    char: "ग",
    wordHindi: "गमला",
    wordEnglish: "Plant Pot",
    assetPath: "/assets/l1_vyanjan_ga_gamla.svg",
    summary: "Use a garden object to make ग easy to remember.",
    prompt: "Say ग while pointing to the pot shape.",
  },
  {
    id: "L1-C02-L03",
    chapterId: "C02",
    chapterTitle: "Vyanjan Discovery",
    title: "घ for Ghar",
    category: "Consonants",
    skill: "Home Vocabulary",
    char: "घ",
    wordHindi: "घर",
    wordEnglish: "Home",
    assetPath: "/house.png",
    summary: "Build a meaningful connection between घ and home.",
    prompt: "Say घर and look for the first sound only.",
  },
  {
    id: "L1-C03-L01",
    chapterId: "C03",
    chapterTitle: "Cha Group",
    title: "च for Charkha",
    category: "Consonants",
    skill: "Picture Reading",
    char: "च",
    wordHindi: "चरखा",
    wordEnglish: "Spinning Wheel",
    assetPath: "/assets/l1_vyanjan_cha_charkha.svg",
    summary: "Discover च through the spinning charkha visual.",
    prompt: "Look for the curl in the letter and say च clearly.",
  },
  {
    id: "L1-C03-L02",
    chapterId: "C03",
    chapterTitle: "Cha Group",
    title: "छ for Chhatri",
    category: "Consonants",
    skill: "Shape Recognition",
    char: "छ",
    wordHindi: "छतरी",
    wordEnglish: "Umbrella",
    assetPath: "/assets/l1_vyanjan_chha_chatri.svg",
    summary: "Trace छ while remembering the umbrella above it.",
    prompt: "Can you imagine rain when you say छतरी?",
  },
  {
    id: "L1-C03-L03",
    chapterId: "C03",
    chapterTitle: "Cha Group",
    title: "ज for Jahaz",
    category: "Consonants",
    skill: "Word Mapping",
    char: "ज",
    wordHindi: "जहाज",
    wordEnglish: "Ship",
    assetPath: "/assets/l1_vyanjan_ja_jahaz.svg",
    summary: "Board the जहाज and practice the ज sound with confidence.",
    prompt: "Say ज as the ship begins its journey.",
  },
  {
    id: "L1-C03-L04",
    chapterId: "C03",
    chapterTitle: "Cha Group",
    title: "झ for Jhanda",
    category: "Consonants",
    skill: "Sound Contrast",
    char: "झ",
    wordHindi: "झंडा",
    wordEnglish: "Flag",
    assetPath: "/assets/l1_vyanjan_jha_jhanda.svg",
    summary: "Practice the stronger झ sound using the waving flag.",
    prompt: "Say the sound with energy: झ.",
  },
  {
    id: "L1-C04-L01",
    chapterId: "C04",
    chapterTitle: "Retroflex Group",
    title: "ट for Tamatar",
    category: "Consonants",
    skill: "Letter Recall",
    char: "ट",
    wordHindi: "टमाटर",
    wordEnglish: "Tomato",
    assetPath: "/assets/l1_vyanjan_ta_tamatar.svg",
    summary: "Spot the retroflex ट and connect it to tomato.",
    prompt: "Listen carefully: ट is sharp and strong.",
  },
  {
    id: "L1-C04-L02",
    chapterId: "C04",
    chapterTitle: "Retroflex Group",
    title: "ठ for Tharmas",
    category: "Consonants",
    skill: "Sound Contrast",
    char: "ठ",
    wordHindi: "थर्मस",
    wordEnglish: "Thermos",
    assetPath: "/assets/l1_vyanjan_tha_tharmas.svg",
    summary: "Differentiate ठ from ट with a fresh everyday object.",
    prompt: "Notice the puff of air while saying ठ.",
  },
  {
    id: "L1-C04-L03",
    chapterId: "C04",
    chapterTitle: "Retroflex Group",
    title: "ड for Damru",
    category: "Consonants",
    skill: "Cultural Recall",
    char: "ड",
    wordHindi: "डमरू",
    wordEnglish: "Drum",
    assetPath: "/assets/l1_vyanjan_da_damru.svg",
    summary: "Use rhythm and sound to remember ड.",
    prompt: "Tap a beat as you say डमरू.",
  },
  {
    id: "L1-C04-L04",
    chapterId: "C04",
    chapterTitle: "Retroflex Group",
    title: "ढ for Dhakkan",
    category: "Consonants",
    skill: "Practical Vocabulary",
    char: "ढ",
    wordHindi: "ढक्कन",
    wordEnglish: "Lid",
    assetPath: "/assets/l1_vyanjan_dha_dhakkan.svg",
    summary: "Strengthen the ढ sound with a familiar object from home.",
    prompt: "Lift an imaginary lid and say ढ.",
  },
  {
    id: "L1-C05-L01",
    chapterId: "C05",
    chapterTitle: "Dental Group",
    title: "त for Tarbooj",
    category: "Consonants",
    skill: "Word Recognition",
    char: "त",
    wordHindi: "तरबूज",
    wordEnglish: "Watermelon",
    assetPath: "/assets/l1_vyanjan_ta_tarbooz.svg",
    summary: "Pair the softer dental त with juicy tarbooj.",
    prompt: "Touch the tip of your tongue lightly for त.",
  },
  {
    id: "L1-C05-L02",
    chapterId: "C05",
    chapterTitle: "Dental Group",
    title: "थ for Thathera",
    category: "Consonants",
    skill: "Advanced Word Exposure",
    char: "थ",
    wordHindi: "थठेरा",
    wordEnglish: "Metal Worker",
    assetPath: "/assets/l1_vyanjan_tha_thathera.svg",
    summary: "Introduce a richer Hindi vocabulary word while practicing थ.",
    prompt: "This is a new word. Repeat it boldly with the coach.",
  },
  {
    id: "L1-C05-L03",
    chapterId: "C05",
    chapterTitle: "Dental Group",
    title: "द for Dawat",
    category: "Consonants",
    skill: "Celebration Vocabulary",
    char: "द",
    wordHindi: "दावत",
    wordEnglish: "Feast",
    assetPath: "/assets/l1_vyanjan_da_dawat.svg",
    summary: "Celebrate the द sound through a lively dawat visual.",
    prompt: "Say द with a soft tongue placement.",
  },
  {
    id: "L1-C05-L04",
    chapterId: "C05",
    chapterTitle: "Dental Group",
    title: "ध for Dhanush",
    category: "Consonants",
    skill: "Story Connection",
    char: "ध",
    wordHindi: "धनुष",
    wordEnglish: "Bow",
    assetPath: "/assets/l1_vyanjan_dha_dhanush.svg",
    summary: "Use story imagination to remember ध.",
    prompt: "Imagine pulling a bow while saying धनुष.",
  },
  {
    id: "L1-C05-L05",
    chapterId: "C05",
    chapterTitle: "Dental Group",
    title: "न for Nal",
    category: "Consonants",
    skill: "Daily Object Recognition",
    char: "न",
    wordHindi: "नल",
    wordEnglish: "Tap",
    assetPath: "/assets/l1_vyanjan_na_nal.svg",
    summary: "Finish the dental set with a simple everyday word.",
    prompt: "Turn the imaginary tap and say नल.",
  },
  {
    id: "L1-C06-L01",
    chapterId: "C06",
    chapterTitle: "First Consonant",
    title: "क for Kamal",
    category: "Consonants",
    skill: "Letter Recognition",
    char: "क",
    wordHindi: "कमल",
    wordEnglish: "Lotus",
    assetPath: "/assets/gemini/vaani_l1_kamal_ka_1777126528907.png",
    summary: "Introduce the first consonant with a blooming lotus.",
    prompt: "Say क like the starting sound in कमल.",
  },
  {
    id: "L1-C07-L01",
    chapterId: "C07",
    chapterTitle: "Pa Group",
    title: "प for Patang",
    category: "Consonants",
    skill: "Sound Association",
    char: "प",
    wordHindi: "पतंग",
    wordEnglish: "Kite",
    assetPath: "/assets/gemini/vaani_l1_patang_pa_1777164221280.png",
    summary: "Fly high with the प sound and a colorful kite.",
    prompt: "Press your lips together to say प.",
  },
  {
    id: "L1-C07-L02",
    chapterId: "C07",
    chapterTitle: "Pa Group",
    title: "फ for Phal",
    category: "Consonants",
    skill: "Aspirated Sound",
    char: "फ",
    wordHindi: "फल",
    wordEnglish: "Fruit",
    assetPath: "/assets/gemini/vaani_l1_phal_pha_1777164245719.png",
    summary: "Learn the fresh फ sound with fruits.",
    prompt: "Blow a little puff of air when you say फ.",
  },
  {
    id: "L1-C07-L03",
    chapterId: "C07",
    chapterTitle: "Pa Group",
    title: "ब for Batakh",
    category: "Consonants",
    skill: "Word Mapping",
    char: "ब",
    wordHindi: "बतख",
    wordEnglish: "Duck",
    assetPath: "/assets/gemini/vaani_l1_batakh_ba_1777164267319.png",
    summary: "Practice the soft ब sound with a quacking batakh.",
    prompt: "Say ब softly with your lips closed.",
  },
  {
    id: "L1-C07-L04",
    chapterId: "C07",
    chapterTitle: "Pa Group",
    title: "भ for Bhalu",
    category: "Consonants",
    skill: "Heavy Sound",
    char: "भ",
    wordHindi: "भालू",
    wordEnglish: "Bear",
    assetPath: "/assets/gemini/vaani_l1_bhalu_bha_1777164287689.png",
    summary: "Make a big sound for भ and the bear.",
    prompt: "Use a deep, heavy voice for भ.",
  },
  {
    id: "L1-C07-L05",
    chapterId: "C07",
    chapterTitle: "Pa Group",
    title: "म for Machli",
    category: "Consonants",
    skill: "Nasal Ending",
    char: "म",
    wordHindi: "मछली",
    wordEnglish: "Fish",
    assetPath: "/assets/gemini/vaani_l1_machli_ma_1777164308458.png",
    summary: "Swim along with the म sound.",
    prompt: "Hum the म lightly like a fish swimming.",
  },
  {
    id: "L1-C08-L01",
    chapterId: "C08",
    chapterTitle: "Semi-Vowels & Fricatives",
    title: "र for Rath",
    category: "Consonants",
    skill: "Rolling Sound",
    char: "र",
    wordHindi: "रथ",
    wordEnglish: "Chariot",
    assetPath: "/assets/gemini/vaani_l1_rath_ra_1777164394440.png",
    summary: "Ride the chariot to practice the rolling र.",
    prompt: "Roll your tongue slightly for the र sound.",
  },
  {
    id: "L1-C08-L02",
    chapterId: "C08",
    chapterTitle: "Semi-Vowels & Fricatives",
    title: "ल for Lattu",
    category: "Consonants",
    skill: "Word Recognition",
    char: "ल",
    wordHindi: "लट्टू",
    wordEnglish: "Spinning Top",
    assetPath: "/assets/gemini/vaani_l1_lattu_la_1777164417029.png",
    summary: "Spin the lattu and learn the ल sound.",
    prompt: "Touch your tongue behind your top teeth for ल.",
  },
  {
    id: "L1-C08-L03",
    chapterId: "C08",
    chapterTitle: "Semi-Vowels & Fricatives",
    title: "व for Vak",
    category: "Consonants",
    skill: "Object Association",
    char: "व",
    wordHindi: "वक",
    wordEnglish: "Crane",
    assetPath: "/assets/gemini/vaani_l1_vak_va_1777164438468.png",
    summary: "Learn the व sound with the elegant crane.",
    prompt: "Say व smoothly.",
  },
  {
    id: "L1-C08-L04",
    chapterId: "C08",
    chapterTitle: "Semi-Vowels & Fricatives",
    title: "श for Shalgam",
    category: "Consonants",
    skill: "Sh Sound",
    char: "श",
    wordHindi: "शलगम",
    wordEnglish: "Turnip",
    assetPath: "/assets/gemini/vaani_l1_shalgam_sha_1777164460564.png",
    summary: "Practice the soft श sound.",
    prompt: "Whisper the श sound.",
  },
  {
    id: "L1-C08-L05",
    chapterId: "C08",
    chapterTitle: "Semi-Vowels & Fricatives",
    title: "ष for Shatkon",
    category: "Consonants",
    skill: "Retroflex Sh",
    char: "ष",
    wordHindi: "षट्कोण",
    wordEnglish: "Hexagon",
    assetPath: "/assets/gemini/vaani_l1_shatkon_sha2_1777164587263.png",
    summary: "Learn the heavier ष sound.",
    prompt: "Fold your tongue slightly to say ष.",
  },
  {
    id: "L1-C08-L06",
    chapterId: "C08",
    chapterTitle: "Semi-Vowels & Fricatives",
    title: "स for Saap",
    category: "Consonants",
    skill: "S Sound",
    char: "स",
    wordHindi: "साँप",
    wordEnglish: "Snake",
    assetPath: "/assets/gemini/vaani_l1_saap_sa_1777164611692.png",
    summary: "Hiss like a snake for the स sound.",
    prompt: "Make a clear, sharp स sound.",
  },
  {
    id: "L1-C08-L07",
    chapterId: "C08",
    chapterTitle: "Semi-Vowels & Fricatives",
    title: "ह for Hathi",
    category: "Consonants",
    skill: "Breath Sound",
    char: "ह",
    wordHindi: "हाथी",
    wordEnglish: "Elephant",
    assetPath: "/assets/gemini/vaani_l1_hathi_ha_1777164643586.png",
    summary: "Feel the breath on ह.",
    prompt: "Let out a breath of air as you say ह.",
  },
  {
    id: "L1-C09-L01",
    chapterId: "C09",
    chapterTitle: "Joint Consonants",
    title: "क्ष for Kshatriya",
    category: "Consonants",
    skill: "Joint Letter",
    char: "क्ष",
    wordHindi: "क्षत्रिय",
    wordEnglish: "Warrior",
    assetPath: "/assets/gemini/vaani_l1_kshatriya_ksha_1777164673402.png",
    summary: "Combine words to make the powerful क्ष.",
    prompt: "Merge the sounds to say क्ष.",
  },
  {
    id: "L1-C09-L02",
    chapterId: "C09",
    chapterTitle: "Joint Consonants",
    title: "त्र for Trishul",
    category: "Consonants",
    skill: "Joint Letter",
    char: "त्र",
    wordHindi: "त्रिशूल",
    wordEnglish: "Trident",
    assetPath: "/assets/gemini/vaani_l1_trishul_tra_1777164698431.png",
    summary: "Combine sounds for the त्र in trishul.",
    prompt: "Say त्र clearly.",
  },
  {
    id: "L1-C09-L03",
    chapterId: "C09",
    chapterTitle: "Joint Consonants",
    title: "ज्ञ for Gyani",
    category: "Consonants",
    skill: "Joint Letter",
    char: "ज्ञ",
    wordHindi: "ज्ञानी",
    wordEnglish: "Wise Man",
    assetPath: "/assets/gemini/vaani_l1_gyani_gya_1777164728645.png",
    summary: "Learn the wise ज्ञ sound.",
    prompt: "Say ज्ञ with wisdom.",
  },
  {
    id: "L1-C09-L04",
    chapterId: "C09",
    chapterTitle: "Joint Consonants",
    title: "श्र for Shramik",
    category: "Consonants",
    skill: "Joint Letter",
    char: "श्र",
    wordHindi: "श्रमिक",
    wordEnglish: "Worker",
    assetPath: "/assets/gemini/vaani_l1_shramik_shra_1777164772360.png",
    summary: "Complete the set with the hard-working श्र.",
    prompt: "Say श्र with energy.",
  },
];

const COURSE_CARD_COLORS = [
  "#f97316",
  "#ef4444",
  "#10b981",
  "#3b82f6",
  "#8b5cf6",
  "#ec4899",
];

function getNextLessonUrl(index: number) {
  const nextLesson = LEVEL_ONE_SEEDS[index + 1];
  return nextLesson ? `/level-1/lesson/${nextLesson.id}` : "/level-1";
}

function buildFlashcards(seed: LevelOneSeed) {
  return [
    { front: seed.char, back: `${seed.wordHindi} (${seed.wordEnglish})` },
    { front: `${seed.char}...`, back: `Listen for the starting sound in ${seed.wordHindi}.` },
    { front: "Coach Tip", back: `Trace ${seed.char} slowly and say it clearly.` },
  ];
}

function buildQuizOptions(seed: LevelOneSeed) {
  const pool = [seed.wordHindi, "आम", "अनार", "जहाज", "तरबूज", "घर"];
  const unique = Array.from(new Set(pool.filter((item) => item !== seed.wordHindi)));
  return [seed.wordHindi, ...unique.slice(0, 2)];
}

export const VAANI_L1_COURSE_LESSONS = LEVEL_ONE_SEEDS.map((seed, index) => ({
  id: seed.id,
  order: index + 1,
  title: `${seed.char} for ${seed.wordEnglish}`,
  category: seed.category,
  durationMin: seed.durationMin ?? 6,
  status: (index < 12 ? "available" : "current") as "available" | "current",
  summary: seed.summary,
  skill: seed.skill,
  boardPreview: {
    type: "visual",
    data: {
      assetPath: seed.assetPath,
      headline: `${seed.char} - ${seed.wordHindi}`,
    },
  },
  image: seed.assetPath,
  startUrl: `/level-1/lesson/${seed.id}`,
  color: COURSE_CARD_COLORS[index % COURSE_CARD_COLORS.length],
}));

export const VAANI_L1_LESSONS: Record<string, any> = Object.fromEntries(
  LEVEL_ONE_SEEDS.map((seed, index) => [
    seed.id,
    {
      course: {
        title: "Vaani AI Level 1",
        grade: "1",
        levelSlug: "level-1",
      },
      lesson: {
        id: seed.id,
        chapterId: seed.chapterId,
        chapterTitle: seed.chapterTitle,
        title: seed.title,
        category: seed.category,
        durationMin: seed.durationMin ?? 6,
        summary: seed.summary,
        xpReward: 60,
        difficulty: "Beginner",
      },
      steps: [
        {
          id: `${seed.id}_observe`,
          label: "Look and Listen",
          skillTags: ["reading", "vocabulary", "pronunciation"],
          tutorText: `Today we learn ${seed.char} through ${seed.wordHindi}. ${seed.prompt}`,
          board: {
            type: "visual",
            data: {
              assetPath: seed.assetPath,
              headline: `${seed.char} से ${seed.wordHindi}`,
              prompt: `${seed.wordEnglish} helps us remember the sound of ${seed.char}.`,
            },
          },
        },
        {
          id: `${seed.id}_trace`,
          label: "Trace the Letter",
          skillTags: ["writing", "pronunciation"],
          tutorText: `Use your finger or mouse to trace ${seed.char}. Say the sound as you draw it.`,
          board: {
            type: "tracing_canvas",
            data: {
              headline: `Trace ${seed.char}`,
              expression: seed.char,
              prompt: `Start slowly, keep the curves smooth, and finish with confidence.`,
            },
          },
        },
        {
          id: `${seed.id}_remember`,
          label: "Word Memory",
          skillTags: ["reading", "vocabulary"],
          tutorText: `Flip the cards and connect ${seed.char} with ${seed.wordHindi}.`,
          board: {
            type: "flashcards",
            data: {
              headline: `Remember ${seed.char}`,
              cards: buildFlashcards(seed),
            },
          },
        },
        {
          id: `${seed.id}_quiz`,
          label: "Quick Check",
          skillTags: ["reading", "vocabulary"],
          tutorText: `Which word matches the sound ${seed.char}? Pick the best answer.`,
          board: {
            type: "mcq",
            data: {
              headline: "Quick Check",
              prompt: `Choose the correct word for ${seed.char}.`,
              options: buildQuizOptions(seed),
              answer: seed.wordHindi,
            },
          },
        },
      ],
      nextLessonUrl: getNextLessonUrl(index),
    },
  ]),
);
