/**
 * Vaani Level 4: Barakhadis (Vowel Series)
 * Focus: All vowels applied to a single consonant
 * Progression: consonant + all 12 vowels = complete barakhaadi
 * Concept: Systematic vowel application patterns
 * Total: 12 lessons (one barakhaadi per consonant)
 */

export interface Level4Seed {
  id: string;
  chapterId: string;
  chapterTitle: string;
  title: string;
  category: string;
  skill: string;
  consonant: string;
  consonantRoman: string;
  wordHindi: string;
  wordRoman: string;
  wordEnglish: string;
  barakhadiRow: Array<{ syllable: string; sound: string; matra: string }>;
  assetPath: string;
  durationMin?: number;
  summary: string;
  prompt: string;
}

// ============================================
// BARAKHADIS: VOWEL SERIES WITH EACH CONSONANT
// ============================================

export const LEVEL_4_DATA: Level4Seed[] = [
  {
    id: "L4-C01-L01",
    chapterId: "C01",
    chapterTitle: "Barakhaadi Series",
    title: "क की बारहखड़ी - Ka Barakhaadi",
    category: "Vowel Series",
    skill: "Complete Vowel Mapping",
    consonant: "क",
    consonantRoman: "ka",
    wordHindi: "कमल",
    wordRoman: "kamal",
    wordEnglish: "Lotus",
    barakhadiRow: [
      { syllable: "क", sound: "ka", matra: "none" },
      { syllable: "का", sound: "kaa", matra: "ा" },
      { syllable: "कि", sound: "ki", matra: "ि" },
      { syllable: "की", sound: "kee", matra: "ी" },
      { syllable: "कु", sound: "ku", matra: "ु" },
      { syllable: "कू", sound: "koo", matra: "ू" },
      { syllable: "के", sound: "ke", matra: "े" },
      { syllable: "कै", sound: "kai", matra: "ै" },
      { syllable: "को", sound: "ko", matra: "ो" },
      { syllable: "कौ", sound: "kau", matra: "ौ" },
      { syllable: "कँ", sound: "kan", matra: "ँ" },
      { syllable: "कः", sound: "kah", matra: "ः" },
    ],
    assetPath: "/assets/gemini/vaani_l4_ka_barakhaadi_1777180001.png",
    summary: "Master the complete vowel series - all 12 vowels with क.",
    prompt: "Say the entire barakhaadi row - notice the pattern!",
  },
  {
    id: "L4-C01-L02",
    chapterId: "C01",
    chapterTitle: "Barakhaadi Series",
    title: "ख की बारहखड़ी - Kha Barakhaadi",
    category: "Vowel Series",
    skill: "Aspirate Barakhaadi",
    consonant: "ख",
    consonantRoman: "kha",
    wordHindi: "खरगोश",
    wordRoman: "khargosh",
    wordEnglish: "Rabbit",
    barakhadiRow: [
      { syllable: "ख", sound: "kha", matra: "none" },
      { syllable: "खा", sound: "khaa", matra: "ा" },
      { syllable: "खि", sound: "khi", matra: "ि" },
      { syllable: "खी", sound: "khee", matra: "ी" },
      { syllable: "खु", sound: "khu", matra: "ु" },
      { syllable: "खू", sound: "khoo", matra: "ू" },
      { syllable: "खे", sound: "khe", matra: "े" },
      { syllable: "खै", sound: "khai", matra: "ै" },
      { syllable: "खो", sound: "kho", matra: "ो" },
      { syllable: "खौ", sound: "khau", matra: "ौ" },
      { syllable: "खँ", sound: "khan", matra: "ँ" },
      { syllable: "खः", sound: "khah", matra: "ः" },
    ],
    assetPath: "/assets/gemini/vaani_l4_kha_barakhaadi_1777180025.png",
    summary: "Aspirate consonants produce different sounds - feel the breath!",
    prompt: "Emphasize the breath sound - it's different from क!",
  },
  {
    id: "L4-C01-L03",
    chapterId: "C01",
    chapterTitle: "Barakhaadi Series",
    title: "ग की बारहखड़ी - Ga Barakhaadi",
    category: "Vowel Series",
    skill: "Voiced Barakhaadi",
    consonant: "ग",
    consonantRoman: "ga",
    wordHindi: "गली",
    wordRoman: "gaali",
    wordEnglish: "Lane",
    barakhadiRow: [
      { syllable: "ग", sound: "ga", matra: "none" },
      { syllable: "गा", sound: "gaa", matra: "ा" },
      { syllable: "गि", sound: "gi", matra: "ि" },
      { syllable: "गी", sound: "gee", matra: "ी" },
      { syllable: "गु", sound: "gu", matra: "ु" },
      { syllable: "गू", sound: "goo", matra: "ू" },
      { syllable: "गे", sound: "ge", matra: "े" },
      { syllable: "गै", sound: "gai", matra: "ै" },
      { syllable: "गो", sound: "go", matra: "ो" },
      { syllable: "गौ", sound: "gau", matra: "ौ" },
      { syllable: "गँ", sound: "gan", matra: "ँ" },
      { syllable: "गः", sound: "gah", matra: "ः" },
    ],
    assetPath: "/assets/gemini/vaani_l4_ga_barakhaadi_1777180049.png",
    summary: "Voiced consonants vibrate - feel the buzz in your throat!",
    prompt: "Let your vocal cords vibrate - it's a voiced consonant!",
  },
  {
    id: "L4-C01-L04",
    chapterId: "C01",
    chapterTitle: "Barakhaadi Series",
    title: "घ की बारहखड़ी - Gha Barakhaadi",
    category: "Vowel Series",
    skill: "Aspirate Voiced",
    consonant: "घ",
    consonantRoman: "gha",
    wordHindi: "घंटी",
    wordRoman: "ghanti",
    wordEnglish: "Bell",
    barakhadiRow: [
      { syllable: "घ", sound: "gha", matra: "none" },
      { syllable: "घा", sound: "ghaa", matra: "ा" },
      { syllable: "घि", sound: "ghi", matra: "ि" },
      { syllable: "घी", sound: "ghee", matra: "ी" },
      { syllable: "घु", sound: "ghu", matra: "ु" },
      { syllable: "घू", sound: "ghoo", matra: "ू" },
      { syllable: "घे", sound: "ghe", matra: "े" },
      { syllable: "घै", sound: "ghai", matra: "ै" },
      { syllable: "घो", sound: "gho", matra: "ो" },
      { syllable: "घौ", sound: "ghau", matra: "ौ" },
      { syllable: "घँ", sound: "ghan", matra: "ँ" },
      { syllable: "घः", sound: "ghah", matra: "ः" },
    ],
    assetPath: "/assets/gemini/vaani_l4_gha_barakhaadi_1777180073.png",
    summary: "Aspirate + voiced = powerful sound with breath and vibration!",
    prompt: "Combine the breath and vibration - it's deep and strong!",
  },
  {
    id: "L4-C01-L05",
    chapterId: "C01",
    chapterTitle: "Barakhaadi Series",
    title: "च की बारहखड़ी - Cha Barakhaadi",
    category: "Vowel Series",
    skill: "Palatal Barakhaadi",
    consonant: "च",
    consonantRoman: "cha",
    wordHindi: "चाँद",
    wordRoman: "chand",
    wordEnglish: "Moon",
    barakhadiRow: [
      { syllable: "च", sound: "cha", matra: "none" },
      { syllable: "चा", sound: "chaa", matra: "ा" },
      { syllable: "चि", sound: "chi", matra: "ि" },
      { syllable: "ची", sound: "chee", matra: "ी" },
      { syllable: "चु", sound: "chu", matra: "ु" },
      { syllable: "चू", sound: "choo", matra: "ू" },
      { syllable: "चे", sound: "che", matra: "े" },
      { syllable: "चै", sound: "chai", matra: "ै" },
      { syllable: "चो", sound: "cho", matra: "ो" },
      { syllable: "चौ", sound: "chau", matra: "ौ" },
      { syllable: "चँ", sound: "chan", matra: "ँ" },
      { syllable: "चः", sound: "chah", matra: "ः" },
    ],
    assetPath: "/assets/gemini/vaani_l4_cha_barakhaadi_1777180097.png",
    summary: "Palatal consonants use the hard palate - tongue position changes!",
    prompt: "Feel where your tongue touches - it's higher and different!",
  },
  {
    id: "L4-C01-L06",
    chapterId: "C01",
    chapterTitle: "Barakhaadi Series",
    title: "छ की बारहखड़ी - Chha Barakhaadi",
    category: "Vowel Series",
    skill: "Palatal Aspirate",
    consonant: "छ",
    consonantRoman: "chha",
    wordHindi: "छाता",
    wordRoman: "chata",
    wordEnglish: "Umbrella",
    barakhadiRow: [
      { syllable: "छ", sound: "chha", matra: "none" },
      { syllable: "छा", sound: "chhaa", matra: "ा" },
      { syllable: "छि", sound: "chhi", matra: "ि" },
      { syllable: "छी", sound: "chhee", matra: "ी" },
      { syllable: "छु", sound: "chhu", matra: "ु" },
      { syllable: "छू", sound: "chhoo", matra: "ू" },
      { syllable: "छे", sound: "chhe", matra: "े" },
      { syllable: "छै", sound: "chhai", matra: "ै" },
      { syllable: "छो", sound: "chho", matra: "ो" },
      { syllable: "छौ", sound: "chhau", matra: "ौ" },
      { syllable: "छँ", sound: "chhan", matra: "ँ" },
      { syllable: "छः", sound: "chhah", matra: "ः" },
    ],
    assetPath: "/assets/gemini/vaani_l4_chha_barakhaadi_1777180121.png",
    summary: "Add aspiration to the palatal consonant - more air!",
    prompt: "The breath is important here - release more air!",
  },
  {
    id: "L4-C01-L07",
    chapterId: "C01",
    chapterTitle: "Barakhaadi Series",
    title: "ट की बारहखड़ी - Ta Barakhaadi (Retroflex)",
    category: "Vowel Series",
    skill: "Retroflex Series",
    consonant: "ट",
    consonantRoman: "ta",
    wordHindi: "टहल",
    wordRoman: "tahal",
    wordEnglish: "Stroll",
    barakhadiRow: [
      { syllable: "ट", sound: "ta", matra: "none" },
      { syllable: "टा", sound: "taa", matra: "ा" },
      { syllable: "टि", sound: "ti", matra: "ि" },
      { syllable: "टी", sound: "tee", matra: "ी" },
      { syllable: "टु", sound: "tu", matra: "ु" },
      { syllable: "टू", sound: "too", matra: "ू" },
      { syllable: "टे", sound: "te", matra: "े" },
      { syllable: "टै", sound: "tai", matra: "ै" },
      { syllable: "टो", sound: "to", matra: "ो" },
      { syllable: "टौ", sound: "tau", matra: "ौ" },
      { syllable: "टँ", sound: "tan", matra: "ँ" },
      { syllable: "टः", sound: "tah", matra: "ः" },
    ],
    assetPath: "/assets/gemini/vaani_l4_ta_retroflex_barakhaadi_1777180145.png",
    summary: "Retroflex consonants curl the tongue back - distinct from dental!",
    prompt: "Curl your tongue back - feel the difference from क!",
  },
  {
    id: "L4-C01-L08",
    chapterId: "C01",
    chapterTitle: "Barakhaadi Series",
    title: "ठ की बारहखड़ी - Tha Barakhaadi (Retroflex)",
    category: "Vowel Series",
    skill: "Retroflex Aspirate",
    consonant: "ठ",
    consonantRoman: "tha",
    wordHindi: "ठंडा",
    wordRoman: "thanda",
    wordEnglish: "Cold",
    barakhadiRow: [
      { syllable: "ठ", sound: "tha", matra: "none" },
      { syllable: "ठा", sound: "thaa", matra: "ा" },
      { syllable: "ठि", sound: "thi", matra: "ि" },
      { syllable: "ठी", sound: "thee", matra: "ी" },
      { syllable: "ठु", sound: "thu", matra: "ु" },
      { syllable: "ठू", sound: "thoo", matra: "ू" },
      { syllable: "ठे", sound: "the", matra: "े" },
      { syllable: "ठै", sound: "thai", matra: "ै" },
      { syllable: "ठो", sound: "tho", matra: "ो" },
      { syllable: "ठौ", sound: "thau", matra: "ौ" },
      { syllable: "ठँ", sound: "than", matra: "ँ" },
      { syllable: "ठः", sound: "thah", matra: "ः" },
    ],
    assetPath: "/assets/gemini/vaani_l4_tha_retroflex_barakhaadi_1777180169.png",
    summary: "Aspirate retroflex - maximum tongue curling plus breath!",
    prompt: "Curl back and release air - bold and clear!",
  },
  {
    id: "L4-C01-L09",
    chapterId: "C01",
    chapterTitle: "Barakhaadi Series",
    title: "त की बारहखड़ी - Ta Barakhaadi (Dental)",
    category: "Vowel Series",
    skill: "Dental Series",
    consonant: "त",
    consonantRoman: "ta",
    wordHindi: "तरंग",
    wordRoman: "tarang",
    wordEnglish: "Wave",
    barakhadiRow: [
      { syllable: "त", sound: "ta", matra: "none" },
      { syllable: "ता", sound: "taa", matra: "ा" },
      { syllable: "ति", sound: "ti", matra: "ि" },
      { syllable: "ती", sound: "tee", matra: "ी" },
      { syllable: "तु", sound: "tu", matra: "ु" },
      { syllable: "तू", sound: "too", matra: "ू" },
      { syllable: "ते", sound: "te", matra: "े" },
      { syllable: "तै", sound: "tai", matra: "ै" },
      { syllable: "तो", sound: "to", matra: "ो" },
      { syllable: "तौ", sound: "tau", matra: "ौ" },
      { syllable: "तँ", sound: "tan", matra: "ँ" },
      { syllable: "तः", sound: "tah", matra: "ः" },
    ],
    assetPath: "/assets/gemini/vaani_l4_ta_dental_barakhaadi_1777180193.png",
    summary: "Dental consonants touch the teeth - softer than retroflex!",
    prompt: "Let your tongue touch your teeth - softer and sweeter!",
  },
  {
    id: "L4-C01-L10",
    chapterId: "C01",
    chapterTitle: "Barakhaadi Series",
    title: "थ की बारहखड़ी - Tha Barakhaadi (Dental)",
    category: "Vowel Series",
    skill: "Dental Aspirate",
    consonant: "थ",
    consonantRoman: "tha",
    wordHindi: "थाली",
    wordRoman: "thali",
    wordEnglish: "Plate",
    barakhadiRow: [
      { syllable: "थ", sound: "tha", matra: "none" },
      { syllable: "था", sound: "thaa", matra: "ा" },
      { syllable: "थि", sound: "thi", matra: "ि" },
      { syllable: "थी", sound: "thee", matra: "ी" },
      { syllable: "थु", sound: "thu", matra: "ु" },
      { syllable: "थू", sound: "thoo", matra: "ू" },
      { syllable: "थे", sound: "the", matra: "े" },
      { syllable: "थै", sound: "thai", matra: "ै" },
      { syllable: "थो", sound: "tho", matra: "ो" },
      { syllable: "थौ", sound: "thau", matra: "ौ" },
      { syllable: "थँ", sound: "than", matra: "ँ" },
      { syllable: "थः", sound: "thah", matra: "ः" },
    ],
    assetPath: "/assets/gemini/vaani_l4_tha_dental_barakhaadi_1777180217.png",
    summary: "Dental aspirate - teeth and breath together!",
    prompt: "Gentle teeth contact with released air!",
  },
  {
    id: "L4-C01-L11",
    chapterId: "C01",
    chapterTitle: "Barakhaadi Series",
    title: "म की बारहखड़ी - Ma Barakhaadi",
    category: "Vowel Series",
    skill: "Nasal Series",
    consonant: "म",
    consonantRoman: "ma",
    wordHindi: "मकान",
    wordRoman: "makan",
    wordEnglish: "House",
    barakhadiRow: [
      { syllable: "म", sound: "ma", matra: "none" },
      { syllable: "मा", sound: "maa", matra: "ा" },
      { syllable: "मि", sound: "mi", matra: "ि" },
      { syllable: "मी", sound: "mee", matra: "ी" },
      { syllable: "मु", sound: "mu", matra: "ु" },
      { syllable: "मू", sound: "moo", matra: "ू" },
      { syllable: "मे", sound: "me", matra: "े" },
      { syllable: "मै", sound: "mai", matra: "ै" },
      { syllable: "मो", sound: "mo", matra: "ो" },
      { syllable: "मौ", sound: "mau", matra: "ौ" },
      { syllable: "मँ", sound: "man", matra: "ँ" },
      { syllable: "मः", sound: "mah", matra: "ः" },
    ],
    assetPath: "/assets/gemini/vaani_l4_ma_nasal_barakhaadi_1777180241.png",
    summary: "Nasals let air flow through the nose - feel the vibration!",
    prompt: "Let the sound flow through your nose - it's nasal!",
  },
  {
    id: "L4-C01-L12",
    chapterId: "C01",
    chapterTitle: "Barakhaadi Series",
    title: "य की बारहखड़ी - Ya Barakhaadi",
    category: "Vowel Series",
    skill: "Semi-Vowel Series",
    consonant: "य",
    consonantRoman: "ya",
    wordHindi: "यमुना",
    wordRoman: "yamuna",
    wordEnglish: "River",
    barakhadiRow: [
      { syllable: "य", sound: "ya", matra: "none" },
      { syllable: "या", sound: "yaa", matra: "ा" },
      { syllable: "यि", sound: "yi", matra: "ि" },
      { syllable: "यी", sound: "yee", matra: "ी" },
      { syllable: "यु", sound: "yu", matra: "ु" },
      { syllable: "यू", sound: "yoo", matra: "ू" },
      { syllable: "ये", sound: "ye", matra: "े" },
      { syllable: "यै", sound: "yai", matra: "ै" },
      { syllable: "यो", sound: "yo", matra: "ो" },
      { syllable: "यौ", sound: "yau", matra: "ौ" },
      { syllable: "यँ", sound: "yan", matra: "ँ" },
      { syllable: "यः", sound: "yah", matra: "ः" },
    ],
    assetPath: "/assets/gemini/vaani_l4_ya_semivowel_barakhaadi_1777180265.png",
    summary: "Semi-vowels behave like both consonants and vowels!",
    prompt: "This consonant flows like a vowel - smooth and gliding!",
  },
];

// Roman transliteration map for Level 4
export const LEVEL_4_ROMAN_MAP: Record<string, string> = {
  "L4-C01-L01": "kamal",
  "L4-C01-L02": "khargosh",
  "L4-C01-L03": "gaali",
  "L4-C01-L04": "ghanti",
  "L4-C01-L05": "chand",
  "L4-C01-L06": "chata",
  "L4-C01-L07": "tahal",
  "L4-C01-L08": "thanda",
  "L4-C01-L09": "tarang",
  "L4-C01-L10": "thali",
  "L4-C01-L11": "makan",
  "L4-C01-L12": "yamuna",
};

// Re-export for compatibility
export const vaaniLevel4Data = LEVEL_4_DATA;
