export interface VaaniStrokeStep {
  id: string;
  label: string;
  path: string;
  hint: string;
}

export interface VaaniStrokeGuide {
  char: string;
  title: string;
  subtitle: string;
  chant: string;
  steps: VaaniStrokeStep[];
}

const GUIDES: Record<string, VaaniStrokeGuide> = {
  "अ": {
    char: "अ",
    title: "Build अ step by step",
    subtitle: "A child-friendly way to remember the letter shape.",
    chant: "Draw the 3 shape, add the side stick, add the middle stick, then the top line.",
    steps: [
      {
        id: "curve",
        label: "Draw the 3 shape",
        path: "M38 24 C18 24 18 44 36 47 C48 49 48 59 30 68",
        hint: "Start with the big curved shape, like a soft 3.",
      },
      {
        id: "side-stick",
        label: "Add the side stick",
        path: "M57 20 L57 80",
        hint: "Now add the straight standing line.",
      },
      {
        id: "middle-stick",
        label: "Add the middle stick",
        path: "M44 46 L57 46",
        hint: "Join the curve to the side stick in the middle.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M24 20 L72 20",
        hint: "Finish with the top line across the letter.",
      },
    ],
  },
  "आ": {
    char: "आ",
    title: "Build आ step by step",
    subtitle: "Start from अ, then stretch it into आ.",
    chant: "Make अ first, then add one more long line on the right.",
    steps: [
      {
        id: "curve",
        label: "Draw the 3 shape",
        path: "M34 24 C16 24 16 44 34 47 C46 49 46 59 29 68",
        hint: "Begin with the same soft 3 shape.",
      },
      {
        id: "side-stick",
        label: "Add the side stick",
        path: "M52 20 L52 80",
        hint: "Place the main standing line.",
      },
      {
        id: "middle-stick",
        label: "Add the middle stick",
        path: "M40 46 L52 46",
        hint: "Connect the middle stroke.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M22 20 L76 20",
        hint: "Draw the top line across.",
      },
      {
        id: "long-line",
        label: "Add the long line",
        path: "M70 20 L70 80",
        hint: "Now add the extra long line to make आ.",
      },
    ],
  },
  "इ": {
    char: "इ",
    title: "Build इ step by step",
    subtitle: "A short curved letter with a standing line and top line.",
    chant: "Make the small curve, add the standing line, then finish with the top line.",
    steps: [
      {
        id: "curve",
        label: "Draw the small curve",
        path: "M38 30 C26 34 24 48 34 56 C42 62 44 70 36 76",
        hint: "Start with the little curved body.",
      },
      {
        id: "stick",
        label: "Add the standing line",
        path: "M58 24 L58 80",
        hint: "Now draw the straight line beside it.",
      },
      {
        id: "join",
        label: "Add the joining touch",
        path: "M42 48 L58 48",
        hint: "Connect the body to the standing line.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L72 24",
        hint: "Finish with the top line across the top.",
      },
    ],
  },
  "ई": {
    char: "ई",
    title: "Build ई step by step",
    subtitle: "Start from इ, then add the extra long tail.",
    chant: "Make इ first, then give it one more long line.",
    steps: [
      {
        id: "curve",
        label: "Draw the small curve",
        path: "M34 30 C22 34 20 48 31 56 C39 62 40 70 33 76",
        hint: "Begin with the small curved body.",
      },
      {
        id: "stick",
        label: "Add the standing line",
        path: "M52 24 L52 80",
        hint: "Place the main standing line.",
      },
      {
        id: "join",
        label: "Add the joining touch",
        path: "M39 48 L52 48",
        hint: "Connect the body into the standing line.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M24 24 L76 24",
        hint: "Draw the top line across the top.",
      },
      {
        id: "long-tail",
        label: "Add the long tail",
        path: "M70 24 L70 82",
        hint: "Now add the extra long line to make ई.",
      },
    ],
  },
  "उ": {
    char: "उ",
    title: "Build उ step by step",
    subtitle: "A bowl shape, a standing line, and a small tail below.",
    chant: "Make the bowl, add the standing line, then curl the little tail below.",
    steps: [
      {
        id: "bowl",
        label: "Draw the bowl shape",
        path: "M28 36 C30 58 44 68 58 62 C67 58 70 48 68 36",
        hint: "Start with the open bowl shape in the middle.",
      },
      {
        id: "stick",
        label: "Add the standing line",
        path: "M68 24 L68 62",
        hint: "Draw the standing line on the right side.",
      },
      {
        id: "tail",
        label: "Add the little tail",
        path: "M46 62 C44 74 48 82 58 82",
        hint: "Finish with the small curved tail below.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M24 24 L74 24",
        hint: "Complete it with the top line.",
      },
    ],
  },
  "ऊ": {
    char: "ऊ",
    title: "Build ऊ step by step",
    subtitle: "Start from उ, then add one more longer tail below.",
    chant: "Make उ first, then stretch the lower tail a little more.",
    steps: [
      {
        id: "bowl",
        label: "Draw the bowl shape",
        path: "M26 36 C28 58 42 68 57 62 C66 58 68 48 66 36",
        hint: "Begin with the open bowl shape.",
      },
      {
        id: "stick",
        label: "Add the standing line",
        path: "M66 24 L66 62",
        hint: "Add the standing line on the right.",
      },
      {
        id: "tail",
        label: "Add the long tail",
        path: "M45 62 C42 76 48 86 62 84",
        hint: "Now draw the longer lower tail for ऊ.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M22 24 L74 24",
        hint: "Finish the letter with the top line.",
      },
    ],
  },
  "ऋ": {
    char: "ऋ",
    title: "Build ऋ step by step",
    subtitle: "Start like a curved body, then add the lower hook and top line.",
    chant: "Make the curve, add the standing line, curl the lower hook, then the top line.",
    steps: [
      {
        id: "curve",
        label: "Draw the curved body",
        path: "M34 28 C24 34 22 48 33 56 C43 63 44 72 35 80",
        hint: "Start with the curved body first.",
      },
      {
        id: "stick",
        label: "Add the standing line",
        path: "M56 24 L56 78",
        hint: "Now draw the straight standing line.",
      },
      {
        id: "hook",
        label: "Add the lower hook",
        path: "M50 68 C58 76 64 78 70 74",
        hint: "Finish the lower sound hook at the bottom.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M26 24 L70 24",
        hint: "Close it with the top line.",
      },
    ],
  },
  "ए": {
    char: "ए",
    title: "Build ए step by step",
    subtitle: "A standing line, curved body, and top line.",
    chant: "Draw the side line, make the curve, add the middle touch, then the top line.",
    steps: [
      {
        id: "stick",
        label: "Draw the side line",
        path: "M60 24 L60 80",
        hint: "Begin with the standing line on the side.",
      },
      {
        id: "curve",
        label: "Draw the curve",
        path: "M34 30 C24 36 22 50 34 58 C42 64 42 72 34 78",
        hint: "Now draw the curved body beside it.",
      },
      {
        id: "join",
        label: "Add the middle touch",
        path: "M42 48 L60 48",
        hint: "Connect the body into the standing line.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M26 24 L72 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "ऐ": {
    char: "ऐ",
    title: "Build ऐ step by step",
    subtitle: "Start from ए, then add the extra upper marker.",
    chant: "Make ए first, then add one more mark above it.",
    steps: [
      {
        id: "stick",
        label: "Draw the side line",
        path: "M58 26 L58 80",
        hint: "Start with the standing line.",
      },
      {
        id: "curve",
        label: "Draw the curve",
        path: "M32 32 C22 38 22 50 33 58 C40 64 40 72 32 78",
        hint: "Add the curved body next.",
      },
      {
        id: "join",
        label: "Add the middle touch",
        path: "M40 48 L58 48",
        hint: "Connect the body to the side line.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M24 26 L72 26",
        hint: "Draw the top line across.",
      },
      {
        id: "extra-mark",
        label: "Add the extra top mark",
        path: "M42 18 L52 18",
        hint: "Add the extra mark to turn ए into ऐ.",
      },
    ],
  },
  "ओ": {
    char: "ओ",
    title: "Build ओ step by step",
    subtitle: "Start from आ, then shape the rounded body.",
    chant: "Make the rounded body, add the side line, then the top line.",
    steps: [
      {
        id: "curve",
        label: "Draw the rounded body",
        path: "M32 32 C22 40 22 56 36 62 C48 68 48 76 38 82",
        hint: "Start with the rounded body on the left.",
      },
      {
        id: "main-stick",
        label: "Add the main line",
        path: "M58 24 L58 80",
        hint: "Draw the standing line on the right.",
      },
      {
        id: "join",
        label: "Add the joining stroke",
        path: "M42 48 L58 48",
        hint: "Connect the body to the main line.",
      },
      {
        id: "extra-line",
        label: "Add the extra line",
        path: "M72 24 L72 80",
        hint: "Add the extra long line that helps make ओ.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M24 24 L78 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "औ": {
    char: "औ",
    title: "Build औ step by step",
    subtitle: "Start from ओ, then add the lower tail.",
    chant: "Make ओ first, then add the lower tail for औ.",
    steps: [
      {
        id: "curve",
        label: "Draw the rounded body",
        path: "M30 32 C20 40 20 56 34 62 C46 68 46 76 36 82",
        hint: "Start with the rounded body.",
      },
      {
        id: "main-stick",
        label: "Add the main line",
        path: "M56 24 L56 80",
        hint: "Draw the main standing line.",
      },
      {
        id: "join",
        label: "Add the joining stroke",
        path: "M40 48 L56 48",
        hint: "Connect the body to the standing line.",
      },
      {
        id: "extra-line",
        label: "Add the extra line",
        path: "M70 24 L70 80",
        hint: "Add the extra right line.",
      },
      {
        id: "tail",
        label: "Add the lower tail",
        path: "M46 70 C48 82 58 88 68 84",
        hint: "Add the little lower tail that makes औ.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M22 24 L76 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "अं": {
    char: "अं",
    title: "Build अं step by step",
    subtitle: "Start from अ, then add the dot sound on top.",
    chant: "Make अ first, then place the little dot above it.",
    steps: [
      {
        id: "curve",
        label: "Draw the 3 shape",
        path: "M38 24 C18 24 18 44 36 47 C48 49 48 59 30 68",
        hint: "Start with the big curved shape, like a soft 3.",
      },
      {
        id: "side-stick",
        label: "Add the side stick",
        path: "M57 20 L57 80",
        hint: "Now add the straight standing line.",
      },
      {
        id: "middle-stick",
        label: "Add the middle stick",
        path: "M44 46 L57 46",
        hint: "Join the curve to the side stick in the middle.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M24 20 L72 20",
        hint: "Finish the letter with the top line.",
      },
      {
        id: "dot",
        label: "Add the dot on top",
        path: "M50 12 L50 12",
        hint: "Now place the little dot above for the nasal sound.",
      },
    ],
  },
  "अः": {
    char: "अः",
    title: "Build अः step by step",
    subtitle: "Start from अ, then add the visarga dots on the side.",
    chant: "Make अ first, then add the two breathing dots on the right.",
    steps: [
      {
        id: "curve",
        label: "Draw the 3 shape",
        path: "M34 24 C16 24 16 44 34 47 C46 49 46 59 28 68",
        hint: "Start with the curved 3-like shape.",
      },
      {
        id: "side-stick",
        label: "Add the side stick",
        path: "M53 20 L53 80",
        hint: "Add the straight standing line.",
      },
      {
        id: "middle-stick",
        label: "Add the middle stick",
        path: "M40 46 L53 46",
        hint: "Join the curve to the standing line.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M22 20 L68 20",
        hint: "Draw the top line across.",
      },
      {
        id: "visarga",
        label: "Add the two dots",
        path: "M70 36 L70 36 M70 56 L70 56",
        hint: "Now add the two small dots on the right for visarga.",
      },
    ],
  },
  "क": {
    char: "क",
    title: "Build क step by step",
    subtitle: "A standing line, open arm, and lower curve.",
    chant: "Draw the stick, open the arm, bend the lower curve, then add the top line.",
    steps: [
      {
        id: "stick",
        label: "Draw the standing line",
        path: "M58 24 L58 80",
        hint: "Start with the straight standing line.",
      },
      {
        id: "arm",
        label: "Open the arm",
        path: "M36 38 L58 38",
        hint: "Now make the open arm in the middle.",
      },
      {
        id: "curve",
        label: "Draw the lower curve",
        path: "M40 38 C26 48 28 68 46 78",
        hint: "Curve down and out to form the lower body.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M32 24 L70 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "ख": {
    char: "ख",
    title: "Build ख step by step",
    subtitle: "Start from क, then add the extra open sweep.",
    chant: "Make क first, then add the extra sweeping line for ख.",
    steps: [
      {
        id: "stick",
        label: "Draw the standing line",
        path: "M58 24 L58 80",
        hint: "Start with the standing line.",
      },
      {
        id: "arm",
        label: "Open the arm",
        path: "M36 38 L58 38",
        hint: "Add the middle arm.",
      },
      {
        id: "curve",
        label: "Draw the lower curve",
        path: "M40 38 C26 48 28 68 46 78",
        hint: "Make the lower curve like क.",
      },
      {
        id: "sweep",
        label: "Add the extra sweep",
        path: "M58 50 C68 54 72 64 68 76",
        hint: "Now add the extra outer sweep to make ख.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M32 24 L70 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "ग": {
    char: "ग",
    title: "Build ग step by step",
    subtitle: "A rounded body with a standing line and top line.",
    chant: "Draw the rounded body, add the standing line, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M36 34 C24 40 24 58 38 64 C48 68 48 76 40 82",
        hint: "Start with the rounded body first.",
      },
      {
        id: "stick",
        label: "Add the standing line",
        path: "M58 24 L58 80",
        hint: "Add the straight standing line.",
      },
      {
        id: "join",
        label: "Add the joining stroke",
        path: "M42 48 L58 48",
        hint: "Connect the body into the standing line.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish the letter with the top line.",
      },
    ],
  },
  "घ": {
    char: "घ",
    title: "Build घ step by step",
    subtitle: "Start from ग, then add the extra lower swing.",
    chant: "Make ग first, then add the extra lower swing for घ.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M34 34 C22 40 22 58 36 64 C46 68 46 76 38 82",
        hint: "Start with the rounded body.",
      },
      {
        id: "stick",
        label: "Add the standing line",
        path: "M56 24 L56 80",
        hint: "Draw the standing line beside it.",
      },
      {
        id: "join",
        label: "Add the joining stroke",
        path: "M40 48 L56 48",
        hint: "Connect the body to the standing line.",
      },
      {
        id: "swing",
        label: "Add the extra lower swing",
        path: "M56 60 C66 64 70 74 64 84",
        hint: "Now add the lower swing to make घ.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L68 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "च": {
    char: "च",
    title: "Build च step by step",
    subtitle: "A curved body, a standing line, and the top line.",
    chant: "Draw the curved body, add the side line, then the top line.",
    steps: [
      {
        id: "curve",
        label: "Draw the curved body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 48 76 40 82",
        hint: "Start with the curved body first.",
      },
      {
        id: "join",
        label: "Add the joining line",
        path: "M42 48 L58 48",
        hint: "Now make the small joining line in the middle.",
      },
      {
        id: "stick",
        label: "Add the standing line",
        path: "M58 24 L58 80",
        hint: "Draw the standing line on the side.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "छ": {
    char: "छ",
    title: "Build छ step by step",
    subtitle: "Start from च, then add the extra open sweep.",
    chant: "Make च first, then add the extra sweep to open it into छ.",
    steps: [
      {
        id: "curve",
        label: "Draw the curved body",
        path: "M32 34 C22 42 22 58 36 64 C46 68 46 76 38 82",
        hint: "Start with the curved body.",
      },
      {
        id: "join",
        label: "Add the joining line",
        path: "M40 48 L56 48",
        hint: "Draw the small joining line in the middle.",
      },
      {
        id: "stick",
        label: "Add the standing line",
        path: "M56 24 L56 80",
        hint: "Add the standing line beside it.",
      },
      {
        id: "sweep",
        label: "Add the extra sweep",
        path: "M56 56 C66 60 72 72 66 84",
        hint: "Now add the extra open sweep for छ.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L70 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "ज": {
    char: "ज",
    title: "Build ज step by step",
    subtitle: "A rounded body with a lower hook and top line.",
    chant: "Draw the body, make the lower hook, then add the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 50 74 46 82",
        hint: "Start with the rounded body first.",
      },
      {
        id: "hook",
        label: "Add the lower hook",
        path: "M46 82 C54 86 62 84 66 76",
        hint: "Curl the lower hook outward at the bottom.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M58 24 L58 62",
        hint: "Add the short standing line beside the body.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "झ": {
    char: "झ",
    title: "Build झ step by step",
    subtitle: "Start from ज, then add the extra lower swing.",
    chant: "Make ज first, then add the extra swing to turn it into झ.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M32 34 C22 42 22 58 36 64 C46 68 48 74 44 82",
        hint: "Start with the rounded body.",
      },
      {
        id: "hook",
        label: "Add the lower hook",
        path: "M44 82 C52 86 60 84 64 76",
        hint: "Curl the lower hook outward.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M56 24 L56 62",
        hint: "Add the short standing line beside the body.",
      },
      {
        id: "swing",
        label: "Add the extra swing",
        path: "M56 60 C66 64 70 76 62 86",
        hint: "Add the extra lower swing for झ.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L68 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "ञ": {
    char: "ञ",
    title: "Build ञ step by step",
    subtitle: "A rounded body with a lower curl and a small finishing mark.",
    chant: "Draw the body, curl the lower hook, add the side touch, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 50 76 44 82",
        hint: "Start with the soft rounded body.",
      },
      {
        id: "curl",
        label: "Add the lower curl",
        path: "M44 82 C52 88 62 84 64 74",
        hint: "Curl the lower part outward to finish the base shape.",
      },
      {
        id: "side-touch",
        label: "Add the side touch",
        path: "M56 30 L56 60",
        hint: "Now add the short side line beside the body.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L68 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "ट": {
    char: "ट",
    title: "Build ट step by step",
    subtitle: "A firm standing shape with a curved base and top line.",
    chant: "Draw the standing line, make the lower curve, then add the top line.",
    steps: [
      {
        id: "stick",
        label: "Draw the standing line",
        path: "M54 24 L54 72",
        hint: "Start with the strong standing line.",
      },
      {
        id: "base-curve",
        label: "Add the lower curve",
        path: "M54 72 C46 82 34 82 28 72",
        hint: "Now bend the bottom into a neat curve.",
      },
      {
        id: "top-hook",
        label: "Add the top touch",
        path: "M44 30 C48 26 52 24 56 24",
        hint: "Add the small top touch to shape the letter well.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M26 24 L68 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "ठ": {
    char: "ठ",
    title: "Build ठ step by step",
    subtitle: "Start from ट, then open the lower curve a little more.",
    chant: "Make ट first, then add the extra open sweep to turn it into ठ.",
    steps: [
      {
        id: "stick",
        label: "Draw the standing line",
        path: "M52 24 L52 72",
        hint: "Start with the standing line.",
      },
      {
        id: "base-curve",
        label: "Add the lower curve",
        path: "M52 72 C44 82 32 82 26 72",
        hint: "Curve the bottom into the base shape.",
      },
      {
        id: "sweep",
        label: "Add the open sweep",
        path: "M52 56 C64 62 70 74 64 86",
        hint: "Add the extra open sweep that makes it ठ.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M24 24 L68 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "ड": {
    char: "ड",
    title: "Build ड step by step",
    subtitle: "A curved body with a strong side line and top line.",
    chant: "Draw the body, add the standing side line, then finish with the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the curved body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 48 78 38 82",
        hint: "Start with the curved body first.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M58 24 L58 78",
        hint: "Add the straight side line beside the body.",
      },
      {
        id: "join",
        label: "Add the joining stroke",
        path: "M42 48 L58 48",
        hint: "Connect the body to the side line in the middle.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "ढ": {
    char: "ढ",
    title: "Build ढ step by step",
    subtitle: "Start from ड, then add the extra lower swing.",
    chant: "Make ड first, then add the extra lower swing to turn it into ढ.",
    steps: [
      {
        id: "body",
        label: "Draw the curved body",
        path: "M32 34 C22 42 22 58 36 64 C46 68 46 78 36 82",
        hint: "Start with the curved body.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M56 24 L56 78",
        hint: "Add the straight side line.",
      },
      {
        id: "join",
        label: "Add the joining stroke",
        path: "M40 48 L56 48",
        hint: "Connect the body to the side line.",
      },
      {
        id: "swing",
        label: "Add the extra lower swing",
        path: "M56 60 C66 66 70 78 62 88",
        hint: "Now add the lower swing that makes it ढ.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L68 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "ण": {
    char: "ण",
    title: "Build ण step by step",
    subtitle: "A rounded body with a firm side line and a finishing curl.",
    chant: "Draw the body, add the side line, curl the bottom, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 48 78 40 82",
        hint: "Start with the rounded body first.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M58 24 L58 78",
        hint: "Draw the straight side line beside it.",
      },
      {
        id: "curl",
        label: "Add the lower curl",
        path: "M42 78 C48 86 58 86 64 78",
        hint: "Curl the bottom outward to complete the shape.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "त": {
    char: "त",
    title: "Build त step by step",
    subtitle: "A light curve with a standing line and top line.",
    chant: "Draw the curve, add the standing line, then finish with the top line.",
    steps: [
      {
        id: "curve",
        label: "Draw the main curve",
        path: "M34 34 C24 42 24 56 38 62 C48 66 48 74 40 80",
        hint: "Start with the soft main curve.",
      },
      {
        id: "stick",
        label: "Add the standing line",
        path: "M58 24 L58 76",
        hint: "Now draw the standing line on the side.",
      },
      {
        id: "join",
        label: "Add the middle join",
        path: "M42 48 L58 48",
        hint: "Connect the curve to the standing line in the middle.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "थ": {
    char: "थ",
    title: "Build थ step by step",
    subtitle: "Start from त, then add the extra open sweep.",
    chant: "Make त first, then add the extra sweep to turn it into थ.",
    steps: [
      {
        id: "curve",
        label: "Draw the main curve",
        path: "M32 34 C22 42 22 56 36 62 C46 66 46 74 38 80",
        hint: "Start with the soft main curve.",
      },
      {
        id: "stick",
        label: "Add the standing line",
        path: "M56 24 L56 76",
        hint: "Draw the standing line beside it.",
      },
      {
        id: "join",
        label: "Add the middle join",
        path: "M40 48 L56 48",
        hint: "Connect the curve to the standing line.",
      },
      {
        id: "sweep",
        label: "Add the extra sweep",
        path: "M56 58 C68 64 72 76 64 88",
        hint: "Now add the open sweep that makes it थ.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L68 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "द": {
    char: "द",
    title: "Build द step by step",
    subtitle: "A rounded body with a short side line and top line.",
    chant: "Draw the body, add the side line, then finish with the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 50 74 46 82",
        hint: "Start with the rounded body first.",
      },
      {
        id: "stick",
        label: "Add the short side line",
        path: "M58 24 L58 62",
        hint: "Add the short side line beside the body.",
      },
      {
        id: "join",
        label: "Add the joining touch",
        path: "M42 48 L58 48",
        hint: "Join the body to the side line in the middle.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "ध": {
    char: "ध",
    title: "Build ध step by step",
    subtitle: "Start from द, then add the extra lower swing.",
    chant: "Make द first, then add the extra lower swing to turn it into ध.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M32 34 C22 42 22 58 36 64 C46 68 48 74 44 82",
        hint: "Start with the rounded body.",
      },
      {
        id: "stick",
        label: "Add the short side line",
        path: "M56 24 L56 62",
        hint: "Add the short side line beside it.",
      },
      {
        id: "join",
        label: "Add the joining touch",
        path: "M40 48 L56 48",
        hint: "Connect the body to the side line.",
      },
      {
        id: "swing",
        label: "Add the extra lower swing",
        path: "M56 60 C66 66 70 78 62 88",
        hint: "Add the extra lower swing that makes it ध.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L68 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "न": {
    char: "न",
    title: "Build न step by step",
    subtitle: "A rounded body, a side line, and a clean lower finish.",
    chant: "Draw the body, add the side line, shape the lower finish, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 50 76 44 82",
        hint: "Start with the rounded body first.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M58 24 L58 78",
        hint: "Draw the straight side line beside the body.",
      },
      {
        id: "finish",
        label: "Add the lower finish",
        path: "M44 82 C50 86 58 84 62 76",
        hint: "Shape the lower finish neatly at the bottom.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "प": {
    char: "प",
    title: "Build प step by step",
    subtitle: "A rounded body with a side line and a neat lower base.",
    chant: "Draw the body, add the side line, finish the lower base, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 48 78 40 82",
        hint: "Start with the rounded body first.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M58 24 L58 80",
        hint: "Draw the standing line on the side.",
      },
      {
        id: "base",
        label: "Add the lower base",
        path: "M40 82 L58 82",
        hint: "Finish the bottom with a neat base line.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "फ": {
    char: "फ",
    title: "Build फ step by step",
    subtitle: "Start from प, then add the extra open sweep.",
    chant: "Make प first, then add the open sweep to turn it into फ.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M32 34 C22 42 22 58 36 64 C46 68 46 78 38 82",
        hint: "Start with the rounded body.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M56 24 L56 80",
        hint: "Draw the standing side line.",
      },
      {
        id: "base",
        label: "Add the lower base",
        path: "M38 82 L56 82",
        hint: "Finish the bottom base first.",
      },
      {
        id: "sweep",
        label: "Add the open sweep",
        path: "M56 56 C68 62 72 76 64 88",
        hint: "Now add the open sweep that makes it फ.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L68 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "ब": {
    char: "ब",
    title: "Build ब step by step",
    subtitle: "A soft rounded body with a side line and top line.",
    chant: "Draw the body, add the side line, join the middle, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 50 76 44 82",
        hint: "Start with the soft rounded body.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M58 24 L58 78",
        hint: "Add the straight side line.",
      },
      {
        id: "join",
        label: "Add the middle join",
        path: "M42 48 L58 48",
        hint: "Connect the body to the side line in the middle.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "भ": {
    char: "भ",
    title: "Build भ step by step",
    subtitle: "Start from ब, then add the extra lower swing.",
    chant: "Make ब first, then add the extra lower swing to turn it into भ.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M32 34 C22 42 22 58 36 64 C46 68 48 76 42 82",
        hint: "Start with the rounded body.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M56 24 L56 78",
        hint: "Draw the side line beside it.",
      },
      {
        id: "join",
        label: "Add the middle join",
        path: "M40 48 L56 48",
        hint: "Connect the body to the side line.",
      },
      {
        id: "swing",
        label: "Add the extra lower swing",
        path: "M56 60 C66 66 70 78 62 88",
        hint: "Add the lower swing that makes it भ.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L68 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "म": {
    char: "म",
    title: "Build म step by step",
    subtitle: "A rounded body with a broad lower finish and top line.",
    chant: "Draw the body, add the side line, finish the lower shape, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 50 76 44 82",
        hint: "Start with the rounded body first.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M58 24 L58 78",
        hint: "Draw the standing side line.",
      },
      {
        id: "finish",
        label: "Add the lower finish",
        path: "M42 82 C50 86 60 84 66 76",
        hint: "Shape the lower finish wider to make म.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "य": {
    char: "य",
    title: "Build य step by step",
    subtitle: "A curved body with a light lower tail and top line.",
    chant: "Draw the body, add the side line, shape the lower tail, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the curved body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 48 76 42 82",
        hint: "Start with the curved body first.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M58 24 L58 74",
        hint: "Draw the side line beside the body.",
      },
      {
        id: "tail",
        label: "Add the lower tail",
        path: "M42 82 C50 86 58 84 62 76",
        hint: "Shape the lower tail neatly at the bottom.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "र": {
    char: "र",
    title: "Build र step by step",
    subtitle: "A simple upright shape with a curved lower finish.",
    chant: "Draw the standing line, add the lower curve, then finish with the top line.",
    steps: [
      {
        id: "stick",
        label: "Draw the standing line",
        path: "M50 24 L50 68",
        hint: "Start with the standing line.",
      },
      {
        id: "curve",
        label: "Add the lower curve",
        path: "M50 68 C44 80 32 82 26 72",
        hint: "Curve the lower part softly to the left.",
      },
      {
        id: "touch",
        label: "Add the top touch",
        path: "M44 30 C46 26 50 24 54 24",
        hint: "Add the small top touch to shape the letter.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M24 24 L62 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "ल": {
    char: "ल",
    title: "Build ल step by step",
    subtitle: "A curved body with a strong side line and lower finish.",
    chant: "Draw the body, add the side line, shape the lower finish, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the curved body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 50 76 44 82",
        hint: "Start with the curved body first.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M58 24 L58 80",
        hint: "Draw the straight side line.",
      },
      {
        id: "finish",
        label: "Add the lower finish",
        path: "M44 82 C52 86 60 84 64 76",
        hint: "Shape the lower finish to complete ल.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "व": {
    char: "व",
    title: "Build व step by step",
    subtitle: "A rounded body with a short side line and top line.",
    chant: "Draw the body, add the short side line, then finish with the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 48 76 42 82",
        hint: "Start with the soft rounded body.",
      },
      {
        id: "stick",
        label: "Add the short side line",
        path: "M58 24 L58 60",
        hint: "Add the short side line beside the body.",
      },
      {
        id: "join",
        label: "Add the joining touch",
        path: "M42 48 L58 48",
        hint: "Join the body to the side line in the middle.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "श": {
    char: "श",
    title: "Build श step by step",
    subtitle: "A curved body with a side line and extra lower finish.",
    chant: "Draw the body, add the side line, shape the lower finish, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the curved body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 50 76 44 82",
        hint: "Start with the curved body first.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M58 24 L58 78",
        hint: "Draw the side line beside it.",
      },
      {
        id: "finish",
        label: "Add the lower finish",
        path: "M44 82 C50 88 60 86 66 76",
        hint: "Shape the lower finish a little wider for श.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "ष": {
    char: "ष",
    title: "Build ष step by step",
    subtitle: "Start from श, then give it a firmer lower finish.",
    chant: "Make the body, add the side line, shape the firm lower finish, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the curved body",
        path: "M32 34 C22 42 22 58 36 64 C46 68 48 76 42 82",
        hint: "Start with the curved body.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M56 24 L56 78",
        hint: "Draw the side line beside it.",
      },
      {
        id: "finish",
        label: "Add the firm lower finish",
        path: "M42 82 C50 88 60 86 64 74",
        hint: "Shape the lower finish a bit firmer for ष.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L68 24",
        hint: "Finish with the top line.",
      },
    ],
  },
  "स": {
    char: "स",
    title: "Build स step by step",
    subtitle: "A rounded body with a short side line and lower finish.",
    chant: "Draw the body, add the short side line, shape the lower finish, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 50 76 44 82",
        hint: "Start with the rounded body first.",
      },
      {
        id: "stick",
        label: "Add the short side line",
        path: "M58 24 L58 62",
        hint: "Add the short side line beside it.",
      },
      {
        id: "finish",
        label: "Add the lower finish",
        path: "M44 82 C50 86 58 84 62 76",
        hint: "Shape the lower finish neatly at the bottom.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "ह": {
    char: "ह",
    title: "Build ह step by step",
    subtitle: "A curved body with a side line and a clear lower tail.",
    chant: "Draw the body, add the side line, curl the lower tail, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the curved body",
        path: "M34 34 C24 42 24 58 38 64 C48 68 50 76 44 82",
        hint: "Start with the curved body first.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M58 24 L58 74",
        hint: "Draw the side line beside the body.",
      },
      {
        id: "tail",
        label: "Add the lower tail",
        path: "M44 82 C52 88 62 84 66 72",
        hint: "Curl the lower tail to complete ह.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M30 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "क्ष": {
    char: "क्ष",
    title: "Build क्ष step by step",
    subtitle: "A special joined letter made by building a firm body and crossing finish.",
    chant: "Draw the main body, add the side line, cross the middle, then finish the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the main body",
        path: "M32 34 C22 42 22 58 36 64 C46 68 46 78 38 84",
        hint: "Start with the main curved body first.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M56 24 L56 80",
        hint: "Add the strong side line on the right.",
      },
      {
        id: "cross",
        label: "Add the crossing stroke",
        path: "M40 46 L60 58",
        hint: "Now cross the middle to show the joined sound.",
      },
      {
        id: "finish",
        label: "Add the lower finish",
        path: "M44 82 C52 88 62 84 66 74",
        hint: "Shape the lower finish to complete क्ष.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "त्र": {
    char: "त्र",
    title: "Build त्र step by step",
    subtitle: "A joined letter with a standing shape and flowing lower curve.",
    chant: "Draw the standing line, add the lower curve, make the join, then the top line.",
    steps: [
      {
        id: "stick",
        label: "Draw the standing line",
        path: "M50 24 L50 72",
        hint: "Start with the standing line.",
      },
      {
        id: "curve",
        label: "Add the lower curve",
        path: "M50 72 C42 84 30 84 24 72",
        hint: "Curve the lower part softly to the left.",
      },
      {
        id: "join",
        label: "Add the joining stroke",
        path: "M40 46 L62 54",
        hint: "Add the joining stroke that gives the combined sound.",
      },
      {
        id: "tail",
        label: "Add the lower tail",
        path: "M56 54 C64 62 66 72 60 84",
        hint: "Finish with the flowing lower tail.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M24 24 L66 24",
        hint: "Close it with the top line.",
      },
    ],
  },
  "ज्ञ": {
    char: "ज्ञ",
    title: "Build ज्ञ step by step",
    subtitle: "A joined letter with a rounded body and a marked lower finish.",
    chant: "Draw the body, add the side line, make the join, then finish the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the rounded body",
        path: "M32 34 C22 42 22 58 36 64 C46 68 48 78 40 84",
        hint: "Start with the rounded body first.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M56 24 L56 76",
        hint: "Draw the side line beside it.",
      },
      {
        id: "join",
        label: "Add the joining stroke",
        path: "M40 46 L62 56",
        hint: "Make the joining stroke for the combined sound.",
      },
      {
        id: "finish",
        label: "Add the lower finish",
        path: "M42 82 C50 88 62 86 68 74",
        hint: "Shape the lower finish to complete ज्ञ.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L70 24",
        hint: "Finish with the top line across.",
      },
    ],
  },
  "श्र": {
    char: "श्र",
    title: "Build श्र step by step",
    subtitle: "A joined letter with a curved body, a side line, and a flowing finish.",
    chant: "Draw the body, add the side line, shape the joining finish, then the top line.",
    steps: [
      {
        id: "body",
        label: "Draw the curved body",
        path: "M32 34 C22 42 22 58 36 64 C46 68 48 78 40 84",
        hint: "Start with the curved body first.",
      },
      {
        id: "stick",
        label: "Add the side line",
        path: "M56 24 L56 76",
        hint: "Draw the side line beside it.",
      },
      {
        id: "join",
        label: "Add the joining finish",
        path: "M40 48 L62 58",
        hint: "Add the joining finish for the blended sound.",
      },
      {
        id: "tail",
        label: "Add the flowing tail",
        path: "M44 82 C52 88 62 86 68 72",
        hint: "Finish with a flowing lower tail.",
      },
      {
        id: "headline",
        label: "Add the top line",
        path: "M28 24 L70 24",
        hint: "Close the letter with the top line.",
      },
    ],
  },
};

export function getStrokeGuide(char: string): VaaniStrokeGuide | null {
  return GUIDES[char] || null;
}
